### PR TITLE
Fix #9255: [Network] TCPConnecter crashes when hostname not found

### LINKED ISSUE #9255: Threading issues with the TCPConnecters
## Version of OpenTTD
b972ed86045e1c287d03b3f7cda1ff21243d00fe, Linux. Though probably any recent version with TCPConnecters and any OS.

## Expected result
1: Expected error messages getting thrown.
2: Game not crashing.

## Actual result
1: No error message gets thrown.
2: Game crashes (quite often) during drawing.

## Steps to reproduce
For both: change "content.openttd.org" in network/core/config.h to something that doesn't resolve.
1: Disable threads and open the network content window.
2: Enable threads and open the network content window.

## Issue
1: OnFailure does not get called as Resolve is called in the constructor of TCPConnecter at which point the virtual call table has not been filled by the sub class, so it calls OnFailure of TCPConnecter and not of NetworkContentConnecter.
2: The resolve fails, calling OnFailure which calls OnConnect(false) on the _network_content_client which deletes the network content window while it is (or might be) drawing the actual window.

Since it is generic for the TCPConnecters and the only "difference" is whether there's threading support, I think the architecture regarding the TCPConnecters needs to be rethought so using it "wrong" cannot happen anymore. Something along the lines of the connecter not starting the thread/resolve in the constructor, but in some later function like is done for TCPConnecter::CheckCallbacks. Similarly the actual failure/succes callbacks should be ran from that function too, so there are no potential threading issues between the UI and this.

Issues found due to alert https://lgtm.com/projects/g/OpenTTD/OpenTTD/snapshot/130a44ec3978b0c0fe99d05be724bc99902667d9/files/src/network/core/tcp_connect.cpp?sort=name&dir=ASC&mode=heatmap#L36

### PR DESCRIPTION
**Pull request by TrueBrain**
Fixes #9255

## Motivation / Problem

#9255 reports two problems:

- ctor calls `Resolve()` which can call `OnFailure` which is not yet loaded at that point in time.
- `Resolve` can call `OnFailure` while the game-state is not locked.

## Description

By solving the second the first automagically solves itself, but I think it is a pitfall the next person will in before you know it. As such, I also addressed the first one. Call it overkill.

Basically:
- `OnFailure` in `Resolve` is delayed till the game-state is locked (in `CheckActivity`, which guarantees this).
- `Resolve` is called from `CheckActivity` and no longer in the ctor.

I could combine both nicely in a single enum, which also helps understanding a bit more what the step are that are taken by the resolvement.

The status is not updated to failure/success in `CheckActivity` itself, as both result in a `return true` which will destroy the object seconds later. In other words, nobody will be able to read this updated status anyway.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/network/core/tcp.h [hunk 1]
```diff
@@ -61,13 +61,27 @@ class NetworkTCPSocketHandler : public NetworkSocketHandler {
...
 
+/**
+ * The current status of the connecter.
+ *
+ * We track the status like this to ensure everything is executed from the
+ * game-thread, and not at another random time where we might not have the
+ * lock on the game-state.
+ */
+enum TCPConnecterStatus {
+	TCP_CONNECTER_STATUS_INIT,       ///< TCPConnecter is created by resolving hasn't started.
```
Comment (rubidium42) [inline src/network/core/tcp.h]: s/by/but/?

**Review by rubidium42 — DISMISSED** [review]

**Review by rubidium42 — APPROVED** [review]
