### PR TITLE
Fix #10419: Water infrastructure accounting when building ship depots and docks

### LINKED ISSUE #10419: [Bug]: Water infrastructure total mismatch when building ship depot over water objects on owned water
### Version of OpenTTD

master

### Expected result

Water infrastructure total is correct

### Actual result

Water infrastructure total is incorrect in the case below.

This may eventually lead to a multiplayer desync.

### Steps to reproduce

1. Build two canal pieces
2. Build object(s) on one or both of these pieces
3. Build a ship depot on the two canal pieces
4. The water infrastructure total is now incorrect
5. Removing the ship depot and canal pieces now leaves a water infrastructure of 1 or 2 (depending on whether one or both tiles had objects).

### PR DESCRIPTION
**Pull request by JGRennison**
## Motivation / Problem

See #10419

Building docks has the same failure cases as ship depots, above.

## Description

Fix water infrastructure accounting when building a ship depot or dock over an object on a canal.

## Limitations

N/A

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by glx22 — DISMISSED** [review]

File: src/station_cmd.cpp [hunk 1]
```diff
@@ -2535,14 +2535,15 @@ CommandCost CmdBuildDock(DoCommandFlag flags, TileIndex tile, StationID station_
...
+		st->ship_station.Add(flat_tile);
 		st->AddFacility(FACIL_DOCK, tile);
 
 		st->rect.BeforeAddRect(dock_area.tile, dock_area.w, dock_area.h, StationRect::ADD_TRY);
 
 		/* If the water part of the dock is on a canal, update infrastructure counts.
-		 * This is needed as we've unconditionally cleared that tile before. */
-		if (wc == WATER_CLASS_CANAL) {
+		 * This is needed as we've cleared that tile before. */
+		if (wc == WATER_CLASS_CANAL && !(HasTileWaterClass(flat_tile) && GetWaterClass(flat_tile) == WATER_CLASS_CANAL && IsTileOwner(flat_tile, _current_company))) {
```
Comment (rubidium42) [inline src/station_cmd.cpp:2548]: Oh, how fun that `ClearTile` for objects does not actually clear the tile but removes the object. That might be messing more things up; maybe also locks?
Maybe at add a note in the comment in these places that for `MP_OBJECT` clearing could yield a `MP_WATER` tile instead of `MP_CLEAR`? I got very confused by this, as it did clear so the tile should have been `MP_CLEAR` and as such the `HasTileWaterClass` would already/still be returning false.

**Review by rubidium42 — APPROVED** [review]
Thanks for the comment update.
