### PR TITLE
Fix #15105: Czech townname generation causing crashes.

### LINKED ISSUE #15105: [Crash]: When generating new map with czech names
### Version of OpenTTD

15.0, openttd-15.0-5.fc43.x86_64, Fedora Linux 43 KDE Plasma

### Steps to reproduce

1. town names = czech
2. click on Generate

### Upload crash files

[crash.zip](https://github.com/user-attachments/files/24592760/crash.zip)

### PR DESCRIPTION
**Pull request by ronvid**
## Motivation / Problem
#15105 

## Description
Generating towns with Czech names causes crashes. This was due to an access on the prefixes with `poststr[2]`, despite all possible prefixes are only of length 2. Changing it to `poststr[1]` should produce the intended behavior according to the comment in code.
There was also redundant code, that is never executed using the values from `_name_czech_subst_postfix`. This was also removed. Those were:
`postlen < 2` all possible values are of length 2.
`postlen > endlen` there are no possible values for `endlen` (from `_name_czech_subst_ending[]`) that are shorter than postlen.
And the following switch case, because while there are possible values that match `endstr[0] == 'i'`, there are no possible values for the `poststr` that end with `k` or `h`.

## Limitations
The code removals do not change functionality for the given values of the Czech townname generation. It could only create unintended names, if someone were to add new (and longer) values for `_name_czech_subst_postfix`, which seems unlikely.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by LordAro — COMMENTED** [review]
Nice! Assigning @glx22 for review because I know he's looked into it already :)

File: src/townname.cpp [hunk 1]
```diff
@@ -706,20 +706,9 @@ static void MakeCzechTownName(StringBuilder &builder, uint32_t seed)
 			assert(postlen > 0 && endlen > 0);
 
 			/* Kill the "avava" and "Jananna"-like cases */
-			if (postlen < 2 || postlen > endlen ||
```
Comment (rubidium42) [inline src/townname.cpp:709]: With a unit test comparing the old and new code I can confirm these two aren't needed; for all seeds the strings are the same.

File: src/townname.cpp [hunk 2]
```diff
@@ -706,20 +706,9 @@ static void MakeCzechTownName(StringBuilder &builder, uint32_t seed)
...
-
-				/* k-i -> c-i, h-i -> z-i */
-				if (endstr[0] == 'i') {
-					std::string &str = builder.GetString();
-					switch (str.back()) {
-						case 'k': str.back() = 'c'; break;
-						case 'h': str.back() = 'z'; break;
-						default: break;
-					}
-				}
```
Comment (rubidium42) [inline src/townname.cpp:722]: With a unit test comparing the old and new code I can confirm these two aren't needed; for all seeds the strings are the same.

File: src/townname.cpp [hunk 3]
```diff
@@ -706,20 +706,9 @@ static void MakeCzechTownName(StringBuilder &builder, uint32_t seed)
 			assert(postlen > 0 && endlen > 0);
 
 			/* Kill the "avava" and "Jananna"-like cases */
-			if (postlen < 2 || postlen > endlen ||
-					((poststr[1] != 'v' || poststr[1] != endstr[1]) &&
-					poststr[2] != endstr[1])) {
+			if ((poststr[1] != 'v' || poststr[1] != endstr[1]) &&
+					poststr[1] != endstr[0]) {
```
Comment (rubidium42) [inline src/townname.cpp]: This change actually affects the output. Given the logic it shouldn't cause any problems with duplicate town names, but I haven't had the time to validate that.

**Review by rubidium42 — COMMENTED** [review]
The `assert` at line 706 is broken/pointless, as all the strings are at least one character. However, it should have checked for being longer than 2 characters to guard the later if-statement. 
I would suggest just removing the assert and the two `len` variables.

File: src/townname.cpp (hunk 2 above)
Comment (glx22) [reply src/townname.cpp:722]: Just looking at the different `_name_czech_subst_postfix` array, I could say this code was never used.

I think it's in the wrong place, looking at `_name_czech_subst_stem` it could actually have a use when `_name_czech_subst_postfix` is skipped, but it's skipped with it.

I'd move it outside of `_name_czech_subst_postfix` handling based on the intended behaviour in the comment and since combinations of `_name_czech_subst_stem` and `_name_czech_subst_ending` can have `ki` or `hi` when not using `_name_czech_subst_postfix`.

Comment (ronvid) [reply src/townname.cpp:722]: Moved it out of the mentioned `_name_czech_subst_postfix` handling. Also had to move out the `endstr`, because it is needed for both parts.

File: src/townname.cpp [hunk 4]
```diff
@@ -697,29 +697,24 @@ static void MakeCzechTownName(StringBuilder &builder, uint32_t seed)
...
+		/* k-i -> c-i, h-i -> z-i */
+		if (endstr[0] == 'i') {
+			std::string &str = builder.GetString();
+			switch (str.back()) {
+				case 'k': str.back() = 'c'; break;
+				case 'h': str.back() = 'z'; break;
+				default: break;
 			}
 		}
 		builder += _name_czech_subst_ending[ending].name;
```
Comment (glx22) [inline src/townname.cpp]:
```suggestion
		builder += endstr;
```

**Comment by rubidium42** [comment]
The old system resulted in 143253 unique names. Of those 5738 changed, and there are 4066 fewer names.

There are 6123 (about 1 in 25) of those old unique names that map to a new name that has more than one old name. These will cause collisions.

For example: old version town names Bažanná, Baženná, Bažná and Bažonná will all be Bažná with the new version.

[The mapping of old to new names](https://github.com/user-attachments/files/25136875/unique.csv)

So the real question is: are we going to fix the crash and remove all the code that wasn't executed, or are we going to fix the code based on the documented logic and have issues with duplicate town names?

**Comment by glx22** [comment]
Yeah new version seems to do what was expected by the comments.
Duplicates only happen for existing savegames, but that can be an issue (most likely only visual but we might get reports about that).

**Comment by rubidium42** [comment]
I have looked into the past of this town name generator, and since the introduction of the dynamic generation in [svn r1929](https://github.com/OpenTTD/OpenTTD/commit/d0f9cc27a3b1709ca0a6a8b466f87be8d6e5f8a7) and [svn r1930](https://github.com/OpenTTD/OpenTTD/commit/2a78d3efa9dabae2bbf41474fd868ee856be26b5) (20+ years ago), the code is logically the same. So essentially it never worked as intended, and contained lots of unreachable code.

Given the problems with changing/duplicate town names I would just fix the crash by removing anything that is unreachable or boils down to a no-op:
https://github.com/OpenTTD/OpenTTD/compare/master...rubidium42:czech

`poststr[2]` used to be `'\0'` and no ending is 1 character long, so `poststr[2] != endstr[1]` is always `true`. Likewise `postlen` is always 2 and `endlen` is always 2 or larger, making `postlen < 2 || postlen > endlen` always be `false`.

The whole character replacement looks at the last character of the buffer after the `poststr` has been appended. That always ends in a 'n', 't' or 'v' and therefore the switch does not trigger and that whole branch is dead code.

**Comment by ronvid** [comment]
Decided to go with rubidium's suggestion, to prevent the issues with duplicate townnames.

**Review by rubidium42 — APPROVED** [review]
