### PR TITLE
Fix #13668, fd2949d: Include the `\0` in TextBuf  max_chars cropping

### LINKED ISSUE #13668: [Bug]: Attempting to rename most vehicle infrastructure with strings with length >=32 characters causes game to crash
### Version of OpenTTD

latest nightly 20250227, Windows 10

### Expected result

(Submitted as bug since behavior seems to be consistent.)

When placing infrastructure such as depots, airports, docks, waypoints, etc, their names are inherited by the nearest town, for instance "Little Brinningstone Falls Train Depot". If we wish to rename the depot, a new text field dialog should pop up with the string `Little Brinningstone Falls Trai`  (string gets truncated to the 32 char limit) pre-filled in order to allow us to edit the name.

Here's 15.0-beta1 working correctly:
Image

### Actual result

Attempting to change the name of a depot, airport, waypoint, dock, etc. that **exceeds 31 characters** of length, for example "Little Brinningstone Falls Train Depot" (38 characters), doesn't show any dialog to edit the name and instead will cause the game to fatally crash with the following message:

* `Assertion failed at line 449 of D:\a\OpenTTD\OpenTTD\src\textbuf.cpp: this-> chars <= this-> max_chars`

Image

This issue affects _train depots, road vehicle depots, ship depots, docks, airports, and waypoints._ ~Train stations are not affected.~ [Edit: they are, as well as buoys, as James points out in the comments..]

### Steps to reproduce

1. In a new game map, rename a town or choose one has a name that, combined with "Train Depot", will be 32 or longer characters.
2. Place a train depot within the jurisdiction of such town.
3. Click on the building, then choose "Change name of depot."

### PR DESCRIPTION
**Pull request by glx22**
## Motivation / Problem
`TextBuf::max_chars` includes the `\0`.
https://github.com/OpenTTD/OpenTTD/commit/fd2949d5594fcecaaf1c020b06247d58c1316e22 accidentally removed a `+ 1` corresponding to this `\0`.
This cause the `TextBuf::buf` to be 1 char too long and triggers an assert in `Textbuf::UpdateSize()`.

## Description
Count the `\0` when cropping the text to `TextBuf::max_chars`.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/textbuf.cpp [hunk 1]
```diff
@@ -427,7 +427,7 @@ void Textbuf::Assign(const std::string_view text)
 	/* Make sure the name isn't too long for the text buffer in the number of
 	 * characters (not bytes). max_chars also counts the '\0' characters. */
 	auto iter = this->buf.begin();
-	for (size_t len = 0; len < this->max_chars && iter != this->buf.end(); ++len) Utf8Consume(iter);
+	for (size_t len = 1; len < this->max_chars && iter != this->buf.end(); ++len) Utf8Consume(iter);
```
Comment (PeterN) [inline src/textbuf.cpp:430]: Could do with a little explanation, probably as part of the `max_chars also counts the '\0' characters` comment.

**Review by LordAro — COMMENTED** [review]
Ooi, why not alter max_chars to not include the \\0? Naively it seems like the better change, now that it's a std::string

**Review by PeterN — APPROVED** [review]
Not crashing with the existing way is probably better than waiting for someone to change the behaviour.
