### PR TITLE
[OSX] Minor 2D scrolling fixes

### LINKED ISSUE #6558: [OSX] "Scrollwheel: Scroll map" causes window focus to follow mouse on macOS 10.12.4 (Sierra)
**_andythenorth_ opened the ticket and wrote:**

> On macOS (OS X) 10.12.4 (Sierra) setting "Function of scrollwheel" to "Scroll map" causes the game window focus to follow the mouse cursor, intermittently.  
> 
> Present in multiple OpenTTD versions, self-compiled (around r27848), and from compile farm (1.6.1).  Cannot reproduce with 1.3.0 (doesn't mean it's not there, but couldn't trigger it).  
> 
> Using a trackpad with two-finger scroll, not a scrollwheel, but eh, should be same result to the OS.
> I have tried independently toggling all the OS-level trackpad and scroll settings, including the accessibility settings, but nothing I tried made a difference.
> No access right now to older OS X versions to test, but I can do that at another time.
> 
> The effect *is* intermittent, but relatively easy to reproduce.  
> \- can be triggered always on the newgrf window at game start screen, by opening newgrf settings window, then a parameters window (which will initially open behind the newgrf settings window, incorrectly)
> \- can be triggered in game by e.g. opening a depot, then 'build vehicles'.  Focus-follows-mouse tends to stop periodically, for undetermined reasons, but can be reliably re-started by using scroll on a game window such as depot or vehicles. 
> 
> I have not been able to reproduce the issue with "Function of scrollwheel: Zoom map" or "Function of scrollwheel: Off".

**Reported version**: _trunk_
**Operating system**: _Mac OS X_

---

### PR DESCRIPTION
**Pull request by alexanderweiss**
- Fixed unintended window focused (fixes #6558) by resetting 2D scrolling values when the interaction isn't 2D scrolling.
- Improved 2D scrolling responsiveness by not reset the 2D scrolling values the first time the 2D scrolling event is triggered.
- Fixed 2D scrolling not working when setting viewport scrolling to use left mouse button (issue introduced in cfe6a8ea4fc38d58babcc6e7b67a9185ee66078c)

Note: these changed were originally included in #6753.

### CODE REVIEW

File: src/window.cpp [hunk 1]
```diff
@@ -2903,19 +2904,28 @@ static void MouseLoop(MouseClick click, int mousewheel)
...
 			case MC_DOUBLE_LEFT:
 				DispatchLeftClickEvent(w, x - w->left, y - w->top, click == MC_DOUBLE_LEFT ? 2 : 1);
-				break;
+				return;
 
 			default:
 				if (!scrollwheel_scrolling || w == NULL || w->window_class != WC_SMALLMAP) break;
 				/* We try to use the scrollwheel to scroll since we didn't touch any of the buttons.
 				 * Simulate a right button click so we can get started. */
 				FALLTHROUGH;
```
Comment (PeterN) [inline src/window.cpp:2913]: Looks like scrollwheel scrolling doesn't simulate a right click any more (good!) in which case none of this default case should be necessary?

File: src/window.cpp [hunk 2]
```diff
@@ -2903,19 +2904,28 @@ static void MouseLoop(MouseClick click, int mousewheel)
...
+			case MC_HOVER:
+				DispatchHoverEvent(w, x - w->left, y - w->top);
+				break;
 		}
 	}
+
+	/* We're not doing anything with 2D scrolling, so reset the value.  */
+	_cursor.h_wheel = 0;
+	_cursor.v_wheel = 0;
+
```
Comment (PeterN) [inline src/window.cpp]: Spurious extra blank line here

**Review by PeterN — CHANGES_REQUESTED** [review]
Makes sense, could you just tidy up that blank line please

File: src/window.cpp (hunk 1 above)
Comment (alexanderweiss) [reply src/window.cpp:2913]: Not quite true: it doesn't simulate right click in a viewport, but does still in any other window. So this default case is still necessary. I could separate scrollwheel scrolling for generic window handling just as I've done for viewport handling.

**Comment by alexanderweiss** [comment]
No problem. Now with one line less @PeterN.

File: src/window.cpp (hunk 1 above)
Comment (PeterN) [reply src/window.cpp:2913]: I think not for now. In the future I'd like to see the event handling reworked including handling scrolling events properly, but for a fix this is fine.

Comment (alexanderweiss) [reply src/window.cpp:2913]: Yes, as I remarked in #6753, there's also some unused logic. So it could use some cleaning up anyways.

**Review by PeterN — APPROVED** [review]
