### PR TITLE
Fix #10502: Refit engine before attaching free wagons.

### LINKED ISSUE #10502: [Crash]: Fatal Application Failure whilst buying an engine
### Version of OpenTTD

13.0 (0), Windows 11

### Steps to reproduce

I'd been playing for a couple of hours without issue.  The only thing I did different than the rest of the play time was rather than buying an engine and then the carriages, I bought a passenger carriage first and then tried to buy an engine and that's when it crashed.  That may have nothing to do with the crash, but it's the last thing I did.

### Upload crash files

[crash20230222200009.zip](https://github.com/OpenTTD/OpenTTD/files/10807987/crash20230222200009.zip)

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

As per #10502, NewGRFs can cause a game crash due to a bug in the order of operations when buying a train engine, as free wagons are attached to the engine before refitting.

## Description

This is resolved by attaching free wagons after the train engine has been refitted.

## Limitations

None

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by PeterN** [comment]
I've now been able to test this and it does resolve the issue.

File: src/vehicle_cmd.cpp [hunk 1]
```diff
@@ -172,6 +172,10 @@ std::tuple<CommandCost, VehicleID, uint, uint16, CargoArray> CmdBuildVehicle(DoC
 		}
 
 		if (flags & DC_EXEC) {
+			if (type == VEH_TRAIN && use_free_vehicles && !(flags & DC_AUTOREPLACE)) { // check if the cars should be added to the new vehicle
```
Comment (TrueBrain) [inline src/vehicle_cmd.cpp]: I know it is existing code, but please move that comment before the if-statement. Tnx :)

Comment (PeterN) [reply src/vehicle_cmd.cpp]: It is a poor comment really, as the only "check" is do the parameters ask for it. So hopefully better comment on next line.

**Review by frosch123 — APPROVED** [review]
