### PR TITLE
Fix #14234, 16b4e73: Skip PLURAL data if parameter is invalid.

### LINKED ISSUE #14234: [Crash]: Placing goods station next to police station
### Version of OpenTTD

15.0-beta2, Debian 12 stable

### Steps to reproduce

1. Placed a goods station next to police station
2. Game crashed
3. It is reproducible, crashed 3 times in a row

### Upload crash files

[crashreport.zip](https://github.com/user-attachments/files/20093360/crashreport.zip)

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

As per #14234, the game can crash when formatting a string (in this case, related to a station)

In this case this happens because a NewGRF references strings in invalid contexts. One of these strings tried to use a plural form, and because the parameter is missing, the processing the plural is skipped.

This unfortunately then leaves the data of the plural itself in the string buffer, which will be read as regular characters. If a NUL character is reached, the game will assert. Before StringConsumer, the NUL character would simply have terminated string processing, thus hiding this error.

## Description

Fixed this situation by skipping the data of a plural even if the parameter is invalid.

The NewGRF still uses an incorrect string, and the output is still (presumably) not intended.

But it doesn't crash now.

## Limitations

Skipping GENDER may need something similar.

EDIT: Looks like in the case of GENDER it's still processed, just with the first gender.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/strings.cpp [hunk 1]
```diff
@@ -765,6 +765,16 @@ static int DeterminePluralForm(int64_t count, uint plural_form)
 	}
 }
 
+static void SkipStringChoice(StringConsumer &consumer)
+{
+	uint n = consumer.ReadUint8();
+	uint len = 0;
```
Comment (glx22) [inline src/strings.cpp:771]: `ParseStringChoice` uses `size_t` for the length.

**Review by glx22 — APPROVED** [review]
The minor diff for length variables types is not blocking.
