### PR TITLE
Fix #14277: Aircraft can land when Zeppeliner in the runway

### LINKED ISSUE #14277: [Bug]: Aircraft can land with a crashed Zeppelin in the runway
### Version of OpenTTD

OpenTTD 20250518-master-g9bbc525e53

### Expected result

Aircraft in the air should circle around the airport. Aircraft in the terminal should not depart.

### Actual result

Aircraft can use airport with a crashed zeppelin in it.

### Steps to reproduce

[crashed zeppelin at airport.sav.zip](https://github.com/user-attachments/files/20272812/crashed.zeppelin.at.airport.sav.zip)
Look at Wrondinghead Airport with a crashed Zeppelin.

### PR DESCRIPTION
**Pull request by ivpravdin**
## Motivation / Problem

Fix #14277: Aircraft can land with a crashed Zeppelin in the runway

It is possible for aircrafts to lend when Zeppelin is in the runway. This does not happen all the time but only when an aircraft block runway at the time of the crash.

## Description

To resolve this issue, create new Zeppeliner AirportBlock. When this block is set, aircraft that currently hold the runway block will not clear its blocks when it moves to the next location, ultimately preventing other planes from landing/taking off.

## Limitations

~~Currently an aircraft that is landing will still land even if the Zeppeliner is in the way.~~
In new patch version, approaching aircraft will abort landing if Zeppeliner crashes

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/aircraft_cmd.cpp [hunk 1]
```diff
@@ -1782,6 +1791,11 @@ static void AirportClearBlock(const Aircraft *v, const AirportFTAClass *apc)
 	if (apc->layout[v->previous_pos].blocks != apc->layout[v->pos].blocks) {
 		Station *st = Station::Get(v->targetairport);
 
+		if (st->airport.blocks.Test(AirportBlock::Zeppeliner) &&
+				(apc->layout[v->previous_pos].blocks == AirportBlock::RunwayIn)) {
```
Comment (rubidium42) [inline src/aircraft_cmd.cpp]:
```suggestion
				apc->layout[v->previous_pos].blocks == AirportBlock::RunwayIn) {
```
The extra parentheses are not needed.

File: src/disaster_vehicle.cpp [hunk 2]
```diff
@@ -263,6 +263,7 @@ static bool DisasterTick_Zeppeliner(DisasterVehicle *v)
 
 		if (IsValidTile(v->tile) && IsAirportTile(v->tile)) {
 			Station *st = Station::GetByTile(v->tile);
+			st->airport.blocks.Reset(AirportBlock::Zeppeliner);
 			st->airport.blocks.Reset(AirportBlock::RunwayIn);
```
Comment (rubidium42) [inline src/disaster_vehicle.cpp]:
```suggestion
			st->airport.blocks.Reset({AirportBlock::Zeppeliner, AirportBlock::RunwayIn});
```
These enum bitsets allow passing multiple enums at once.

File: src/disaster_vehicle.cpp [hunk 3]
```diff
@@ -300,7 +301,9 @@ static bool DisasterTick_Zeppeliner(DisasterVehicle *v)
 	}
 
 	if (IsValidTile(v->tile) && IsAirportTile(v->tile)) {
-		Station::GetByTile(v->tile)->airport.blocks.Set(AirportBlock::RunwayIn);
+		Station *st = Station::GetByTile(v->tile);
+		st->airport.blocks.Set(AirportBlock::Zeppeliner);
+		st->airport.blocks.Set(AirportBlock::RunwayIn);
```
Comment (rubidium42) [inline src/disaster_vehicle.cpp]:
```suggestion
		st->airport.blocks.Set({AirportBlock::Zeppeliner, AirportBlock::RunwayIn});
```
The intermediate variable `st` could be also removed.

File: src/airport.h [hunk 4]
```diff
@@ -124,6 +124,7 @@ enum class AirportBlock : uint8_t {
 	RunwayOut2       = 10, ///< @note re-uses #AirportBlock::TaxiwayBusy
 	HelipadGroup     = 13, ///< @note re-uses #AirportBlock::AirportEntrance
 	OutWay3          = 31,
+	Zeppeliner       = 32, ///< Block for the zeppeliner disaster vehicle.
```
Comment (rubidium42) [inline src/airport.h]: Maybe this 'special' block state with extra features should be next to `AirportClosed`, i.e. with a value of `62`. That way eventual future functional blocks can remain contiguous.

**Review by rubidium42 — COMMENTED** [review]
Mostly cosmetic changes.

I was questioning the need for a new block, but after landing the aircraft will still occupy the `RunwayIn` (or `RunwayInOut` or `AirportBusy` [different names for the same ID]) block. So when they leave the runway, usually while the zeppeliner is still falling, they'd open up the airport again. So it does indeed seem like the new block is needed.

**Comment by ivpravdin** [comment]
> I was questioning the need for a new block, but after landing the aircraft will still occupy the `RunwayIn` (or `RunwayInOut` or `AirportBusy` [different names for the same ID]) block. So when they leave the runway, usually while the zeppeliner is still falling, they'd open up the airport again. So it does indeed seem like the new block is needed.

Yes, unfortunately blocks do not store information about who holds it. Thanks for the feedback!

**Review by rubidium42 — APPROVED** [review]
