### PR TITLE
Fix #10361, fe30f66: Don't try to give saved data to a dead script

### LINKED ISSUE #10361: [Crash]: GS crashes OpenTTD with malformed comment prefix
### Version of OpenTTD

750d89d37b372b808e616091913f7e48f6d4d0ea but rev is probably not significant

### Steps to reproduce

Use a python-style comment by mistake in a GS/squirrel .nut file.

E.g. 

`# foo`

instead of

`// foo`

### Upload crash files

```
[2023-01-15 23:34:24] dbg: [script] [18] [S] Error /Users/cabbage/Documents/OpenTTD/game/firs-gs/temp_prototyping.nut:59/10: expression expected
[2023-01-15 23:34:24] dbg: [misc] [squirrel] Failed to compile '/Users/cabbage/Documents/OpenTTD/game/firs-gs/temp_prototyping.nut'
[2023-01-15 23:34:24] dbg: [script] [18] [S] Your script made an error: expression expected
[2023-01-15 23:34:24] dbg: [script] [18] [S] 
[2023-01-15 23:34:24] dbg: [script] [18] [S] *FUNCTION [main()] /Users/cabbage/Documents/OpenTTD/game/firs-gs/main.nut line [55]
[2023-01-15 23:34:24] dbg: [script] [18] [S] 
[2023-01-15 23:34:24] dbg: [script] [18] [S] [this] TABLE
[2023-01-15 23:34:24] dbg: [misc] [squirrel] Failed to compile '/Users/cabbage/Documents/OpenTTD/game/firs-gs/main.nut'
[2023-01-15 23:34:24] dbg: [script] The script died unexpectedly.
Crash encountered, generating crash log...
*** OpenTTD Crash Report ***

Crash at: 2023-01-15 23:34:24 (UTC)
In game date: 1900-10-13 (45)

Crash reason:
 Signal:  Segmentation fault: 11 (11)
 Message: <none>

OpenTTD version:
 Version:    20230115-master-m96ec9908a0 (2)
 NewGRF ver: 1e006d64
 Bits:       64
 Endian:     little
 Dedicated:  no
 Build date: Jan 15 2023 15:12:49


Stacktrace:
 [00] openttd              0x00000001006bf16c (CrashLog::FillCrashLog(char*, char const*) const + 368)
 [01] openttd              0x0000000100598558 (CrashLogOSX::MakeCrashLog() + 100)
 [02] openttd              0x0000000100598448 (HandleCrash(int) + 276)
 [03] libsystem_platform.dylib 0x00000001a86434a4 (_sigtramp + 56)
 [04] openttd              0xba798001003b29c4 (Game::StartNew() + -5009832372984610448)
 [05] openttd              0x00000001003b29c4 (Game::StartNew() + 368)
 [06] openttd              0x00000001005d5a44 (AfterLoadGame() + 54380)
 [07] openttd              0x0000000100611ffc (DoLoad(LoadFilter*, bool) + 3348)
 [08] openttd              0x0000000100612884 (SaveOrLoad(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, SaveLoadOperation, DetailedFileType, Subdirectory, bool) + 1404)
 [09] openttd              0x000000010081b064 (SafeLoad(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, SaveLoadOperation, DetailedFileType, GameMode, Subdirectory, LoadFilter*) + 212)
 [10] openttd              0x000000010081b86c (SwitchToMode(SwitchMode) + 1468)
 [11] openttd              0x000000010081f62c (GameLoop() + 472)
 [12] openttd              0x0000000100655e8c (VideoDriver::GameLoop() + 116)
 [13] openttd              0x00000001006560ac (VideoDriver::GameThreadThunk(VideoDriver*) + 80)
 [14] openttd              0x0000000100656984 (void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, bool StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::__1::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::'lambda'(char const*, void (*&&)(VideoDriver*), VideoDriver*&&), char const*, void (*)(VideoDriver*), VideoDriver*> >(void*) + 84)
 [15] libsystem_pthread.dylib 0x00000001a862c26c (_pthread_start + 148)
 [16] libsystem_pthread.dylib 0x885e8001a862708c (thread_start + -8620311899252195320)

Operating system:
 Name:     Mac OS X
 Release:  12.6.2
 Machine:  ARM64E
 Min Ver:  101300
 Max Ver:  130100
 Compiler: GCC 4.2.1 "Apple LLVM 14.0.0 (clang-1400.0.29.202)"

Configuration:
 Blitter:      40bpp-anim
 Graphics set: original_windows (0)
 Language:     /Users/cabbage/stuff/build/lang/english.lng
 Music driver: cocoa
 Music set:    original_windows (1)
 Network:      no
 Sound driver: cocoa
 Sound set:    original_windows (0)
 Video driver: cocoa-opengl (Apple M1 Pro, 4.1 Metal - 76.3)

Fonts:
 Small:  sprite
 Medium: sprite
 Large:  sprite
 Mono:   sprite

AI Configuration (local: 0) (current: 18):
  0: Human
 GS: FIRS GS (v1)

Libraries:
 LZMA:       5.0.5
 LZO:        2.10
 PNG:        1.6.39
 Zlib:       1.2.11

---- gamelog start ----
Tick 0: new game started
Revision text changed to m96ec9908a051f, savegame version 302, modified, _openttd_newgrf_version = 0x1e006d64
New game mode: 1 landscape: 0
Added NewGRF: GRF ID 43415000, checksum FBAE0C1ACFDA5AE8B95B4DA230A395FE, filename: opengfx_airports-0.5.0/ogfx-airports.grf (md5sum matches)
Added NewGRF: GRF ID 9787EAFE, checksum 04ACD20A006E345283D6464678AFFA8B, filename: road_hog-1.4.1/road-hog.grf (md5sum matches)
Added NewGRF: GRF ID 44440A80, checksum 2F7F4BC7FBAD4544CA241DFE6D5A6F39, filename: av9.8-0.97/av9point8.grf (md5sum matches)
Added NewGRF: GRF ID FBFB9905, checksum F747797A14AAA646402DC4E16DE5E82C, filename: longer_girder__steel_bridge.1/longergirdersteelbridge.grf (md5sum matches)
Added NewGRF: GRF ID 55535333, checksum 7648EE94EC567D8931F691AAA5BCF912, filename: unsinkable-sam.grf (md5sum matches)
Added NewGRF: GRF ID 43485054, checksum F09180381B487C911D5EAF5DFF4FDDF2, filename: chips_station_set_2-2.0.0/chips.grf (md5sum matches)
Added NewGRF: GRF ID 54540301, checksum F7CDD4F730E4F3EE87100CE42E5070AE, filename: itl_houses-2.1/itl_houses.grf (md5sum matches)
Added NewGRF: GRF ID F1250008, checksum 1C665399A6ED1E6DD57D53D6FBB17DA1, filename: firs-crustywell-game.grf (matches GRFID only)
Added NewGRF: GRF ID 43411222, checksum 7E62085010B3FB43CAA1F9116655405E, filename: iron-horse.grf (md5sum matches)
Tick 14816: GRF config changed
Added NewGRF: GRF ID 41501202, checksum B13DD8FB0D7C34CACAC2FE68BD137BB9, filename: heqs_heavy_equipment_set-1.5.2/heqs.grf (md5sum matches)
Tick 24462: game loaded
New game mode: 2 landscape: 0
Tick 24462: game loaded
New game mode: 1 landscape: 0
Tick 27309: game loaded
New game mode: 2 landscape: 0
Compatible NewGRF loaded: GRF ID F1250008, checksum 3CCB099044174030418F5072010454C3, filename: firs-crustywell-game.grf (matches GRFID only)
Tick 27309: game loaded
New game mode: 1 landscape: 0
Tick 48444: game loaded
Compatible NewGRF loaded: GRF ID F1250008, checksum 31DDF2236B86CCA6735E56F590C29202, filename: firs.grf (md5sum matches)
---- gamelog end ----

Recent news messages:

*** End of OpenTTD Crash Report ***

Crash log generated.

Writing crash log to disk...
Writing crash savegame...
Writing crash screenshot...
[2023-01-15 23:34:24] dbg: [misc] /Users/cabbage/stuff/src/game/game_core.cpp:88: Backed-up value was not restored!
[2023-01-15 23:34:24] dbg: [sl] Game Save Failed
(undefined string)
^C
```

### PR DESCRIPTION
**Pull request by glx22**
Fixes #10361

## Motivation / Problem
Syntax error kills the script but loading script saved data requires a non dead script.

## Description
Check the script is alive before trying to load the data.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/script/script_instance.cpp [hunk 1]
```diff
@@ -691,7 +691,7 @@ void ScriptInstance::LoadOnStack(ScriptData *data)
 {
 	ScriptObject::ActiveInstance active(this);
 
-	if (data == nullptr) return;
+	if (this->IsDead() || data == nullptr) return;
```
Comment (rubidium42) [inline src/script/script_instance.cpp:694]: Not necessarily for this PR, but shouldn't the `ScriptData` be released somewhere when the script is dead?

**Review by michicc — APPROVED** [review]

File: src/script/script_instance.cpp (hunk 1 above)
Comment (glx22) [reply src/script/script_instance.cpp:694]: It is released on any case after the call to `ScriptInstance::LoadOnStack()`
