### PR TITLE
Fix #10405, a3dd750: [Script] Test engine and vehicle type validity for ScriptGroup::GetNumEngines

### LINKED ISSUE #10405: [Crash]: OpenTTD asserts when ScriptGroup.GetNumEngines passes an invalid engine, or an engine of a different vehicle type of that of the group
### Version of OpenTTD

13.0-RC1, Windows 11 Pro

### Steps to reproduce

On ScriptGroup.GetNumEngines, if you pass an invalid engine, or an engine of a different vehicle type of that of the group, openttd asserts

### Upload crash files

passing invalid engine -> [crash20230124113146.zip](https://github.com/OpenTTD/OpenTTD/files/10489167/crash20230124113146.zip)

passing engine of a different vehicle type of that of the group -> [crash20230124113929.zip](https://github.com/OpenTTD/OpenTTD/files/10489199/crash20230124113929.zip)

### PR DESCRIPTION
**Pull request by SamuXarick**
## Motivation / Problem
Fix #10405 

## Description
This fixes a crash that would occur if GetNumEngines was passed an invalid engine or an engine of a different vehicle type of that of the group.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/script/api/script_group.hpp [hunk 1]
```diff
@@ -128,7 +128,9 @@ class ScriptGroup : public ScriptObject {
 	 * Get the number of engines in a given group.
 	 * @param group_id The group to get the number of engines in.
 	 * @param engine_id The engine id to count.
+	 * @pre ScriptEngine::IsValidEngine(engine_id).
 	 * @pre IsValidGroup(group_id) || group_id == GROUP_ALL || group_id == GROUP_DEFAULT.
+	 * @pre !IsValidGroup(group_id) || ScriptEngine::GetVehicleType(engine_id) == GetVehicleType(group_id).
```
Comment (2TallTyler) [inline src/script/api/script_group.hpp]: `!IsValidGroup(group_id)` conflicts with the line above. Isn't `valid_group` checked in the code just to short_circuit GetVehicleType() if the group is invalid?

I think the precondition is just ensuring the type is the same.
```suggestion
	 * @pre ScriptEngine::GetVehicleType(engine_id) == GetVehicleType(group_id).
```

Comment (SamuXarick) [reply src/script/api/script_group.hpp]: `GROUP_ALL` and `GROUP_DEFAULT` are not valid groups. For these two, the vehicle type is extracted inside `GetGroupNumEngines`, from the `engine_id`.

Comment (2TallTyler) [reply src/script/api/script_group.hpp]: I'm not questioning your code, but the precondition documentation (which does not match the code).

Comment (SamuXarick) [reply src/script/api/script_group.hpp]: Sorry, I disagree.
It's either
`* @pre !IsValidGroup(group_id) || ScriptEngine::GetVehicleType(engine_id) == GetVehicleType(group_id).`
or
`* @pre group_id == GROUP_ALL || group_id == GROUP_DEFAULT || ScriptEngine::GetVehicleType(engine_id) == GetVehicleType(group_id).`

If I omit the first part, `ScriptEngine::GetVehicleType(engine_id) == GetVehicleType(group_id)` will run erroneously for `GROUP_DEFAULT` or `GROUP_ALL`.

Comment (glx22) [inline src/script/api/script_group.hpp]:
```suggestion
	 * @pre (IsValidGroup(group_id) && ScriptEngine::GetVehicleType(engine_id) == GetVehicleType(group_id)) || group_id == GROUP_ALL || group_id == GROUP_DEFAULT.
```

**Review by glx22 — APPROVED** [review]
