### PR TITLE
Fix #14701: Company colour remap for sprites in badge filter dropdowns.

### LINKED ISSUE #14701: [Bug]: no company colour remap for sprites in badge filter dropdowns
### Version of OpenTTD

a617d009cca418255a9682fd83c9cebc6423303e

### Expected result

Sprites in badge filter dropdown have company colour applied.

### Actual result

Sprites in badge filter dropdown don't have company colour applied (should be red / white in the screenshot, not blue / green).   In the screenshot, the badge for "Basic Banger" is approximately vertically aligned with a train example for it in buy menu.

Image

### Steps to reproduce

Use attached Iron Horse.  Start around 2000 if you want to compare intended appearance (buy menu badge) vs. actual (filter dropdown badge).
[iron-horse.grf.zip](https://github.com/user-attachments/files/22727190/iron-horse.grf.zip)

### PR DESCRIPTION
**Pull request by Rito13**
## Motivation / Problem

https://github.com/OpenTTD/OpenTTD/issues/14701
Sprites in badge filter dropdown don't have company colour applied.

## Description

Apply company colour to sprites in badge filter dropdown.
### Example screenshot
Zrzut ekranu z 2025-10-25 12-39-37

Fixes #14701.

## Limitations

Works only with the main company colour.
Zrzut ekranu z 2025-10-25 12-39-41

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/build_vehicle_gui.cpp [hunk 1]
```diff
@@ -1731,7 +1731,12 @@ struct BuildVehicleWindow : Window {
 
 			default:
 				if (IsInsideMM(widget, this->badge_filters.first, this->badge_filters.second)) {
-					ShowDropDownList(this, this->GetWidget<NWidgetBadgeFilter>(widget)->GetDropDownList(), -1, widget, 0, false);
+					const Company *c = Company::Get(_current_company);
+					const Livery *livery = &c->livery[LS_DEFAULT];
+					PaletteID map = (PaletteID)SPR_2CCMAP_BASE;
+					map += livery->colour1;
+					map += livery->colour2 * 16;
```
Comment (PeterN) [inline src/build_vehicle_gui.cpp]: As used elsewhere:
```c++
const Livery &l = Company::Get(_local_company)->livery[LS_DEFAULT];
PaletteID palette = SPR_2CCMAP_BASE + l.colour1 + l.colour2 * 16;
```

Comment (LordAro) [reply src/build_vehicle_gui.cpp]: Perhaps helper function?

**Review by 2TallTyler — DISMISSED** [review]
Will need a rebase once #14740 is merged, but looks good to me for now.

**Review by 2TallTyler — APPROVED** [review]
