### PR TITLE
Fix #13740: [Script] Handle implicit orders for jump orders

### LINKED ISSUE #13740: [Bug]: ScriptOrder::SetOrderJumpTo does not call ScriptOrderPositionToRealOrderPosition
### Version of OpenTTD

master

### Expected result

The code suggests that script CMD_MODIFY_ORDER commands should always use ScriptOrderPositionToRealOrderPosition to translate the order index.

### Actual result

ScriptOrder::SetOrderJumpTo does not call ScriptOrderPositionToRealOrderPosition for either of its OrderPosition arguments, unlike all the other CMD_MODIFY_ORDER script calls.
This seems like it would produce the wrong result in the presence of implicit orders.
These adjustments are added to other cases here: 1750b2ad9f7855db3d54b5104ab3e0ccbe39ab7e

I've not attempted to write a script to check if this is in fact incorrect.
Using both implicit orders and conditional jump orders also seems quite a niche case in any event.

### Steps to reproduce

See above

### PR DESCRIPTION
**Pull request by glx22**
## Motivation / Problem
All `ScriptOrder::SetOrderXXX` functions use `ScriptOrderPositionToRealOrderPosition` but `ScriptOrder::SetOrderJumpTo` does not.

`ScriptOrder::InsertConditionalOrder` has the same issue.

## Description
Use `ScriptOrderPositionToRealOrderPosition` in `ScriptOrder::SetOrderJumpTo` and `ScriptOrder::InsertConditionalOrder`.

## Limitations
Totally untested.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by PeterN — DISMISSED** [review]

File: src/script/api/script_order.cpp [hunk 1]
```diff
@@ -104,6 +104,24 @@ static int ScriptOrderPositionToRealOrderPosition(VehicleID vehicle_id, ScriptOr
...
+ * Convert an order index from OpenTTD to a ScriptOrder::OrderPosition (which is the manual order index)
+ * @param order_position The OpenTTD-internal index to convert.
+ * @return An OrderPosition for the same order.
+ */
+static ScriptOrder::OrderPosition RealOrderPositionToScriptOrderPosition(VehicleID vehicle_id, int order_position)
+{
+	const Vehicle *v = ::Vehicle::Get(vehicle_id);
+	const Order *order = v->GetFirstOrder();
+	assert(order != nullptr);
+	int res = -1;
```
Comment (SamuXarick) [inline src/script/api/script_order.cpp]:
```suggestion
	int res = 0;
```

**Comment by SamuXarick** [comment]
https://github.com/OpenTTD/OpenTTD/blob/3cb13726ad404f970eb55ddbbf380ddd246a27dc/src/order_cmd.cpp#L1336-L1338
This line should be added to prevent SetOrderJumpTo to jump to itself.
`if (v->GetOrder(data) == order) return CMD_ERROR;`

**Review by LordAro — APPROVED** [review]
