### PR TITLE
Fix #9720: Delay start of GS/AI to after loading of savegame

### LINKED ISSUE #9720: [Crash]: Can't start game with CityGrowthLimiter GS
### Version of OpenTTD

12.1 (compiled on RaspberryPi), aarch64 (RP3B+)

### Steps to reproduce

1. Open Scenario Editor
2. Configure GS CGL 
3.  Save scenario
4.  Start game with new scenario
5.  Save game to run in on Raspberry Pi
6.  Start game on RPi3B+ with command `/opt/openttd-12.1/build/openttd -D -g /root/.openttd/save/autosave/mygame.sav`
7. Crash while starting game (as dedicated server)

### Upload crash files

[crash.zip](https://github.com/OpenTTD/OpenTTD/files/7612391/crash.zip)

### PR DESCRIPTION
**Pull request by glx22**
Fixes #9720.

## Motivation / Problem
See https://github.com/OpenTTD/OpenTTD/issues/9720#issuecomment-980808344

## Description
During loading, AI/GS saved data is stored in `ScriptConfig`.
AI/GS are started after loading is fully completed.
On AI/GS start, the saved data is put on stack right after initialisation.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/openttd.cpp [hunk 1]
```diff
@@ -939,7 +940,17 @@ bool SafeLoad(const std::string &filename, SaveLoadOperation fop, DetailedFileTy
 	_game_mode = newgm;
 
 	switch (lf == nullptr ? SaveOrLoad(filename, fop, dft, subdir) : LoadWithFilter(lf)) {
-		case SL_OK: return true;
+		case SL_OK:
+			/* Start the GameScript. */
+			Game::StartNew();
```
Comment (frosch123) [inline src/openttd.cpp]: Does the GS/AI start need to check _networking and _network_server here? Or is that already done somewhere else?

I would have expected the GS/AI start at the end of "AfterLoadGame" together with "InitializeWindowsAndCaches"/"AfterLoadLinkGraphs". I am not sure whether this place is equivalent.

File: src/script/script_config.cpp [hunk 2]
```diff
@@ -238,3 +241,15 @@ const char *ScriptConfig::GetTextfile(TextfileType type, CompanyID slot) const
 
 	return ::GetTextfile(type, (slot == OWNER_DEITY) ? GAME_DIR : AI_DIR, this->GetInfo()->GetMainScript());
 }
+
+void ScriptConfig::SetToLoadData(ScriptInstance::ScriptData *data)
+{
+	if (this->to_load_data != nullptr) delete this->to_load_data;
```
Comment (frosch123) [inline src/script/script_config.cpp]: `delete nullptr` is fine.
Alternatrively could be a unique_ptr::reset()

File: src/script/script_instance.hpp [hunk 3]
```diff
@@ -25,6 +27,9 @@ class ScriptInstance {
 	friend class ScriptObject;
 	friend class ScriptController;
 
+	typedef std::variant<byte, SQInteger, std::string, SQBool> ScriptDataVariant;
```
Comment (frosch123) [inline src/script/script_instance.hpp]: Isn't the "byte" always a "SQSaveLoadType"?

File: src/openttd.cpp (hunk 1 above)
Comment (glx22) [reply src/openttd.cpp]: `StartNew()` checks `_networking` and `_network_server`.

I tried to start in "AfterLoadGame", was not a good idea as it also started them in intro game (and for dedicated servers it would start them at the end of test SaveOrLoad, then again after the real load done by `SM_LOAD_GAME` mode switch), while `SafeLoad()` is only done when switching to `SM_LOAD_GAME`

File: src/script/script_instance.hpp (hunk 3 above)
Comment (glx22) [reply src/script/script_instance.hpp]: It is, I guess I should move the enum to the header.

File: src/script/script_instance.hpp [hunk 4]
```diff
@@ -21,10 +23,25 @@ static const uint SQUIRREL_MAX_DEPTH = 25; ///< The maximum recursive depth for
...
+		SQSL_BOOL            = 0x04, ///< The following data is a boolean.
+		SQSL_NULL            = 0x05, ///< A null variable.
+		SQSL_ARRAY_TABLE_END = 0xFF, ///< Marks the end of an array or table, no data follows.
+	};
+
 public:
 	friend class ScriptObject;
 	friend class ScriptController;
 
+	typedef std::variant<SQInteger, std::string, SQBool,SQSaveLoadType> ScriptDataVariant;
```
Comment (rubidium42) [inline src/script/script_instance.hpp]: Missing space after `SQBool,`

File: src/openttd.cpp [hunk 5]
```diff
@@ -940,7 +941,17 @@ bool SafeLoad(const std::string &filename, SaveLoadOperation fop, DetailedFileTy
...
+
+			/* Start the AIs. */
+			for (const Company *c : Company::Iterate()) {
+				if (Company::IsValidAiID(c->index)) AI::StartNew(c->index, false);
+			}
+
+			ShowAIDebugWindowIfAIError();
```
Comment (rubidium42) [inline src/openttd.cpp]: I think this should be a separate function named `StartScripts()` or so. Maybe even in some file in the script folder.

File: src/script/script_instance.hpp (hunk 4 above)
Comment (rubidium42) [inline src/script/script_instance.hpp]: Are we aware that each element in `ScriptData` is `sizeof(std::string)` + overhead of variant large. So usually 40 bytes on 64 bits platforms and usually 28 bytes on 32 bit platforms. Not sure how big the impact is on memory usage, but for non-trivial savegames it might be considerable.

Comment (glx22) [reply src/script/script_instance.hpp]: `ScriptData` used memory is released when loading is done. But maybe using `std::unique_ptr<char *>` instead of `std::string` would be better.

**Review by LordAro — DISMISSED** [review]
#YOLO

**Comment by 2TallTyler** [comment]
@glx22 Needs a rebase (and someone who understands GS/AI well enough to approve/merge it 🙂 )

**Comment by glx22** [comment]
Back to draft because https://github.com/OpenTTD/OpenTTD/issues/10206#issuecomment-1334631103

**Comment by glx22** [comment]
Scripts are already not started by first commit but the saved data is still in memory and without setting `c->is_ai` to false OpenTTD assumes a script is started and crashes.
Maybe I should just merge both commits.

File: src/openttd.cpp (hunk 1 above)
Comment (glx22) [reply src/openttd.cpp]: After working on #10241, I now know scripts must be started at the end of "AfterLoadGame".

**Comment by glx22** [comment]
#10241 already fixed the crash reported in #9720, but here I'm addressing https://github.com/OpenTTD/OpenTTD/issues/9720#issuecomment-980808344

File: src/script/script_instance.cpp [hunk 6]
```diff
@@ -588,37 +577,79 @@ bool ScriptInstance::IsPaused()
...
+			if (data != nullptr) data->push_back((SQSaveLoadType)_script_sl_byte);
+			return true;
+		}
+
+		case SQSL_ARRAY_TABLE_END: {
+			if (data != nullptr) data->push_back((SQSaveLoadType)_script_sl_byte);
+			return false;
+		}
+
+		default: NOT_REACHED();
```
Comment (rubidium42) [inline src/script/script_instance.cpp]: `_script_sl_byte` is coming from the savegame, isn't it? So might throwing some error/exception that the data is corrupt be a better option than crashing the game?

File: src/script/script_instance.hpp [hunk 7]
```diff
@@ -146,11 +163,18 @@ class ScriptInstance {
...
 
 	/**
-	 * Load data from a savegame and store it on the stack.
+	 * Load data from a savegame.
 	 * @param version The version of the script when saving, or -1 if this was
 	 *  not the original script saving the game.
+	 * @return a pointer to loaded data.
 	 */
-	void Load(int version);
+	static ScriptData *Load(int version);
```
Comment (rubidium42) [inline src/script/script_instance.hpp:171]: I'm not quite fond of the two `Load` functions with the same name and wildly different behaviours. What about something like `LoadFromSavegame` and `LoadIntoInstance` (for the next function)?

**Review by rubidium42 — APPROVED** [review]
