### PR TITLE
Fix #12010: Use economy timer for vehicle stats minimum age, not calendar

### LINKED ISSUE #12010: [Bug]: Vehicle profit/loss indicators use calendar age of vehicle, and may have eternal youth
### Version of OpenTTD

14.0-beta2

### Expected result

Profit/loss icons in vehicle lists show "too new" if a vehicle hasn't been driving around long enough to have meaningful stats. Then, after a time, they show whether it's making money or operating at a loss.

### Actual result

Vehicle age is calendar-based and these stats look at the vehicle age. But if the calendar progression rate is slowed down, they show "too new" for too long, and if it is frozen they will be "too new" forever.

### Steps to reproduce

1. Freeze calendar time.
2. Build a vehicle and wait (forever) for it to show a profit/loss icon next to its name in vehicle lists.

### PR DESCRIPTION
**Pull request by 2TallTyler**
## Motivation / Problem

Profit/loss icons in vehicle lists show "too new" if a vehicle hasn't been driving around long enough to have meaningful stats. Then, after a time, they show whether it's making money or operating at a loss.

Vehicle age is calendar-based and these stats look at the vehicle age. But if the calendar progression rate is slowed down, they show "too new" for too long, and if it is frozen they will be "too new" forever.

## Description

* Add a new `economy_age` tracker that counts economy days, and use that for checking if a vehicle is old enough to have its profit considered.
* Handle savegame conversion to fill the new property.
* Use an existing `VEHICLE_PROFIT_MIN_AGE` const instead of magic numbers for the minimum age to check.

Fixes #12010.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/saveload/saveload.h [hunk 1]
```diff
@@ -377,6 +377,7 @@ enum SaveLoadVersion : uint16_t {
 	SLV_DEPOT_UNBUNCHING,                   ///< 331  PR#11945 Allow unbunching shared order vehicles at a depot.
 	SLV_AI_LOCAL_CONFIG,                    ///< 332  PR#12003 Config of running AI is stored inside Company.
 	SLV_SCRIPT_RANDOMIZER,                  ///< 333  PR#12063 v14.0 Save script randomizers.
+	SLV_VEHICLE_ECONOMY_AGE,                ///< 334  PR#12141 Add vehicle age in economy year, for profit stats minimum age
```
Comment (TrueBrain) [inline src/saveload/saveload.h]: Nitpick: missing dot at end of sentence.

File: src/vehicle_base.h [hunk 2]
```diff
@@ -285,7 +285,8 @@ struct Vehicle : VehiclePool::PoolItem<&_vehicle_pool>, BaseVehicle, BaseConsist
 
 	/* Related to age and service time */
 	TimerGameCalendar::Year build_year;           ///< Year the vehicle has been built.
-	TimerGameCalendar::Date age;                  ///< Age in days
+	TimerGameCalendar::Date age;                  ///< Age in calendar days
+	TimerGameEconomy::Date economy_age;           ///< Age in economy days
```
Comment (TrueBrain) [inline src/vehicle_base.h]: Nitpick: missing dots :)

**Review by TrueBrain — COMMENTED** [review]
Minor stuff. I have no clue if this is actually the right solution; hopefully another dev knows :)

File: src/saveload/saveload.h (hunk 1 above)
Comment (rubidium42) [reply src/saveload/saveload.h]: Since this is going to be backported, should we add the v14.0 tag on this line and change the v14.0 on the previous line to v14.0-RC1?
Or is that something to not do until the backport? With the risk that it gets forgotten.

Comment (TrueBrain) [reply src/saveload/saveload.h]: When we do it at the backport, the master is wrong. So I agree, let's do it in this PR :)

**Review by TrueBrain — DISMISSED** [review]
Seems nobody dared. Owh well. YOLO!

**Comment by glx22** [comment]
Script API uses calendar timer for `ScriptVehicle::GetAge()`, `ScriptVehicle::GetMaxAge()` and `ScriptVehicle::GetAgeLeft()`. I assume they need to be changed to use economy timer too.

**Comment by 2TallTyler** [comment]
Yes, although GetAge() might gain a way to check calendar age the script is operating in calendar time mode.

**Comment by 2TallTyler** [comment]
Oh, actually... Age remaining is still calendar years. Vehicles age more slowly if calendar time is slower. This PR only changes how the break-in period for profit/loss calculation works.

That said, AIs might want to know about that. Probably as a separate PR.

**Comment by TrueBrain** [comment]
I do not see why this should be made into the Script API. The human also has no direct access to this value, and only sees the result of this value increasing (in the form of news telling a vehicle is not profitable).

What am I missing?

**Review by TrueBrain — APPROVED** [review]
Preemptively approving this PR under the assumption I am right and this needs no Script API entry :P

**Comment by 2TallTyler** [comment]
Yes, this PR probably shouldn't touch scripts. If compatibility changes are required for the economy/calendar split, they can be in a different PR. But I have no idea what that would entail right now, so let's not hold up this legitimate fix to a GUI issue.
