### PR TITLE
Fix: if bootstrap failed, it could end with an empty screen instead of error

### LINKED ISSUE #8855: Black/red window on startup (macOS 10.15.7)
## Version of OpenTTD
1.11.0-beta2 on macOS 10.15.7

## Expected result
I expect the game's title screen to appear

## Actual result
The game window appears but stays black. Alternatively, it stays red when I launch with cocoa-opengl

## Steps to reproduce
Start the game

## Logs
```
/Applications/OpenTTD.app/Contents/MacOS/openttd -d 9,freetype=0
dbg: [misc] /Users/dhe/Documents/OpenTTD/ added as search path
dbg: [misc] /Library/Application Support/OpenTTD/ added as search path
dbg: [misc] /Applications/ added as search path
dbg: [misc] /Applications/OpenTTD.app/Contents/Resources/ added as search path
dbg: [misc] /Users/dhe/Documents/OpenTTD/content_download/ added as search path
dbg: [misc] /Users/dhe/Documents/OpenTTD/ found as config directory
dbg: [misc] /Users/dhe/Documents/OpenTTD/ found as personal directory
dbg: [misc] Scanning for tars
dbg: [misc] Scan complete, found 0 files
dbg: [grf] Checking /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos.obg for base graphics set
dbg: [grf] The file TRG1.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos.obg is missing
dbg: [grf] The file TRGI.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos.obg is missing
dbg: [grf] The file TRGC.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos.obg is missing
dbg: [grf] The file TRGH.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos.obg is missing
dbg: [grf] The file TRGT.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos.obg is missing
dbg: [grf] Adding original_dos (1) as base graphics set
dbg: [grf] Checking /Applications/OpenTTD.app/Contents/Resources/baseset/orig_win.obg for base graphics set
dbg: [grf] The file TRG1R.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_win.obg is missing
dbg: [grf] The file TRGIR.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_win.obg is missing
dbg: [grf] The file TRGCR.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_win.obg is missing
dbg: [grf] The file TRGHR.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_win.obg is missing
dbg: [grf] The file TRGTR.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_win.obg is missing
dbg: [grf] Adding original_windows (0) as base graphics set
dbg: [grf] Checking /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos_de.obg for base graphics set
dbg: [grf] The file TRG1.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos_de.obg is missing
dbg: [grf] The file TRGI.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos_de.obg is missing
dbg: [grf] The file TRGC.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos_de.obg is missing
dbg: [grf] The file TRGH.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos_de.obg is missing
dbg: [grf] The file TRGT.GRF specified in /Applications/OpenTTD.app/Contents/Resources/baseset/orig_dos_de.obg is missing
dbg: [grf] Not adding original_dos_de (0) as base graphics set (duplicate, lower version)
dbg: [misc] Loading blitter...
dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Could not change to foreground application. Error -50
dbg: [driver] Successfully probed video driver 'cocoa'
dbg: [net] [core] starting network...
dbg: [net] [udp] initializing listeners
dbg: [net] [core] network online, multiplayer available
dbg: [net] Detected broadcast addresses:
dbg: [net] 0) 192.168.0.255
```

### PR DESCRIPTION
**Pull request by TrueBrain**
Fixes #8855

## Motivation / Problem

Bootstrap had a flow where it could leave the screen with no open window. This is rather confusing for any human. Show an error instead, with next steps.

## Description

```
There are various of ways bootstrap can fail:
- Failing network connection
- Incomplete download
- No write permissions
- Disk full
- (others I forgot)

They all result in a screen with no windows. To ensure we at least
always show something when anything bad happens, if the bootstrap
is not successful, show a screen what the next step for the human
should be.
```

image

## Limitations

This does not show the real error that happened. Some flows do have some snippets of information (like "write to file failed"), but most just close the download window. Additionally, showing real errors is rather difficult without hacking or rewriting the error window. Both felt a bit excessive for something that shouldn't happen in most cases.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/bootstrap_gui.cpp [hunk 1]
```diff
@@ -61,6 +62,65 @@ class BootstrapBackground : public Window {
...
+	WDP_CENTER, nullptr, 0, 0,
+	WC_BOOTSTRAP, WC_NONE,
+	WDF_MODAL,
+	_nested_bootstrap_errmsg_widgets, lengthof(_nested_bootstrap_errmsg_widgets)
+);
+
+/** The window for a failed bootstrap. */
+class BootstrapErrorWindow : public Window {
+public:
+	/** Start listening to the content client events. */
```
Comment (glx22) [inline src/bootstrap_gui.cpp]: Too much copy paste ?

File: src/bootstrap_gui.cpp [hunk 2]
```diff
@@ -61,6 +62,65 @@ class BootstrapBackground : public Window {
...
+	BootstrapErrorWindow() : Window(&_bootstrap_errmsg_desc)
+	{
+		this->InitNested(1);
+	}
+
+	/** Stop listening to the content client events. */
```
Comment (glx22) [inline src/bootstrap_gui.cpp]: Same here.

**Review by LordAro — APPROVED** [review]
