### PR TITLE
Fix #8713: Change OTTD2FS and FS2OTTD to return string objects

### LINKED ISSUE #8713: Win32 OTTD2FS/FS2OTTD used from multiple threads but use a static buffer
## Version of OpenTTD
master

## Expected result
No thread safety issues

## Actual result
The OTTD2FS/FS2OTTD functions are used in a wide variety of places in the codebase, including indirectly from non-main threads. (e.g. file scanner thread, network threads when debug output is on, crash logger). Various macros also use these functions (e.g. fopen, MB_TO_WIDE/WIDE_TO_MB, etc.).

On Win32, these methods use a static buffer, and return a pointer to that buffer.
In the event that the method is called from multiple threads in the same general time frame, callers could receive output from a different thread. Theoretically this could result in a buffer over-read if a thread is reading the buffer at the same time as another is in the middle of writing it.

I used TLS to make this go away: https://github.com/JGRennison/OpenTTD-patches/commit/0a61671ff15e3c05835632a447421597f618348b. std::string conversion could also be an option.

## Steps to reproduce
I'm sure there must be a way of automatically detecting this on Windows.

### PR DESCRIPTION
**Pull request by nielsmh**
## Motivation / Problem

The `OTTD2FS` and `FS2OTTD` functions are not thread safe, they use static (global) buffers to hold the returned string data and require the caller to copy the data to somewhere better, and pray there isn't any race condition.

## Description

Change the functions to return `std::string` and `std::wstring` objects instead, to get automatic lifetime management of the data, and avoid data sharing between threads.

Additionally, this removes mostly any pretense that we can still build Windows 95 versions of the game.

## Limitations

Several of these changes are done blind, so far. Only tested in a single configuration on Windows, the changes for other OS may not compile.

There are unrelated changes here that should probably be split off.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* ~~This PR affects the save game format? (label 'savegame upgrade')~~
* ~~This PR affects the GS/AI API? (label 'needs review: Script API')~~
* ~~This PR affects the NewGRF API? (label 'needs review: NewGRF')~~

### CODE REVIEW

File: src/os/unix/unix.cpp [hunk 1]
```diff
@@ -213,12 +213,12 @@ const char *FS2OTTD(const char *name)
...
 
-	return convert_tofrom_fs(convd, name);
+	return convert_tofrom_fs(convd, name.c_str(), buf, lengthof(buf));
 }
 
 #else
-const char *FS2OTTD(const char *name) {return name;}
-const char *OTTD2FS(const char *name) {return name;}
+std::string FS2OTTD(const std::string &name) {return name;}
+std::string OTTD2FS(const std::string &name) {return name;}
```
Comment (JGRennison) [inline src/os/unix/unix.cpp]: This seems a bit of a pessimisation for non-Windows platforms.
This will always create a copy of the input, even if the input could otherwise be an rvalue which could be moved from, or if the result is passed straight through to c_str(), in which no copy is needed at all.

Edit: Passing a char* to these is actually 2 copies. You could reduce that to one by using a std:string signature instead.

Comment (nielsmh) [reply src/os/unix/unix.cpp]: I guess maybe defining them as a template function?
```c++
template <typename T> std::string FS2OTTD(T name) { return name; }
```
I think that will avoid all unnecessary copies?

Comment (LordAro) [reply src/os/unix/unix.cpp]: https://godbolt.org/z/7hdd1b Suggests that the templated version generates the simplest code

Comment (nielsmh) [reply src/os/unix/unix.cpp]: Oh, turns out the templated version is not quite possible, since `stdafx.h` has just a forward declaration, and the implementations are in `unix.cpp` (null-implementation and iconv implementation) and `os2.cpp` (null-implementation). I guess `stdafx.h` could select on `defined(WITH_ICONV)` whether to forward declare or use the templated version.

**Comment by nielsmh** [comment]
Redid the UNICODE removal in #8720 instead.

File: src/debug.cpp [hunk 2]
```diff
@@ -135,8 +135,8 @@ static void debug_print(const char *dbg, const char *buf)
 		seprintf(buffer, lastof(buffer), "%sdbg: [%s] %s\n", GetLogPrefix(), dbg, buf);
 #if defined(_WIN32)
 		wchar_t system_buf[512];
-		convert_to_fs(buffer, system_buf, lengthof(system_buf), true);
-		_fputts(system_buf, stderr);
+		convert_to_fs(buffer, system_buf, lengthof(system_buf));
+		fputws(system_buf, stderr);
```
Comment (glx22) [inline src/debug.cpp:137]: Should be in the other commit

File: src/os/windows/font_win32.cpp [hunk 3]
```diff
@@ -439,7 +439,7 @@ void Win32FontCache::SetFontSize(FontSize fs, int pixels)
 	this->glyph_size.cx = otm->otmTextMetrics.tmMaxCharWidth;
 	this->glyph_size.cy = otm->otmTextMetrics.tmHeight;
 
-	DEBUG(freetype, 2, "Loaded font '%s' with size %d", FS2OTTD((LPTSTR)((BYTE *)otm + (ptrdiff_t)otm->otmpFullName)).c_str(), pixels);
+	DEBUG(freetype, 2, "Loaded font '%s' with size %d", FS2OTTD((LPWSTR)((BYTE *)otm + (ptrdiff_t)otm->otmpFullName)).c_str(), pixels);
```
Comment (glx22) [inline src/os/windows/font_win32.cpp:442]: Same here

File: src/fileio.cpp [hunk 4]
```diff
@@ -279,7 +279,7 @@ bool FioCheckFileExists(const std::string &filename, Subdirectory subdir)
  */
 bool FileExists(const std::string &filename)
 {
-	return access(OTTD2FS(filename.c_str()), 0) == 0;
+	return access(OTTD2FS(filename).c_str(), 0) == 0;
```
Comment (LordAro) [inline src/fileio.cpp:282]: I'm concerned about the correctness of `OTTD2FS(..).c_str()` and it's use of the temporary std::string object. Is that definitely all correct?

Comment (JGRennison) [reply src/fileio.cpp:282]: In this case the temporary will not be destructed until the end of the statement (after access has returned), so it is OK.

Comment (LordAro) [reply src/fileio.cpp:282]: How about all the others? :)

Comment (nielsmh) [reply src/fileio.cpp:282]: I went over the changes and checked, yes all the cases of `OTTD2FS(x).c_str()` are safe: The C string returned is only expected to live until the called function has returned. All the cases where it caused problems the temporary string returned from the conversion function is stored into a proper local variable to manage its lifetime.

**Review by LordAro — APPROVED** [review]
