### PR TITLE
Fix #7592: Limit road vehicle caching near destination

### LINKED ISSUE #7592: Road vehicles don't balance between multiple loading bays
Based on [post on TT-Forums](https://www.tt-forums.net/viewtopic.php?p=1221859#p1221859)

## Version of OpenTTD
Likely after merge of road vehicle path caching

## Expected result
Road vehicles choose a free loading bay to head towards when multiple are available at a station.

## Actual result
Road vehicles head towards the same loading bay even after it has been filled.

## Steps to reproduce
Send many road vehicles to the same few stations with mutiple loading bays.

## Suggested fix
Prevent road vehicles from caching the last 1 or 2 turns (or 10 tiles if that's shorter) before their scheduled next stop.

### PR DESCRIPTION
**Pull request by nielsmh**
Ported from https://github.com/JGRennison/OpenTTD-patches/commit/79d5be7e265df3be8b73d484f0c7261b3c23229d as suggested in https://github.com/OpenTTD/OpenTTD/issues/7592#issuecomment-546629800

Seems to work from my preliminary testing, although I haven't verified that the caching is still efficient when not near the destination.

### CODE REVIEW

**Comment by nielsmh** [comment]
I don't see any significant difference in road vehicle ticks time with or without this patch on Wentbourne Transport, so the caching should still be working.

File: src/pathfinder/yapf/yapf_road.cpp [hunk 1]
```diff
@@ -402,6 +407,22 @@ class CYapfFollowRoadT
...
+
+			/* Check if target is a station, and cached path ends within 8 tiles of the dest tile */
+			const Station *st = Yapf().GetDestinationStation();
+			if (st) {
+				const RoadStop *stop = st->GetPrimaryRoadStop(v);
+				if (stop != nullptr && (IsDriveThroughStopTile(stop->xy) || stop->GetNextRoadStop(v) != nullptr)) {
+					/* Destination station has at least 2 usable road stops, or first is a drive-through stop,
+					 * trim end of path cache within 8 tiles of road stop tile area */
+					TileArea non_cached_area = v->IsBus() ? st->bus_station : st->truck_station;
+					non_cached_area.Expand(8);
```
Comment (LordAro) [inline src/pathfinder/yapf/yapf_road.cpp]: Could be useful to put this in a named constant

**Review by LordAro — APPROVED** [review]
