### PR TITLE
Fix #12914: Fix use of invalidated pointer in viewport drawer.

### LINKED ISSUE #12914: [Bug]: AddChildSpriteToFoundation can cause a use after free via ViewportDrawer::last_child
### Version of OpenTTD

master

### Expected result

AddChildSpriteToFoundation can't cause a use-after-free via ViewportDrawer::last_child

### Actual result

AddChildSpriteToFoundation saves the current value of ViewportDrawer::last_child which points into the ViewportDrawer::child_screen_sprites_to_draw std::vector, then calls AddChildSpriteScreen which appends to this vector.
AddChildSpriteScreen handles updates ViewportDrawer::last_child, so it is still valid when ViewportDrawer::child_screen_sprites_to_draw reallocates.

However AddChildSpriteToFoundation then restores the old value of ViewportDrawer::last_child which is a dangling pointer if ViewportDrawer::child_screen_sprites_to_draw was reallocated.

Subsequent calls to AddChildSpriteScreen can then cause a use after free via this dangling pointer.

### Steps to reproduce

See above

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

As per #12914, use of invalid dangling pointer due to vector reallocation in viewport drawer.

## Description

~~Store destination list and index within the list, instead of a direct pointer, to find child index to update.~~

Use index of last child instead of pointer to update next_child element.

In case there is no child sprite yet, the most recent parent sprite's first_child is updated instead.

## Limitations

I haven't been able to prove that child sprites are only even added to the most recent parent sprite.

Switching to std::deque is probably less intrusive but not sure about iteration performance.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/viewport.cpp [hunk 1]
```diff
@@ -612,7 +610,7 @@ void OffsetGroundSprite(int x, int y)
 	}
 
 	/* _vd.last_child == nullptr if foundation sprite was clipped by the viewport bounds */
```
Comment (glx22) [inline src/viewport.cpp]: This comment is outdated.

File: src/viewport.cpp [hunk 2]
```diff
@@ -831,15 +829,20 @@ void AddChildSpriteScreen(SpriteID image, PaletteID pal, int x, int y, bool tran
...
 
 	/* make the sprites transparent with the right palette */
 	if (transparent) {
 		SetBit(image, PALETTE_MODIFIER_TRANSPARENT);
 		pal = PALETTE_TO_TRANSPARENT;
 	}
 
-	*_vd.last_child = (uint)_vd.child_screen_sprites_to_draw.size();
+	int32_t child_id = static_cast<int32_t>(_vd.child_screen_sprites_to_draw.size());
+	if (_vd.last_child >= 0) {
```
Comment (rubidium42) [inline src/viewport.cpp]: I'm a bit conflicted about this line. On its own it looks very reasonable to guard indexing into an array with a non-negative value. However, `LAST_CHILD_PARENT` is only set and never read, and here the "meaning" seems to be `if (_vd.last_child != LAST_CHILD_PARENT)`. That'd make me think... how is `LAST_CHILD_NONE` then handled as that's a negative value, just to discover that if that's the case you leave the function a couple of lines earlier.

So yeah, not sure. Either question where `LAST_CHILD_PARENT` is read or question why `LAST_CHILD_NONE` is not checked for in this `if`.

**Review by rubidium42 — DISMISSED** [review]

File: src/viewport.cpp (hunk 2 above)
Comment (PeterN) [reply src/viewport.cpp]: Decided to go with `!= LAST_CHILD_PARENT` as that is the actual intention and it took me a moment to register that already.

If it was for bounds checking then `>= 0` is not a sufficient check, and it would not have the correct result either.

**Review by rubidium42 — APPROVED** [review]
