### PR TITLE
Fix #13954: Plotting graphs with limited data to the right

### LINKED ISSUE #13954: [Bug]: Company plots with limited data are not right-aligned
### Version of OpenTTD

14.1

### Expected result

Company graph with limited quartal data should be right-aligned:
Image

### Actual result

Company graph is left-aligned:
Image

### Steps to reproduce

1. Start a new game.
2. Wait 3 quarters.
3. View any company performance chart.

### PR DESCRIPTION
**Pull request by xJayMorex**
## Motivation / Problem

Fixes #13954.

## Description

Plotting graphs with limited data to the right.

## Limitations

None.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/graph_gui.cpp [hunk 1]
```diff
@@ -453,6 +453,11 @@ struct BaseGraphWindow : Window {
 				iterator = this->x_values_increment;
 			}
 
+			// if there are not enough datapoints to fill the graph, align to the right
```
Comment (frosch123) [inline src/graph_gui.cpp]: Is there a reason to not use a multiplication?
```c++
x += (this->num_vert_lines - this->num_on_x_axis) * x_sep;
```

**Comment by frosch123** [comment]
I tested this rebased on #13957. It works well in wallclock mode.

@xJayMorex Is there a reason for this to behave differently in calender mode?

**Comment by xJayMorex** [comment]
> I tested this rebased on #13957. It works well in wallclock mode.
> 
> @xJayMorex Is there a reason for this to behave differently in calender mode?

To me it makes more sense to start plotting a line diagram from the left, especially if the x axis represents the calendar.

**Comment by xJayMorex** [comment]
@frosch123 Changed logic to align incomplete graphs to the right regardless of timekeeping mode.

File: src/graph_gui.cpp [hunk 2]
```diff
@@ -442,10 +442,14 @@ struct BaseGraphWindow : Window {
 			y += y_sep;
 		}
 
+		x = rtl ? r.right : r.left;
+		y = r.bottom + ScaleGUITrad(2);
+
+		// if there are not enough datapoints to fill the graph, align to the right
```
Comment (frosch123) [inline src/graph_gui.cpp]:
```suggestion
		/* if there are not enough datapoints to fill the graph, align to the right */
```

File: src/graph_gui.cpp [hunk 3]
```diff
@@ -512,6 +513,9 @@ struct BaseGraphWindow : Window {
 				x = r.left + (x_sep / 2);
 			}
 
+			// if there are not enough datapoints to fill the graph, align to the right
```
Comment (frosch123) [inline src/graph_gui.cpp]:
```suggestion
			/* if there are not enough datapoints to fill the graph, align to the right */
```

**Review by frosch123 — APPROVED** [review]
