### PR TITLE
Fix #10574 -- revert the change and don't list unavailable road types to game script.

### LINKED ISSUE #10574: [Bug]: Map generation fails when no town buildable roads are available
### Version of OpenTTD

20230316-master-g0bf6d80cd7 (Win10 64)

### Expected result

Without failures of creating a new map

### Actual result

Message

### Steps to reproduce

1. Download NewGRF: or U&RaTT, or Rattroads
2. Starting game in 1900 year

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

See #10574. 

## Description

Re-allow town-buildable to override hidden, but do check for availability for game script listing.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/script/api/script_railtypelist.cpp [hunk 1]
```diff
@@ -18,6 +18,6 @@ ScriptRailTypeList::ScriptRailTypeList()
 {
 	EnforceDeityOrCompanyModeValid_Void();
 	for (RailType rt = RAILTYPE_BEGIN; rt != RAILTYPE_END; rt++) {
-		if (ScriptCompanyMode::IsDeity() || ::HasRailtypeAvail(ScriptObject::GetCompany(), rt)) this->AddItem(rt);
+		if (::HasRailtypeAvail(ScriptObject::GetCompany(), rt)) this->AddItem(rt);
```
Comment (rubidium42) [inline src/script/api/script_railtypelist.cpp]: This function has no special case for town/deity, so this for a GS (not in company scope/mode) will dereference a null/invalid pointer.

Comment (PeterN) [reply src/script/api/script_railtypelist.cpp]: Oops, forgot to check that.

**Comment by PeterN** [comment]
Updated to remove anything to do with rail types.

**Review by rubidium42 — DISMISSED** [review]

**Comment by Andrew350** [comment]
FWIW, as a NewGRF developer affected by the initial change this would be my preferred solution compared to the other options so far, although I'm obviously a bit biased here since this means no changes necessary on our side.

My only question is if this solution has any negative effect on the GS side of things? From what @rubidium42 explained, the reason for the change in the first place was that a GS could have issues determining which roadtypes were actually viable to build based on the way we define some of them with both the HIDDEN and TOWN_BUILD flags.

If that was the main issue and this solution solves it for both sides in a good way (which it does from my perspective, at least) then this seems like the ideal fix to me.

**Comment by Brickblock1** [comment]
I would also prefer this option, while I haven't made a roadset I still think that this option is more flexible and therefore better.

**Comment by michicc** [comment]
Needs a rebase after the recent CI changes.

**Review by rubidium42 — APPROVED** [review]
