### PR TITLE
Fix #14610: Do not treat aircraft with only depot orders as having valid orders

### LINKED ISSUE #14610: [Bug]: Aircraft can remain suspended in mid-air if its only order is "go to nearest hangar" but there is no usable hangar
### Version of OpenTTD

3317997976 on Windows 10, 64-bit (via Steam)

### Expected result

An aircraft whose only order is "Go to the nearest Hangar" but with no usable hangar crashes after a while, with "Aircraft ran out of fuel."

### Actual result

An aircraft whose only order is "Go to the nearest Hangar" but with no usable hangar can remain suspended in mid-air indefinitely.

Ordering such an aircraft to go to a hangar using the button on its vehicle window produces this nonsensical error message, where the error detail and error title texts are the same:
Image

### Steps to reproduce

1. Build two airports.
2. Buy an aircraft and order it to go to both airports.
3. After the aircraft takes off, demolish both airports, insert "Go to the nearest Hangar" in its orders, then remove its other orders.
4. Wait until both airports are removed from the system and the aircraft is suspended in mid-air.

Or load this savegame for a completed reproduction:
[Dodingbury Transport, 2200-02-05.zip](https://github.com/user-attachments/files/22291232/Dodingbury.Transport.2200-02-05.zip)

### PR DESCRIPTION
**Pull request by Nusioos**
## Motivation / Problem

Fixes #14610

Aircraft with only "go to nearest depot" orders could enter an undefined state.
When `CheckForValidOrders()` considered `OT_GOTO_DEPOT` as a valid order these
aircraft would not be handled by `HandleMissingAircraftOrders()`, potentially
causing them to hang or behave incorrectly.

The issue was identified and the solution suggested in the issue comments:
"ignore all 'go to nearest hangar' orders in CheckForValidOrders".

## Description

Modified `CheckForValidOrders()` to exclude OT_GOTO_DEPOT orders when checking
validity for aircraft. Aircraft with only depot orders are now treated as having
no valid orders this ensures they are properly handled by `HandleMissingAircraftOrders()`.

This implements the solution suggested in the original issue comments.

## Limitations

- Only affects aircraft (VEH_AIRCRAFT)
- Other vehicle types unchanged

### CODE REVIEW

File: src/order_cmd.cpp [hunk 1]
```diff
@@ -1881,7 +1881,18 @@ uint16_t GetServiceIntervalClamped(int interval, bool ispercent)
  */
 static bool CheckForValidOrders(const Vehicle *v)
 {
-	return std::ranges::any_of(v->Orders(), [](const Order &order) { return order.IsGotoOrder(); });
+	if (v->type == VEH_AIRCRAFT) {
+		// For aircraft only exclude OT_GOTO_DEPOT from valid orders
+		// This treats aircraft with only "go to depot" orders as having no valid orders
```
Comment (rubidium42) [inline src/order_cmd.cpp]: Our coding style says that comments on their own line should be in `/* ... */`-style.

File: src/order_cmd.cpp [hunk 2]
```diff
@@ -1881,7 +1881,18 @@ uint16_t GetServiceIntervalClamped(int interval, bool ispercent)
  */
 static bool CheckForValidOrders(const Vehicle *v)
 {
-	return std::ranges::any_of(v->Orders(), [](const Order &order) { return order.IsGotoOrder(); });
+	if (v->type == VEH_AIRCRAFT) {
```
Comment (rubidium42) [inline src/order_cmd.cpp]: This function is only called for aircraft, so this check isn't really needed.

That fact is not clear when looking at the function, so maybe the function should be named `CheckForValidAircraftOrders` with the appropriate amendments to the documentation.

**Review by rubidium42 — COMMENTED** [review]
Thanks for your PR. It seems to be solving the issue.

With respect to the commit message, I do not think this is a 'Codefix' as it actually changes the visible behaviour for the end user. Also, since you fix something with a bug report, it would be nice if it could be mentioned. For example `Fix #14610: Do not treat aircraft with only depot orders as having valid orders`.

Finally, we do not use merge commits to keep things conceptually simpler. Are you able to remove the merge commit? One of the required checks will prevent us from merging any PR with a merge commit in it.

File: src/order_cmd.cpp (hunk 2 above)
Comment (Nusioos) [reply src/order_cmd.cpp]: Thanks for feedback! I will do suggested changes as soon as I can.

Comment (Nusioos) [reply src/order_cmd.cpp]: @rubidium42 I've fixed the commit message and code. 
I see there's a merge commit (6b3196b092) in the history. 
Could you please help me rebase the PR to remove it?
I am a Github noobie and I have problems with that.

File: src/order_cmd.cpp [hunk 3]
```diff
@@ -1881,7 +1881,11 @@ uint16_t GetServiceIntervalClamped(int interval, bool ispercent)
  */
 static bool CheckForValidOrders(const Vehicle *v)
 {
-	return std::ranges::any_of(v->Orders(), [](const Order &order) { return order.IsGotoOrder(); });
+	/* Check if vehicle has any valid orders
+	Function is only called for aircraft, no type check needed*/
+	return std::ranges::any_of(v->Orders(), [](const Order &order) {
+		return order.IsGotoOrder() && !order.IsType(OT_GOTO_DEPOT);
+		});
```
Comment (2TallTyler) [inline src/order_cmd.cpp]: Indentation of the closing brackets looks wrong to me (hard to tell on GitHub sometimes).

```suggestion
	});
```

File: src/order_cmd.cpp [hunk 4]
```diff
@@ -1881,7 +1881,11 @@ uint16_t GetServiceIntervalClamped(int interval, bool ispercent)
  */
 static bool CheckForValidOrders(const Vehicle *v)
 {
-	return std::ranges::any_of(v->Orders(), [](const Order &order) { return order.IsGotoOrder(); });
+	/* Check if vehicle has any valid orders
+	Function is only called for aircraft, no type check needed*/
```
Comment (2TallTyler) [inline src/order_cmd.cpp]: Comment formatting isn't quite right, you need another * at the start of the second line, a space before the comment closing tag, and periods on both sentences.

```suggestion
	/* Check if vehicle has any valid orders.
	 * Function is only called for aircraft, no type check needed. */
```

**Review by 2TallTyler — COMMENTED** [review]
To get rid of the merge commit, you'll need to do an interactive rebase using the Git command line. `git rebase -i head~4` will start an interactive rebase open your default text editor to choose what to do with the last 4 commits. You want to `drop` any merge commits. 

Not relevant here, but in the future if you ever have any extra commits to fix an original commit, this is how you get rid of them too. I like to `fixup` the later commits to squash them upwards into the original commit.

File: src/order_cmd.cpp (hunk 2 above)
Comment (rubidium42) [reply src/order_cmd.cpp]: I've rebased it for you. You'll need to pull and reset if you want to make any further changes.

How to rebase depends on the tool you're using. However, most tools forbid you by default to rebase in the master branch. So, for the next PR I suggest that you make a git branch. That'll make it more likely that the tool you are using shows rebasing functionality.

**Review by rubidium42 — APPROVED** [review]
