### PR TITLE
Fix #7847: Use ViewportSign coordinates for sign Kdtree coordinates

### LINKED ISSUE #7847: Crash - Assertion failed at line 213 of src\core\kdtree.hpp: next != INVALID_NODE
## Version of OpenTTD
1.10.0-beta1
## Steps to reproduce
[crash.zip](https://github.com/OpenTTD/OpenTTD/files/3906285/crash.zip)

### PR DESCRIPTION
**Pull request by nielsmh**
Fix #7847 by ensuring the same coordinates are used for a station sign regardless of how the landscape changes below it after the coordinates were first determined.

By keeping track of whether the ViewportSign is valid for Kdtree use (and only ever registering the station viewport sign when the sign object is valid) a lot of code can be simplified, and it should prevent a lot of similar bugs too.

I think this is the real solution to all Kdtree bugs regarding station signs. I think something similar needs to be done for town names and player signs too.

### CODE REVIEW

File: src/waypoint_cmd.cpp [hunk 1]
```diff
@@ -39,8 +39,13 @@
 void Waypoint::UpdateVirtCoord()
 {
 	Point pt = RemapCoords2(TileX(this->xy) * TILE_SIZE, TileY(this->xy) * TILE_SIZE);
```
Comment (SamuXarick) [inline src/waypoint_cmd.cpp:41]: I think you forgot to change this line.

Comment (nielsmh) [reply src/waypoint_cmd.cpp]: I'm going to do the opposite, change the regular station one back. The only reason the RemadCoords() not-2 change was made originally was to solve a crash issue during loading some savegames from specific versions. I think this new approach will avoid those issues in a better way.

Comment (nielsmh) [reply src/waypoint_cmd.cpp:41]: That's the old, more correct method. Changing the one for regular stations back instead.

**Comment by nielsmh** [comment]
Tested #7371 report, PSG 201 save remains loadable without crashing.

Tested #7440 report, is still able to create and then remove a town in scenario editor.

Tested #7481 and #7530 via the save provided in the latter, seems to pass the oil rig deletion.

**Review by glx22 — APPROVED** [review]
Looks good to me
