### PR TITLE
Fix #11067, ed83c4b: Don't start competitors during map generation

### LINKED ISSUE #11067: [Bug]: Starting new game with 0 minutes between competitor starts causes some inconsistencies.
### Version of OpenTTD

78c9446aef on Windows 10, 64-bit

### Expected result

When "Interval between starting of competitors" is greater than 0,
* Starting a new game puts the first human company in slot 0 (`(Company 1)`), as should always be case.
* When AIs start, they start in order according to the AI configuration. The first competitor should use the first AI slot below "Human player", the second competitor should use the second AI slot below the first, etc.

Both of these should still hold when "Interval between starting of competitors" is 0.

The following screenshots were taken from a scenario where 2 AIs by the name of "IdleMoreMore" are scheduled to start.

Expected behavior (currently occurs when interval > 0):
image

### Actual result

When "Interval between starting of competitors" is 0,
* Starting a new game puts the first human company in slot N (`(Company N+1)`), where N is the maximum number of AI competitors to automatically start. For example, with 0 interval and 2 "Maximum no. competitors", the human company is in slot 2 (`(Company 3)`).
* The first AI is started as a random AI.
* The second AI uses the AI config normally used for the first AI to start in a regular game.
* The third AI uses the AI config normally used for the second AI in a regular game, etc.

Actual behavior (when interval = 0) - notice the first AI is randomly selected:
image

### Steps to reproduce

1. In the AI config window, set "Maximum no. competitors" greater than 0 and "Interval between starting of competitors" equal to 0.
2. Start a new game.
3. Open the company dropdown (or company info, finances window for your company).
4. Notice the first human company is put in a slot other than the slot labelled "Company 1".

### PR DESCRIPTION
**Pull request by glx22**
Fixes #11067.

## Motivation / Problem
When "Interval between starting of competitors" is 0, competitors are started during map generation while human company is started after map generation.

## Description
Start the competitors after map generation, and after human company startup.
I put the start in `OnTick_Companies()` because when game is just created the timer is fired which will immediately start as many AIs as needed and reset the timer for ~10 minutes. Then on timeout a new AI is started if needed and `OnTick_Companies()` will start the remaining as needed if more than one disappeared during the delay.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/company_cmd.cpp [hunk 1]
```diff
@@ -617,7 +617,10 @@ void StartupCompanies()
 {
 	/* Ensure the timeout is aborted, so it doesn't fire based on information of the last game. */
 	_new_competitor_timeout.Abort();
+}
 
+/** Start all competitors if needed. */
+void StartCompetitors() {
```
Comment (rubidium42) [inline src/company_cmd.cpp]:
```suggestion
void StartCompetitors()
{
```

**Comment by PeterN** [comment]
StartupCompanies is a bit of a weird function now.

**Comment by glx22** [comment]
Maybe I should keep `StartupCompanies()` as it was and just move its call to where I put the new `StartCompetitors()` call.

**Review by 2TallTyler — DISMISSED** [review]
Assuming it works in your tests, it looks fine to me.

**Comment by 2TallTyler** [comment]
Needs a rebase, then I'll be happy to re-approve.

**Review by 2TallTyler — APPROVED** [review]
