### PR TITLE
Fix: tell the user if a font fails to load and fallback is about to be used

### LINKED ISSUE #7615: "medium_font" setting is not applied properly in korean
## Version of OpenTTD
1.9.1 and recent nightlies

## Expected result
image
Font must be seemed like readme's fonts (="mono_font" setting)

## Actual result
image

## Steps to reproduce
* Used fonts: [Fonts.zip](https://github.com/OpenTTD/OpenTTD/files/3253732/Fonts.zip)
  * NanumGothic.ttf
  * KoPubBatangLight.ttf

and both ttf files stored into ./font/ directory under the directory which openttd.exe is.

* openttd.cfg (that works):
```
(...)
small_font = ./font/KoPubBatangLight.ttf
medium_font = ./font/NanumGothic.ttf
large_font = ./font/KoPubBatangLight.ttf
mono_font = ./font/KoPubBatangLight.ttf
(...)
```

* openttd.cfg (that occurs errors):
```
(...)
small_font = ./font/KoPubBatangLight.ttf
medium_font = ./font/KoPubBatangLight.ttf
large_font = ./font/KoPubBatangLight.ttf
mono_font = ./font/KoPubBatangLight.ttf
(...)
```

It's been a long time problem as korean users to set fonts correctly in OpenTTD, and I have provided korean users to proper openttd.cfg file to users who suffer as font errors.

But recently, I have noticed that only _medium_font_ setting in openttd.cfg works differently.

I had tried to change my game font as **KoPubBatangLight** (by someone's request), 
but the only _medium_font_ is not applied.
The only korean fonts that is applied as _medium_font_ are default Windows fonts such as **Gulim**, **Dotum** or **NanumGothic** (which I attached, not a default) as I know.

As you can see above _actual result_, small/large/mono_font setting works very fine for me, but not for _medium_font_.

The questions are:
1. I have no idea why **NanumGothic** doesn't make errors while other fonts including **KoPubBatangLight** does.
1. Why only _medium_font_ setting's are not applied while small/large/mono_font setting are applied.

* I'm using Windows 10, but lots of errors without openttd.cfg has been occured since OpenTTD supports korean.
* I've also installed the font file, it was the same.
* I've setted ```medium_font = C:\\Windows\\Fonts\\KoPubBatangLight.ttf```, it was the same. Single backslash was the same.

### PR DESCRIPTION
**Pull request by TrueBrain**
Fixes #7615 (well, not really fixes, but informs the user better).

## Motivation / Problem

When fonts fail to load, the user is not informed why and that it failed. Instead, system fallback is loaded, and that is all she wrote. Really frustrating for the user, as he would think he did the path wrong or something. None of that .. if only a single glyph is missing, all the fonts are rejected and the system fallback is used.

## Description

So instead of doing stuff in silence, be a bit more talkative:

- Report in console what character failed to render
- Show a GUI error that the font failed, and that the system fallback is used

Hopefully that makes it a bit easier to debug font issues :)

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/strings.cpp [hunk 1]
```diff
@@ -2002,7 +2002,7 @@ const char *GetCurrentLanguageIsoCode()
  * @return If glyphs are missing, return \c true, else return \c false.
  * @post If \c true is returned and str is not nullptr, *str points to a string that is found to contain at least one missing glyph.
  */
-bool MissingGlyphSearcher::FindMissingGlyphs(const char **str)
```
Comment (glx22) [inline src/strings.cpp:2005]: Don't forget to update doxygen comment ;)

**Comment by LC-Zorg** [comment]
(From the perspective of the average gamer)
I have not encountered this problem because...
1. For a long time I didn't know that it is possible to change the font in the game.
2. And when I found out about it, I didn't know how to do it.
3. Later I knew, but today I forgot again how and where.

People familiar with how to change the font will likely benefit from this change. However, the vast majority of players don't know about this possibility.

This proposal is a completely different level of complexity of the work and it is probably not very revealing, but...
The option to select the type and size of fonts available in the settings window would be useful in the game. The current variant x1 / x2 / x4 rarely gives satisfactory results.

**Comment by TrueBrain** [comment]
> 
> 
> (From the perspective of the average gamer)
> I have not encountered this problem because...
> 
>     1. For a long time I didn't know that it is possible to change the font in the game.
> 
>     2. And when I found out about it, I didn't know how to do it.
> 
>     3. Later I knew, but today I forgot again how and where.
> 
> 
> People familiar with how to change the font will likely benefit from this change. However, the vast majority of players don't know about this possibility.
> 
> This proposal is a completely different level of complexity of the work and it is probably not very revealing, but...
> The option to select the type and size of fonts available in the settings window would be useful in the game. The current variant x1 / x2 / x4 rarely gives satisfactory results.

Please keep comments relevant to the topic at hand. This Pull Request is, as you already conclude, to fix a specific problem. It is not about fixing [everything else]. If you feel what you describe is a bug, create an issue please, so it can be processed properly. Tnx!

**Review by LordAro — APPROVED** [review]

**Review by glx22 — APPROVED** [review]
If it can give better debug output than currently (as seen in #7615) let's go
