### PR TITLE
Fix #7958: Custom catenary missing on road bridges

### LINKED ISSUE #7958: Roadtype catenary not shown over bridges
## Version of OpenTTD
20200124-master-gf88ac83408

## Expected result
If a road type provides catenary graphics, they should be shown instead of default catenary.

## Actual result
The new catenary graphics are shown on normal tiles but not on bridge tiles. Instead, the default catenary is shown on bridges.

## Steps to reproduce
The attached grf defines catenary for ROAD (just a large red square) which shows the behaviour.
[catenarytest.grf.zip](https://github.com/OpenTTD/OpenTTD/files/4111817/catenarytest.grf.zip)

### PR DESCRIPTION
**Pull request by nielsmh**
Turns out this was simply a wrong condition, used `||` where it should have used `&&`.

### CODE REVIEW

File: src/tunnelbridge_cmd.cpp [hunk 1]
```diff
@@ -1104,6 +1104,31 @@ static void DrawBridgePillars(const PalSpriteID *psid, const TileInfo *ti, Axis
...
+ * @param rti              RoadTypeInfo for the road or tram type to get catenary for
+ * @param head_tile        Bridge head tile with roadtype information
+ * @param offset           Sprite offset identifying flat to sloped bridge tiles
+ * @param head             Are we drawing bridge head?
+ * @param[out] spr_back    Back catenary sprite to use
+ * @param[out] spr_front   Front catenary sprite to use
+ */
+static void GetBridgeRoadCatenary(const RoadTypeInfo *rti, TileIndex head_tile, int offset, bool head, SpriteID &spr_back, SpriteID &spr_front)
+{
+	static const SpriteID back_offsets[6] = { 95,  96,  99, 102, 100, 101 };
```
Comment (LordAro) [inline src/tunnelbridge_cmd.cpp]: Broken alignment here - needs extra space

**Comment by frosch123** [comment]
This is still inconsistent with road tiles.
When both road and tram have catenary, DrawRoadCatenary() draws both.
Bridges only draw one.

**Comment by nielsmh** [comment]
@frosch123 That issue seems sufficiently separate and requiring more discussion, that I'd rather leave that for another time.

**Review by LordAro — APPROVED** [review]
As per discussions. Consistency can be dealt with separately
