### PR TITLE
Fix #15234: Null pointer dereference opening sign edit window when sign 0 does not exist

### LINKED ISSUE #15234: [Crash]: Null pointer dereference opening sign edit window when sign 0 does not exist
### Version of OpenTTD

Since 8e35553208f

### Steps to reproduce

Open the sign edit window when sign 0 does not exist.
e.g. by creating two signs in an empty map, removing the first and editing the second.

### Upload crash files

The GetWidgetString for WID_QES_COLOUR implicitly requires that the colour of sign 0 can be read, because InitNested is called before cur_sign is assigned.

```
#0  0x0000555555fb900c in std::optional<Colours>::value_or<Colours&>(Colours&) const & (__u=<error reading variable: Cannot access memory at address 0x45>, this=0x7fff75a53f70) at /usr/include/c++/13/optional:1034
#1  SignWindow::GetWidgetString[abi:cxx11](int, unsigned int) const (this=0x7fff75a53d70, widget=<optimised out>, stringid=0) at /home/jgr/openttd/trunk/src/signs_gui.cpp:479
#2  0x00005555560ee16b in GetStringForWidget (w=w@entry=0x7fff75a53d70, nwid=nwid@entry=0x5555575505d0, secondary=secondary@entry=false) at /home/jgr/openttd/trunk/src/widget.cpp:41
#3  0x00005555560f63ef in NWidgetLeaf::SetupSmallestSize (this=0x5555575505d0, w=0x7fff75a53d70) at /home/jgr/openttd/trunk/src/widget.cpp:2944
#4  0x00005555560f10ad in NWidgetStacked::SetupSmallestSize (this=0x5555579d87e0, w=0x7fff75a53d70) at /home/jgr/openttd/trunk/src/widget.cpp:1356
#5  0x00005555560f16ac in NWidgetHorizontal::SetupSmallestSize (this=0x555557a2de70, w=0x7fff75a53d70) at /home/jgr/openttd/trunk/src/widget.cpp:1549
#6  0x00005555560f1a0c in NWidgetVertical::SetupSmallestSize (this=0x55555757a580, w=0x7fff75a53d70) at /home/jgr/openttd/trunk/src/widget.cpp:1732
#7  0x00005555560fc6d2 in Window::InitializeData (this=this@entry=0x7fff75a53d70, window_number=...) at /home/jgr/openttd/trunk/src/window.cpp:1431
#8  0x00005555560fd024 in Window::FinishInitNested (this=0x7fff75a53d70, window_number=...) at /home/jgr/openttd/trunk/src/window.cpp:1811
#9  0x00005555560fd144 in Window::InitNested (this=<optimised out>, window_number=...) at /home/jgr/openttd/trunk/src/window.cpp:1825
#10 0x0000555555fb722d in SignWindow::SignWindow (this=0x7fff75a53d70, desc=<optimised out>, si=0x5555584aea10) at /home/jgr/openttd/trunk/src/window_type.h:765
#11 0x0000555555fb4e2a in ShowRenameSignWindow (si=0x5555584aea10) at /home/jgr/openttd/trunk/src/signs_gui.cpp:647
#12 HandleClickOnSign (si=0x5555584aea10) at /home/jgr/openttd/trunk/src/signs_gui.cpp:635
#13 0x00005555560d9a93 in CheckClickOnViewportSign (y=329, x=<optimised out>, vp=...) at /home/jgr/openttd/trunk/src/viewport.cpp:2368
#14 HandleViewportClicked (vp=..., x=x@entry=770, y=y@entry=329) at /home/jgr/openttd/trunk/src/viewport.cpp:2515
#15 0x0000555556100de9 in MouseLoop (mousewheel=0, click=MC_LEFT) at /home/jgr/openttd/trunk/src/window.cpp:2910
#16 HandleMouseEvents () at /home/jgr/openttd/trunk/src/window.cpp:3024
#17 0x0000555555ccec35 in VideoDriver_SDL_Base::PollEvent (this=0x555556718380) at /home/jgr/openttd/trunk/src/video/sdl2_v.cpp:443
#18 0x0000555555cd3585 in VideoDriver::Tick (this=this@entry=0x555556718380) at /home/jgr/openttd/trunk/src/video/video_driver.cpp:137
#19 0x0000555555cce19e in VideoDriver_SDL_Base::LoopOnce (this=0x555556718380) at /home/jgr/openttd/trunk/src/video/sdl2_v.cpp:660
#20 VideoDriver_SDL_Base::LoopOnce (this=0x555556718380) at /home/jgr/openttd/trunk/src/video/sdl2_v.cpp:633
#21 VideoDriver_SDL_Base::MainLoop (this=0x555556718380) at /home/jgr/openttd/trunk/src/video/sdl2_v.cpp:678
#22 0x0000555555f00c27 in openttd_main (arguments=Python Exception <class 'gdb.error'>: value has been optimised out
) at /home/jgr/openttd/trunk/src/openttd.cpp:811
#23 0x000055555582fba4 in main (argc=<optimised out>, argv=<optimised out>) at /home/jgr/openttd/trunk/src/os/unix/unix_main.cpp:36
```

### PR DESCRIPTION
**Pull request by abi9ail**
## Motivation / Problem

#15234

## Description

`SignWindow::cur_sign` is now initialised (as in `UpdateSignEditWindow`) before `InitNested` is called.

## Limitations
N/A

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/signs_gui.cpp [hunk 1]
```diff
@@ -413,6 +413,7 @@ struct SignWindow : Window, SignList {
 		this->name_editbox.caption = STR_EDIT_SIGN_CAPTION;
 		this->name_editbox.cancel_button = WID_QES_CANCEL;
 		this->name_editbox.ok_button = WID_QES_OK;
+		this->cur_sign = si->index;
```
Comment (Rito13) [inline src/signs_gui.cpp]: Why not use member initializer list? 
```
SignWindow(WindowDesc &desc, const Sign *si) : Window(desc), name_editbox(MAX_LENGTH_SIGN_NAME_CHARS * MAX_CHAR_LENGTH, MAX_LENGTH_SIGN_NAME_CHARS), cur_sign(si->index) 
```
_Just asking out of pure curiosity_

Comment (abi9ail) [reply src/signs_gui.cpp]: Could do... Wasn't sure what the preferred approach is.

Comment (rubidium42) [reply src/signs_gui.cpp]: The member initialiser list is the preferred way.

**Review by rubidium42 — APPROVED** [review]
