### PR TITLE
Fix #12319, 3a676a5: Some SSE blitters were broken due to ODR violations

### LINKED ISSUE #12319: [Bug]: 32bpp-sse2 blitter is broken in debug build
### Version of OpenTTD

master(0cff40dd19a52ebd1b2435991dab9ebfdacbcec1), Ubuntu 22.04.4 LTS
g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Only affects debug build

### Expected result

Correct rendering.

### Actual result

Screenshot from 2024-03-17 02-49-55

### Steps to reproduce

Run `./openttd -b 32bpp-sse2`

### PR DESCRIPTION
**Pull request by frosch123**
## Motivation / Problem

#12319

## Description

``32bpp_sse_type.h`` and ``32bpp_sse_func.hpp`` are no proper "header" files.
They are "inline" files, which are included by different translation units with different defines for ``SSE_VERSION`` and ``MARGIN_NORMAL_THRESHOLD``.

As such everything has to use internal linkage.

## Limitations

I looked into replacing the defines with template parameters.
Unfortunately ``MARGIN_NORMAL_THRESHOLD`` is redefined to different values, thus this code is very fragile and easy to break.
Readding the ``static`` makes this back-portable.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/blitter/32bpp_sse_func.hpp [hunk 1]
```diff
@@ -10,10 +10,16 @@
 #ifndef BLITTER_32BPP_SSE_FUNC_HPP
 #define BLITTER_32BPP_SSE_FUNC_HPP
 
+/* ATTENTION
+ * This file is compiled multiple times with different defines for SSE_VERSION and MARGIN_NORMAL_THRESHOLD.
+ * Be careful when declaring things with external linkage.
+ * Use internal linkage instead, i.e. "static".
+ */
+
```
Comment (rubidium42) [inline src/blitter/32bpp_sse_func.hpp:19]: This is too far away to be in the diff when someone would remove the static. In the commit that introduced the bug I didn't look beyond the diff, so I would not have noticed this message and neither would the reviewer.

Comment (frosch123) [reply src/blitter/32bpp_sse_func.hpp:19]: What's your suggestion? Duplicate in front of every single function?

Comment (frosch123) [reply src/blitter/32bpp_sse_func.hpp:19]: I can also rename the file to ``.inl`` or something.

Comment (rubidium42) [reply src/blitter/32bpp_sse_func.hpp:19]: Maybe something short like `/* Do not remove 'static', see attention above. */` just before each of the `static`s?

Comment (frosch123) [reply src/blitter/32bpp_sse_func.hpp:19]: Now I used another define to obfuscate ``static``, so search/replace won't find it.

**Review by rubidium42 — APPROVED** [review]
