### PR TITLE
Fix #12831: Delay vehicle cache initialisation to after map upgrades in load

### LINKED ISSUE #12831: [Crash]: Systematic crashes while loading a save
### Version of OpenTTD

20240630-master-gb5f2004c26 (x64), Windows 10 Home (x64)

### Steps to reproduce

1. Open game via steam.
2. Load a save (see zip file) from a network drive (located on the same computer).

Other information :
- It only happens with nightly version 20240625-master-ga1e94ccddb and ulterior : save can be loaded using older nightlies.

### Upload crash files

[CRASHFILE.zip](https://github.com/user-attachments/files/16046312/CRASHFILE.zip)

### PR DESCRIPTION
**Pull request by JGRennison**
## Motivation / Problem

#12831 and other potential bugs in the same general category.

## Description

Split AfterLoadVehicles into two functions.
Vehicle cache initialisation and related setup requiring that the map has already been suitably upgraded is in the second function. This is called later in the load process.

Minor re-orderings of FixupTrainLengths, and the SLV_139 fixup (this no longer needs to be done early).
Updating the disable elrails setting during load no longer updates all train caches.

## Limitations

New function names are not very creative.
Could do with testing on a wide variety of savegame versions to ensure that there are no regressions.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/saveload/afterload.cpp [hunk 1]
```diff
@@ -2398,6 +2382,14 @@ bool AfterLoadGame()
 		}
 	}
 
+	if (IsSavegameVersionBefore(SLV_139)) {
```
Comment (PeterN) [inline src/saveload/afterload.cpp:2386]: Probably still wants a comment about oilrig being moved.

**Review by PeterN — APPROVED** [review]
