### PR TITLE
Fix #11307: Incorrect GroupStatistics after selling leading wagon when this results in a countable consist

### LINKED ISSUE #11307: [Bug]: Vehicle count underflow when putting the cart before the horse
### Version of OpenTTD

13.4

### Expected result

Buying and selling trains keeps track of the company's vehicle count properly.

### Actual result

underflow

It is possible to underflow the vehicle list; see reproduction steps below.

### Steps to reproduce

1. Build a depot.
2. Buy a locomotive and a wagon.
3. Open the company vehicle list. It says there is 1 train.
4. Move the wagon ahead of the locomotive (cart before the horse 😛). The list says there are 0 trains.
5. Sell the wagon. The locomotive returns to the leading position, but the list still says there are 0 trains.
6. Sell the locomotive. The list now says you have 65,535 trains, and attempting to buy any more gives a "too many vehicles" error.

### PR DESCRIPTION
**Pull request by JGRennison**
## Motivation / Problem

#11307

## Description

The code path for selling the leading vehicle resulting in a countable consist was incorrectly not applied for a wagon leading vehicle.

## Limitations

N/A

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by 2TallTyler — APPROVED** [review]

File: src/train_cmd.cpp [hunk 1]
```diff
@@ -1421,16 +1421,18 @@ CommandCost CmdSellRailWagon(DoCommandFlag flags, Vehicle *t, bool sell_chain, b
...
+				/* We are selling the front engine. In this case we want to
+				 * 'give' the order, unit number and such to the new head. */
+				new_head->orders = first->orders;
+				new_head->AddToShared(first);
+				DeleteVehicleOrders(first);
+
+				/* Copy other important data from the front engine */
+				new_head->CopyVehicleConfigAndStatistics(first);
+			}
+			GroupStatistics::CountVehicle(new_head, 1); // after copying over the profit, if required
```
Comment (PeterN) [inline src/train_cmd.cpp:1435]: This (existing) comment is a bit weird, where is profit come into it...

Comment (JGRennison) [reply src/train_cmd.cpp:1435]: From Vehicle::CopyVehicleConfigAndStatistics, on the line above
