### PR TITLE
Change #13915: Share one window for engine preview pop ups.

### LINKED ISSUE #13915: [Bug]: Excessive (spam of) vehicle testing offers
### Version of OpenTTD

15.0-beta1 (not a new bug)

### Expected result

The number of offers is reasonable and does not take up too much of the player's attention, even if a lot of vehicles are introduced in the game.

For example, no more than 2-3 offers appear in one month and no more than 5-6 in a year.
The offers do not appear month after month, but there is at least a 2-3 month gap between them (offers could appear in specific months).
Adding an option to disable these offers could be a solution, but I don't think that most players would expect it. These offers are not bad, they can still be interesting and expected by the player. There are simply too many of them and they interfere with the game.

### Actual result

If the game uses rich NewGRF with many vehicles (e.g. 2CC sets, Iron Horse, eGRVTS, Shark, ...) and the player uses every means of transport, the number of offers that appear can be overwhelming and burdensome. I often encounter situations when even for several months in a row, several or a dozen offers appear every month. In extreme cases, even 24 offers appear at the same time.

I don't follow all forums, but this problem has already been reported at least once on the steamcommunity website - [here](https://steamcommunity.com/app/1536610/discussions/0/4354495356172713623/)

Below is one year of the game, in which a total of 49 offers appeared. The next year there were 38, the next 51...
Image

24 offers in one month
Image

### Steps to reproduce

1. Start the save below with an unreasonable number of add-ons - the next month 24 offers will appear, then for 5 years there will be nothing and the spam will start again. 
[SPAM, 1990-12-31.zip](https://github.com/user-attachments/files/19511415/SPAM.1990-12-31.zip)
 or
2. Choose a few add-ons with a large number of vehicles (e.g. the ones listed above), start the game, build some connections for each type of transport, try to play at a fast pace - the screen will be covered with offers almost all the time.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

Closes #13915.

As per #13915, if many engine previews occur at the same date, the game will spam the player with lots of windows.

#14605 adds selections, filtering, sorting etc to the preview window to solve this but, in my opinion, goes way over the top and makes this overly complex.

Therefore...

## Description

Add previous/next buttons to the engine preview window.

If more than one engine preview occurs at the same time, previous/next buttons allow the player to switch between engines.

The current "page" is shown in the window title. Clicking on "Yes" or "No" to accept to decline a preview will remove it from the list, and if a preview is not longer available it will be removed too.

If no previews are left, the window is closed.

[Screencast from 2025-10-06 23-01-46.webm](https://github.com/user-attachments/assets/b6017a98-d41b-4699-b3a8-c7010b655b65)

## Limitations

Doesn't yet properly determine the largest window size to use, so goes by the first engine. I figured I'd gauge interest first.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by Rito13** [comment]
This idea forces players to scroll through all previews in order to just see what has been offered. They would need to consider them one by one. More over comparison of two offers (for example 3 and 10) would be painfull and possible with use of piece of paper or players with good memory. A go to specifc position button with a box to write the position and a go to last viewed button would solve this problem.
#14605 opposed to #14703 allows players to do not consider groups of vehicles that they know they will not use.

**Comment by PeterN** [comment]
Now includes a dropdown menu to jump between numbered entries quickly:

image

**Comment by LordAro** [comment]
I would suggest that this is a Feature (or at least Change) rather than a fix. But otherwise... sure, ship it (with the necessary warning fixes ;) )

**Comment by Rito13** [comment]
> Now includes a dropdown menu to jump between numbered entries quickly:

Will that work with filter in dropdown (https://github.com/OpenTTD/OpenTTD/pull/14842)?

**Comment by PeterN** [comment]
> Will that work with filter in dropdown (#14842)?

No reason not to.

File: src/engine_gui.cpp [hunk 1]
```diff
@@ -66,49 +67,105 @@ static constexpr std::initializer_list<NWidgetPart> _nested_engine_preview_widge
...
+					size.width = std::max(size.width, x + std::abs(x_offs));
+				}
+
+				/* Then account for the description of each vehicle. */
+				int title_height = 0;
+				int body_height = 0;
+				for (const EngineID &engine : this->engines) {
+					title_height = std::max(title_height, GetStringHeight(GetString(STR_ENGINE_PREVIEW_MESSAGE, GetEngineCategoryName(engine)), size.width));
+					body_height = std::max(body_height, GetStringHeight(GetEngineInfoString(engine), size.width));
+				}
```
Comment (rubidium42) [inline src/engine_gui.cpp:143]: Wouldn't it make sense to determine the total required height for each engine separately, and take the maximum of that instead of the maximum of each of the different things.

Now engine A with a high sprite, B with a high title and C with a high body might leave lots of unused space for each of them. When checking total height for each engine, and taking the maximum of that there'll be at least one engine that has no unused space along the Y axis.

**Review by rubidium42 — APPROVED** [review]
