### PR TITLE
Fix #15310: Incorrect map tile indices used for aircraft outside the map when crashing aircraft or finding hangars

### LINKED ISSUE #15310: [Crash]: aircraft landing outside of the map can be a problem
### Version of OpenTTD

OpenTTD 20260218-master-g549d555be7, Windows 11 Pro

### Steps to reproduce

1. Build a heliport at the bottom tile of the map, then close airport.
2. Build a helidepot nearby, close airport.
3. Build and start ~100 helicopters going to heliport 1.
4. Demolish helidepot first, wait a few seconds, then demolish heliport.

An OpenTTD crash is expected to happen when the helicopters run out of fuel.

### Upload crash files

[crash20260218224405.zip](https://github.com/user-attachments/files/25401997/crash20260218224405.zip)

### PR DESCRIPTION
**Pull request by JGRennison**
## Motivation / Problem

#15310

## Description

Clamp aircraft x_pos/y_pos to be within map bounds when calculating ground tile in CrashAirplane and FindNearestHangar.
Add convenience function to implement the above.

## Limitations

N/A

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/map.cpp [hunk 1]
```diff
@@ -74,6 +74,17 @@
...
+/**
+ * Get a tile from the virtual XY-coordinate.
+ * Coordinates outside of the map are clamped to the map edge.
+ * @param x The virtual x coordinate of the tile.
+ * @param y The virtual y coordinate of the tile.
+ * @return The TileIndex calculated by the coordinate, clamped to the map bounds.
+ */
+TileIndex TileVirtXYClampedToMap(int x, int y)
+{
+	return TileIndex{(static_cast<uint>(Clamp<int>(y >> 4, 0, Map::MaxX())) << Map::LogX()) + static_cast<uint>(Clamp<int>(x >> 4, 0, Map::MaxX()))};
```
Comment (PeterN) [inline src/map.cpp]: I would prefer `y / TILE_SIZE` (and same for x) here, although handling negative values may affect that. (Shouldn't because they're all clamped to 0)

Comment (JGRennison) [reply src/map.cpp]: This is for symmetry with TileVirtXY, but I can adjust that.

Comment (JGRennison) [reply src/map.cpp]: TILE_SIZE is an unsigned constant, so this needs to be cast to signed as otherwise the compiler will do the wrong kind of division, which is unhelpful.

**Review by rubidium42 — APPROVED** [review]
