### PR TITLE
Fix #8956: Industry disaster news messages showed the wrong location

### LINKED ISSUE #8956: Disasters: wrong location shown in factory/refinery destroyed message
## Version of OpenTTD
1.11.0
## Expected result
The message shows the correct location of the incident
## Actual result
The shown location of the incident is incorrect - it always shows the top left edge of the map.
Wrong localisation of disaster 1

## Steps to reproduce
The bug always appears, just start the game with disasters.

### PR DESCRIPTION
**Pull request by LordAro**
## Motivation / Problem
Industry disaster news messages showed the wrong location

## Description
Caused by dff7ee8e1c6
Used dest_tile as the location, which was actually the Industry ID. Use the correct news message function instead

## Limitations
Haven't actually been able to trigger the disaster to test it yet...

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/disaster_vehicle.cpp [hunk 1]
```diff
@@ -456,7 +456,7 @@ static bool DisasterTick_Aircraft(DisasterVehicle *v, uint16 image_override, boo
 			DestructIndustry(i);
 
 			SetDParam(0, i->town->index);
-			AddTileNewsItem(news_message, NT_ACCIDENT, v->dest_tile);
+			AddIndustryNewsItem(news_message, NT_ACCIDENT, (IndustryID)v->dest_tile);
```
Comment (TrueBrain) [inline src/disaster_vehicle.cpp]: better use `i->index` ? As `i->town->index` is still valid, I assume so is `i->index`. But that is an assumption :D

Comment (TrueBrain) [reply src/disaster_vehicle.cpp]: Owh, it used to be `i->index`. Seems we should just revert the change I made in dff7ee8e1c68199a0dc105e82e588ac097543645 as the correct solution. I think it just got caught in my search for `->index`, without realising this was the industry, instead of the vehicle.

Comment (LordAro) [reply src/disaster_vehicle.cpp]: I thought about it, but figured it might be slightly cleaner to use the variable that we use to get the `Industry` object in the first place, a couple of lines further up ¯\\\_(ツ)_/¯

**Review by TrueBrain — APPROVED** [review]
