### PR TITLE
Fix #10150: Force FS_SMALL for small viewport signs.

### LINKED ISSUE #10150: [Bug]: Names of cities on the map are shortened pointlessly after changing the font
### Version of OpenTTD

12.2 (not new bug)

### Expected result

City names are only shortened if they are really long or they are never shortened.

### Actual result

After changing the font, the names of cities on the game map (zoom out) are shortened against any visible logic. Very often, short names are abbreviated while long names remain unchanged. Moreover, the abbreviated name of the city + ... also very often have the same or very similar length as not abbreviated. This is rare for original English names and quite common for Fictional Town Names. Not all fonts are affected.

small Arial

small Verdana

Better town names

Better town names 2

### Steps to reproduce

1. Change small font to Arial, Calibri or Verdana.
2. Generate a map with multiple cities, preferably with some add-on that change the names of the cities.
3. More or less of the cities will have a shortened name in the zoom out view.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

As per #10150, small town sign labels may be cropped with Truetype fonts.

image

This is a workaround for string widths being different with mixed font-sizes.

For some reason (with Uniscribe at least), the string bounding box of "{FS_SMALL}Text" can be different when called starting with FS_SMALL and FS_NORMAL.

## Description

image

This is resolved by explicitly drawing small signs with FS_SMALL, although the underlying problem is not touched.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/viewport.cpp [hunk 1]
```diff
@@ -1323,7 +1323,7 @@ void ViewportAddString(const DrawPixelInfo *dpi, ZoomLevel small_from, const Vie
 		int shadow_offset = 0;
 		if (string_small_shadow != STR_NULL) {
 			shadow_offset = 4;
-			AddStringToDraw(sign->center - sign_half_width + shadow_offset, sign->top, string_small_shadow, params_1, params_2, INVALID_COLOUR, sign->width_small);
+			AddStringToDraw(sign->center - sign_half_width + shadow_offset, sign->top, string_small_shadow, params_1, params_2, INVALID_COLOUR, sign->width_small | 0x8000);
```
Comment (2TallTyler) [inline src/viewport.cpp:1326]: Is there not a flag enum for this?

Comment (PeterN) [reply src/viewport.cpp:1326]: No, it is only used here, and only tested with `HasBit(ss.width, 15)`. I have in mind a proper rewrite so don't really want to start adding flags.

**Review by 2TallTyler — APPROVED** [review]
