### PR TITLE
Fix #9697: don't extend the Online Players window too wide on opening

### LINKED ISSUE #9697: [Bug]: Long server name sometimes forces Online Players window to be very wide
### Version of OpenTTD

12.0 / 12.1 Win10

### Expected result

You can significantly reduce the width of the window. Saving window size works.

### Actual result

The width of the window varies almost each time the game is started and gives the impression of being random. Very often this width is senselessly large and cannot be reduced. Sometimes changing the language unlocks the possibility of reducing the width. Saving the window size doesn't work.

The minimum width of the window after entering the server
Senselessly big window

The minimum width of the window after closing the game and re-entering the server
Narrower window after changing the language

This method doesn't always work.

### Steps to reproduce

The situation is repetitive, but I don't see the key. The problem seems to arise after trying to save the window size.

### PR DESCRIPTION
**Pull request by TrueBrain**
## Motivation / Problem

Fixes #9697.

## Description

Cap the server-name / client-name to 200px when opening. This prevents a very wide Online Players for no real good reason.

Users can still scale it to bigger formats if they want.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/network/network_gui.cpp [hunk 1]
```diff
@@ -1677,6 +1677,18 @@ struct NetworkClientListWindow : Window {
...
+			case WID_CL_SERVER_NAME:
+			case WID_CL_CLIENT_NAME:
+				if (widget == WID_CL_SERVER_NAME) {
+					SetDParamStr(0, _network_server ? _settings_client.network.server_name : _network_server_name);
+				} else {
+					const NetworkClientInfo *own_ci = NetworkClientInfo::GetByClientID(_network_own_client_id);
+					SetDParamStr(0, own_ci != nullptr ? own_ci->client_name : _settings_client.network.client_name);
+				}
+				*size = GetStringBoundingBox(STR_JUST_RAW_STRING);
+				size->width = std::min(size->width, 200u); // By default, don't open the window too wide.
```
Comment (frosch123) [inline src/network/network_gui.cpp]: Shouldn't this 200 account for GUI zoom?

Comment (TrueBrain) [reply src/network/network_gui.cpp]: @PeterN told me to think about it.

Clearly I failed the assignment.

**Review by rubidium42 — APPROVED** [review]
