### PR TITLE
Fix #6659: Bus stations can be demolished when not in demolish mode

### LINKED ISSUE #6659: Bus stations can be demolished when not in the demolish mode.
**_james1101_ opened the ticket and wrote:**

> Using Win 7 Ultimate
> 
> To Reproduce:
> 1. Build a bus stop.
> 2. Select the bus stop building icon and then select the demolish icon.
> 3. Click and hold on the bus stop you just built.
> 4. Press R to go out of the demolishing mode.
> 5. Release the mouse button.
> 6. The bus stop is still demolished, even though when you released the mouse it was not in the demolish mode.
> To clarify the steps, I've attached a visual version of them.
> 
> Works with: Bus and tram stops (both passenger and freight)
> Does not work with: Train stations, railway tracks and roads

**Attachments**
- [ottd-busstop-destroy-build_mode.png](https://bugs.openttd.org/task/6659/getfile/10939/ottd-busstop-destroy-build_mode.png) (50.72 KiB)

**Reported version**: _1.7.2-RC1_
**Operating system**: _Windows_

---

### PR DESCRIPTION
**Pull request by alex6m59**
For Bus and Road stations only, if you are in demolish mode and click on the station
without releasing the button. Then you cancel demolish mode with R key.
Finally you release the mouse button. The station was demolished, instead of being built.

The demolish mode was not checked when mouse up event occured.

### CODE REVIEW

File: src/road_gui.cpp [hunk 1]
```diff
@@ -633,22 +633,28 @@ struct BuildRoadToolbarWindow : Window {
...
-					break;
-
-				case DDSP_BUILD_TRUCKSTOP:
-					PlaceRoadStop(start_tile, end_tile, (_ctrl_pressed << 5) | RoadTypeToRoadTypes(_cur_roadtype) << 2 | ROADSTOP_TRUCK, CMD_BUILD_ROAD_STOP | CMD_MSG(_road_type_infos[_cur_roadtype].err_build_station[ROADSTOP_TRUCK]));
-					break;
-
 				case DDSP_REMOVE_BUSSTOP: {
-					TileArea ta(start_tile, end_tile);
-					DoCommandP(ta.tile, ta.w | ta.h << 8, (_ctrl_pressed << 1) | ROADSTOP_BUS, CMD_REMOVE_ROAD_STOP | CMD_MSG(_road_type_infos[_cur_roadtype].err_remove_station[ROADSTOP_BUS]), CcPlaySound_SPLAT_OTHER);
+					if(this->IsWidgetLowered(WID_ROT_BUS_STATION)) {
```
Comment (PeterN) [inline src/road_gui.cpp]: Space between if and ( please.

File: src/road_gui.cpp [hunk 2]
```diff
@@ -633,22 +633,28 @@ struct BuildRoadToolbarWindow : Window {
...
 
 				case DDSP_BUILD_BUSSTOP:
-					PlaceRoadStop(start_tile, end_tile, (_ctrl_pressed << 5) | RoadTypeToRoadTypes(_cur_roadtype) << 2 | ROADSTOP_BUS, CMD_BUILD_ROAD_STOP | CMD_MSG(_road_type_infos[_cur_roadtype].err_build_station[ROADSTOP_BUS]));
-					break;
-
-				case DDSP_BUILD_TRUCKSTOP:
-					PlaceRoadStop(start_tile, end_tile, (_ctrl_pressed << 5) | RoadTypeToRoadTypes(_cur_roadtype) << 2 | ROADSTOP_TRUCK, CMD_BUILD_ROAD_STOP | CMD_MSG(_road_type_infos[_cur_roadtype].err_build_station[ROADSTOP_TRUCK]));
-					break;
-
 				case DDSP_REMOVE_BUSSTOP: {
```
Comment (PeterN) [inline src/road_gui.cpp]: Braces are no longer needed for this switch case.

**Review by PeterN — APPROVED** [review]
