### PR TITLE
Fix #9908: Close company windows only after all its infrastructure is removed

### LINKED ISSUE #9908: [Crash]: order backup
### Version of OpenTTD

20220531-master-g9fca8af586, windows 10

### Steps to reproduce

1. start openttd
2. click multiplayer
3. click start server
4. click new game
5. build a depot
6. build a vehicle in that depot (this is vehicle 1)
7. give it orders
8. clone vehicle 1 (vehicle 2 is created)
9. sell vehicle 2
10. important: leave the depot window open
11. on the online players window, join spectators
12. delete the company where you built the vehicles

crash!

### Upload crash files

[crash20220601104256.zip](https://github.com/OpenTTD/OpenTTD/files/8813369/crash20220601104256.zip)

### PR DESCRIPTION
**Pull request by SamuXarick**
## Motivation / Problem
When a company bankrupts, and the user has a depot window open with an order backup, it will cause the command clearing this backup to fire during execution of the bankrupt command. This is not allowed, and asserts.

## Description
Since the company infrastructure is being removed anyway, let the game logic, i.e. the clearing of the depot tile, remove the order backup, as there is no need to actually sync this.

Closes #9908 - edit 2TT

## Limitations
I'm assuming there will be none.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/company_cmd.cpp [hunk 1]
```diff
@@ -876,8 +876,6 @@ CommandCost CmdCompanyCtrl(DoCommandFlag flags, CompanyCtrlAction cca, CompanyID
 
 			if (!(flags & DC_EXEC)) return CommandCost();
 
-			/* Delete any open window of the company */
-			CloseCompanyWindows(c->index);
```
Comment (glx22) [inline src/company_cmd.cpp:880]: I think it should be moved somewhere between  `ChangeOwnershipOfCompanyItems()` call and `delete c`.
Many windows will be closed automatically when removing assets (like depot windows), but you want to make sure to also close possible left over.

Comment (SamuXarick) [reply src/company_cmd.cpp:880]: `delete c` does also call `CloseCompanyWindows` by itself, so I thought it wouldn't be needed.

**Review by glx22 — APPROVED** [review]
