### PR TITLE
List recent news messages in crashlog output

### LINKED ISSUE #5722: Add news messages to crashlog
**_LordAro_ opened the ticket and wrote:**

> As per the Todo list, i have added pending news messages to the crashlog
> 
> hg patch queue, based on r25739
> patch 02_ isn't strictly necessary, but is nice to have :)
> 
> However, i would like some feedback regarding patch 03 - 
> Alberth pointed out to me that converting StringIDs to text after a crash probably isn't very safe.
> So, should i store a char* of the message in the NewsItem object, or just list the relevant numbers from the NewsItem? Or something else altogether?

**Attachments**
- [01_refactor_news.diff](https://bugs.openttd.org/task/5722/getfile/9305/01_refactor_news.diff) (56.71 KiB)
- [02_doxyment_fixes.diff](https://bugs.openttd.org/task/5722/getfile/9306/02_doxyment_fixes.diff) (24.22 KiB)
- [03_crashlog_newsitems.diff](https://bugs.openttd.org/task/5722/getfile/9307/03_crashlog_newsitems.diff) (4.34 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

### PR DESCRIPTION
**Pull request by LordAro**
As per todo list. A very-much cut down version of a patch I made 5 years ago in #5722 with further comments applied to it.

Output looks approximately like:

Closes #5722.

### CODE REVIEW

File: src/news_gui.cpp [hunk 1]
```diff
@@ -42,10 +42,10 @@
 
 const NewsItem *_statusbar_news_item = NULL;
 
-static uint MIN_NEWS_AMOUNT = 30;           ///< preferred minimum amount of news messages
-static uint _total_news = 0;                ///< current number of news items
-static NewsItem *_oldest_news = NULL;       ///< head of news items queue
-static NewsItem *_latest_news = NULL;       ///< tail of news items queue
+static uint MIN_NEWS_AMOUNT = 30;      ///< preferred minimum amount of news messages
+static uint _total_news = 0;           ///< current number of news items
+NewsItem *_oldest_news = NULL;         ///< head of news items queue
```
Comment (TrueBrain) [inline src/news_gui.cpp:47]: This is visually weird. Please don't group static and non-static this close together. Also, _ means 'local'. It now is global. I believe g_ is the global identifier?

Comment (frosch123) [reply src/news_gui.cpp:47]: We do not distinguish internal and external linkage in names.
We only distinguish scope, and _ prefix is for variables in global scope.

**Review by frosch123 — APPROVED** [review]

File: src/news_gui.cpp (hunk 1 above)
Comment (TrueBrain) [reply src/news_gui.cpp:47]: Owh my ... I clearly havent read any code in OpenTTD for a while :D My apologizes!
