### PR TITLE
Fix #12901: Savegame format of company allow lists

### LINKED ISSUE #12901: [Bug]: Savegame storage of CompanyProperties::allow_list results in invalid table format
### Version of OpenTTD

Since #12337

### Expected result

Savegame chunks which use the new table format meet the format requirements

### Actual result

Savegames where CompanyProperties::allow_list is non-empty can't be parsed by savegame reader tools like https://github.com/TrueBrain/OpenTTD-savegame-reader, because the field as saved does not use the required format.
If the field is not present when loading, the discard unknown table field mechanism does not work with this field when it is non-empty.

### Steps to reproduce

Create a savegame which has an allow public key (e.g. start a new multiplayer server).
Look at the savegame with https://github.com/TrueBrain/OpenTTD-savegame-reader or an equivalent tool.

### PR DESCRIPTION
**Pull request by JGRennison**
## Motivation / Problem

#12901: Savegame format of company allow lists .

## Description

Use sub-struct list for company allow lists.
Disallow saving of invalid string container table fields.

## Limitations

N/A

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by PeterN** [comment]
I'm confused as to what makes a `SL_...VECTOR` of `SLE_STR` special and not valid.

**Comment by JGRennison** [comment]
In the new table format, a string is a length-prefixed sequence of chars.
i.e. the field type is SLE_FILE_STRING | SLE_FILE_HAS_LENGTH_FIELD.

The total length of the field is therefore the size of the length prefix itself plus the length value.

It is not valid to put a second length prefix in front, but still label the field as SLE_FILE_STRING | SLE_FILE_HAS_LENGTH_FIELD.
In #12337 the outer length prefix is not actually a length prefix, but a number of sub-items, it does not match the number of bytes which follow in the field.
As the field is still advertised as a string with one length prefix, readers are entitled to incorrectly read this length prefix as the number of chars in the string.

Potentially the table format could be extended to support fields with nested length prefixes, with a new field type for this, but it seems more pragmatic to use SLE_FILE_STRUCT | SLE_FILE_HAS_LENGTH_FIELD along with a string field in the sub-table, which seems the intended way that the format is meant to be used.

**Comment by PeterN** [comment]
Ah, so both `SL_...VECTOR` and `SLE_STR` are using the same flag `SLE_FILE_HAS_LENGTH_FIELD` in the same place, which only works because `_company_desc` knows what the record is.

File: src/saveload/saveload.cpp [hunk 1]
```diff
@@ -1368,7 +1364,6 @@ static inline size_t SlCalcDequeLen(const void *deque, VarType conv)
 		case SLE_VAR_U32: return SlStorageHelper<std::deque, uint32_t>::SlCalcLen(deque, conv);
 		case SLE_VAR_I64: return SlStorageHelper<std::deque, int64_t>::SlCalcLen(deque, conv);
 		case SLE_VAR_U64: return SlStorageHelper<std::deque, uint64_t>::SlCalcLen(deque, conv);
-		case SLE_VAR_STR: return SlStorageHelper<std::deque, std::string>::SlCalcLen(deque, conv, SL_STDSTR);
```
Comment (rubidium42) [inline src/saveload/saveload.cpp:1371]: Might be useful to retain the `case` with documentation that no  variable-sized elements may be in the `deque`, and similar to the variant in `SlCalcVectorLen`.
Maybe something along the lines of: `case SLE_VAR_STR: // Variable-sized elements require special handling for the save game to follow the specifications. Use a struct list instead.` should "scare" us from doing it again. And it would make it much easier to prevent such things in future reviews.

**Review by rubidium42 — APPROVED** [review]
