### PR TITLE
Fix #8860: [Win32] Crashlog window wasn't reliably shown for crashes.

### LINKED ISSUE #8860: Windows: wrong stack pointer for crash log dialog window on non-main thread
In the current Windows exception handler, a dialog box is shown by changing the instruction and stack pointers and then continuing execution.

_safe_esp is used as the new stack pointer.
ShowCrashlogWindow is used as the new instruction pointer.

_safe_esp is set to a value of the stack pointer of the main thread during initialisation. Therefore, this mechanism is not valid for handling crashes on non-main threads as the wrong stack would be used. When testing on 32 and 64 bit x86 the dialog box indeed failed to be displayed.

As the game loop and other functionality is now no longer in the main thread, crashes which are also not in the main thread can be expected to become less uncommon in future.

I've resolved this in my branch by using the top of stack from the thread environment block for non-main threads, but I don't expect you to necessarily be happy with that solution. I still thought it may be of interest to draw your attention to it though.
I did not add a fix for ARM as I've got no way of testing it, in principle you can use the same mechanism though.
https://github.com/JGRennison/OpenTTD-patches/commit/883e19f2c623e501195fdbbb4ade09c24bdce65a

### PR DESCRIPTION
**Pull request by michicc**
## Motivation / Problem

If a crash occurs on a different thread to the main thread, the crashlog window wasn't reliably shown on windows.

## Description

Crashlog on windows relies on a captured stack pointer to always have a safe stack area. We only captured the stack pointer on the main thread, which doesn't work when calling the crashlog handler from a different thread.

To solve this, we make the stack pointer a thread local var and capture it on thread init.

## Limitations

@JGRennison has an alternate suggestion in #8860, which, as far as I can see, would be enough for Windows (expect ARM64). This PR implements a solution that is more general, which in the future could be used to support thread specific things also on other platforms.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/crashlog.h [hunk 1]
```diff
@@ -114,6 +114,12 @@ class CrashLog {
 	 */
 	static void InitialiseCrashLog();
 
+	/**
+	 * Initialiser in case a newly started thread has to be prepared for the crash log.
```
Comment (TrueBrain) [inline src/crashlog.h]: this is a weird sentence .. initialiser in case a thread has to be prepared .. feels really vague :D Can't you make it more absolute in what it does / when it has to be called?

Comment (michicc) [reply src/crashlog.h]: I just copied the language from the comment for `InitialiseCrashLog` directly above, but you are right that it reads a bit strange.

**Review by TrueBrain — APPROVED** [review]
