### PR TITLE
Remove: [Script] CONFIG_RANDOM from AddSetting flags

### LINKED ISSUE #9540: [Bug]: AI/GS settings with the flag SCRIPTCONFIG_RANDOM are re-randomized after loading from a savegame
### Version of OpenTTD

12.0-beta2, Windows 10

### Expected result

AI/GS settings with the flag SCRIPTCONFIG_RANDOM are unaltered after loading from a savegame.

### Actual result

AI/GS settings with the flag SCRIPTCONFIG_RANDOM are re-randomized after loading from a savegame.

### Steps to reproduce

1. Download LuDiAI AfterFix from the online content, as it is one such AI that makes use of SCRIPTCONFIG_RANDOM flag on some of its settings.
2. Set it up to start.
3. Start new game and let the AI start.
4. Take a screenshot of the AI settings window, via AI Debug / Settings
Unnamed, 1935-01-09

5. Save game.
6. Load it back.
7. Check AI Settings again, compare it to the screenshot, they've been randomized.
Unnamed, 1935-01-20

Note that only the following settings use SCRIPTCONFIG_RANDOM, combined with SCRIPTCONFIG_INGAME, resulting in the re-randomization of settings after loading from a savegame, and that is not the intended behaviour:
"is_friendly" - flags = CONFIG_BOOLEAN | CONFIG_RANDOM | CONFIG_INGAME
"station_spread" - flags = CONFIG_BOOLEAN | CONFIG_RANDOM | CONFIG_INGAME
"pf_profile" - flags = CONFIG_RANDOM | CONFIG_INGAME
"road_cap_mode" - flags = CONFIG_RANDOM | CONFIG_INGAME
"road_load_mode" - flags = CONFIG_RANDOM | CONFIG_INGAME

The following settings also use SCRIPTCONFIG_RANDOM, but don't get re-randomized, which is the intended behaviour:
"select_town_cargo" - flags = CONFIG_RANDOM
"cities_only" - flags = CONFIG_BOOLEAN | CONFIG_RANDOM
"pick_mode" - flags =  CONFIG_RANDOM
"scp_support" - flags = CONFIG_BOOLEAN | CONFIG_RANDOM

### PR DESCRIPTION
**Pull request by TrueBrain**
## Motivation / Problem

Closes #11914
Fixes #9540

`CONFIG_RANDOM`, which can be used as flag in `AIInfo.AddSetting` and `GSInfo.AddSetting` is a weird flag. It is commented to only be used when difficulty is "custom", but this wasn't actually what the code was doing. It was only checked and used when an AI was "changed", which happens in several moments:

- When the current saved version of an AI can't be loaded, but an older version is
- When a random AI is starting

And some other weird cases. Anyway, when that happened, the setting was randomized, no matter what the difficulty setting was. But this flag was never read when an AI started via normal configuration. This is all a very weird interaction, with unpredictable results.

Upon further investigation, turns out no AI / GS actually uses it, all but one. That gives me the impression the flag was also actually never understood. Time to remove it.

With access to all BaNaNaS content:
```
$ grep -R CONFIG_RANDOM | cut -d/ -f2,3 | cut -d- -f1 | uniq
4c444146/LuDiAI_AfterFix
46454747/Feca_Goal_Games
49444c49/Limitations
```
The 2nd and 3rd hit are commented out references to `CONFIG_RANDOM`. Only the first actually uses it.

## Description

Remove `CONFIG_RANDOM`. Well, I say remove, but as it is `AIInfo`, we actually can't remove it, as there is no compatibility layer for this class (as it needs info from that class to load the right layer). So it just maps to `CONFIG_NONE`. But it is removed from the documentation :)

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by frosch123 — DISMISSED** [review]

File: src/script/script_config.hpp [hunk 1]
```diff
@@ -20,7 +20,6 @@ static const int INT32_DIGITS_WITH_SIGN_AND_TERMINATION = 10 + 1 + 1;
 /** Bitmask of flags for Script settings. */
 enum ScriptConfigFlags {
 	SCRIPTCONFIG_NONE      = 0x0, ///< No flags set.
-	SCRIPTCONFIG_RANDOM    = 0x1, ///< When randomizing the Script, pick any value between min_value and max_value when on custom difficulty setting.
```
Comment (glx22) [inline src/script/script_config.hpp:23]: Maybe replace with a comment to explain the hole

**Review by glx22 — APPROVED** [review]
