### PR TITLE
Fix #7590: decrement allocated_size in ScriptAllocator::Free()

### LINKED ISSUE #7590: If you change the game mode 9 times in succession, then the game crashes on the ninth attempt.
## Version of OpenTTD
20190511-master-g38bb6b7d1b

## Expected result
The game doesn't crash at all when creating a new map, loading a saved game, or otherwise modifying the game state.

## Actual result
On the ninth time that you create a new world, load a saved game, or otherwise modify the gamemode, the game crashes hard. Note that the exact crash is different depending on the last game-mode-modifying action you took, but there are two similar crash logs that account for all situations mentioned below.
[Crash log for the hard crash (no error message)](https://github.com/OpenTTD/OpenTTD/files/3170748/Crash.log.when.creating.new.world.zip)
[Crash log for the crash with the error message](https://github.com/OpenTTD/OpenTTD/files/3170749/Crash.log.when.loading.any.savegame.zip)

## Steps to reproduce
Create a new world, load a saved game, start scenario editor, connect to or (re)start a server, return to the title screen, or otherwise modify the game mode 9 times. The 1st through 8th attempts will go through, but the 9th attempt crashes with either an E06D7363 error or C0000005 error.

Edit: Just running "rescanai" 9 times or running "rescangame" 18 times is enough to crash the game with [this log (should be similar to above).](https://github.com/OpenTTD/OpenTTD/files/3175085/OpenTTD.-.1.zip)

### PR DESCRIPTION
**Pull request by glx22**
There are other issues to fix in relation to `ScriptAllocator`, but properly counting will already reduce the probability of apparition of these issues.

### CODE REVIEW

**Review by PeterN — DISMISSED** [review]

File: src/script/script_scanner.cpp [hunk 1]
```diff
@@ -52,8 +53,12 @@ bool ScriptScanner::AddFile(const char *filename, size_t basepath_length, const
 	if (!FioCheckFileExists(filename, this->subdir) || !FioCheckFileExists(this->main_script, this->subdir)) return false;
 
 	this->ResetEngine();
-	this->engine->LoadScript(filename);
-
+	try {
+		this->engine->LoadScript(filename);
+	} catch (Script_FatalError e) {
```
Comment (michicc) [inline src/script/script_scanner.cpp]: The general recommendation is to catch exceptions by reference to avoid copy constructors being run during exception handling.

Comment (glx22) [reply src/script/script_scanner.cpp]: I did as other catches in this area, but I guess they should all change to reference. That can be done in another PR I think.

**Review by michicc — APPROVED** [review]
