### PR TITLE
Fix #14802: close NewGRF inspection window when overbuilding with default station/waypoint

### LINKED ISSUE #14802: [Crash]: Crash when overbuilding a station with the default station while the newgrf inspector window is open
### Version of OpenTTD

20251118

### Steps to reproduce

A very esoteric bug which few people are going to encounter, but it is what it is.

- Build a newgrf station.
- Inspect with '?', then open the newgrf debug window.
- Overbuild the station with the default station.

### Upload crash files

Image

### PR DESCRIPTION
**Pull request by rubidium42**
## Motivation / Problem

Fixes #14802.

## Description

The NewGRF station debug window is tile-based, so just close the window when we (over)build a default station/waypoint.

## Limitations

None I can think of.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/station_cmd.cpp [hunk 1]
```diff
@@ -1560,6 +1560,7 @@ CommandCost CmdBuildRailStation(DoCommandFlags flags, TileIndex tile_org, RailTy
 				DeallocateSpecFromStation(st, old_specindex);
 
 				SetCustomStationSpecIndex(tile, *specindex);
+				if (*specindex == 0) DeleteNewGRFInspectWindow(GSF_STATIONS, tile);
 				SetStationTileRandomBits(tile, GB(Random(), 0, 4));
 				SetAnimationFrame(tile, 0);
```
Comment (PeterN) [inline src/station_cmd.cpp:1565]: I think I'd prefer to keep the `Set.*()` lines that modify the map together and put the GUI-affecting line separate.

There is also the `if (statspec != nullptr)` if-condition just below, of which the `else` would also be a `*specindex == 0`.

Comment (rubidium42) [reply src/station_cmd.cpp:1565]: Though that `if` condition is followed by yet another of the `Set.*()` lines.

With stations the GUI affecting code is in a completely different function. What about putting it after the calls to `DeallocateSpecFromStation`? Those seem reasonably related I'd say.

Comment (PeterN) [reply src/station_cmd.cpp:1565]: Yes that works, and also helps with intentions.

**Review by PeterN — APPROVED** [review]
