### PR TITLE
Fix #9546: Crash when no industries are present in game

### LINKED ISSUE #9546: [Crash]: Assertion failed on "Fund new industry" when no industries exist
### Version of OpenTTD

12.0 beta 2 Windows 10

### Steps to reproduce

1. Install and activate the [feature disabler NewGRF](https://bananas.openttd.org/package/newgrf/47572121), making sure that the parameters are set to remove all industries.
2. Start a new game.
3. Click on industry button > "Fund new industries"
4. The game asserts here:
https://github.com/OpenTTD/OpenTTD/blob/7469f00c5b8d0dc5cc2034eb9dc91c6e8721ac03/src/industry_cmd.cpp#L121-L125

### Upload crash files

[crash.zip](https://github.com/OpenTTD/OpenTTD/files/7136473/crash.zip)

### PR DESCRIPTION
**Pull request by Kiptoke**
## Motivation / Problem

Resolves #9546:
When industries are removed entirely using the [feature disabler NewGRF](https://bananas.openttd.org/package/newgrf/47572121), a crash occurs when the player opens up the "Fund New Industries" window.

## Description

In the `GetIndustrySpec` function within `industry_cmp.cpp`, changed the assertion statement from `assert(thistype < NUM_INDUSTRYTYPES);` to `assert(thistype <= NUM_INDUSTRYTYPES);`

This resolves #9546 - now instead of the Fund New Industries window crashing the game, it shows up empty.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/industry_cmd.cpp [hunk 1]
```diff
@@ -115,12 +115,12 @@ IndustryType GetIndustryType(TileIndex tile)
...
  * @param thistype of industry (which is the index in _industry_specs)
- * @pre thistype < NUM_INDUSTRYTYPES
+ * @pre thistype <= NUM_INDUSTRYTYPES
  * @return a pointer to the corresponding industry spec
  */
 const IndustrySpec *GetIndustrySpec(IndustryType thistype)
 {
-	assert(thistype < NUM_INDUSTRYTYPES);
+	assert(thistype <= NUM_INDUSTRYTYPES);
 	return &_industry_specs[thistype];
```
Comment (glx22) [inline src/industry_cmd.cpp]: But if `thistype` is equal to `NUM_INDUSTRYTYPES` you can cause an invalid read, as `NUM_INDUSTRYTYPES` is out of the array bounds.

File: src/industry_gui.cpp [hunk 2]
```diff
@@ -732,6 +736,7 @@ class BuildIndustryWindow : public Window {
 	void OnHundredthTick() override
 	{
 		if (_game_mode == GM_EDITOR) return;
+		if (count == 0) return;
```
Comment (nielsmh) [inline src/industry_gui.cpp]:
```suggestion
		if (this->count == 0) return;
```
Code style guidelines prescribe that class members must always be qualified,

File: src/industry_gui.cpp [hunk 3]
```diff
@@ -499,8 +499,12 @@ class BuildIndustryWindow : public Window {
 					/* We've chosen many random industries but no industries have been specified */
 					SetDParam(0, STR_FUND_INDUSTRY_BUILD_NEW_INDUSTRY);
 				} else {
-					const IndustrySpec *indsp = GetIndustrySpec(this->index[this->selected_index]);
-					SetDParam(0, (_settings_game.construction.raw_industry_construction == 2 && indsp->IsRawIndustry()) ? STR_FUND_INDUSTRY_PROSPECT_NEW_INDUSTRY : STR_FUND_INDUSTRY_FUND_NEW_INDUSTRY);
+					if (count > 0) {
+						const IndustrySpec *indsp = GetIndustrySpec(this->index[this->selected_index]);
+						SetDParam(0, (_settings_game.construction.raw_industry_construction == 2 && indsp->IsRawIndustry()) ? STR_FUND_INDUSTRY_PROSPECT_NEW_INDUSTRY : STR_FUND_INDUSTRY_FUND_NEW_INDUSTRY);
+					} else {
+						SetDParam(0, (_settings_game.construction.raw_industry_construction == 2 && false) ? STR_FUND_INDUSTRY_PROSPECT_NEW_INDUSTRY : STR_FUND_INDUSTRY_FUND_NEW_INDUSTRY);
```
Comment (LordAro) [inline src/industry_gui.cpp]: `&& false` ?

I think we can remove some code here

Comment (LordAro) [inline src/industry_gui.cpp:506]: `&& false` ?

I think we can remove some code here

**Review by LordAro — CHANGES_REQUESTED** [review]
You seem to have changed file modes to 100644 -> 100755 as well - please revert this change

(If you're on Windows, this can be tricky - see http://blog.lesc.se/2011/11/how-to-change-file-premissions-in-git.html (but use `-x` instead of `+x` )

**Review by rubidium42 — DISMISSED** [review]

**Review by LordAro — APPROVED** [review]
