### PR TITLE
Fix #12973: Don't exclude high score after using sandbox options

### LINKED ISSUE #12973: [Bug]: Score excluded from highscore when using sandbox
### Version of OpenTTD

from 14.0

### Expected result

Since these are no longer cheating options, using any of the sandbox options by the player should not cause any consequences for them - the final score should not be excluded from the highscore table.

### Actual result

After using a sandbox setting, the players score no longer ends up in the highscore.

### Steps to reproduce

Use the sandbox option and try to save your company to the highscore table.

### PR DESCRIPTION
**Pull request by Da-W1nn3r**
## Motivation / Problem

#12973 Score excluded from highscore when using sandbox
Using the sandbox options now no longer excludes you from the highscore list

## Description
Check for using cheats removed from highscore
All has_been_used flags for cheats have been removed
Using the sandbox options now no longer excludes you from the highscore list

Closes #12973.

## Limitations

None that I am aware of.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by 2TallTyler — COMMENTED** [review]
Thanks for the contribution! It's always nice to see a new face around here. 🙂 

A few notes for you:
* The commit message must match our standard format. In this case, I suggest `Fix #12973: Don't exclude high score after using sandbox options` (I have changed the PR title to match).
* `CheatHasBeenUsed()` is no longer called anywhere, so it should be removed from `highscore.cpp` and `cheat_func.h`.

**Review by 2TallTyler — COMMENTED** [review]
You need to remove the function definition, not just the declaration. 🙂 

Also, don't forget to squash your commits into one message meeting our guidelines (I suggested a message previously). You can do this with an interactive rebase.

**Review by 2TallTyler — COMMENTED** [review]
Now that you're removing `been_used`, you'll need to fix the cheat save/load code. This is in `cheat_sl.cpp` and `cheat_sl_compat.h`.

That said, the plan is to eliminate the cheat/sandbox menu entirely and move cheats to the existing Settings menu. It might be less effort to just do that. Of course, some cheats are actions (money cheat, change date, and change company) and don't fit in Settings in their current form. Some strategic thinking is needed. 🙂

(I am not asking or expecting you to lead this, just explaining that this is a much bigger topic than it appears.)

**Comment by 2TallTyler** [comment]
Actually, on second thought, you'll have a much easier time if you leave `been_used` alone. We can still [read it in savegames](https://truebrain.github.io/OpenTTD-savegame-reader/), and removing it is a much bigger project, as described in my previous comment. 😄

File: src/cheat_gui.cpp [hunk 1]
```diff
@@ -249,7 +249,7 @@ struct CheatWindow : Window {
 
 		bool rtl = _current_text_dir == TD_RTL;
 		uint button_left = rtl ? ir.right - SETTING_BUTTON_WIDTH : ir.left;
-		uint text_left   = ir.left + (rtl ? 0 : WidgetDimensions::scaled.hsep_wide + SETTING_BUTTON_WIDTH);
+		uint text_left 	 = ir.left + (rtl ? 0 : WidgetDimensions::scaled.hsep_wide + SETTING_BUTTON_WIDTH);
```
Comment (2TallTyler) [inline src/cheat_gui.cpp]: Sneaky space snuck in here somehow. 😉

Comment (Da-W1nn3r) [reply src/cheat_gui.cpp]: Did not realise there was a tab there, sorry. Should be fixed now.

**Review by rubidium42 — APPROVED** [review]

**Comment by 2TallTyler** [comment]
Thanks for the fix, @Da-W1nn3r! 😄
