### PR TITLE
Fix #9527: Crash when trying to place multitile objects at map edge

### LINKED ISSUE #9527: [Crash]: NewGRF with multi-tile object causes OpenTTD 12.0-beta2 to crash on map generation
### Version of OpenTTD

OpenTTD 12.0-beta2

### Steps to reproduce

1. Create a simple 2x2 object in nml with the following switch (or use attached NewGRF)

```
switch (FEAT_OBJECTS, SELF, switch_sprite_layouts_rocks, relative_pos) {
		relative_coord(0, 0):			spritelayout_rocks;
		relative_coord(0, 1):			spritelayout_rocks;
		relative_coord(1, 0):			spritelayout_rocks;
		relative_coord(1, 1):			spritelayout_rocks;
}
```
2. Build the NewGRF with NML 0.6.0

3. Start a new game

4. OpenTTD will crash during map generation
image

The same NewGRF works properly in OpenTTD 1.10.2.

### Upload crash files

[crash.zip](https://github.com/OpenTTD/OpenTTD/files/7084901/crash.zip)
[multitile_object.zip](https://github.com/OpenTTD/OpenTTD/files/7084953/multitile_object.zip)

### PR DESCRIPTION
**Pull request by LordAro**
## Motivation / Problem
#9527

Building objects did not do any bounds checking. Fine for 1x1 objects, less so for others

Also spotted an issue with a previous fix in the same area

## Description

Add a check of all the tiles for validity. Not sure if there's a better way.

Also fix the check for zero-size objects, which was missing a bitshift (32 != 0). and bump the grf message up a level (to 0), as grf makers will probably want to see it
Example of issue: `0xF0 & 0x22 === 0x20 === 32 !== 2` Therefore if the lower nibble is 0, it would not be correctly detected as such.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/object_cmd.cpp [hunk 1]
```diff
@@ -220,6 +220,9 @@ CommandCost CmdBuildObject(TileIndex tile, DoCommandFlag flags, uint32 p1, uint3
 	int size_x = GB(spec->size, HasBit(view, 0) ? 4 : 0, 4);
 	int size_y = GB(spec->size, HasBit(view, 0) ? 0 : 4, 4);
 	TileArea ta(tile, size_x, size_y);
+	for (TileIndex t : ta) {
+		if (!IsValidTile(t)) return CMD_ERROR; // Might be off the map
```
Comment (James103) [inline src/object_cmd.cpp]: Could this be changed to any of the two following lines?
```c++
if (!IsValidTile(t)) return_cmd_error(STR_ERROR_OFF_EDGE_OF_MAP); // Might be off the map
```
or alternatively,
```c++
if (!IsValidTile(t)) return_cmd_error(STR_ERROR_TOO_CLOSE_TO_EDGE_OF_MAP); // Might be off the map
```

**Review by TrueBrain — APPROVED** [review]

**Comment by JGRennison** [comment]
The existing zero-object size check is correct. Other than style issues there doesn't appear to be anything being fixed?

> Also fix the check for zero-size objects, which was missing a bitshift (32 != 0)

> Therefore if the lower nibble is 0, it would not be correctly detected as such.

I don't see how these follow from the existing code. Both nybbles are checked separately, and a bitshift has no effect.


(I've got no objections to this PR, incidentally).

**Comment by LordAro** [comment]
Yes, I just became very confused about what it was doing. Commits have since been updated to reflect that it was just a codechange, but PR description had not
