### PR TITLE
Fix #8973: [win32] Use user UI language for initial language selection

### LINKED ISSUE #8973: Wrong language loaded on first game start
## Version of OpenTTD
Own Windows build of master 130a052

## Expected result
My Windows display language and keyboard are configured as 'English (United States)'.
I was expecting that the game would start in English.

## Actual result
The game started in Dutch.
Maybe because my 'Regional format' (date & time format) is configured as 'Dutch (Belgium)'.

Also tested with 'French (Belgium)' and the game starts in French.

## Steps to reproduce
1. delete the value for language in `openttd.cfg`
2. change 'Regional format' in Windows settings
3. start the game

### PR DESCRIPTION
**Pull request by WimLeflere**
## Description
Use user UI language instead of date/time locale for initial language selection [win32] (#8973)

## Details

1. Use [GetUserDefaultUILanguage()](https://docs.microsoft.com/en-us/windows/win32/api/winnls/nf-winnls-getuserdefaultuilanguage) to get the user UI language
2. Use the returned LANGID instead of `LOCALE_USER_DEFAULT` to get the language code used for initial language selection

### CODE REVIEW

File: src/os/windows/win32.cpp [hunk 1]
```diff
@@ -629,9 +629,11 @@ wchar_t *convert_to_fs(const char *name, wchar_t *system_buf, size_t buflen)
 /** Determine the current user's locale. */
 const char *GetCurrentLocale(const char *)
 {
+	const LANGID userUiLang = GetUserDefaultUILanguage();
+
 	char lang[9], country[9];
-	if (GetLocaleInfoA(LOCALE_USER_DEFAULT, LOCALE_SISO639LANGNAME, lang, lengthof(lang)) == 0 ||
-	    GetLocaleInfoA(LOCALE_USER_DEFAULT, LOCALE_SISO3166CTRYNAME, country, lengthof(country)) == 0) {
+	if (GetLocaleInfoA(userUiLang, LOCALE_SISO639LANGNAME, lang, lengthof(lang)) == 0 ||
+	    GetLocaleInfoA(userUiLang, LOCALE_SISO3166CTRYNAME, country, lengthof(country)) == 0) {
```
Comment (michicc) [inline src/os/windows/win32.cpp]: Small nitpick: technically, it should be `MAKELCID(userUiLang, SORT_DEFAULT)`.
(Yes, `SORT_DEFAULT` is 0 so this is a no-op, but formally LANGID is not a LCID).

**Review by michicc — APPROVED** [review]
