### PR TITLE
Fix: several bugs related to joining a network server

### LINKED ISSUE #8751: Disconnecting clients affect other clients in the queue
## Version of OpenTTD
master (af326753a95489459c509088010350d09b0af1f8), 1.10.3, 1.9.3

## Expected result
Client connects without issues regardless of what other clients do.

## Actual result
Client loses connection

## Steps to reproduce
1. Start a network server. (larger map size and no indusries will make testing easier)
2. Start two clients and select that server
3. Join the server on both clients at about the same time
4. Cancel first client while it is downloading the map
5. Second client will fail to connect

There is also a variation of this bug where second client gets desync. Happens when first client connects with "new company" and leaves the server before the second one finishes downloading the map.

P.S. it also says 0 clients in front of you while waiting

### PR DESCRIPTION
**Pull request by TrueBrain**
Fixes #8751

## Motivation / Problem

There are four bugs mentioned in the above ticket:
1) waiting queue seems off by 1
2) when client that is downloading disconnects, all others in queue will never start their download
3) while in queue, you get after 5 seconds that the server is not responding
4) if a client creates a new company and leaves while you are downloading a map, the client desyncs

## Description

1) is a linguistic issue. "1 person waiting" means 1 is being served while there is 1 more waiting. So when you are the next in line, there are 0 people waiting, so 0 people in front of you. But this just looks odd and weird. So let's ignore "strictly seen correct" and go with the more expected version: 1 people in front of you means that person is downloading the map.

2) the state machine was poorly designed around unhappy flows. Now, if for what-ever reason the client disconnects while downloading the map, the savegame process is stopped and the next person is getting the map.

3) every second all people in queue now receive a packet, letting them know the server is alive.

4) after the server approved the CmdCompanyCtrl, clients and server could still reject it depending if they received that the client left the server. This is latency depending, and can cause desync. Introduced in f8f7febe41311ff3562c57a10672e3a62174104b, which originally avoided this situation, but stricter validation created the possibility to desync (the check changed from an out-of-bound check to a "does this still exist" check).

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/network/network_server.cpp [hunk 1]
```diff
@@ -620,26 +658,12 @@ NetworkRecvStatus ServerNetworkGameSocketHandler::SendMap()
 			 *  to send it is ready (maybe that happens like never ;)) */
 			this->status = STATUS_DONE_MAP;
 
-			/* Find the best candidate for joining, i.e. the first joiner. */
-			NetworkClientSocket *best = nullptr;
+			this->CheckNextClientToSendMap();
+		} else if (std::chrono::steady_clock::now() > last_time + std::chrono::seconds(1)) {
```
Comment (ldpl) [inline src/network/network_server.cpp]: This only helps if downloading client is actually active. If he just went mia whole queue can get disconnected before network.max_download_time kicks in for downloading client.

File: src/network/network_server.cpp [hunk 2]
```diff
@@ -281,6 +281,16 @@ NetworkRecvStatus ServerNetworkGameSocketHandler::CloseConnection(NetworkRecvSta
 		}
 	}
 
+	/* If we are transfer a map to this client, queue the next client to
```
Comment (ldpl) [inline src/network/network_server.cpp]: shouldn't it be transferRING?

**Comment by ldpl** [comment]
Not sure why is it happening but two clients can't connect at the same time now if they do it with "new company" button.
Screenshot from 2021-02-27 20-20-38

**Comment by James103** [comment]
What was the "invalid or unexpected packet" that the client received?

**Review by ldpl — APPROVED** [review]
Ok, that bug is unrelated so I'll open another issue. 
Everything else looks fine

**Review by LordAro — APPROVED** [review]
