### PR TITLE
Fix #8037: assertion failed when reloading AI for last existing company in offline mode

### LINKED ISSUE #8037: Crash when Reloading AI in single player
## Version of OpenTTD
1.10.0-RC1
## Expected result
Reload the AI
## Actual result
Crash when reloading AI in single player
## Steps to reproduce
Start only one AI in single player
Cheat and move to AI company
Let human company bankrupt.
Reload AI -> crash
[crash.zip](https://github.com/OpenTTD/OpenTTD/files/4351009/crash.zip)

### PR DESCRIPTION
**Pull request by glx22**
Fixes #8037
## Motivation / Problem
Reloading AI means deleting and recreating a company.
This is not possible if it's the last existing company in offline mode, as it's the only company in which player can be.

## Description
First commit prevents deletion of last existing company.
Second commit prevents the reloading of AI for local company, in the same way `stop_ai` does it.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)_

### CODE REVIEW

File: src/ai/ai_gui.cpp [hunk 1]
```diff
@@ -14,6 +14,7 @@
 #include "../querystring_gui.h"
 #include "../stringfilter_type.h"
 #include "../company_base.h"
+#include "../company_func.h"
```
Comment (LordAro) [inline src/ai/ai_gui.cpp]: Could be extern _local_company instead of an #include ?

File: src/company_cmd.cpp [hunk 2]
```diff
@@ -875,6 +876,9 @@ CommandCost CmdCompanyCtrl(TileIndex tile, DoCommandFlag flags, uint32 p1, uint3
 			CompanyRemoveReason reason = (CompanyRemoveReason)GB(p1, 24, 8);
 			if (reason >= CRR_END) return CMD_ERROR;
 
+			/* We can't delete the last existing company in offline mode. */
+			if (!_networking && Company::GetNumItems() == 1) return CMD_ERROR;
```
Comment (TrueBrain) [inline src/company_cmd.cpp:886]: Maybe a good idea to throw a STR_ERROR so the user knows why this is failing?

File: src/console_cmds.cpp [hunk 3]
```diff
@@ -1248,7 +1248,7 @@ DEF_CONSOLE_CMD(ConReloadAI)
 		return true;
 	}
 
-	if (Company::IsHumanID(company_id)) {
+	if (Company::IsHumanID(company_id) || company_id == _local_company) {
```
Comment (TrueBrain) [inline src/console_cmds.cpp:1252]: Maybe more to the question: why is `IsHumanID` not returning true, as clearly the human is in the company?

(and if it is correct, at least add a comment why this exception is added .. nobody will know in 5 years :P)

File: src/ai/ai_gui.cpp (hunk 1 above)
Comment (glx22) [reply src/ai/ai_gui.cpp]: Yeah should work too.

File: src/console_cmds.cpp (hunk 3 above)
Comment (glx22) [reply src/console_cmds.cpp:1252]: I think the case where a human is in an AI company can only happen in offline mode after cheating (or loading a dedicated server save with an AI in first slot).
And `IsHumanID` is also used to determine if a network client can join/be moved to a company, and to prevent some disasters that would destroy AI infrastructure.
So I'll add comments.

File: src/company_cmd.cpp (hunk 2 above)
Comment (glx22) [reply src/company_cmd.cpp:886]: In theory, with second commit, the call should not happen.
And for an error message to be displayed, it seems all `DoCommand()` calls for that command need to be updated with `CMD_MSG()`

Comment (TrueBrain) [reply src/company_cmd.cpp:886]: Someone wise told me a few weeks ago:

`CMD_MSG` is the default error shown when there is no other after a `CMD_ERROR`.
Use `return_cmd_error(STR_ERROR_XXX);` is you want to return a specific one :)

Anyway, if you covered all routes via UI elements, I am fine with that. It just didn't read like that, hence the comment :D

Comment (glx22) [reply src/company_cmd.cpp:886]: But `return_cmd_error(STR_ERROR_XXX)` has no visible effect if there was no `CMD_MSG`

File: src/ai/ai_gui.cpp [hunk 4]
```diff
@@ -1406,7 +1406,8 @@ struct AIDebugWindow : public Window {
 		this->SetWidgetLoweredState(WID_AID_MATCH_CASE_BTN, this->case_sensitive_break_check);
 
 		this->SetWidgetDisabledState(WID_AID_SETTINGS, ai_debug_company == INVALID_COMPANY);
-		this->SetWidgetDisabledState(WID_AID_RELOAD_TOGGLE, ai_debug_company == INVALID_COMPANY || ai_debug_company == OWNER_DEITY);
+		extern CompanyID _local_company;
+		this->SetWidgetDisabledState(WID_AID_RELOAD_TOGGLE, ai_debug_company == INVALID_COMPANY || ai_debug_company == OWNER_DEITY || ai_debug_company == _local_company);
```
Comment (SamuXarick) [inline src/ai/ai_gui.cpp:1410]: I think this should only be disabled if it's the last company available, not just because I'm on it.

Comment (glx22) [reply src/ai/ai_gui.cpp:1410]: It's the same check for `stop_ai` and `reload_ai` console commands.

Comment (SamuXarick) [reply src/ai/ai_gui.cpp:1410]: The console commands should follow suit then, too.

If there is another company I can be in, and I'm in an AI company, I don't expect the button to be disabled, nor the console commands to fail.

**Comment by TrueBrain** [comment]
The mention of `offline mode` triggered something in me, so I did some grepping in the code:

- 2 instances of `offline` references
- 13 instances of `singleplayer` (5) / `single player` (8) references

In commits, `offline mode` is never references, and `singleplayer` (4) / `single player` (5) a total of 9 times.

Not sure what we should call non-multiplayer, but for sure we use different names for it currently :) Maybe good to tackle that for this PR already?

**Review by LordAro — APPROVED** [review]
