### PR TITLE
Fix #9810: 'Rebuilding' a through road stop costs money.

### LINKED ISSUE #9810: [Bug]: 'Rebuilding' a through road stop costs money.
### Version of OpenTTD

12.1 Windows 10

### Expected result

"Rebuilding" a through road stop should not cost money, ie. clicking with the through stop build tool on an existing through road stop should not have any effect. This is the existing behaviour for any other build tool, if the object is already built re-clicking with the build tool has no effect.

### Actual result

"Rebuilding" a through road stop costs the standard build cost for building on an existing road tile. This behaviour happens when building a bus or lorry road stop.

### Steps to reproduce

Replicate by building a through road station, then click again on the same tile and it charges the road station cost.

### PR DESCRIPTION
**Pull request by wholepuncher**
## Motivation / Problem

Issue #9810 and comments: Overbuilding of road stops, rail stations, and rail waypoints on pre-existing buildings of same type charge money.

## Description

For road stops:
Tiles that already have a road stop do not contribute to the build cost anymore.
Non-through road stops can be rotated by overbuilding for free.
Through road stops cannot be rotated by overbuilding since there is already an error if the underlying road is in the wrong orientation.
If no new road stops are built or rotated, the command returns  a STR_ERROR_ALREADY_BUILT error.

For rail stations:
Tiles that already have a rail station of the same orientation do not contribute to the build cost anymore, even if the station gfx is changed by the command.
Rail stations cost money to rotate since they rebuild the underlying rail as well.
If no new rail stations are built or rotated, the command returns  a STR_ERROR_ALREADY_BUILT error.

For rail waypoints:
If there already is a rail waypoint, the command returns a STR_ERROR_ALREADY_BUILT error.

These changes mean overbuilding either errors or charges only for significant changes and not for pre-existing stations.

Closes #9810 - edit 2TT

## Limitations

I decided to use STR_ERROR_ALREADY_BUILT as the error, but as seen in the comments of issue #9810, there's still a bit of inconsistency with other overbuilding building errors.
The cost calculations for road stops and rail stations use two new entire functions, one for each type.
The costs for all changed building are calculated before placements. No actual placement updating code was changed. This means the actual tile changes still happen as before.
The waypoint building interface seems to allow areas of selection, but in-game only allows single tile placements. The code change accounts for areas, but effectively only errors for waypoint overbuilding.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/station_cmd.cpp [hunk 1]
```diff
@@ -1810,6 +1862,49 @@ static CommandCost FindJoiningRoadStop(StationID existing_stop, StationID statio
...
+static CommandCost CalculateRoadStopCost(TileArea tile_area, DoCommandFlag flags, bool is_drive_through, bool is_truck_stop, Axis axis, DiagDirection ddir, StationID *est, RoadType rt)
+{
+	CommandCost cost(EXPENSES_CONSTRUCTION);
+
+	bool success = false;
+
+	/* Check every tile in the area. */
+	for (TileIndex cur_tile : tile_area) {
+
+		CommandCost ret = CheckFlatLandRoadStop(TileArea(cur_tile, cur_tile), flags, is_drive_through ? 5 << axis : 1 << ddir, is_drive_through, is_truck_stop, axis, est, rt);
```
Comment (2TallTyler) [inline src/station_cmd.cpp]: Are there constants that could replace these magic numbers?

File: src/station_cmd.cpp [hunk 2]
```diff
@@ -1810,6 +1862,49 @@ static CommandCost FindJoiningRoadStop(StationID existing_stop, StationID statio
...
+ */
+static CommandCost CalculateRoadStopCost(TileArea tile_area, DoCommandFlag flags, bool is_drive_through, bool is_truck_stop, Axis axis, DiagDirection ddir, StationID *est, RoadType rt)
+{
+	CommandCost cost(EXPENSES_CONSTRUCTION);
+
+	bool success = false;
+
+	/* Check every tile in the area. */
+	for (TileIndex cur_tile : tile_area) {
+
```
Comment (2TallTyler) [inline src/station_cmd.cpp]: Unneeded newline

File: src/station_cmd.cpp [hunk 3]
```diff
@@ -1243,6 +1243,61 @@ static void RestoreTrainReservation(Train *v)
...
+static CommandCost CalculateRailStationCost(TileArea tile_area, DoCommandFlag flags, Axis axis, StationID *station, RailType rt, std::vector<Train *> &affected_vehicles, StationClassID spec_class, byte spec_index, byte plat_len, byte numtracks)
+{
+	CommandCost cost(EXPENSES_CONSTRUCTION);
+	bool success = false;
+	bool length_price_ready = true;
+	/* Need to add _price[PR_BUILD_STATION_RAIL_LENGTH] for each plat_len, accounting for existing stations. */
+	byte tracknum = 0;
+
+	for (TileIndex cur_tile : tile_area) {
+
```
Comment (2TallTyler) [inline src/station_cmd.cpp]: Unneeded newline

File: src/station_cmd.cpp [hunk 4]
```diff
@@ -1243,6 +1243,61 @@ static void RestoreTrainReservation(Train *v)
...
+ * @param plat_len Platform length.
+ * @param numtracks Number of platforms.
+ * @return The cost in case of success, or an error code if it failed.
+ */
+static CommandCost CalculateRailStationCost(TileArea tile_area, DoCommandFlag flags, Axis axis, StationID *station, RailType rt, std::vector<Train *> &affected_vehicles, StationClassID spec_class, byte spec_index, byte plat_len, byte numtracks)
+{
+	CommandCost cost(EXPENSES_CONSTRUCTION);
+	bool success = false;
+	bool length_price_ready = true;
+	/* Need to add _price[PR_BUILD_STATION_RAIL_LENGTH] for each plat_len, accounting for existing stations. */
```
Comment (2TallTyler) [inline src/station_cmd.cpp]: This reads like a TODO comment. Is it? If not, it should be reworded. 🙂

**Review by 2TallTyler — COMMENTED** [review]
Consistency is good, so I'm in favor of this. Just a few things to fix.

I haven't thoroughly tested this yet, but will do so before approving.

**Comment by LordAro** [comment]
We prefer rebases over merge commits for PRs, if at all possible (which is why the commit checker CI is failing)

(Though we can force rebase ourselves if necessary)

File: src/station_cmd.cpp (hunk 1 above)
Comment (wholepuncher) [reply src/station_cmd.cpp]: I wasn't able to find anything that can.

Comment (rubidium42) [reply src/station_cmd.cpp]: Technically you could do something like the following to get rid of the magic numbers (untested though):
```
uint invalid_dirs = 0;
if (is_drive_through) {
   SetBit(invalid_dirs, AxisToDiagDir(axis));
   SetBit(invalid_dirs, ReverseDiagDir(AxisToDiagDir(axis)));
} else {
   SetBit(invalid_dirs, ddir) {
}
```
Conceptually one might want to introduce `DiagDirBits` as type just as `TrackDirBits`, with the right functions to set bits given an axis or direction. However, I reckon that's out of the scope of this PR. And it probably would only be really useful when there are other places that use such functionality as well.

Comment (wholepuncher) [reply src/station_cmd.cpp]: Thank you, your code looks equivalent and it works as far as I could test it. There's a few other spots in the file where bitwise operations are done with plain numbers, like at line 880, but yeah, they are outside the scope of this change.

**Review by LordAro — DISMISSED** [review]

**Review by rubidium42 — APPROVED** [review]
