### PR TITLE
Fix #8055: Fix crash when the road toolbar is open, but the availabil…

### LINKED ISSUE #8055: Road Construction UI unavailable
If you start the game with Maximum number of road vehicles per company: 0, u cannot build any road, the button is just greyed out and disabled. If you go into settings while in that game and set the number of vehicles to 100, the road construction becomes available and u can build road, but if you go back into settings set the road vehicle limit back to 0 WITHOUT closing the ROAD CONSTRUCTION UI the game just crashes.

## Version of OpenTTD
openttd-1.10.0-windows-win64.exe

## Expected result
To be able to do road construction even tho the allowed road vehicle per company is set to 0

## Actual result
The road construction is greyed out, if road vehicle per company is set to 0. Also crashes OpenTTD if you leave the Road Construction UI on, while going into Settings to change road vehicles per company 100 -> 0.

## Steps to reproduce
1. Create any game with Limitations -> Maximum number of road vehicles per company: 0
2. Go into Settings while in the created game.
3. Find Limitations -> Maximum Number of road vehicles per company, set it to 100
4. Road Construction becomes available, select it, build some road whatever doesnt matter.
5. Do not close Road Construction UI.
6. Go back into Settings -> Limitations -> Maximum number of road vehicles per company, set it back 100 -> 0.
7. Game crashes.

### PR DESCRIPTION
**Pull request by stormcone**
…ity of the current road type has changed.

This patch is only fixes the crash part of the issue.

### CODE REVIEW

File: src/road_gui.cpp [hunk 1]
```diff
@@ -304,13 +304,16 @@ struct BuildRoadToolbarWindow : Window {
...
+		if (can_build && !CanBuildVehicleInfrastructure(VEH_ROAD, GetRoadTramType(this->roadtype))) {
+			delete this;
+		} else {
+			this->SetWidgetsDisabledState(!can_build,
+					WID_ROT_DEPOT,
+					WID_ROT_BUS_STATION,
+					WID_ROT_TRUCK_STATION,
+					WIDGET_LIST_END);
+		}
 		if (!can_build) {
```
Comment (glx22) [inline src/road_gui.cpp]: This block should also be executed when the window is destroyed.
Maybe with something like
```suggestion
		if (!can_build || !CanBuildVehicleInfrastructure(VEH_ROAD, GetRoadTramType(this->roadtype))) {
```
 (only tested in my head ;) after reading the change in this function by c02ef3e4)

Comment (stormcone) [reply src/road_gui.cpp]: I'm not sure. If we close the window, its does not matter whether widgets are disabled or not. And if we reopen the toolbar, the constructor calls this function, so that the widgets will be in the correct state when the new window opens.

Comment (glx22) [reply src/road_gui.cpp]: This part is about closing other build windows (depots, station), it doesn't depend on disabling widgets or not.

Comment (stormcone) [reply src/road_gui.cpp]: But if the window is destroyed, it will destroy its child windows too. So the depot and station windows will be deleted too.

File: src/road_gui.cpp [hunk 2]
```diff
@@ -304,13 +304,16 @@ struct BuildRoadToolbarWindow : Window {
...
-				WIDGET_LIST_END);
+		if (can_build && !CanBuildVehicleInfrastructure(VEH_ROAD, GetRoadTramType(this->roadtype))) {
+			delete this;
+		} else {
+			this->SetWidgetsDisabledState(!can_build,
+					WID_ROT_DEPOT,
+					WID_ROT_BUS_STATION,
+					WID_ROT_TRUCK_STATION,
+					WIDGET_LIST_END);
+		}
```
Comment (glx22) [inline src/road_gui.cpp]: The `else` can be removed
```suggestion
		if (can_build && !CanBuildVehicleInfrastructure(VEH_ROAD, GetRoadTramType(this->roadtype))) {
			delete this;
			return;
		}
		this->SetWidgetsDisabledState(!can_build,
				WID_ROT_DEPOT,
				WID_ROT_BUS_STATION,
				WID_ROT_TRUCK_STATION,
				WIDGET_LIST_END);
```

File: src/road_gui.cpp (hunk 1 above)
Comment (glx22) [reply src/road_gui.cpp]: Ah yes you're right, so I suggested another change to make everything simpler.

Comment (glx22) [reply src/road_gui.cpp]: Hmm and now I'm starting to think that the whole `!can_build` block is actually useless. It was there before c02ef3e because the window was not destroyed, but now it only deletes windows that can't be opened anyway as they are disabled in editor.

File: src/road_gui.cpp (hunk 2 above)
Comment (stormcone) [reply src/road_gui.cpp]: I think this `SetWidgetsDisabledState` call could be removed as well. There are 2 toolbars, one for the scenario editor and one for the normal game. The scenario edition does not even contain the depot and station widgets. And the `can_build` depends on only whether the game mode is scenario editor or not. It is possibly a remnant from an earlier version when the scenario editor did not have its own toolbar.

https://github.com/OpenTTD/OpenTTD/blob/71e79edfc1adaa4ea1e19d6ec87cb045ef7f69fe/src/road_gui.cpp#L788

https://github.com/OpenTTD/OpenTTD/blob/71e79edfc1adaa4ea1e19d6ec87cb045ef7f69fe/src/road_gui.cpp#L890

And because of this, maybe the delete windows block could be also removed.

Comment (glx22) [reply src/road_gui.cpp]: No the `SetWidgetsDisabledState` call is needed for the hotkeys, even if the widgets are not shown in scenario editor, they are still existing and could be triggered via hotkeys if not disabled.
But for the delete block I agree, it became useless.

Edit: started the debugger to check, and I think you're right. Basically the fix should be to just delete https://github.com/OpenTTD/OpenTTD/blob/71e79edfc1adaa4ea1e19d6ec87cb045ef7f69fe/src/road_gui.cpp#L308-L318
as all this code is actually useless

Comment (stormcone) [reply src/road_gui.cpp]: I removed those lines.

**Review by glx22 — DISMISSED** [review]
LGTM, commit message may need to be rewritten to include reference to c02ef3e and shortening

**Comment by stormcone** [comment]
Do you have any suggestions, or could you rewrite it when you merge?

**Review by glx22 — APPROVED** [review]
Yes it can be rewritten on merge
