### PR TITLE
Fix #13307: Return non-zero value when there is a mistake in command-line arguments

### LINKED ISSUE #13307: [Bug]: OpenTTD returns exit status 0 upon failing to read a savefile with the -q option
### Version of OpenTTD

14.1, Arch Linux

### Expected result

OpenTTD returns a non-zero status code, indicating a failure state.

### Actual result

OpenTTD returns status code 0 (i.e, success) upon exit, and the only indication anything is amiss is the message "Failed to open savegame" on std_err. This makes it extremely difficult to tell for programs invoking OpenTTD (i.e. wrapper scripts which need certain information on the save file) whether the operation has actually succeeded or failed without directly parsing std_err, which is both inconvenient and prone to complications.

### Steps to reproduce

1. Invoke OpenTTD with the `-q` option and an invalid filename, i.e. `openttd -q foobar`.
2. Obtain the exit code using your shell's functionality to do so (i.e. `echo $?` under Bash)
3. Note that OpenTTD returns exit code 0 despite ostensibly failing to open the save file.

### PR DESCRIPTION
**Pull request by merni-ns**
## Motivation / Problem
- #13307 
- When non-existent arguments are used, the return value of the game is still 0

## Description
Return 1 when the savegame passed to `-q` cannot be read or invalid arguments are used. Still return 0 when `-h` is used to display help.

Fixes #13307.

## Limitations
None that I can think of.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/openttd.cpp [hunk 1]
```diff
@@ -625,6 +625,7 @@ int openttd_main(std::span<char * const> arguments)
 					SetDParamStr(0, _load_check_data.error_msg);
 					fmt::print(stderr, "{}\n", GetString(_load_check_data.error));
 				}
+				ret = 1;
 				return ret;
```
Comment (TrueBrain) [inline src/openttd.cpp]:
```suggestion
				return 1;
```

And I won't mind if you fix that too in line 612. I have no clue why anyone would write it like that :P

File: src/openttd.cpp [hunk 2]
```diff
@@ -659,6 +658,7 @@ int openttd_main(std::span<char * const> arguments)
 		BaseSounds::FindSets();
 		BaseMusic::FindSets();
 		ShowHelp();
+		if (i != 'h') ret = 1;
 		return ret;
```
Comment (TrueBrain) [inline src/openttd.cpp]:
```suggestion
		/* Return zero when printing help, and 1 for all other cases. */
		if (i == 'h') return 0;
		return 1;
```

Feel free to write down any other comment; but something to indicate what is happening, would be nice.

Fun fact: I think with my two suggested changes, the variable `ret` will be unused. So you can remove that too :)

**Review by TrueBrain — DISMISSED** [review]

**Comment by 2TallTyler** [comment]
Hi @merni-ns, just looking through old PRs and issues -- do you have time to finish this? 🙂

**Review by PeterN — APPROVED** [review]
