### PR TITLE
Fix #11968: Always set string parameters to avoid undefined behavior

### LINKED ISSUE #11968: [Crash]: Crash when opening orders of new vehicle
### Version of OpenTTD

OpenTTD 14.0-beta1, Windows 10

### Steps to reproduce

1. Bought a new road vehicle. (Road vehicle 23)
2. I clicked the orders button on the window for the road vehicle.
3. The game crashed.

This also happens when the attached savefile is loaded, and the orders button for road vehicle 23 is pushed.

### Upload crash files

[crash20240203220310.zip](https://github.com/OpenTTD/OpenTTD/files/14154430/crash20240203220310.zip)

### PR DESCRIPTION
**Pull request by 2TallTyler**
## Motivation / Problem

#11968 crashes because we break out of setting a string parameter, resulting in undefined behavior.

## Description

Define the behavior by setting the parameter to a safe value.

Closes #11968.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/order_gui.cpp [hunk 1]
```diff
@@ -1166,7 +1166,11 @@ struct OrdersWindow : public Window {
 			case WID_O_DEPOT_ACTION: {
 				VehicleOrderID sel = this->OrderGetSel();
 				const Order *order = this->vehicle->GetOrder(sel);
-				if (order == nullptr || !order->IsType(OT_GOTO_DEPOT)) break;
+				if (order == nullptr || !order->IsType(OT_GOTO_DEPOT)) {
+					/* We can't leave this param empty or the undefined behavior can cause a crash. */
+					SetDParam(0, STR_EMPTY);
```
Comment (michicc) [inline src/order_gui.cpp]: Maybe say "We can't leave this param unset", it reads a bit strange to that you may not leave it empty and yet it is set to STR_EMPTY :)

Comment (2TallTyler) [reply src/order_gui.cpp]: Indeed. 🙂

**Comment by glx22** [comment]
A failsafe solution could be use `SetDParam()` unconditionally as first thing for the case.
Possibly the same for `WID_O_COND_VALUE` as its STR_JUST_COMMA could receive random garbage too.

**Review by rubidium42 — APPROVED** [review]
