### PR TITLE
Fix #13459, #13546: Crash when changing NewGRFs in game with picker window open.

### LINKED ISSUE #13459: [Bug]: Assertion after removing NewGRF with items saved in picker
### Version of OpenTTD

15

### Expected result

Scenario editor might get this crash if you have favorite building from newgrf (thats been favorited) and that newgef gets deleted afterwards with building still on list.

"Assettion failed at line 79 of /src/newgrf/newgrf_house.cpp: house_id < NUM_HOUSES"

### Actual result

When clicking favorites menu from house placer game crashes.

### Steps to reproduce

Add newgrf house to favorites.
Remove newgrf
Try entering liked menu from house placer

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

As per #13459 and #13546, changing NewGRFs with a picker window open can crash the game, as the state of the picker window becomes out of date.

## Description

Force invalidation of picker window state when NewGRFs are changed.

As the flags to specify which state to invalidate is a bitset, this has also been converted to an EnumBitSet first.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/picker_gui.cpp [hunk 1]
```diff
@@ -678,3 +678,13 @@ std::unique_ptr<NWidgetBase> MakePickerTypeWidgets()
...
 }
+
+void InvalidateAllPickerWindows()
+{
+	InvalidateWindowClassesData(WC_BUS_STATION, PickerWindow::PICKER_INVALIDATION_ALL.base());
+	InvalidateWindowClassesData(WC_TRUCK_STATION, PickerWindow::PICKER_INVALIDATION_ALL.base());
+	InvalidateWindowClassesData(WC_SELECT_STATION, PickerWindow::PICKER_INVALIDATION_ALL.base());
+	InvalidateWindowClassesData(WC_BUILD_WAYPOINT, PickerWindow::PICKER_INVALIDATION_ALL.base());
+	InvalidateWindowClassesData(WC_BUILD_OBJECT, PickerWindow::PICKER_INVALIDATION_ALL.base());
+	InvalidateWindowClassesData(WC_BUILD_HOUSE, PickerWindow::PICKER_INVALIDATION_ALL.base());
```
Comment (rubidium42) [inline src/picker_gui.cpp]: Isn't the `EnumBitSet` `ConvertibleThroughBase`? Then the `.base()`s shouldn't be needed.

**Review by rubidium42 — APPROVED** [review]
Bit early for pi day, but what the heck :D
