### PR TITLE
Fix #8316: Make sort industries by production and transported with a cargo filter possible

### LINKED ISSUE #8316: Sorting of produced cargo for industries with multiple products are inaccurate
## Version of OpenTTD
1.10.3

## Expected result
In Industries dialog, when doing Sort by Production on Produced cargo such as Oil, Livestock, and Grain, the sort order is exact for that product.

## Actual result
The sorting is approximately in order
image

## Steps to reproduce
Open Industries dialog, set Sort by to Production, change Produced cargo to Oil, Livestock, Grain, or Passenger

### PR DESCRIPTION
**Pull request by SamuXarick**
## Motivation / Problem
#8316 
When sorting by production with a cargo filter on industries that produce more than one cargo, it would sort by the sum of all cargoes produced, and not by the chosen cargo.
EDIT: 
Sorting by transported only accounts for the 2 first produced cargoes of an industry. If an industry produces more cargoes, the transported percentage of those cargoes would not be evaluated.
Even in the case of industries producing just 2 cargoes, the transported % was not displayed orderly in the string of a single industry, nor would the percentage be sorted correctly when compared with other industries.

## Description
The sort by production problem is solved by making the sorter function able to know which cargo filter is applied, then sort by either the sum of cargoes when any cargo is selected, or only by the cargo selected.

The sort by transported problem is a bit tricky. The string displaying the various details is now sorted by cargo transported, instead of cargo production. Then it also knows which cargo filter is applied. If all cargo types is selected, then it sorts the list by the average of percentages of cargoes transported. If a cargo type is selected, then it sorts the list by that cargo percentage.

## Limitations
I think the sort by production problem is solved in all scenarios. There was also a cargo filter that would sort by none. I simply made it not go through the whole cargoes that the industries produce, only to return zero.

The sort by transported problem has industries that don't produce any cargo at all. I thought of grouping them all together, similar to the original code, but in the reverse position, instead of a "101%", it's a "-1%". I made it this way due to code being based on the sum of percentages, and when iterating over invalid cargoes of industries that produce at least one cargo, it returns a +"0%" to the sum. All in the name of making some sense in the sorted list.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by glx22** [comment]
Not fan of the global variables, there should be a cleaner way.

**Comment by glx22** [comment]
In https://github.com/glx22/OpenTTD/commit/e42ab5af13ba4f67bd716e980e780e050bb98056 I tried something a bit cleaner.
Ideally we should pass the filter to `Sort()`, but that implies touching all sorters in the source.

**Comment by SamuXarick** [comment]
I noticed Sort by Transported also needs a similar treatment.

File: src/industry_gui.cpp [hunk 1]
```diff
@@ -1364,7 +1374,7 @@ class IndustryDirectoryWindow : public Window {
 	{
 		assert(id < lengthof(i->produced_cargo));
 
-		if (i->produced_cargo[id] == CT_INVALID) return 101;
+		if (i->produced_cargo[id] == CT_INVALID) return 0;
```
Comment (LordAro) [inline src/industry_gui.cpp]: I've no idea what 101 was doing, but the docstring says -1 if industry doesn't use this cargo slot. Either this return value is now (or still) wrong, or the doc comment needs updating

Comment (LordAro) [reply src/industry_gui.cpp]: Looking at intended usage, you're now checking outside the function. Perhaps a rename to remove "IfValid" and convert this if into an assert instead?

File: src/industry_gui.cpp [hunk 2]
```diff
@@ -1449,11 +1485,28 @@ class IndustryDirectoryWindow : public Window {
...
+					return std::get<3>(a) > std::get<3>(b);
+				});
+				break;
+
+			case IDW_SORT_BY_TRANSPORTED:
+				/* Sort by descending transported, then descending production */
+				std::sort(cargos.begin(), cargos.end(), [](const CargoInfo a, const CargoInfo b) {
+					if (std::get<3>(a) != std::get<3>(b)) return std::get<3>(a) > std::get<3>(b);
+					return std::get<1>(a) > std::get<1>(b);
+				});
```
Comment (LordAro) [inline src/industry_gui.cpp]: Probably best to turn CargoInfo into a proper struct, so these rather ugly sort functions get better names

File: src/industry_gui.cpp [hunk 3]
```diff
@@ -1449,11 +1485,28 @@ class IndustryDirectoryWindow : public Window {
...
+				break;
+
+			default:
+				NOT_REACHED();
```
Comment (LordAro) [inline src/industry_gui.cpp]: You're covering every value of the enum already, so no need for a default block. Compiler will warn if (somehow) another value gets added to the enum but this switch gets forgotten. Would get silently missed (until it causes a crash) otherwise

File: src/industry_gui.cpp [hunk 4]
```diff
@@ -1256,6 +1256,14 @@ class IndustryDirectoryWindow : public Window {
 	StringID cargo_filter_texts[NUM_CARGO + 3]; ///< Texts for filter_cargo, terminated by INVALID_STRING_ID
 	byte produced_cargo_filter_criteria;        ///< Selected produced cargo filter index
 	byte accepted_cargo_filter_criteria;        ///< Selected accepted cargo filter index
+	static CargoID produced_cargo_filter;
```
Comment (LordAro) [inline src/industry_gui.cpp:1312]: Why make this variable static? Something to do with maintaining filter if you close/open the window? Is that worthwhile?

**Review by LordAro — CHANGES_REQUESTED** [review]
Fairly minor

File: src/industry_gui.cpp (hunk 1 above)
Comment (SamuXarick) [reply src/industry_gui.cpp]: I made it match the docstring, -1, and work around with the returned value in the parent call.

File: src/industry_gui.cpp (hunk 3 above)
Comment (SamuXarick) [reply src/industry_gui.cpp]: I moved default up and removed NOT_REACHED().

File: src/industry_gui.cpp (hunk 4 above)
Comment (SamuXarick) [reply src/industry_gui.cpp:1312]: I don't know. I copied over from @glx22

File: src/industry_gui.cpp [hunk 5]
```diff
@@ -1503,11 +1539,26 @@ class IndustryDirectoryWindow : public Window {
 			cargos.emplace_back(i->produced_cargo[j], i->last_month_production[j], cargo_suffix[j].text, ToPercent8(i->last_month_pct_transported[j]));
 		}
 
-		/* Sort by descending production, then descending transported */
-		std::sort(cargos.begin(), cargos.end(), [](const CargoInfo a, const CargoInfo b) {
-			if (std::get<1>(a) != std::get<1>(b)) return std::get<1>(a) > std::get<1>(b);
-			return std::get<3>(a) > std::get<3>(b);
-		});
+		switch (static_cast<IndustryDirectoryWindow::SorterType>(this->industries.SortType())) {
+			default:
```
Comment (LordAro) [inline src/industry_gui.cpp]: No, remove the default entirely

File: src/industry_gui.cpp (hunk 2 above)
Comment (SamuXarick) [reply src/industry_gui.cpp]: I'm not sure how to do this

File: src/industry_gui.cpp (hunk 5 above)
Comment (SamuXarick) [reply src/industry_gui.cpp]: Just removed it.

File: src/industry_gui.cpp (hunk 2 above)
Comment (LordAro) [reply src/industry_gui.cpp]: Instead of 
```
typedef std::tuple<CargoID, uint16, const char*, uint> CargoInfo;
```
use
```
struct CargoInfo {
    Foo foo;
    Bar bar;
    Baz baz;
};
```

Then instead of `std::get<3>(a)` it becomes `a.baz` etc
(You can define the struct within the function, that's fine)

File: src/industry_gui.cpp [hunk 6]
```diff
@@ -1430,12 +1440,26 @@ class IndustryDirectoryWindow : public Window {
 	 */
 	static int GetCargoTransportedSortValue(const Industry *i)
 	{
-		int p1 = GetCargoTransportedPercentsIfValid(i, 0);
-		int p2 = GetCargoTransportedPercentsIfValid(i, 1);
-
-		if (p1 > p2) Swap(p1, p2); // lower value has higher priority
+		CargoID filter = IndustryDirectoryWindow::produced_cargo_filter;
+
+		int p = 0, c = 0;
```
Comment (stormcone) [inline src/industry_gui.cpp]: I would like to see some comments about what is going on here in that function. And what `p`, `c`, & `t` is for? :)

File: src/industry_gui.cpp [hunk 7]
```diff
@@ -1494,26 +1530,46 @@ class IndustryDirectoryWindow : public Window {
...
+			uint transported;
+		};
 		std::vector<CargoInfo> cargos;
 
 		for (byte j = 0; j < lengthof(i->produced_cargo); j++) {
 			if (i->produced_cargo[j] == CT_INVALID) continue;
-			cargos.emplace_back(i->produced_cargo[j], i->last_month_production[j], cargo_suffix[j].text, ToPercent8(i->last_month_pct_transported[j]));
-		}
+			CargoInfo ci{ i->produced_cargo[j], i->last_month_production[j], cargo_suffix[j].text, ToPercent8(i->last_month_pct_transported[j]) };
+			cargos.emplace_back(ci);
```
Comment (LordAro) [inline src/industry_gui.cpp]:
```suggestion
			cargos.emplace_back(i->produced_cargo[j], i->last_month_production[j], cargo_suffix[j].text, ToPercent8(i->last_month_pct_transported[j]));
```
so that the object is actually constructed inplace, or `push_back` instead

File: src/industry_gui.cpp [hunk 8]
```diff
@@ -1399,6 +1407,8 @@ class IndustryDirectoryWindow : public Window {
 		                             this->cargo_filter[this->produced_cargo_filter_criteria]);
 
 		this->industries.Filter(filter);
+
+		this->produced_cargo_filter = this->cargo_filter[this->produced_cargo_filter_criteria];
```
Comment (LordAro) [inline src/industry_gui.cpp]: static member variable should be used statically - `IndustryDirectoryWindow::produced_...`

File: src/industry_gui.cpp (hunk 6 above)
Comment (LordAro) [reply src/industry_gui.cpp]: Indeed. We're not limited on space, use your words :)

File: src/industry_gui.cpp [hunk 9]
```diff
@@ -1417,7 +1427,7 @@ class IndustryDirectoryWindow : public Window {
 	{
 		assert(id < lengthof(i->produced_cargo));
 
-		if (i->produced_cargo[id] == CT_INVALID) return 101;
+		if (i->produced_cargo[id] == CT_INVALID) return -1;
```
Comment (LordAro) [inline src/industry_gui.cpp:1430]: Looked at it a bit closer, and judging by usages of the *IfValid functions, it should return 101 as "lower value has higher priority" - correct the documentation, not the code

File: src/industry_gui.cpp [hunk 10]
```diff
@@ -1494,26 +1530,46 @@ class IndustryDirectoryWindow : public Window {
...
+				break;
 
-		/* Sort by descending production, then descending transported */
-		std::sort(cargos.begin(), cargos.end(), [](const CargoInfo a, const CargoInfo b) {
-			if (std::get<1>(a) != std::get<1>(b)) return std::get<1>(a) > std::get<1>(b);
-			return std::get<3>(a) > std::get<3>(b);
-		});
+			case IndustryDirectoryWindow::SorterType::IDW_SORT_BY_TRANSPORTED:
+				/* Sort by descending transported, then descending production */
+				std::sort(cargos.begin(), cargos.end(), [](const CargoInfo a, const CargoInfo b) {
```
Comment (LordAro) [inline src/industry_gui.cpp]: Need some `&` here and above to prevent unnecessary copies

File: src/industry_gui.cpp (hunk 9 above)
Comment (SamuXarick) [reply src/industry_gui.cpp:1430]: How? "lower value has higher priority" in this context makes no sense, as we're returning the averaging percentages of all produced cargoes. Or in the case of a single cargo selected, return a value for an industry which doesn't produce it.

Returning -1 or 101 only matters for the position where we want industries not producing the cargo type in relation to industries that do.

Like this (single cargo selected):
Industry A, doesn't produce cargo type 'x': -1
Industry B, transported 0% cargo type 'x': 0
Industry C, transported 50% cargo type 'x': 50

Or this (any cargo selected):
Industry A, doesn't produce any cargo type: -1
Industry B, average transported 0%: 0
Industry C, average transported 33%: 33

Where do you want them listed? At the end or at the start?

Comment (LordAro) [reply src/industry_gui.cpp:1430]: OK, it doesn't matter anymore - this function is only called in GetCargoTransportedSortValue, and the -1 return value is explicitly checked for. Previously the order mattered, but it no longer does

File: src/industry_gui.cpp [hunk 11]
```diff
@@ -1494,26 +1530,45 @@ class IndustryDirectoryWindow : public Window {
 		GetAllCargoSuffixes(CARGOSUFFIX_OUT, CST_DIR, i, i->type, indsp, i->produced_cargo, cargo_suffix);
 
 		/* Get industry productions (CargoID, production, suffix, transported) */
-		typedef std::tuple<CargoID, uint16, const char*, uint> CargoInfo;
+		struct CargoInfo {
+			CargoID cargo_id;
+			uint16 production;
+			char *suffix;
```
Comment (LordAro) [inline src/industry_gui.cpp]: This is unowning, should be const

File: src/industry_gui.cpp [hunk 12]
```diff
@@ -1430,12 +1440,26 @@ class IndustryDirectoryWindow : public Window {
...
+				int transported = GetCargoTransportedPercentsIfValid(i, id);
+				if (transported != -1) produced_cargo_count++;
+				percentage += transported == -1 ? 0 : transported;
+				if (produced_cargo_count == 0 && id == lengthof(i->produced_cargo) - 1 && percentage == 0) {
+					return transported;
+				}
+			} else if (filter == i->produced_cargo[id]) {
+				return GetCargoTransportedPercentsIfValid(i, id);
+			}
+		}
```
Comment (LordAro) [inline src/industry_gui.cpp]: This for loop (and the one in the sorter) is weird - it still enters the loop even if `filter == CF_NONE` which is unconnected to the loop

File: src/industry_gui.cpp [hunk 13]
```diff
@@ -1430,12 +1440,26 @@ class IndustryDirectoryWindow : public Window {
...
+		CargoID filter = IndustryDirectoryWindow::produced_cargo_filter;
+
+		int percentage = 0, produced_cargo_count = 0;
+		for (uint id = 0; id < lengthof(i->produced_cargo); id++) {
+			if (filter == CF_NONE) {
+				return percentage;
+			} else if (filter == CF_ANY) {
+				int transported = GetCargoTransportedPercentsIfValid(i, id);
+				if (transported != -1) produced_cargo_count++;
+				percentage += transported == -1 ? 0 : transported;
```
Comment (LordAro) [inline src/industry_gui.cpp]: Should consolidate the `transported` checks
```suggestion
				if (transported != -1) {
					produced_cargo_count++;
					percentage += transported;
				}
```

Comment (SamuXarick) [reply src/industry_gui.cpp]: Thanks. it is done.

File: src/industry_gui.cpp (hunk 12 above)
Comment (SamuXarick) [reply src/industry_gui.cpp]: `filter == CF_NONE` is now outside the two `for `loops.

File: src/industry_gui.cpp (hunk 11 above)
Comment (SamuXarick) [reply src/industry_gui.cpp]: Oh, my bad. Fixed it.

**Review by LordAro — APPROVED** [review]
