### PR TITLE
Fix #9740: Fix loading of gamelog change items from savegame ver >= 294

### LINKED ISSUE #9740: [Bug]: Savegame load of versions >= SLV_RIFF_TO_ARRAY fails to correctly load gamelog LoggedChange items
### Version of OpenTTD

master

### Expected result

Gamelog loaded correctly

### Actual result

In `SlGamelogAction::Load` `LoggedAction::changes` is never assigned in the non `IsSavegameVersionBefore(SLV_RIFF_TO_ARRAY)` path.
`LoggedChange` items are loaded into `LoggedAction::change` beyond the logical (but not allocated) end of the array.
When the Gamelog is cleared, pointers referenced by `LoggedChange` items are leaked, which is how the issue was noticed.

### Steps to reproduce

Load a savegame with a version >= SLV_RIFF_TO_ARRAY (294).
Run the `gamelog` command or otherwise observe the gamelog.

### PR DESCRIPTION
**Pull request by JGRennison**
## Motivation / Problem

Fix #9740

## Description

See #9740 for description of problem

## Limitations

N/A

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by glx22 — APPROVED** [review]

File: src/saveload/gamelog_sl.cpp [hunk 1]
```diff
@@ -328,6 +328,7 @@ class SlGamelogAction : public DefaultSaveLoadHandler<SlGamelogAction, LoggedAct
 
 		size_t length = SlGetStructListLength(UINT32_MAX);
 		la->change = ReallocT(la->change, length);
+		la->changes = (uint32)length;
```
Comment (nielsmh) [inline src/saveload/gamelog_sl.cpp:331]: But wow that's a bad variable name, `changes`, especially right next to one named `change`.
