### PR TITLE
Fix #6598: prevent client crashes due to failing connects

### LINKED ISSUE #6598: Possible for client to be in a nonexistent company on a server; but then the client crashes.
**_james1101_ opened the ticket and wrote:**

> To Reproduce this Crash:
> Start OTTD server.
> Remember it's ip address.
> Start OTTD client.
> Client: Connect to server.
> Client: Execute 'join 255'.
> \-> Client joins spectators.
> Client: Execute 'join N', where N is greater than 15 and less than 255.
> \-> Client throws: 'Error: Company does not exist.'
> Client: Execute 'connect <server-ip># N', where N is greater than 15 and less than 255.
> \-> Client: Connect should be successful.
> Client: Open company list.
> \-> Client crashes. Crash files are attached.
> 
> Client version 1.7.1 on Windows 7 Ultimate; Server version 1.7.1 on Windows 7 Ultimate
> 
> Suggested Fix: Make the company id part of the connect command's argument follow the same rules as the join command's company id argument, ie must be between 0 and max_companies, or 255 (spectator).

**Attachments**
- [crash.png](https://bugs.openttd.org/task/6598/getfile/10764/crash.png) (211.85 KiB)
- [crash.log](https://bugs.openttd.org/task/6598/getfile/10765/crash.log) (8.83 KiB)
- [crash.dmp](https://bugs.openttd.org/task/6598/getfile/10766/crash.dmp) (12978.97 KiB)

**Reported version**: _1.7.1_
**Operating system**: _All_

---

### PR DESCRIPTION
**Pull request by rubidium42**
Closes #6598 

## Motivation / Problem

See #6598. Though the premise is, if you are in a network game and you use (re)connect from the console you can get into a weird limbo state when that attempt fails. This is mostly due to NetworkDisconnect closing/freeing things that might be used later, causing many potential places with reading invalid data.

## Description

The first step is to remove the NetworkDisconnect from the `connect` command. This solves all cases where a client tries to join an invalid company number.
The second step is more involved. Upon the join it checks whether the user is in main menu. When it is in the main menu, it will happily continue. When it is not in the main menu, it will load the main menu and trigger the join process to start.

## Limitations

Reconnect and connect from within a network game is now slower as it first needs to load the main menu.

## Backporting

Backport the following commits:
* Fix #6598: Do not disconnect before company number validation … -> should work without any extra effort
* Fix #6598: Prevent invalid memory accesses when abandoning a join fro… -> will cause conflicts, that require using the old `_network_join_...` variables and adding a `_network_join_address` variable that can be "local" to network.cpp. The strecpy with last_join should be kept out too.

Leave the following two commits out / do not backport:
* Change: [Console] Show help when passing invalid company number -> mostly required due to another change that is not in 1.11, which moved the validation out of the console command
* Codechange: Move join information into a single structure -> makes the code nicer/more maintainable, but not needed for the fix

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/network/network_client.h [hunk 1]
```diff
@@ -112,9 +112,15 @@ typedef ClientNetworkGameSocketHandler MyClient;
...
 void NetworkClientSetCompanyPassword(const char *password);
 
-extern CompanyID _network_join_as;
+/** Information required to join a server. */
+struct NetworkJoinInfo {
+	NetworkJoinInfo() : company(COMPANY_SPECTATOR), server_password(nullptr), company_password(nullptr) {}
+	NetworkAddress address;          ///< The address of the server to join.
+	CompanyID      company;          ///< The company to join.
+	const char    *server_password;  ///< The password of the server to join.
+	const char    *company_password; ///< The password of the company to join.
```
Comment (TrueBrain) [inline src/network/network_client.h]: Please don't align like this; it is a nightmare to do when types change .. personally aligning for comments is already "meh" (but we do it everywhere, so I guess we should), but for types is just even worse :P

File: src/openttd.cpp [hunk 2]
```diff
@@ -1068,6 +1068,14 @@ void SwitchToMode(SwitchMode new_mode)
 			break;
 		}
 
+		case SM_JOIN_GAME:
+			/* Used in case a (re)connect is triggered from inside a (network) game
+			 * to prevent invalid pointer dereferences. Loads the main menu and then
```
Comment (TrueBrain) [inline src/openttd.cpp]: you keep mentioning "invalid pointer dereferences" in comments, but it is not really clear why/how. Is there any chance we can be more clear in what the issue is? Maybe borrow some text from the commit message, as that does seem to explain the "why" in more detail?

File: src/network/network_client.h [hunk 3]
```diff
@@ -112,9 +112,15 @@ typedef ClientNetworkGameSocketHandler MyClient;
 void NetworkClient_Connected();
 void NetworkClientSetCompanyPassword(const char *password);
 
-extern CompanyID _network_join_as;
+/** Information required to join a server. */
+struct NetworkJoinInfo {
+	NetworkJoinInfo() : company(COMPANY_SPECTATOR), server_password(nullptr), company_password(nullptr) {}
+	NetworkAddress address;          ///< The address of the server to join.
+	CompanyID      company;          ///< The company to join.
+	const char    *server_password;  ///< The password of the server to join.
```
Comment (TrueBrain) [inline src/network/network_client.h]: any chance we can make this into std::strings while we are here? ("no" is a valid answer)

File: src/network/network.cpp [hunk 4]
```diff
@@ -713,40 +713,87 @@ class TCPClientConnecter : TCPConnecter {
...
+ * Join a client to the server at the given address.
+ * See the overloaded NetworkClientConnectGame for more details.
+ *
+ * @param address               The network address of the server to join to.
+ * @param join_as               The company number to join as.
+ * @param join_server_password  The password for the server.
+ * @param join_company_password The password for the company.
+ * @return Whether the join has started.
+ */
+bool NetworkClientConnectGame(NetworkAddress &address, CompanyID join_as, const char *join_server_password, const char *join_company_password)
```
Comment (TrueBrain) [inline src/network/network.cpp:758]: Similar as elsewhere, any chance we can make this into std::string while we are here?

File: src/network/network.cpp [hunk 5]
```diff
@@ -713,40 +713,87 @@ class TCPClientConnecter : TCPConnecter {
...
-	_network_join_server_password = join_server_password;
-	_network_join_company_password = join_company_password;
+	if (_game_mode == GM_MENU) {
+		/* From the menu we can immediately continue with the actual join. */
+		NetworkClientJoinGame();
+	} else {
+		/* When not in the main menu, force going to the main menu to prevent half
+		 * joined clients being in weird states. Like most of the UI still believing
+		 * they are in a network game when other parts have been disconnected.
+		 * Not going to the main menu will cause all kinds of invalid pointer dereferences.*/
```
Comment (TrueBrain) [inline src/network/network.cpp]: nitpick: missing space at end of sentence.

File: src/network/network.cpp [hunk 6]
```diff
@@ -713,40 +713,87 @@ class TCPClientConnecter : TCPConnecter {
 	}
 };
 
-void NetworkClientConnectGame(const std::string &connection_string, CompanyID default_company, const char *join_server_password, const char *join_company_password)
+/**
+ * Join a client to the server at with the given connection string.
+ * The default for the passwords is \c nullptr. When the server or company needs a
+ * password and none is given, the user is asked to enter the password in the UI.
```
Comment (TrueBrain) [inline src/network/network.cpp]: nitpick: `in the GUI`. The graphical part is improtant here, I would guess :)

**Review by TrueBrain — COMMENTED** [review]
This PR feels a bit messy till I started to look at the commits one by one. There are two seemly unrelated fixes in this PR.

I would suggest we do not backport the first part, as it touches parts that should not go in 1.11 to start with.

The second part might be worth it, but honestly, I don't know if it does. If we do, it might be good to split this into two PRs, but I leave this fully up to you :)

File: src/network/network_client.h (hunk 3 above)
Comment (rubidium42) [reply src/network/network_client.h]: Not in this at this moment, as then I'd also need to put parts of other PRs into here like sending std::string_view into a packet.

File: src/openttd.cpp (hunk 2 above)
Comment (rubidium42) [reply src/openttd.cpp]: If added more information to NetworkClientJoinGame and added a reference in the documentation to there.

File: src/network/network.cpp (hunk 4 above)
Comment (rubidium42) [reply src/network/network.cpp:758]: Not yet; would add too much interdependency between different PRs of me.

**Review by TrueBrain — APPROVED** [review]
