### PR TITLE
Fix #12250: YAPF Trivial rail pathfinding crashes due to #12217

### LINKED ISSUE #12250: [Crash]: YAPF: Trivial rail pathfinding crashes due to #12217 because ChooseRailTrack best node no longer always has a parent as currently required
### Version of OpenTTD

Since #12217

### Steps to reproduce

image
[YapfGroup Ltd, 1990-01-16.sav.zip](https://github.com/OpenTTD/OpenTTD/files/14548699/YapfGroup.Ltd.1990-01-16.sav.zip)

### Upload crash files

```
#0  CYapfFollowRailT<CYapfRail_TypesT<CYapfRail2, CFollowTrackT<(TransportType)0, Train, false, false>, CNodeList_HashTableT<CYapfRailNodeT<CYapfNodeKeyTrackDir>, 8, 10>, CYapfDestinationTileOrStationRailT, CYapfFollowRailT> >::ChooseRailTrack(Train const*, StrongType::Typedef<unsigned int, TileIndexTag, StrongType::Compare, StrongType::Integer, StrongType::Compatible<int>, StrongType::Compatible<long> >, DiagDirection, TrackBits, bool&, bool, PBSTileInfo*, StrongType::Typedef<unsigned int, TileIndexTag, StrongType::Compare, StrongType::Integer, StrongType::Compatible<int>, StrongType::Compatible<long> >*)
    (this=this@entry=0x7fff93a9fbd0, v=v@entry=0x55555785b780, path_found=@0x7fff93aa25d3: true, reserve_track=reserve_track@entry=true, target=target@entry=0x7fff93aa2610, dest=dest@entry=0x0)
    at /home/jgr/openttd/trunk/src/pathfinder/yapf/yapf_rail.cpp:451
#1  0x0000555555c173fd in CYapfFollowRailT<CYapfRail_TypesT<CYapfRail2, CFollowTrackT<(TransportType)0, Train, false, false>, CNodeList_HashTableT<CYapfRailNodeT<CYapfNodeKeyTrackDir>, 8, 10>, CYapfDestinationTileOrStationRailT, CYapfFollowRailT> >::stChooseRailTrack(Train const*, StrongType::Typedef<unsigned int, TileIndexTag, StrongType::Compare, StrongType::Integer, StrongType::Compatible<int>, StrongType::Compatible<long> >, DiagDirection, TrackBits, bool&, bool, PBSTileInfo*, StrongType::Typedef<unsigned int, TileIndexTag, StrongType::Compare, StrongType::Integer, StrongType::Compatible<int>, StrongType::Compatible<long> >*)
    (v=0x55555785b780, tile=..., enterdir=<optimised out>, tracks=<optimised out>, path_found=@0x7fff93aa25d3: true, reserve_track=<optimised out>, target=0x7fff93aa2610, dest=0x0)
    at /home/jgr/openttd/trunk/src/pathfinder/yapf/yapf_rail.cpp:405
#2  0x0000555555bfcbfb in YapfTrainChooseTrack(Train const*, StrongType::Typedef<unsigned int, TileIndexTag, StrongType::Compare, StrongType::Integer, StrongType::Compatible<int>, StrongType::Compatible<long> >, DiagDirection, TrackBits, bool&, bool, PBSTileInfo*, StrongType::Typedef<unsigned int, TileIndexTag, StrongType::Compare, StrongType::Integer, StrongType::Compatible<int>, StrongType::Compatible<long> >*)
    (v=v@entry=0x55555785b780, tile=..., enterdir=<optimised out>, tracks=tracks@entry=TRACK_BIT_Y, path_found=<optimised out>, reserve_track=reserve_track@entry=true, target=0x7fff93aa2610, dest=0x0)
    at /home/jgr/openttd/trunk/src/pathfinder/yapf/yapf_rail.cpp:546
#3  0x00005555560aa13f in DoTrainPathfind(Train const*, TileIndex, DiagDirection, TrackBits, bool&, bool, PBSTileInfo*, TileIndex*) (v=v@entry=0x55555785b780, tile=..., 
    tile@entry=..., enterdir=<optimised out>, tracks=tracks@entry=TRACK_BIT_Y, path_found=@0x7fff93aa25d3: true, do_track_reservation=do_track_reservation@entry=true, dest=<optimised out>, final_dest=<optimised out>)
    at /home/jgr/openttd/trunk/src/train_cmd.cpp:2480
#4  0x00005555560b3cf5 in ChooseTrainTrack(Train*, TileIndex, DiagDirection, TrackBits, bool, bool*, bool)
    (v=0x55555785b780, tile=..., enterdir=<optimised out>, tracks=<optimised out>, force_res=<optimised out>, got_reservation=0x7fff93aa26bf, mark_stuck=false) at /home/jgr/openttd/trunk/src/train_cmd.cpp:2815
#5  0x00005555560b4b39 in TryPathReserve(Train*, bool, bool) (first_tile_okay=<optimised out>, mark_as_stuck=false, v=0x55555785b780) at /home/jgr/openttd/trunk/src/train_cmd.cpp:2911
#6  TryPathReserve(Train*, bool, bool) (v=0x55555785b780, mark_as_stuck=<optimised out>, first_tile_okay=<optimised out>) at /home/jgr/openttd/trunk/src/train_cmd.cpp:2861
#7  0x00005555560b8ffb in CheckTrainStayInDepot (v=<optimised out>) at /home/jgr/openttd/trunk/src/train_cmd.cpp:2319
#8  TrainLocoHandler(Train*, bool) (v=v@entry=0x55555785b780, mode=mode@entry=false) at /home/jgr/openttd/trunk/src/train_cmd.cpp:3987
#9  0x00005555560b93f6 in TrainLocoHandler (mode=false, v=0x55555785b780) at /home/jgr/openttd/trunk/src/train_cmd.cpp:3943
#10 Train::Tick() (this=0x55555785b780) at /home/jgr/openttd/trunk/src/train_cmd.cpp:4120
#11 0x00005555560d5542 in CallVehicleTicks() () at /home/jgr/openttd/trunk/src/vehicle.cpp:1001
#12 0x0000555555f359ea in StateGameLoop() () at /home/jgr/openttd/trunk/src/openttd.cpp:1488
#13 0x0000555555f36b21 in GameLoop() () at /home/jgr/openttd/trunk/src/openttd.cpp:1609
#14 0x0000555555ccf2c2 in VideoDriver::GameLoop() (this=0x55555679c600) at /home/jgr/openttd/trunk/src/video/video_driver.cpp:39
#15 0x0000555555ccf363 in VideoDriver::GameThread() (this=0x55555679c600) at /home/jgr/openttd/trunk/src/video/video_driver.cpp:46
#16 0x0000555555cd1832 in StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&)(VideoDriver*), VideoDriver*&&)#1}::operator()(char const*, void (*&&)(VideoDriver*), VideoDriver*&&) const (__closure=<optimised out>, A#0=<optimised out>, F=<optimised out>, name=0x55555618a726 "ottd:game") at /home/jgr/openttd/trunk/src/video/../thread.h:65
#17 std::__invoke_impl<void, StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&)(VideoDriver*), VideoDriver*&&)#1}, char const*, void (*)(VideoDriver*), VideoDriver*>(std::__invoke_other, StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&&&)(VideoDriver*), VideoDriver*&&)#1}, char const*&&, void (*&&)(VideoDriver*), VideoDriver*&&) (__f=<optimised out>) at /usr/include/c++/11/bits/invoke.h:61
#18 _ZSt8__invokeIZ14StartNewThreadIPFvP11VideoDriverEJS2_EEbPSt6threadPKcOT_DpOT0_EUlS8_OS4_OS2_E_JS8_S4_S2_EENSt15__invoke_resultIS9_JDpSB_EE4typeESA_SD_ (__fn=<optimised out>) at /usr/include/c++/11/bits/invoke.h:96
#19 std::thread::_Invoker<std::tuple<StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&)(VideoDriver*), VideoDriver*&&)#1}, char const*, void (*)(VideoDriver*), VideoDriver*> >::_M_invoke<0ul, 1ul, 2ul, 3ul>(std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) (this=<optimised out>) at /usr/include/c++/11/bits/std_thread.h:259
#20 std::thread::_Invoker<std::tuple<StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&)(VideoDriver*), VideoDriver*&&)#1}, char const*, void (*)(VideoDriver*), VideoDriver*> >::operator()() (this=<optimised out>) at /usr/include/c++/11/bits/std_thread.h:266
#21 std::thread::_State_impl<std::thread::_Invoker<std::tuple<StartNewThread<void (*)(VideoDriver*), VideoDriver*>(std::thread*, char const*, void (*&&)(VideoDriver*), VideoDriver*&&)::{lambda(char const*, void (*&&)(VideoDriver*), VideoDriver*&&)#1}, char const*, void (*)(VideoDriver*), VideoDriver*> > >::_M_run() (this=0x55555792ec50) at /usr/include/c++/11/bits/std_thread.h:211
#22 0x00007ffff7364253 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#23 0x00007ffff6fecac3 in start_thread (arg=<optimised out>) at ./nptl/pthread_create.c:442
#24 0x00007ffff707e850 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

### PR DESCRIPTION
**Pull request by Kuhnovic**
## Motivation / Problem

Fixes #12250

## Description

My changes in #12217 causes YAPF to stop the search if start_node == destination_node. The YAPF train pathfinder was not able to deal with a situation like that, which led to a nullptr dereference.

## Limitations

YAPF is scary

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/pathfinder/yapf/yapf_rail.cpp [hunk 1]
```diff
@@ -446,6 +446,11 @@ class CYapfFollowRailT : public CYapfReserveTrack<Types>
 
 				this->FindSafePositionOnNode(pPrev);
 			}
+
+			/* There is no next track if the origin node is also a destination node.
+			 * Note that we still consider the path to be found, this is on purpose. */
```
Comment (TrueBrain) [inline src/pathfinder/yapf/yapf_rail.cpp]: This sentence is hard to decipher, and I am not sure what you are trying to say. The return indicates something invalid, and the comment says "the path to be found".

Mind rewording it a bit to make more clear what you are trying to say? :D

Comment (Kuhnovic) [reply src/pathfinder/yapf/yapf_rail.cpp]: See my updated commit, I hope this clears things up a bit :)

**Review by TrueBrain — APPROVED** [review]
