### PR TITLE
Fix #7593: Crash in ScriptOrder::GetOrderDistance in VT_AIR mode

### LINKED ISSUE #7593: Null pointer dereference in ScriptOrder::GetOrderDistance in VT_AIR mode on waypoint tiles
## Version of OpenTTD
Current master

## Expected result
No null pointer dereference occurs when calling ScriptOrder::GetOrderDistance in VT_AIR mode with either origin_tile or dest_tile as a waypoint tile.

## Actual result
Null pointer dereference occurs when calling ScriptOrder::GetOrderDistance in VT_AIR mode with either origin_tile or dest_tile as a waypoint tile.
ScriptTile::IsStationTile() (i.e. IsTileType(tile, MP_STATION)) returns true for waypoint tiles, however Station::GetByTile() returns nullptr.

## Steps to reproduce
Load and unpause the attached savegame.
AIAI v97 calls ScriptOrder::GetOrderDistance in VT_AIR on the west and north corners at initialisation.

[GetOrderDistance bug.sav.zip](https://github.com/OpenTTD/OpenTTD/files/3184950/GetOrderDistance.bug.sav.zip)

See also:
https://github.com/JGRennison/OpenTTD-patches/commit/bdcafb38ccad4bb5ce94ee9c54dc9adfe2edca03
Thread starting from: https://www.tt-forums.net/viewtopic.php?p=1221446#p1221446

### PR DESCRIPTION
**Pull request by JGRennison**
Null pointer dereference occurred when either origin_tile or dest_tile
were waypoint tiles.

### CODE REVIEW

**Review by LordAro — DISMISSED** [review]
That if statement is getting a bit long, can you separate it into a couple of temporaries? `origin_station` & `dest_station`, probably

**Review by glx22 — DISMISSED** [review]

File: src/script/api/script_order.cpp [hunk 1]
```diff
@@ -667,8 +667,10 @@ static void _DoCommandReturnSetOrderFlags(class ScriptInstance *instance)
 /* static */ uint ScriptOrder::GetOrderDistance(ScriptVehicle::VehicleType vehicle_type, TileIndex origin_tile, TileIndex dest_tile)
 {
 	if (vehicle_type == ScriptVehicle::VT_AIR) {
-		if (ScriptTile::IsStationTile(origin_tile) && ::Station::GetByTile(origin_tile)->airport.tile != INVALID_TILE) origin_tile = ::Station::GetByTile(origin_tile)->airport.tile;
-		if (ScriptTile::IsStationTile(dest_tile) && ::Station::GetByTile(dest_tile)->airport.tile != INVALID_TILE) dest_tile = ::Station::GetByTile(dest_tile)->airport.tile;
+		Station *orig_station = ::Station::GetByTile(origin_tile);
```
Comment (glx22) [inline src/script/api/script_order.cpp]: This will assert if the tile is not a station

**Review by glx22 — APPROVED** [review]
Now it should be correct :)
