### PR TITLE
Fix #14827: Store random trigger information per-tile.

### LINKED ISSUE #14827: [Bug]: Station randomisation issues
### Version of OpenTTD

20251125

### Expected result

I'm not sure if this is a bug, or something I'm doing, but it's weird.

I have a station with little passenger graphics, which are supposed to rerandomise on a per-platform basis when a train is loading in the station. And it works - so long as the station is comprised entirely of this platform type (or, in my full grf, of platform types with similar code).

If I have a platform of a different type - including other grf stations, but also the default station! - a train loading on the *different* platform causes *all* the passenger sprites to rerandomise. How is this other platform updating the per-tile bits of other tiles (or, why are my triggers firing because of the train over *there*)? I have no idea.

I've simplified the code down, and the issue persists. Test grf is attached.

### Actual result

Image

With both platforms using the newgrf-type, only the platform where the train is loading gets rerandomised. This is the desired behaviour!

Image

With one platform replaced with the default station, a train loading there rerandomises the passengers on all the other tiles, too! This is not supposed to happen!

### Steps to reproduce

test grf:

[stationtest.zip](https://github.com/user-attachments/files/23747229/stationtest.zip)

  nfo:

```  
  // Automatically generated by GRFCODEC. Do not modify!
  // (Info version 32)
  // Escapes: 2+ 2- 2< 2> 2u< 2u> 2/ 2% 2u/ 2u% 2* 2& 2| 2^ 2sto = 2s 2rst = 2r 2psto 2ror = 2rot 2cmp 2ucmp 2<< 2u>> 2>>
  // Escapes: 71 70 7= 7! 7< 7> 7G 7g 7gG 7GG 7gg 7c 7C
  // Escapes: D= = DR D+ = DF D- = DC Du* = DM D* = DnF Du<< = DnC D<< = DO D& D| Du/ D/ Du% D%
  // Format: spritenum imagefile depth xpos ypos xsize ysize xrel yrel zoom flags
      0 * 4	 26 01 00 00
  
  // INFO DATA CHUNKS
  
      1 * 19	 14 "C" "INFO"
                    "B" "VRSN" \w4 \d1
                00
      00
      2 * 19	 14 "C" "INFO"
                    "B" "MINV" \w4 \d1
                00
      00
  
      3 * 16	 14 "C" "INFO"
                    "B" "PALS" \w1 "D"
                00
      00
  
      4 * 16	 14 "C" "INFO"
                    "B" "BLTR" \w1 "3"
                00
      00
  
      5 * 16	 14 "C" "INFO"
                  "B" "NPAR" \w1 \b0
  		00
  	00		
  
  
      6 * 34	 08 08 44 44 ff 08 "Station Randomisation Test" 00 00
  
  	// cargo table
  
      7 * 10	 00 08 01 01 00 09
              "PASS" // 00
  
  
  // passenger platforms ======================================================================================
  
  // 31 Square End Platform
  
      8 * 6	 01 04 \b1 ff \w269 // 13 + (64 * 4)
  
  << realsprites >>
  
    278 * 9	 02 04 04 01 01 \wx0 \wx0
    
    279 * 227	 00 04 \b12 \b1 \bx31
  
  08 "DFLT"	//	D Class ID, see below
  0B 02		//	B Callback flags (1 = dis/enable, 2 = select layout)
  0C 00		//	B Bit mask of disabled numbers of platforms
  0D 00		//	B Bit mask of disabled platform lengths
  11 ff 		//	B Pylon placement (set to enable)
  14 00		//	B Overhead wire placement (set to disable)
  13 00		//	B General flags
  15 00 		//	B Can train enter tile (set to disable)
  
  20 \bx8 01 01 01 01 01 01 01 01 // can bridge
  21 \bx8 00 00 00 00 00 00 00 00	// pillars
  
  12 \dx01 	// cargos to randomise on (pax)
  
  1a 04  
  \bx44
  \w1012 00 00 \wx0  							 		 // ground
  \dx8000042e \wx0  0 0 0  10 5 4			     // platform sprite
  \dx80000430 \wx0  0 b 0  10 5 4			     // platform sprite
  \dx80000438 \wx2   0 2 4  10 3 4	\bx18	 // waiting passenger sprite	(+ reg 18)
  \dx80000438 \wx2   0 c 4  10 3 4	\bx19	 // waiting passenger sprite	(+ reg 19)
  
    \bx44
  \w1011 00 00 \wx0  							 		 // ground
  \dx8000042d \wx0  b 0 0  5 10 4				 // platform sprite
  \dx8000042f \wx0  0 0 0  5 10 4				 // platform sprite  
  \dx80000439 \wx2   2 0 4  3 10 4	\bx1a	 // waiting passenger sprite	(+ reg 1a)
  \dx80000439 \wx2   c 0 4  3 10 4	\bx1b	 // waiting passenger sprite	(+ reg 1b)
  
  // buy menu
    \bx42 
  \w1012 00 00 \wx0  							 		 // ground
  \dx8000042e \wx0  0 0 0  10 5 4		 // platform sprite
  \dx80000430 \wx0  0 b 0  10 5 4		 // platform sprite
  
    \bx42
  \w1011 00 00 \wx0  							 		 // ground
  \dx8000042d \wx0  b 0 0  5 10 4		 // platform sprite
  \dx8000042f \wx0  0 0 0  5 10 4		 // platform sprite
  
    280 * 14	 02 04 04 81 1a 00 ff 01  00 00 00 00 00 00		
  
  // waiting passengers  ----------------------
  
    // full
    281 * 57	 02 04 14 85 5f 38 0f 00 // random val
  			 \2+ 1a 20 \w193 // + 193
    			 \2sto 1a 20 \wx18 // store in reg 18
  			 \2+ 1a 20 \w16 // + 16
    			 \2sto 1a 20 \wx19 // store in reg 19	
  			 \2+ 1a 20 \w16 // + 16
    			 \2sto 1a 20 \wx1a // store in reg 1a	
  			 \2+ 1a 20 \w16 // + 16
    			 \2sto 1a 00 \wx1b // store in reg 1b				 
  												01 04 00 \w0 \w0 04 00
  
  
    282 * 39	 02 04 14 80 10 10 10 // randomise on trainload
  	14 00 14 00 14 00 14 00 14 00 14 00 14 00 14 00 14 00 14 00 14 00 14 00 14 00 14 00 14 00 14 00 
  
  
    283 * 52	 02 04 00 85   // init storages  
  						 1a 20 \w0 \2sto 1a 20 \wx18 \2rst
  						 1a 20 \w0 \2sto 1a 20 \wx19 \2rst
  						 1a 20 \w0 \2sto 1a 20 \wx1a \2rst	
  						 1a 20 \w0 \2sto 1a 00 \wx1b
  												01 14 00 \w0 \w0 14 00
  
  
    284 * 14	 02 04 00 81 0c 00 ff 01 \wx8000 14 14 00 00		// cb 14 select layout
   // ---------------------
    285 * 14	 02 04 f0 81 0c 00 ff 01 \wx8002 // layout for menu
   14 14 00 00		
   // ---------------------
    286 * 10	 03 04 \b1 \bx31		// action 3
  01 ff f0 00 00 00  
    287 * 20	 04 04 ff 01 \wxc531 "Test Platform" 00
  
```

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

As per #14827, waiting random triggers for stations are broken by design as they are combined into a single value for each station, but random triggers can be per-platform instead.

## Description

Keep a record of waiting random triggers per-tile, allowing per-tile/per-platform triggers to have independent data.

## Limitations

Removal/clearing of per-tile waiting random triggers may be incomplete.
Nasty bit of const mangling in the saveload handler, though not really anything new there.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/saveload/station_sl.cpp [hunk 1]
```diff
@@ -229,6 +229,37 @@ class SlStationSpecList : public VectorSaveLoadHandler<SlStationSpecList<T>, Bas
 template class SlStationSpecList<StationSpec>;
 template class SlStationSpecList<RoadStopSpec>;
 
+class SlStationWaitingTriggers : public DefaultSaveLoadHandler<SlStationWaitingTriggers, BaseStation> {
```
Comment (Rito13) [inline src/saveload/station_sl.cpp:232]: I have noticed that majority of classes in saveload directory is not documented, but `SlStationBase` and `SlStationNormal` do. Why not add a doxygen comment when creating a new class?

File: src/base_station_base.h [hunk 2]
```diff
@@ -74,6 +74,7 @@ struct BaseStation : StationPool::PoolItem<&_station_pool> {
 	TimerGameCalendar::Date build_date{}; ///< Date of construction
 
 	uint16_t random_bits = 0; ///< Random bits assigned to this station
+	std::unordered_map<TileIndex, StationRandomTriggers> tile_waiting_random_triggers;
```
Comment (Rito13) [inline src/base_station_base.h:77]: Other members are documented, why not this one?

**Review by Rito13 — COMMENTED** [review]
As hard as I have tried to break this PR, I was not able to. :)

**Review by rubidium42 — APPROVED** [review]

**Comment by PeterN** [comment]
I added stuff to the savegame but didn't bump it. Seems to work without it but not sure if that's right.
