### PR TITLE
Fix #12279: Update random path each step

### LINKED ISSUE #12279: [Bug]: CreateRandomPath not updating tile nor dir for each step it advances
### Version of OpenTTD

OpenTTD 20240312-master-g1addeddc07

### Expected result

Move to the next tile and retrieve the next trackdirs available each step.

### Actual result

`CreateRandomPath` `tile` and `trackdir` aren't being updated for each step it advances, generating a bad `path_cache` as a result.

### Steps to reproduce

it's not updating `tile` nor `dir` for each time it advances, also, going north should alternate between `TRACKDIR_LEFT_N` and `TRACKDIR_RIGHT_N`:
image

[look at ship 3.zip](https://github.com/OpenTTD/OpenTTD/files/14571410/look.at.ship.3.zip)

### PR DESCRIPTION
**Pull request by SamuXarick**
## Motivation / Problem
CreateRandomPath tile and trackdir aren't being updated for each step it advances, generating a bad path_cache as a result.

## Description
Move to the next tile and retrieve the next trackdirs available each step. Fix #12279 

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/pathfinder/yapf/yapf_ship.cpp [hunk 1]
```diff
@@ -173,7 +173,7 @@ class CYapfFollowShipT
 	}
 
 	/** Returns a random trackdir that can be reached from the current tile/trackdir, or INVALID_TRACK if none is available. */
-	static Trackdir GetRandomFollowUpTrackdir(const Ship *v, TileIndex tile, Trackdir dir, bool include_90_degree_turns)
+	static Trackdir GetRandomFollowUpTrackdir(const Ship *v, TileIndex &tile, Trackdir dir, bool include_90_degree_turns)
```
Comment (Kuhnovic) [inline src/pathfinder/yapf/yapf_ship.cpp]: TileIndex is a value type, but calling this function changes the provided tile. This is not visible from the calling site (in CreateRandomPath), which makes is a bit counter intuitive.

 Some alternative options:
- return a std::pair<TileIndex, Trackdir>
- Add a parameter, for example `TileIndex &new_tile`. Fill that tile with the new tile from the Trackfollower.

File: src/pathfinder/yapf/yapf_ship.cpp [hunk 2]
```diff
@@ -206,7 +207,7 @@ class CYapfFollowShipT
 	static Trackdir ChooseShipTrack(const Ship *v, TileIndex tile, DiagDirection enterdir, bool &path_found, ShipPathCache &path_cache)
 	{
 		/* Move back to the old tile/trackdir (where ship is coming from). */
-		const TileIndex src_tile = TileAddByDiagDir(tile, ReverseDiagDir(enterdir));
+		TileIndex src_tile = TileAddByDiagDir(tile, ReverseDiagDir(enterdir));
```
Comment (Kuhnovic) [inline src/pathfinder/yapf/yapf_ship.cpp]: Leave it const. The src_tile will always be the source tile.

**Review by Kuhnovic — CHANGES_REQUESTED** [review]

File: src/pathfinder/yapf/yapf_ship.cpp (hunk 1 above)
Comment (SamuXarick) [reply src/pathfinder/yapf/yapf_ship.cpp]: I went with std::pair. I tried the 2nd alternative but I still fail at dealing with & and * stuff.

File: src/pathfinder/yapf/yapf_ship.cpp [hunk 3]
```diff
@@ -172,28 +172,28 @@ class CYapfFollowShipT
...
 	{
 		TrackFollower follower(v);
 		if (follower.Follow(tile, dir)) {
-			tile = follower.m_new_tile;
 			TrackdirBits dirs = follower.m_new_td_bits;
 			if (!include_90_degree_turns) dirs &= ~TrackdirCrossesTrackdirs(dir);
 			const int strip_amount = _random.Next(CountBits(dirs));
 			for (int s = 0; s < strip_amount; ++s) RemoveFirstTrackdir(&dirs);
-			return FindFirstTrackdir(dirs);
+			return std::make_pair(follower.m_new_tile, FindFirstTrackdir(dirs));
```
Comment (Kuhnovic) [inline src/pathfinder/yapf/yapf_ship.cpp]: It's not wrong to use std::make_pair, but you can also initialize a pair using braced initialization: `{follower.m_new_tile, FindFirstTrackdir(dirs)}`

File: src/pathfinder/yapf/yapf_ship.cpp [hunk 4]
```diff
@@ -172,28 +172,28 @@ class CYapfFollowShipT
...
 		}
-		return INVALID_TRACKDIR;
+		return std::make_pair(follower.m_new_tile, INVALID_TRACKDIR);
```
Comment (Kuhnovic) [inline src/pathfinder/yapf/yapf_ship.cpp]: All calls to GetRandomFollowUpTrackdir end up only using the trackdir (second) of the pair. And the function is called GetRandomFollowUpTrackdir, so you might as well just return the trackdir instead of the whole pair.

**Review by Kuhnovic — CHANGES_REQUESTED** [review]

File: src/pathfinder/yapf/yapf_ship.cpp (hunk 4 above)
Comment (SamuXarick) [reply src/pathfinder/yapf/yapf_ship.cpp]: No, the `m_new_tile` is used in `CreateRandomPath` `for` loop to follow up to the next tile.

Comment (Kuhnovic) [reply src/pathfinder/yapf/yapf_ship.cpp]: Oh right, I didn't see that one. Then rename the function to GetRandomFollowUpTileTrackdir to reflect what it does :)

**Review by Kuhnovic — APPROVED** [review]
