### PR TITLE
Fix #10059: Clamp config item values to int, disallow negative random deviation, and allow values up to 12 digits including '-'

### LINKED ISSUE #10059: [Crash]: CTD and incorrect parameter value when adding GSInfo setting with certain int max values
### Version of OpenTTD

OpenTTD 12.2, Windows 10 64-bit

### Steps to reproduce

1. Create an info.nut file for a game script
2. Under the GSInfo derived class create a setting
3. Set the max value of this setting really high (as an example I did 4 billion, i dont know the exact range this happens at)
    - Note that setting this value too high (such as 4 trillion) will cause it to work normally. In this case, if you try to enter 4 billion as a value, it will stop typing at 400 million.
5. Set the other parameters of the setting to something random (It didn't matter in my testing)
6. Add a label for this setting for the value 0
7. Load the game into the "Configure Game Script Parameters" window
8. Click the dropdown (which is shown instead of a number picker)
9. Crash the game to desktop

See below for the screenshot at crash time. **I have attached a minimal game script setup to test this functionality:** [MinimalCTDTest.zip](https://github.com/OpenTTD/OpenTTD/files/9662175/MinimalCTDTest.zip)

**NOTE:** if you skip step 5 and do not put a label, the game will not crash but you will instead have incorrect parameters:
image
In this case, it does not show a drop down but the correct number picker, although it is grayed out. Inputting any number into the parameter will cause it to change from 0 to -29496729

### Upload crash files

The exception is "0xC0000094: The thread tried to divide an integer value by an integer divisor of zero."
[crash20220928063447.log](https://github.com/OpenTTD/OpenTTD/files/9662170/crash20220928063447.log)
crash20220928063447

### PR DESCRIPTION
**Pull request by SamuXarick**
## Motivation / Problem
We can't input custom negative values via query string on a config item and it can't be more than 10 digits.
Crash report is caused by implicit 64 bit to 32 bit conversions during construction of a script's settings.
We can't create labels for settings with a negative value.

## Description
- Clamp config item values to int32. They're already correctly read as int64 (or SQInteger).
- Disallow negative random_deviation. It would cause weirdness during AddDeviation, because it expects uint. If it is negative, the abs of it is set instead.
- Allow custom values via query string to be negative and up to 12 digits, to allow for a large enough number, like -2 147 483 648.
- Also allow saving to the savegame and openttd.cfg numbers these large.
- AddLabels now checks the second character of key_string identifiers. If it finds a '_', then the integer that comes after becomes negative, allowing adding labels to negative values of a setting.

## Limitations
I suppose none.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by glx22 — COMMENTED** [review]
Documentation should mention the clamping and the allowed range.

File: src/script/script_info.cpp [hunk 1]
```diff
@@ -252,7 +252,14 @@ SQInteger ScriptInfo::AddLabels(HSQUIRRELVM vm)
 		if (SQ_FAILED(sq_getstring(vm, -1, &label))) return SQ_ERROR;
 		/* Because squirrel doesn't support identifiers starting with a digit,
 		 * we skip the first character. */
-		int key = atoi(key_string + 1);
+		key_string++;
+		int sign = 1;
+		if (strchr(key_string, '_')) {
```
Comment (glx22) [inline src/script/script_info.cpp]:
```suggestion
		if (*key_string == '_') {
```

File: src/script/script_info.cpp [hunk 2]
```diff
@@ -252,7 +252,14 @@ SQInteger ScriptInfo::AddLabels(HSQUIRRELVM vm)
...
+			/* When the second character is '_', it indicates the value is negative. */
+			sign = -1;
+			key_string++;
+		}
+		int key = atoi(key_string);
```
Comment (glx22) [inline src/script/script_info.cpp]: You don't apply the sign.

File: src/script/api/script_info_docs.hpp [hunk 3]
```diff
@@ -218,17 +218,23 @@ class ScriptInfo {
 	 *    store the current configuration of Scripts. Required.
 	 *  - description A single line describing the setting. Required.
 	 *  - min_value The minimum value of this setting. Required for integer
-	 *    settings and not allowed for boolean settings.
+	 *    settings and not allowed for boolean settings. The value will be
+	 *    clamped in the range [-2147483648, 2147483647] (inclusive).
```
Comment (glx22) [inline src/script/api/script_info_docs.hpp]: Didn't check all documentation, but some places use `MIN(int32) .. MAX(int32)` style.
Not sure which one is better, but consistency is good.

File: src/script/api/script_info_docs.hpp [hunk 4]
```diff
@@ -218,17 +218,23 @@ class ScriptInfo {
...
-	 *    is selected. Required.
+	 *    is selected. Required. The value will be clamped in the range
+	 *    [-2147483648, 2147483647] (inclusive).
 	 *  - custom_value The default value if the custom difficulty level
-	 *    is selected. Required.
+	 *    is selected. Required. The value will be clamped in the range
+	 *    [-2147483648, 2147483647] (inclusive).
 	 *  - random_deviation If this property has a nonzero value, then the
 	 *    actual value of the setting in game will be randomized in the range
 	 *    [user_configured_value - random_deviation, user_configured_value + random_deviation] (inclusive).
```
Comment (glx22) [inline src/script/api/script_info_docs.hpp:240]: This one is also clamped but to `0 .. MAX(int32)`

Comment (SamuXarick) [reply src/script/api/script_info_docs.hpp:240]: It's not exactly "clamped". I just don't know how to describe it. It's Clamp(abs(res)) in code. -30 becomes 30, not 0.

Comment (glx22) [reply src/script/api/script_info_docs.hpp:240]: Sign is ignored, and it's clamped.

File: src/script/script_config.cpp [hunk 5]
```diff
@@ -216,7 +216,7 @@ std::string ScriptConfig::SettingsToString() const
 	char *s = string;
 	*s = '\0';
 	for (const auto &item : this->settings) {
-		char no[10];
+		char no[12];
```
Comment (rubidium42) [inline src/script/script_config.cpp]: First of all the commit message is not correct compared to this code. The 12 in here contains a trailing `\0`, so at most 11 digits could be placed.
Secondly, the whole function is trying hard to stay within the artificial 1024 byte limit, but then returns a theoreticall unbounded `string`, so why not use proper C++ constructs to create this settings string?
Thirdly, the ini file reading seems to use a 1024 byte buffer as well, so how can the written value ever be correctly read, because I think there is some key in front of the configuration.

So all-in-all it's more broken than this commit fixes, though I can agree that the second and third issue are not for this PR. The commit message definitely is broken, and the current number is magic-y without any comments, so what about something like:
`char no[10 + 1 + 1]; // Maximum of 10 digits for MIN/MAX_INT32, 1 for the sign and 1 for '\0'.`
And if the "12" gets used in many more places, a constant would be better as it can be reused, maybe something like `INT32_DIGITS_WITH_SIGN_AND_TERMINATION`.

Comment (SamuXarick) [reply src/script/script_config.cpp]: I placed INT32_DIGITS_WITH_SIGN_AND_TERMINATION in the script_config.hpp with comment, added includes in script_gui.cpp and game_gui.cpp to read this value. Also edited 2 commit messages.

**Review by rubidium42 — APPROVED** [review]
