### PR TITLE
Fix #10638: Incorrect water infrastructure total when building canal over object

### LINKED ISSUE #10638: [Bug]: CmdBuildCanal over an object built on a unowned canal incorrectly updates infrastructure totals
### Version of OpenTTD

master

### Expected result

CmdBuildCanal correctly updates infrastructure totals

### Actual result

CmdBuildCanal does not correctly update infrastructure totals in the case where the tile already has a unowned canal tile with an unowned object on it.

Clearing the object leaves an unowned canal tile, CmdBuildCanal does not then correctly update the infrastructure total when replacing the unowned canal with an owned one.

This can result in multiplayer desyncs, etc.

This is a sub-case of issue #9870.

#9888 only fixes the case where the object/canal owner and the new canal piece owner are the same.

### Steps to reproduce

1. Build a canal tile, in the scenario editor.
2. Build an object (with OBJECT_FLAG_AUTOREMOVE) on the canal tile, in the scenario editor.
3. Play the scenario.
4. Build a canal tile on the object on the canal tile.
5. The company's infrastructure totals are now incorrect, this can be verified by using a desync debug level >= 2.
6. Clear the canal tile to get an infrastructure total of UINT32_MAX.

### PR DESCRIPTION
**Pull request by JGRennison**
## Motivation / Problem

#10638

## Description

Replace #9888 with https://github.com/JGRennison/OpenTTD-patches/commit/0a31b27a209f71a2a71b3fab740fb39253b3f2c4.

Result was previously only correct when the previous canal owner was the same as the new canal owner.

## Limitations

N/A

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/water_cmd.cpp [hunk 1]
```diff
@@ -481,6 +481,14 @@ CommandCost CmdBuildCanal(DoCommandFlag flags, TileIndex tile, TileIndex start_t
 		if (!water) cost.AddCost(ret);
 
 		if (flags & DC_EXEC) {
+			if (IsTileType(current_tile, MP_WATER) && IsCanal(current_tile)) {
+				Owner owner = GetTileOwner(tile);
```
Comment (glx22) [inline src/water_cmd.cpp]: Is it the correct tile ?

Comment (JGRennison) [reply src/water_cmd.cpp]: Oops

**Review by glx22 — APPROVED** [review]

**Comment by PeterN** [comment]
Slightly confused as to the background of one player building over another player's canal.

**Comment by rubidium42** [comment]
> Slightly confused as to the background of one player building over another player's canal.

Another valid player seems weird indeed. Maybe an `assert(owner, _current_company); // If the owner is valid, the current company should have been the owner` at line 487? In any case replacing `owner` with `_current_company` in there seems even more wrong.

**Comment by JGRennison** [comment]
Canals and any objects on them are permitted to be unowned. e.g. when created in the scenario editor or by a GS.
When a player company builds canals or objects on canals the resulting tile is owned by the player.
