### PR TITLE
Fix #7692: Added industry tile to GetOrderCmdFromTile()

### LINKED ISSUE #7692: Industry stations could be made easier to click
## Version of OpenTTD
All

## Expected result
Clicking anywhere on an industry with attached station (e.g. oil rig) while building vehicle orders will send the vehicle to that industry's station.

## Actual result
You have to click the specific one or two tiles that are marked as "station tiles", which can be difficult to guess and hit depending on zoom level.

## Steps to reproduce
1. Zoom out all the way
2. Build a ship or helicopter
3. Attempt to make orders for the vehicle to stop at an oil rig

## Other notes
Based on this thread: https://www.tt-forums.net/viewtopic.php?f=32&t=85764

Can probably be implemented easily by catching clicks on industry tiles with the "go-to" tool used to build orders, and follow a link from clicked industry to linked station.

### PR DESCRIPTION
**Pull request by JMcKiern**
Sending order command to an industry tile now checks if a neutral_station is available and sends the order to that station.

This is to solve #7692.

### CODE REVIEW

**Review by nielsmh — DISMISSED** [review]
This looks spot-on. I'll admit to not testing, but it compiles and the code is straight forward.

File: src/order_gui.cpp [hunk 1]
```diff
@@ -389,11 +390,17 @@ static Order GetOrderCmdFromTile(const Vehicle *v, TileIndex tile)
...
 
-	if (IsTileType(tile, MP_STATION)) {
-		StationID st_index = GetStationIndex(tile);
-		const Station *st = Station::Get(st_index);
+	/* check for station or industry with neutral station */
+	if (IsTileType(tile, MP_STATION) || IsTileType(tile, MP_INDUSTRY)) {
+		const Station *st = nullptr;
 
-		if (st->owner == _local_company || st->owner == OWNER_NONE) {
+		if (IsTileType(tile, MP_STATION)){
```
Comment (LordAro) [inline src/order_gui.cpp]: missing space
```suggestion
		if (IsTileType(tile, MP_STATION)) {
```

**Review by LordAro — DISMISSED** [review]

**Review by nielsmh — APPROVED** [review]
