### PR TITLE
Fix #11402: Make string filter locale-aware.

### LINKED ISSUE #11402: [Bug]: Search fields are case sensitive in some languages
### Version of OpenTTD

OpenTTD 20231026

### Expected result

Search fields are not case sensitive, just like in English
изображение
изображение
изображение

### Actual result

At least in Cyrillic, the search fields are case sensitive.
изображение
изображение
изображение

### Steps to reproduce

1. Switch language to Russian/Belarusian/Ukrainian/Bulgarian
2. Try searching for something in «aviable trains» using lowercase text, for example паровоз / Паровоз

### PR DESCRIPTION
**Pull request by michicc**
## Motivation / Problem

String filters are currently not doing a locale-aware string match, which leads to issues as described in #11402 .

## Description

Use appropriate Win32/OSX/ICU functions to build a locale-aware `strstr` function, which then makes the string filter work as expected. Tested with the Russian example from the issue on all three platforms.

As locale-aware matching might not be suitable for every string filter usage, I've added an additional parameter to `StringFilter` to keep using the locale-unaware match. Currently, I've only enabled this for the script debug window break string filter.

## Limitations

There might be some other uses of `StringFilter` that should keep using the old matching.

I've only tested the Russian example from the issue report.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/os/macosx/string_osx.cpp [hunk 1]
```diff
@@ -336,6 +336,31 @@ int MacOSStringCompare(std::string_view s1, std::string_view s2)
...
 }
 
+/**
+ * Search if a string is contained in another string.
+ *
+ * @param str String to search in.
+ * @param value String to search for.
+ * @param case_insensitive Search case-insensitive.
+ * @return 1 if value was found, 0 if it was not found, or -1 if not supported by the OS.
+ */
```
Comment (TrueBrain) [inline src/os/macosx/string_osx.cpp:346]: Why only document the OSX variant? :D

File: src/stringfilter.cpp [hunk 2]
```diff
@@ -118,9 +118,16 @@ void StringFilter::AddLine(const char *str)
...
+			if (this->locale_aware) {
+				if (match_case ? StrNaturalContains(str, ws.start) : StrNaturalContainsIgnoreCase(str, ws.start)) {
+					ws.match = true;
+					this->word_matches++;
+				}
+			} else {
+				if ((match_case ? strstr(str, ws.start) : strcasestr(str, ws.start)) != nullptr) {
+					ws.match = true;
+					this->word_matches++;
+				}
```
Comment (LordAro) [inline src/stringfilter.cpp:130]: ternery inside an if is... a thing. I was thinking maybe a function pointer, but locale/notlocale has different signatures

File: src/string_func.h [hunk 3]
```diff
@@ -39,6 +39,8 @@ void StrTrimInPlace(std::string &str);
 [[nodiscard]] int StrCompareIgnoreCase(const std::string_view str1, const std::string_view str2);
 [[nodiscard]] bool StrEqualsIgnoreCase(const std::string_view str1, const std::string_view str2);
 [[nodiscard]] int StrNaturalCompare(std::string_view s1, std::string_view s2, bool ignore_garbage_at_front = false);
+[[nodiscard]] bool StrNaturalContains(const std::string_view str, const std::string_view value);
+[[nodiscard]] bool StrNaturalContainsIgnoreCase(std::string_view str, const std::string_view value);
```
Comment (LordAro) [inline src/string_func.h]: why is this not const?

File: src/stringfilter.cpp (hunk 2 above)
Comment (michicc) [reply src/stringfilter.cpp:130]: Well, the ternary was already there, I just adapted to it 😄

**Review by rubidium42 — APPROVED** [review]
