### PR TITLE
Change: Use an indent, not a dash, to list train capacity

### LINKED ISSUE #9882: [Bug]: Negative train total cargo
### Version of OpenTTD

Built from latest master (0dce7bf85d56b879e6e7e42b2bef4ef827275cf9) on Ubuntu 22.04

### Expected result

Total cargo that the train is carrying should be a positive number

### Actual result

Total cargo that the train is carrying is presented as a negative number:
Screenshot from 2022-05-08 16-14-33

### Steps to reproduce

Unsure what scenario caused the issue.
I only see it on trains, not on trucks.
I don't have any boats or planes in this scenario so I'm not sure if the bug is present there too.

### PR DESCRIPTION
**Pull request by 2TallTyler**
## Motivation / Problem

In #9882 a player thought the dash used as a list entry prefix for in the train Total Cargo GUI was a minus sign.

## Description

We discussed other characters and reached a consensus that no character would be better.

I also added an indent (the same size used in the finance window in #9827) for the list items.

indent

Closes #9882.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/train_gui.cpp [hunk 1]
```diff
@@ -363,6 +363,11 @@ void DrawTrainDetails(const Train *v, int left, int right, int y, int vscroll_po
 	/* get rid of awkward offset */
 	y -= WD_MATRIX_TOP;
 
+	/* Indent the total cargo capacity details */
+	int EXP_INDENT = 10;
```
Comment (glx22) [inline src/train_gui.cpp]: Should at least be `const`, and the `EXP_` part comes from expenses window ;)

**Review by glx22 — APPROVED** [review]
