### PR TITLE
Fix #7836: check coherency of newgrf parameter min/max

### LINKED ISSUE #7836: Negativ Integer values for GRF Parameters crashes the game
## Version of OpenTTD
Unknown. Issue exists in 1.9/master and JGR. Probably exists in older versions aswell.

## Error
When a GRF Parameter has negativ integer values, clicking on the dropdown crashes the game.

Assertion Error

## Reproduce
Example GRF to reproduce:
[grf.zip](https://github.com/OpenTTD/OpenTTD/files/3854457/grf.zip)

Link to the NML issue: https://github.com/OpenTTD/nml/issues/57

### PR DESCRIPTION
**Pull request by glx22**

### CODE REVIEW

File: src/newgrf_config.cpp [hunk 1]
```diff
@@ -313,6 +313,10 @@ void GRFParameterInfo::SetValue(struct GRFConfig *config, uint32 value)
 void GRFParameterInfo::Finalize()
 {
 	this->complete_labels = true;
+	if (this->min_value > this->max_value) {
+		grfmsg(2, "StaticGRFInfo: incoherent min/max values, forcing default value");
+		this->min_value = this->max_value = this->def_value;
```
Comment (LordAro) [inline src/newgrf_config.cpp]: is it correct to just force a default value, or should the grf be rejected as invalid? I'd be tempted to say the latter...

Comment (Eddi-z) [reply src/newgrf_config.cpp]: what would the game do with an "invalid" GRF, and how would people debug their grf?

Comment (planetmaker) [reply src/newgrf_config.cpp]: The specs say that a min value for parameters is by default 0 is and a max value of 2^32-1 (which are also the hard limits); default value is to be assumed 0, if not specified otherwise in action 14.
Thus my choice of solution would be to set min=0, max=2^32-1 if max < min or either min or max out of bounds (can that happen?)

**Comment by glx22** [comment]
Checking the values earlier (and ignoring incoherent ones) seems better for me.

**Comment by glx22** [comment]
BTW I noticed it's not possible to enter values > 999 999 999 in the GUI. I tried increasing `max_len` in `ShowQueryString()` call, but it's still not possible to go above 2 147 483 647 because `atoi()` is used for the conversion.

**Review by LordAro — APPROVED** [review]
Entering high numbers is probably a separate issue, crash is more important
