### PR TITLE
Fix #14396: Industry production graph showed zero instead of N/A.

### LINKED ISSUE #14396: [Bug]: Industry cargo graphs are initialized to all visible zeroes instead of invisible/blank values.
### Version of OpenTTD

f41ad372a3 on Windows 10, 64-bit (via Steam)
Originally found while testing the preview for PR https://github.com/OpenTTD/OpenTTD/pull/14321.

### Expected result

Industry cargo graphs should be initialized with blank entries and invisible data points for time periods not part of the industry's existence, just like company graphs.

### Actual result

The following graph is of an industry built at the start of a game (game start = 1 January 2200).
All of the data points from before December 2199 are visible with a value of 0, when they should be invisible.
The December 2199 data points represent the initial "last month's production" figures at the start of a game.

Image

### Steps to reproduce

Start a new game and immediately check an industry's production graph, or build an industry and immediately check its production graph while it is under construction.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

Industry production graphs show all data points as zero, even before the industry existed. While this is... technically true, it's inconsistent with company graphs which do not display missing data points.

image

## Description

Record the which history records are valid per industry so that the graph can avoid showing values which are not present as zero.

Note for a new game, history starts before the game's start date as the last month of history is pre-populated during world generation.

image

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/industry_cmd.cpp [hunk 1]
```diff
@@ -2502,6 +2504,8 @@ static void UpdateIndustryStatistics(Industry *i)
 			p.history[THIS_MONTH].transported = 0;
 		}
 	}
+
+	if (i->num_valid_history < 24) ++i->num_valid_history;
```
Comment (2TallTyler) [inline src/industry_cmd.cpp]: Is there a constant for this max history records? (Maybe not important now, but could be for your 24 months/quarters/years PR).

File: src/industry.h [hunk 2]
```diff
@@ -94,6 +94,7 @@ struct Industry : IndustryPool::PoolItem<&_industry_pool> {
 	Station *neutral_station = nullptr; ///< Associated neutral station
 	ProducedCargoes produced{}; ///< produced cargo slots
 	AcceptedCargoes accepted{}; ///< accepted cargo slots
+	uint8_t num_valid_history = 0; ///< Number of valid history records.
```
Comment (2TallTyler) [inline src/industry.h]: Might be worth noting here that we only count up to 24 (maybe refer to a constant if you add one).

Comment (PeterN) [reply src/industry.h]: I don't think it's too relevant, we can't have valid history past the total number of records.

**Comment by PeterN** [comment]
After experimenting, this solution would need to be replaced­ with extended month/quarter/year history, so it makes sense to use a layout that works for both 24 month history and extended history.

That requires a 64-bit bitmask rather than a single 8-bit value. It is still per-industry rather than per-history table, so not a massive amount of overhead. However if we ever wanted to extend further, the bitmask approach would need to change too.

**Comment by PeterN** [comment]
This is now updated to use a bitmask of valid history records, to make it compatible with the "upcoming" monthly/quarterly/yearly feature. To ease this, this PR now also includes the basic history container changes too.

File: src/saveload/industry_sl.cpp [hunk 3]
```diff
@@ -228,6 +230,20 @@ struct INDYChunkHandler : ChunkHandler {
...
+				/* Before this version we did not keep track of valid history, so assume it from the oldest non-zero value. */
+				uint oldest_valid = 0;
+				for (const auto &p : i->produced) {
+					if (!IsValidCargoType(p.cargo)) continue;
+					for (uint n = LAST_MONTH; n < static_cast<uint>(std::size(p.history)); ++n) {
+						if (p.history[n].production == 0 && p.history[n].transported == 0) continue;
+						oldest_valid = std::max(oldest_valid, n);
+					}
+				}
+				for (uint n = LAST_MONTH; n <= oldest_valid; ++n) SetBit(i->valid_history, n);
```
Comment (rubidium42) [inline src/saveload/industry_sl.cpp]: Why `uint` instead of `size_t`? `std::size` returns `size_t` and all the `operator[]` calls require `size_t`, so a lot of conversions between `uint` and `size_t` need to be made here.

Comment (PeterN) [reply src/saveload/industry_sl.cpp]: And now with `size_t` MSVC moans :)

Comment (rubidium42) [reply src/saveload/industry_sl.cpp]: Oh sigh... `uint` to `uint8_t` doesn't lose data, but `size_t` to `uint8_t`. MSVC, please explain...

**Review by rubidium42 — APPROVED** [review]
