### PR TITLE
Fix #10334: Store separate newgrf-safe version of date_of_last_service

### LINKED ISSUE #10334: [Crash]: Unsafe NewGRF use of date_of_last_service crashes after using date cheat
### Version of OpenTTD

13 RC1 (Reported by other xUSSRset devs as well on 12.2)

### Steps to reproduce

Easy to set up but not 100% results in crash.

Happens with xUSSRset container wagons (any).

Steps:
Start new game in modern days (2020 for example).
Buy a train with container wagons - refit them to refrigirated or liquid cargo. In crashed game - oil was used.
Let it start loading. While it does - change date to earler years. In crashed game - 1960 was used.
Let time pass by.
...
Profit! (?)

As said - not guaranteed to crash. There is an error window when train start to move that capacity changed outside of depot.

In crashed game - train entered depot for service and left. Shortly after - crash.

### Upload crash files

[xUSSRset Crash.zip](https://github.com/OpenTTD/OpenTTD/files/10387861/xUSSRset.Crash.zip)

### PR DESCRIPTION
**Pull request by 2TallTyler**
## Motivation / Problem

When a player uses the date cheat, it shifts the `date_of_last_service` for all vehicles. This variable is exposed to NewGRF authors, who can cause crashes by doing creative things with said variable, like changing #10334.

Also, my ongoing NotDayLength work (#10700) will require NewGRFs to read the calendar date while servicing is based on the economy date.

## Description

If we provide a separate `date_of_last_service_newgrf` to the NewGRF API, we can solve both needs. This was started by @PeterN in #10721 — thanks for that! 😄 I rebased, made a few small changes, and (unlike #10721) actually tested to make sure it works! It does indeed fix #10334. 😉 

I don't know if this is the right approach, but it's time to figure it out so I can move forward with #10700.

Note: NotDayLength will need a similar split with the `build_year` property of vehicles, since aging and renewal is based on economy time while NewGRFs need a stable calendar year for their mischef. That would be orphaned now, so I'll save it for when we actually split off economy time.

Closes #10334.
Supersedes and closes #10721.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/vehicle.cpp [hunk 1]
```diff
@@ -761,6 +762,8 @@ uint32 Vehicle::GetGRFID() const
 void Vehicle::ShiftDates(int interval)
 {
 	this->date_of_last_service = std::max(this->date_of_last_service + interval, 0);
+	/* date_of_last_service_newgrf is not update here as it must stay stable
```
Comment (James103) [inline src/vehicle.cpp]:
```suggestion
	/* date_of_last_service_newgrf is not updated here as it must stay stable
```

**Review by michicc — APPROVED** [review]
Looks sound to me, but my NewGRF patch track record is spotty, so take this with a big spoon of salt.

**Comment by 2TallTyler** [comment]
No dissenters in the month since I opened this (or in #10721, or in Discord), so I guess I'll merge it since I'm in a tidying-up sort of mood. 😃
