### PR TITLE
Fix 0125892: Don't crash when towns upgrade road tiles during expansion

### LINKED ISSUE #8650: Assertion failed at line 111 of D:\a\OpenTTD\OpenTTD\src\core/pool_type.hpp: index < this->first_unused
## Version of OpenTTD
1.11.0-beta1 (Win10 x64), 2021-01-22 10:21 UTC.
## Steps to reproduce
(NewGRFs &c. installed as required)
- Open savegame (crash.sav)
- Allow game to run at high speed
- Crash occurs after circa 1-2 years of game time
[crash.zip](https://github.com/OpenTTD/OpenTTD/files/5937543/crash.zip)

### PR DESCRIPTION
**Pull request by mattkimber**
## Motivation / Problem

0125892 introduced a fix for converting road types not updating infrastructure counters.

When a town expands in a game with multiple town-buildable road types introduced over time, it may result in a road tile being upgraded by the build road command. This causes an assert when the new code tries to get a company from the company pool using company ID 15.

Fixes #8650 

## Description

This fix checks that the current company ID is a valid company before attempting to get the company from the pool and update infrastructure counters.

## Limitations

There do not appear to be any other attempts to get companies from the pool introduced by the mentioned commit, so this should be sufficient to fix the observed bug. I haven't done an exhaustive search for other cases, although my experience is this bug has only occurred in versions build after December 28th so it's likely that is the sole cause.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by mattkimber** [comment]
This is an example save game demonstrating the issue. The town will attempt to convert a road tile in the top right corner from Sett to Town Road after a few days of running.

[test_fail_case.zip](https://github.com/OpenTTD/OpenTTD/files/5937550/test_fail_case.zip)

File: src/road_cmd.cpp [hunk 1]
```diff
@@ -2429,7 +2429,7 @@ CommandCost CmdConvertRoad(TileIndex tile, DoCommandFlag flags, uint32 p1, uint3
 
 			if (flags & DC_EXEC) { // we can safely convert, too
 				/* Update the company infrastructure counters. */
-				if (owner == _current_company) {
+				if (owner == _current_company && Company::IsValidID(_current_company)) {
 					Company * c = Company::Get(_current_company);
 					c->infrastructure.road[from_type] -= num_pieces;
 					c->infrastructure.road[to_type] += num_pieces;
```
Comment (glx22) [inline src/road_cmd.cpp]: Based on my reading of https://github.com/OpenTTD/OpenTTD/commit/0125892f041026d049dd9ce7e6d1a63ed5fd67eb, but not tested, I think
```suggestion
				if (owner == _current_company) {
					ConvertRoadTypeOwner(tile, num_pieces, owner, from_type, to_type);
```
should be a valid option too.

Comment (mattkimber) [reply src/road_cmd.cpp]: Yes, that works fine, cleans up some duplication of code and makes sure the infrastructure window is properly dirtied when converting road.

**Review by LordAro — APPROVED** [review]
