### PR TITLE
Fix #13202: Rail station tile flags were not set early enough.

### LINKED ISSUE #13202: [Crash]: on loading an old save
### Version of OpenTTD

e76cc892558745bc4ceffe36de343903c322516d on Windows 10, 64-bit

### Steps to reproduce

Load the attached savegame (`iTrans, 21st Oct 2072.sav`).

The game will crash with one of the following asserts:
```
Assertion failed at line 82 of D:\\a\\OpenTTD\\OpenTTD\\src\\pbs.cpp: HasTrack(TrackStatusToTrackBits(GetTileTrackStatus(tile, TRANSPORT_RAIL, 0)), t)
Assertion failed at line 1886 of D:\\a\\OpenTTD\\OpenTTD\\src\\vehicle.cpp: index / BITMAP_SIZE < this->used_bitmap.size()
```

### Upload crash files

[crash20241227133016.zip](https://github.com/user-attachments/files/18260658/crash20241227133016.zip)

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

Rail station tile flags now use bits that were (long ago) used to store railtype.

During Afterload, there are some calls that need the state of station tile flags to be correct which were executed before the station tile flags were set.

These flags were always set too late, but it was not as noticeable before as the bits used would always be clear.

## Description

Set station tile flags in AfterLoadStations() instead of later during AfterLoadGame().

This is the earliest point that NewGRF station specs are mapped correctly to stations, and also occurs after the station's railtype has been moved from m3 to m8.

Fixes #13202 

## Limitations

It is still possible for issues to occur if station NewGRFs are changed and a train is on a tile now marked as blocked, but that case is at least due to changing NewGRFs.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/saveload/station_sl.cpp [hunk 1]
```diff
@@ -130,6 +130,12 @@ void AfterLoadStations()
 		StationUpdateCachedTriggers(st);
 		RoadStopUpdateCachedTriggers(st);
 	}
+
+	/* Station blocked, wires and pylon flags need to be stored in the map. This is effectively cached data, so no
+	 * version check is necessary. This is done here as the SLV_182 check below needs the blocked status. */
```
Comment (michicc) [inline src/saveload/station_sl.cpp]: There's no `SLV_182 check below` anymore.

**Review by michicc — APPROVED** [review]
