### PR TITLE
Fix #12145: Incorrect date handling in date cheat in wallclock time-keeping mode

### LINKED ISSUE #12145: [Crash]: CargoDist assertion, date >= edge.LastUpdate()
### Version of OpenTTD

14.0-RC1

### Steps to reproduce

Just playing a vanilla map, when suddenly this assertion triggered in `station_cmd.cpp`, in `DeleteStaleLinks()`:
`assert(TimerGameEconomy::date >= edge.LastUpdate());`

### Upload crash files

[crash20240220222810.json.zip](https://github.com/OpenTTD/OpenTTD/files/14351850/crash20240220222810.json.zip)

### PR DESCRIPTION
**Pull request by JGRennison**
## Motivation / Problem

#12145
The date cheat change shifted stored economy dates even when no change was or should be made to the current economy date.

## Description

No longer shift stored economy dates when using the date cheat in wallclock time-keeping mode.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by glx22** [comment]
Probably also fixes #12027

File: src/cheat_gui.cpp [hunk 1]
```diff
@@ -107,18 +107,21 @@ static int32_t ClickChangeDateCheat(int32_t new_value, int32_t)
...
 	TimerGameCalendar::YearMonthDay ymd = TimerGameCalendar::ConvertDateToYMD(TimerGameCalendar::date);
 	TimerGameCalendar::Date new_calendar_date = TimerGameCalendar::ConvertYMDToDate(new_year, ymd.month, ymd.day);
-	/* Keep economy and calendar dates synced. */
-	TimerGameEconomy::Date new_economy_date = new_calendar_date.base();
-
-	/* Shift cached dates before we change the date. */
-	for (auto v : Vehicle::Iterate()) v->ShiftDates(new_economy_date - TimerGameEconomy::date);
-	LinkGraphSchedule::instance.ShiftDates(new_economy_date - TimerGameEconomy::date);
 
 	/* Now it's safe to actually change the date. */
```
Comment (2TallTyler) [inline src/cheat_gui.cpp]: This comment relates only to the economy date, and should move down to L122.

**Review by 2TallTyler — COMMENTED** [review]
Thanks. ❤️ This is how I originally handled this, but it got lost in a rebase somewhere. 😄

**Review by 2TallTyler — APPROVED** [review]
