### PR TITLE
Fix #6969: Account for BOM when reading script files

### LINKED ISSUE #6969: Bug in extracting .tar file
When in OpenTTD the AI RailwAI (version 8 or version 9) is downloaded from BaNaNaS, OpenTTD seems to incorrectly extracts the downloaded .tar file. Specifically: the file shippathfinder.nut gets an additional 3 bytes appended. Because the tar file doesn't have zero-padding here, the characters "Rai" are added, that are part of the folder/filename for the next file in the .tar file.
Extracting the downloaded .tar file with any extraction software (I use 7-zip) and put the files in the ai-folder gives the correct version of the AI. Thus, it is clearly a bug in openTTD that needs to be solved.

Note that I'll give the AI an update (version 10), hoping to work around this issue. For reproducing the bug, one can download [version 9](http://binaries.openttd.org/bananas/ai/RailwAI-9.tar.gz) and put it manually in the content_download folder.

### PR DESCRIPTION
**Pull request by LordAro**
Squirrel was reading past the end of files files that had a BOM and a size that's a multiple of 512 bytes

What a nice edge case.

### CODE REVIEW

File: src/script/squirrel.cpp [hunk 1]
```diff
@@ -450,17 +450,18 @@ SQRESULT Squirrel::LoadFile(HSQUIRRELVM vm, const char *filename, SQBool printer
 	}
 
 	if (file != NULL) {
-		SQFile f(file, size);
 		ret = fread(&us, 1, sizeof(us), file);
 		/* Most likely an empty file */
-		if (ret != 2) us = 0;
+		if (ret != sizeof(us)) us = 0;
```
Comment (frosch123) [inline src/script/squirrel.cpp]: This "if" won't trigger in tar files. It needs a "if (size >= 2)" before calling the fread.
And also if it triggers, it would have to do a fseek by "ret", and not by "2" as in the "default" case.

File: src/script/squirrel.cpp [hunk 2]
```diff
@@ -474,7 +475,10 @@ SQRESULT Squirrel::LoadFile(HSQUIRRELVM vm, const char *filename, SQBool printer
 				 * machine. Either way, swap the bytes of every word we read. */
 				func = _io_file_lexfeed_UCS2_swap;
```
Comment (frosch123) [inline src/script/squirrel.cpp]: Missing "size -= 2;" ?

File: src/script/squirrel.cpp [hunk 3]
```diff
@@ -474,7 +475,10 @@ SQRESULT Squirrel::LoadFile(HSQUIRRELVM vm, const char *filename, SQBool printer
...
 				break;
-			case 0xFEFF: func = _io_file_lexfeed_UCS2_no_swap; break;
+			case 0xFEFF:
+				func = _io_file_lexfeed_UCS2_no_swap;
+				size -= 2; // Skip BOM
+				break;
 			case 0xBBEF: // UTF-8
 			case 0xEFBB: // UTF-8 on big-endian machine
 				if (fread(&uc, 1, sizeof(uc), file) == 0) {
```
Comment (frosch123) [inline src/script/squirrel.cpp]: Needs simiar "size" check as above.

**Review by frosch123 — DISMISSED** [review]

**Review by frosch123 — APPROVED** [review]
