### PR TITLE
Fix #12118: When adding an unbunching order, properly check for unsafe conditions

### LINKED ISSUE #12118: [Bug]: Most "unbunching" compatibility checks are done only on GUI side
### Version of OpenTTD

master

### Expected result

`Ctrl+Click on roadstop, then Ctrl+Click on depot` should fail like `Ctrl+Click on depot, then Ctrl+Click on roadstop` does.

### Actual result

`Ctrl+Click on roadstop, then Ctrl+Click on depot` doesn't fail
image

### Steps to reproduce

* Build a depot and a roadstop
* Build a vehicle
* Click on order button (it opens in "Go-To" mode)
* Ctrl+Click on the roadstop
* Ctrl+Click on the depot

### PR DESCRIPTION
**Pull request by 2TallTyler**
## Motivation / Problem

Unbunching depot orders added in #11945 cannot coexist with conditional orders or full load orders.

We validate this when modifying an order to have an unbunching flag, but not when creating new orders that already have the flag, as is possible when Ctrl+Clicking on a depot (#12023), or for AIs.

## Description

* Add command validation to return an error if either of these order types exist.
* Add descriptive errors when Ctrl+Clicking on a depot.
* Reuse the new functions in `CmdModifyOrder`.

Fixes #12118.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by TrueBrain** [comment]
Nitpick: missing # in commit message :)

**Comment by 2TallTyler** [comment]
Commit has it, but I missed it in the PR title. 🙂

File: src/order_cmd.cpp [hunk 1]
```diff
@@ -820,6 +820,9 @@ CommandCost CmdInsertOrder(DoCommandFlag flags, VehicleID veh, VehicleOrderID se
 			if (new_order.GetDepotOrderType() & ~(ODTFB_PART_OF_ORDERS | ((new_order.GetDepotOrderType() & ODTFB_PART_OF_ORDERS) != 0 ? ODTFB_SERVICE : 0))) return CMD_ERROR;
 			if (new_order.GetDepotActionType() & ~(ODATFB_HALT | ODATFB_NEAREST_DEPOT | ODATFB_UNBUNCH)) return CMD_ERROR;
 			if ((new_order.GetDepotOrderType() & ODTFB_SERVICE) && (new_order.GetDepotActionType() & ODATFB_HALT)) return CMD_ERROR;
```
Comment (SamuXarick) [inline src/order_cmd.cpp]:
```suggestion
			if ((new_order.GetDepotOrderType() & ODTFB_SERVICE) && (new_order.GetDepotActionType() & (ODATFB_HALT | ODATFB_UNBUNCH))) return CMD_ERROR;
```

File: src/order_cmd.cpp [hunk 2]
```diff
@@ -820,6 +820,9 @@ CommandCost CmdInsertOrder(DoCommandFlag flags, VehicleID veh, VehicleOrderID se
...
+
+			/* Check if we're allowed to have a new unbunching order. */
+			if ((new_order.GetDepotActionType() & ODATFB_UNBUNCH) && (v->HasFullLoadOrder() || v->HasUnbunchingOrder() || v->HasConditionalOrder())) return CMD_ERROR;
```
Comment (SamuXarick) [inline src/order_cmd.cpp]: This would return a generic `ERR_UNKNOWN` for AIs once unbunch is implemented for them. Could these return each their own error string, similar to that of `CmdModifyOrder` below?

Comment (2TallTyler) [reply src/order_cmd.cpp]: Sure, I can do that.

File: src/order_cmd.cpp [hunk 3]
```diff
@@ -819,7 +819,16 @@ CommandCost CmdInsertOrder(DoCommandFlag flags, VehicleID veh, VehicleOrderID se
 			if (new_order.GetNonStopType() != ONSF_STOP_EVERYWHERE && !v->IsGroundVehicle()) return CMD_ERROR;
 			if (new_order.GetDepotOrderType() & ~(ODTFB_PART_OF_ORDERS | ((new_order.GetDepotOrderType() & ODTFB_PART_OF_ORDERS) != 0 ? ODTFB_SERVICE : 0))) return CMD_ERROR;
 			if (new_order.GetDepotActionType() & ~(ODATFB_HALT | ODATFB_NEAREST_DEPOT | ODATFB_UNBUNCH)) return CMD_ERROR;
-			if ((new_order.GetDepotOrderType() & ODTFB_SERVICE) && (new_order.GetDepotActionType() & ODATFB_HALT)) return CMD_ERROR;
+
+			/* Vehicles cannot have a "service if needed" order that also has a depot action. */
+			if ((new_order.GetDepotOrderType() & ODTFB_SERVICE) && (new_order.GetDepotActionType() & ODATFB_HALT | ODATFB_UNBUNCH)) return CMD_ERROR;
```
Comment (TrueBrain) [inline src/order_cmd.cpp]: You are aware you missed some `()` in the if-statement? At least, a few compilers tells me that :) Also seems sensible, to not write something like you did :D

Comment (2TallTyler) [reply src/order_cmd.cpp]: I was not aware, but I am now!

**Review by TrueBrain — APPROVED** [review]
