### PR TITLE
Fix #9020: Update station coverage highlight when adding/removing tiles

### LINKED ISSUE #9020: Coverage not updated directly when expanding
## Version of OpenTTD
1.11.0

## Expected result
Coverage to update immediately when expanding.

## Actual result
New coverage is not marked dirty, so slow appears when you move your mouse around.

## Steps to reproduce
- Build station.
- Disable `Coverage area highlight` on build window.
- Click station, click coverage.
- Extend station with new station (CTRL+build).
- Tiles of new coverage not marked dirty, looks odd.

image

After moving around:
image

### PR DESCRIPTION
**Pull request by 2TallTyler**
## Motivation / Problem

See #9020.

## Description

Marks catchment area tiles dirty whenever tiles are added or removed from a station.

I'd previously created a PR (#9793) to fix this bug and closed it after getting stuck and frustrated. After force-pushing my new commit to the branch, it wouldn't let me reopen the old PR. 

Closes #9020.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/station_cmd.cpp [hunk 1]
```diff
@@ -744,9 +744,14 @@ static void DeleteStationIfEmpty(BaseStation *st)
 void Station::AfterStationTileSetChange(bool adding, StationType type)
 {
 	this->UpdateVirtCoord();
-	this->RecomputeCatchment();
-	DirtyCompanyInfrastructureWindows(this->owner);
```
Comment (michicc) [inline src/station_cmd.cpp:748]: You seem to have lost a line here.

**Review by michicc — APPROVED** [review]
