### PR TITLE
Fix: getaddrinfo/UDP blocking locks up whole game

### LINKED ISSUE #8878: Dedicated server slow to stop while generating map
## Version of OpenTTD
1.11.0-RC1

## Expected result
Server stops quickly (within a few seconds)

## Actual result
Server takes too long to stop.
Timed at ~1m on a 2,048 x 2,048 map (`map_x` = `map_y` = 11).
```console
[2021-03-20 17:15:53] dbg: [net] Map generation percentage complete: 5
^C[2021-03-20 17:15:55] dbg: [net] Generating map failed, aborting
[2021-03-20 17:16:12] dbg: [net] [udp] received new session key from master server (IPv4)
[2021-03-20 17:16:12] ‎*** Game paused (number of players)
[2021-03-20 17:16:12] dbg: [net] [udp] advertising to master server
[2021-03-20 17:16:12] dbg: [misc] Renaming /home/openttd/.openttd/openttd.cfg.new to /home/openttd/.openttd/openttd.cfg failed; configuration not saved
[2021-03-20 17:16:12] dbg: [net] [udp] removing advertise from master server
[2021-03-20 17:16:52] dbg: [net] [server] closed listeners
[2021-03-20 17:16:52] dbg: [net] [admin] closed listeners
[2021-03-20 17:16:52] dbg: [net] [udp] closed listeners
[2021-03-20 17:16:52] dbg: [net] [udp] initializing listeners
[2021-03-20 17:16:52] dbg: [net] [udp] closed listeners
[2021-03-20 17:16:52] dbg: [net] [core] shutting down network
```
Note: `server_advertise = true`
The rest of `openttd.cfg` does not seem to matter.

## Steps to reproduce
```console
openttd -D
<Ctrl-C (SIGINT)>
```
Also reproducible by sending SIGTERM

### PR DESCRIPTION
**Pull request by rubidium42**
## Motivation / Problem

That getaddrinfo timing out/taking a long time for the advertising blocks the whole GameLoop. Consequently the server does not reply quickly enough to the master server for the advertising to sporadically fail, but more importantly other clients connected using UDP will be booted.

## Description

Firstly nielsm's solution (see #9001) is taken, but with some (significant) changes.
1. The locking is now done on a per-socket basis, so the server UDP processing can still happen while the master UDP processing is blocked
2. Some missed locks are added where applicable, and some code from network.cpp is moved to network_udp.cpp to accomplish that
3. Extra checking for a slow getaddrinfo is added, together with some hints in the troubleshooting so the user can solve the root cause of the problems.

Closes #9001 
Fixes #8878
## Limitations

Closing a server or unadvertising will still need to wait for the getaddrinfo resolving to complete, and actually it needs to wait until it has resolved for each socket it wants to send on. Similarly the unadvertise will still be blocky due to the same underlying getaddrinfo timeout.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/network/core/address.cpp [hunk 1]
```diff
@@ -239,7 +239,18 @@ SOCKET NetworkAddress::Resolve(int family, int socktype, int flags, SocketList *
 		strecpy(this->hostname, fam == AF_INET ? "0.0.0.0" : "::", lastof(this->hostname));
 	}
 
+	static bool _resolve_timeout_error_message_shown = false;
+	auto start = std::chrono::steady_clock::now();
 	int e = getaddrinfo(StrEmpty(this->hostname) ? nullptr : this->hostname, port_name, &hints, &ai);
+	auto end = std::chrono::steady_clock::now();
+	std::chrono::duration<double> duration = end - start;
+	if (!_resolve_timeout_error_message_shown && duration.count() > 5) {
```
Comment (TrueBrain) [inline src/network/core/address.cpp]: what I personally found an easier way of reading this, is something like this:

`end - start >= std::chrono::seconds(5)`

That makes it more clear what the time unit is, and allows easier changing that :)

File: src/network/network_udp.cpp [hunk 2]
```diff
@@ -33,19 +33,52 @@
...
+		socket->Close();
+		delete socket;
+		socket = nullptr;
+	}
+
+	void ReceivePackets()
+	{
+		std::unique_lock<std::mutex> lock(mutex, std::defer_lock);
+		if (!lock.try_lock()) {
+			if (receive_iterations_locked++ % 32 == 0) {
```
Comment (TrueBrain) [inline src/network/network_udp.cpp]: shouldn't this be `++receive_iterations_locked` ? As now the first iteration always returns 0? (honest question, these constructs confuse the fuck out of me)

File: docs/multiplayer.md [hunk 3]
```diff
@@ -211,3 +211,10 @@ Last updated:    2011-02-16
      communication from an admin tool reach the programme. See section 1
      'Starting a server' further up for the ports and protocols used by OpenTTD.
      The ports can be configured in the config file.
+
+ - My advertising server warns a lot about getaddrinfo taking N seconds
+     This could be a transient issue with your (local) DNS server, but if the
+     problem persists there is likely a configuration issue in DNS resolving
+     on your computer. This seems to be a common configuration issue for
+     docker instances, where the DNS resolving waits for a time out of usually
```
Comment (TrueBrain) [inline docs/multiplayer.md]: nitpick: software is called `Docker`

**Comment by LordAro** [comment]
Is this in addition to #9001, or instead of ?

File: src/network/core/address.cpp (hunk 1 above)
Comment (rubidium42) [reply src/network/core/address.cpp]: The problem is that I need the number of seconds later again. I have messed with the code itself so it is clearer that they are actually seconds.

File: src/network/network_udp.cpp (hunk 2 above)
Comment (rubidium42) [reply src/network/network_udp.cpp]: Yes, you're right. Now you also get a message for the first iteration... which might be a bit too spammy.

**Comment by rubidium42** [comment]
> Is this in addition to #9001, or instead of ?

Instead of, as in: pulling this also does what #9001 is doing but more fine grained.

File: src/network/network_udp.cpp [hunk 4]
```diff
@@ -33,19 +33,52 @@
...
-NetworkUDPSocketHandler *_udp_client_socket = nullptr; ///< udp client socket
-NetworkUDPSocketHandler *_udp_server_socket = nullptr; ///< udp server socket
-NetworkUDPSocketHandler *_udp_master_socket = nullptr; ///< udp master socket
+static bool _network_udp_server;         ///< Is the UDP server started?
+static uint16 _network_udp_broadcast;    ///< Timeout for the UDP broadcasts.
+static uint8 _network_advertise_retries; ///< The number of advertisement retries we did.
+
+/** Some information about a socket, which exists before the actual socket has been created to provide locking and the likes. */
+struct UDPSocket {
+	const std::string name;                     ///< The name of the socket
```
Comment (TrueBrain) [inline src/network/network_udp.cpp]: Very minor nitpick: sentences end with a dot :) I am perfectly okay if you don't fix this :)

**Review by TrueBrain — DISMISSED** [review]
Assuming you tested this, looks good to me.

**Comment by LordAro** [comment]
...rebase? :>

**Comment by rubidium42** [comment]
> Assuming you tested this, looks good to me.

I indeed tested it myself by introducing a sleep just before the getaddrinfo call, but it would be nice to get it tested by Berbe in the "broken" Docker environment we used for figuring out the cause of his problems.

**Comment by LordAro** [comment]
cc @Berbe for testing please :)

**Comment by Berbe** [comment]
I [rebased this work onto `1.11.0`](https://github.com/Berbe/OpenTTD/tree/udp-blocking), and gave it a spin.

Server advertisement happened while a client was connected without loss of connection. I guess @rubidium42's work did the trick (provided thorough tests are made). Good job!
<details>
<summary>Excerpt of 1.11.0 & udp-blocking server's output</summary>

```console
dbg: [net] Starting dedicated version 1.11.0
dbg: [net] [core] starting network...
dbg: [net] [udp] initializing listeners
dbg: [net] [core] network online, multiplayer available
dbg: [net] Detected broadcast addresses:
dbg: [net] 0) <IP #1>
[2021-04-11 21:11:04] OpenTTD Game Console Revision 7 - 1.11.0
[2021-04-11 21:11:04] ------------------------------------
[2021-04-11 21:11:04] use "help" for more information
[2021-04-11 21:11:04]
[2021-04-11 21:11:04] dbg: [net] [udp] closed listeners
[2021-04-11 21:11:04] dbg: [net] [udp] initializing listeners
[2021-04-11 21:11:04] dbg: [net] [udp] closed listeners
[2021-04-11 21:11:04] dbg: [net] [udp] initializing listeners
[2021-04-11 21:11:04] dbg: [net] starting listeners for clients
[2021-04-11 21:11:04] dbg: [net] [tcp] listening on IPv4 port 0.0.0.0:3982 (IPv4)
[2021-04-11 21:11:04] dbg: [net] [tcp] listening on IPv6 port [::]:3982 (IPv6)
[2021-04-11 21:11:04] dbg: [net] starting listeners for incoming server queries
[2021-04-11 21:11:04] dbg: [net] [udp] listening on IPv4 port 0.0.0.0:3982 (IPv4)
[2021-04-11 21:11:04] dbg: [net] [udp] listening on IPv6 port [::]:3982 (IPv6)
[2021-04-11 21:11:04] dbg: [net] [udp] advertising to master server
[2021-04-11 21:11:04] dbg: [net] [udp] listening on IPv4 port 0.0.0.0:0 (IPv4)
[2021-04-11 21:11:04] dbg: [net] [udp] listening on IPv6 port [::]:0 (IPv6)
[2021-04-11 21:11:05] dbg: [net] Generating map, please wait...
[2021-04-11 21:11:05] dbg: [net] Map generation percentage complete: 5
[2021-04-11 21:11:05] dbg: [net] Map generation percentage complete: 10
[2021-04-11 21:11:06] dbg: [net] Map generation percentage complete: 15
[2021-04-11 21:11:07] dbg: [net] Map generation percentage complete: 20
[2021-04-11 21:11:07] dbg: [net] Map generation percentage complete: 25
[2021-04-11 21:11:07] dbg: [net] Map generation percentage complete: 30
[2021-04-11 21:11:07] dbg: [net] Map generation percentage complete: 35
[2021-04-11 21:11:08] dbg: [net] Map generation percentage complete: 40
[2021-04-11 21:11:08] dbg: [net] Map generation percentage complete: 45
[2021-04-11 21:11:08] dbg: [net] Map generation percentage complete: 50
[2021-04-11 21:11:08] dbg: [net] Map generation percentage complete: 55
[2021-04-11 21:11:09] dbg: [net] Map generation percentage complete: 60
[2021-04-11 21:11:09] dbg: [net] Map generation percentage complete: 65
[2021-04-11 21:11:09] dbg: [net] Map generation percentage complete: 70
[2021-04-11 21:11:09] dbg: [net] Map generation percentage complete: 75
[2021-04-11 21:11:09] dbg: [net] Map generation percentage complete: 80
[2021-04-11 21:11:09] dbg: [net] Map generation percentage complete: 85
[2021-04-11 21:11:09] dbg: [net] Map generation percentage complete: 90
[2021-04-11 21:11:09] dbg: [net] getaddrinfo for hostname "master.openttd.org", port 3978, address family IPv4 and socket type tcp took 5 seconds
[2021-04-11 21:11:09] dbg: [net]   this is likely an issue in the DNS name resolver's configuration causing it to time out
[2021-04-11 21:11:10] dbg: [net] Map generation percentage complete: 99
[2021-04-11 21:11:10] dbg: [net] Map generated, starting game
[2021-04-11 21:11:10] dbg: [net] Network revision name is '1.11.0'
[2021-04-11 21:11:10] ‎*** Game paused (number of players)
[2021-04-11 21:11:11] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:11] dbg: [net] [server] Client connected from <IP #2> on frame 43
[2021-04-11 21:11:11] dbg: [net] Closed client connection 2
[2021-04-11 21:11:12] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:12] dbg: [net] [server] Client connected from <IP #2> on frame 77
[2021-04-11 21:11:13] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:14] ‎*** Player has joined the game (Client #3)
[2021-04-11 21:11:14] ‎*** Player has started a new company (#1)
[2021-04-11 21:11:14] ‎*** Game unpaused (number of players)
[2021-04-11 21:11:14] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:14] dbg: [net] [udp] advertising to master server
[2021-04-11 21:11:15] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:16] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:17] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:18] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:19] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:20] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:20] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:21] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:22] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:23] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:24] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:24] dbg: [net] [udp] advertising to master server
[2021-04-11 21:11:24] dbg: [net] [udp] advertising to the master server is failing
[2021-04-11 21:11:24] dbg: [net] [udp]   we are not receiving the session key from the server
[2021-04-11 21:11:25] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:26] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:27] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:28] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:29] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:29] dbg: [net] [udp]   please allow udp packets from [master.openttd.org]:3978 to you to be delivered
[2021-04-11 21:11:29] dbg: [net] [udp]   please allow udp packets from you to [master.openttd.org]:3978 to be delivered
[2021-04-11 21:11:30] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:31] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:32] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:33] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:34] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:35] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:36] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:37] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:38] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:39] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:40] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:41] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:42] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:43] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:44] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:44] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:11:45] dbg: [net] [udp] received new session key from master server (IPv4)
[2021-04-11 21:11:45] dbg: [net] [udp] received new session key from master server (IPv4)
[2021-04-11 21:11:45] dbg: [net] [udp] received new session key from master server (IPv6)
[2021-04-11 21:11:45] dbg: [net] [udp] received new session key from master server (IPv6)
[2021-04-11 21:11:45] dbg: [net] [udp] received new session key from master server (IPv6)
[2021-04-11 21:26:24] dbg: [net] [udp] advertising to master server
[2021-04-11 21:26:25] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:26] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:27] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:28] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:29] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:30] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:31] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:32] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:33] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:34] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:34] dbg: [net] [udp] advertising to master server
[2021-04-11 21:26:35] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:36] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:37] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:38] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:39] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:40] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:41] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:42] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:43] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:44] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:44] dbg: [net] [udp] advertising to master server
[2021-04-11 21:26:44] dbg: [net] [udp] advertising to the master server is failing
[2021-04-11 21:26:44] dbg: [net] [udp]   we are not receiving the acknowledgement from the server
[2021-04-11 21:26:44] dbg: [net] [udp]   this usually means that the master server cannot reach us
[2021-04-11 21:26:44] dbg: [net] [udp]   please allow udp and tcp packets to port 3982 to be delivered
[2021-04-11 21:26:44] dbg: [net] [udp]   please allow udp and tcp packets from port 3982 to be delivered
[2021-04-11 21:26:45] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:46] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:46] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:47] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:48] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:49] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:50] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:51] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:52] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:53] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:54] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:55] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:56] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:57] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:58] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:26:59] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:00] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:01] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:02] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:03] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:04] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:05] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:06] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:07] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:08] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:09] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:10] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:10] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:11] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:12] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:13] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:14] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:15] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:16] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:17] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:18] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:19] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:20] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:21] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:22] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:23] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:24] dbg: [net] [udp] Master background UDP loop processing appears to be blocked. Your OS may be low on UDP send buffers.
[2021-04-11 21:27:25] dbg: [net] [udp] advertising on master server successful (IPv4)
[2021-04-11 21:27:25] dbg: [net] [udp] advertising on master server successful (IPv4)
[2021-04-11 21:27:25] dbg: [net] [udp] advertising on master server successful (IPv4)
[2021-04-11 21:27:25] dbg: [net] [udp] advertising on master server successful (IPv6)
[2021-04-11 21:27:25] dbg: [net] [udp] advertising on master server successful (IPv6)
[2021-04-11 21:27:25] dbg: [net] [udp] advertising on master server successful (IPv6)
```
</details>

**Review by TrueBrain — APPROVED** [review]
