### PR TITLE
Consolidate IConsolePrint functions and improve some of the messages

### LINKED ISSUE #8853: There are 17 places where "IConsoleError" can be used instead of "IConsolePrintF".
## Version of OpenTTD
9c5a7d3a572d02813e6bab83004334b9a154a62b

## Expected result
The function `IConsoleError` behaves exactly the same as using `IConsolePrintF(CC_ERROR, "ERROR: %s", string);`, but is shorter and more concise.
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console.cpp#L168-L171

Therefore, `IConsoleError(string)` should in general be used instead of `IConsolePrintF(CC_ERROR, "ERROR: %s", string)`.

## Actual result
The following 14 occurrences of `IConsolePrintF(CC_ERROR, "ERROR: %s", string)` still exist:
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L361-L364
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L385-L388
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L430-L433
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L487
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L534
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L558
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L738
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L759
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L791
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L830
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L1577

Additionally, there are 3 additional occurrences of `IConsolePrint(CC_ERROR, "ERROR: %s", string)`:
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L271
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L284
https://github.com/OpenTTD/OpenTTD/blob/9c5a7d3a572d02813e6bab83004334b9a154a62b/src/console_cmds.cpp#L314

## Steps to reproduce
Look in the source of `commands.cpp` for the above occurrences.

### PR DESCRIPTION
**Pull request by rubidium42**
## Motivation / Problem

Where to start?
* Some warnings get "WARNING" added, others do not.
* Some errors get "ERROR" added, others do not.
* Some issues that mean a command cannot be run are shown as warnings, whereas other times they are called as errors.
* Some messages starting with "WARNING" are shown in the error color.
* Vast inconsistency in writing of messages.
* Pointless "-" in front of the help messages, but not for all of them.
* Some "warnings" (or rather issues that would prevent the command to be not run) would not get their "error" shown based on a setting.
* IConsoleError/IConsoleWarning/IConsoleDebug/IConsoleHelp "helper" functions did not support formatting of strings.
* IConsolePrint and IConsolePrintF were used interchangeably, well... IConsolePrintF was used when IConsolePrint could have been used.

## Description

* Consolidate all the console printing functions into IConsolePrint, which now has the same functionality as IConsolePrintF.
* Remove `IConsoleWarning(` in lieu of `IConsolePrint(CC_WARNING, `.
* Remove the filtering of some warning messages.
* Remove `IConsoleError(` in lieu of `IConsolePrint(CC_ERROR, `.
* Remove `IConsoleHelp(` in lieu of `IConsolePrint(CC_HELP, `.
* Add `CC_HELP` to distinguish between `CC_HELP` and `CC_WARNING`.
* Revisit all error messages on their writing and their "color", i.e. make some errors warnings and vice versa.

Feel free to propose other improvements to strings printed to the in-game console.

If this approach is taken over adding formatting functionality to IConsoleError/Warning, then this closes #8853 and closes #8894.

## Limitations

None I think, unless someone did matching on colors of strings, or was actually parsing the strings... as then those might now be broken in some cases.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/console.cpp [hunk 1]
```diff
@@ -218,7 +218,7 @@ static std::string RemoveUnderscores(std::string name)
 /* static */ void IConsole::AliasRegister(const std::string &name, const std::string &cmd)
 {
 	auto result = IConsole::Aliases().try_emplace(RemoveUnderscores(name), name, cmd);
-	if (!result.second) IConsoleError("an alias with this name already exists; insertion aborted");
+	if (!result.second) IConsolePrint(CC_ERROR, "An alias with the name '%s' already exists; insertion aborted", name.c_str());
```
Comment (TrueBrain) [inline src/console.cpp]: `insertion aborted` is a weird way of saying this. Maybe just remove that part? Doesn't really add value, I guess. (given it is already an error and all)

File: src/console_cmds.cpp [hunk 2]
```diff
@@ -957,13 +957,13 @@ DEF_CONSOLE_CMD(ConExec)
 	FILE *script_file = FioFOpenFile(argv[1], "r", BASE_DIR);
 
 	if (script_file == nullptr) {
-		if (argc == 2 || atoi(argv[2]) != 0) IConsoleError("script file not found");
+		if (argc == 2 || atoi(argv[2]) != 0) IConsolePrint(CC_ERROR, "Script file %s not found", argv[1]);
```
Comment (TrueBrain) [inline src/console_cmds.cpp]: maybe quote `%s`?

File: src/console_cmds.cpp [hunk 3]
```diff
@@ -988,7 +988,7 @@ DEF_CONSOLE_CMD(ConExec)
 	}
 
 	if (ferror(script_file)) {
-		IConsoleError("Encountered error while trying to read from script file");
+		IConsolePrint(CC_ERROR, "Encountered error while trying to read from script file %s", argv[1]);
```
Comment (TrueBrain) [inline src/console_cmds.cpp]: Similar here, and with others. Might help for weird cases, like non-breaking-white-space etc :P

File: src/console_cmds.cpp [hunk 4]
```diff
@@ -1891,7 +1891,7 @@ DEF_CONSOLE_CMD(ConContent)
 
 	if (strcasecmp(argv[1], "unselect") == 0) {
 		if (argc <= 2) {
-			IConsoleError("You must enter the id.");
+			IConsolePrint(CC_ERROR, "You must enter the id.");
```
Comment (TrueBrain) [inline src/console_cmds.cpp:1882]: While at it, remove the dot at the end of the line for consistency? Similar in other cases.

File: src/network/network_server.cpp [hunk 5]
```diff
@@ -1073,18 +1073,18 @@ NetworkRecvStatus ServerNetworkGameSocketHandler::Receive_CLIENT_COMMAND(Packet
 	NetworkClientInfo *ci = this->GetInfo();
 
 	if (err != nullptr) {
-		IConsolePrintF(CC_ERROR, "WARNING: %s from client %d (IP: %s).", err, ci->client_id, this->GetClientIP());
+		IConsolePrint(CC_WARNING, "Dropping client #%u (IP: %s) due to %s.", ci->client_id, this->GetClientIP(), err);
```
Comment (TrueBrain) [inline src/network/network_server.cpp]: Similar as with others, drop the dot at the end?

File: src/console.cpp [hunk 6]
```diff
@@ -274,7 +228,7 @@ static void IConsoleAliasExec(const IConsoleAlias *alias, byte tokencount, char
 	DEBUG(console, 6, "Requested command is an alias; parsing...");
 
 	if (recurse_count > ICON_MAX_RECURSE) {
-		IConsoleError("Too many alias expansions, recursion limit reached. Aborting");
+		IConsolePrint(CC_ERROR, "Too many alias expansions, recursion limit reached. Aborting");
```
Comment (TrueBrain) [inline src/console.cpp]: I guess we can remove all these `aborting` statements now, as it is much more clear that is happening?

File: src/console_cmds.cpp [hunk 7]
```diff
@@ -1422,8 +1414,8 @@ DEF_CONSOLE_CMD(ConAlias)
 DEF_CONSOLE_CMD(ConScreenShot)
 {
 	if (argc == 0) {
-		IConsoleHelp("Create a screenshot of the game. Usage: 'screenshot [viewport | normal | big | giant | heightmap | minimap] [no_con] [size <width> <height>] [<filename>]'");
-		IConsoleHelp("'viewport' (default) makes a screenshot of the current viewport (including menus, windows, ..), "
+		IConsolePrint(CC_HELP, "Create a screenshot of the game. Usage: 'screenshot [viewport | normal | big | giant | heightmap | minimap] [no_con] [size <width> <height>] [<filename>]'");
+		IConsolePrint(CC_HELP, "'viewport' (default) makes a screenshot of the current viewport (including menus, windows, ..), "
```
Comment (TrueBrain) [inline src/console_cmds.cpp]: guess this should in fact be multiple print statements now? It was to avoid the silly `-` in front of it :P

File: src/console_cmds.cpp [hunk 8]
```diff
@@ -1586,37 +1578,37 @@ DEF_CONSOLE_CMD(ConHelp)
...
 			return true;
 		}
 
-		IConsoleError("command not found");
+		IConsolePrint(CC_ERROR, "Command not found");
 		return true;
 	}
 
-	IConsolePrint(CC_WARNING, " ---- OpenTTD Console Help ---- ");
+	IConsolePrint(CC_HELP, " ---- OpenTTD Console Help ---- ");
```
Comment (TrueBrain) [inline src/console_cmds.cpp]: If this becomes `CC_HELP`, shouldn't the rest of this list too?

**Review by TrueBrain — COMMENTED** [review]
The first commit is ofc a big no-no, so if anyone during bisecting happens to go back to it, they can get some weird prints, I guess .. but from what I could tell, only in a handful of places, so you have to be really unlucky :P

There also really isn't another way to get where you wanted to go, so I think it is worth doing it like this :)

File: src/console_cmds.cpp (hunk 4 above)
Comment (rubidium42) [reply src/console_cmds.cpp:1882]: The real question with the consistency is, remove all the dots or add all the dots?

Comment (TrueBrain) [reply src/console_cmds.cpp:1882]: Good question :P Personally, I think sentences should always end with a dot, so there is that. But I am fully okay with either one .. and even the 3rd hidden option: "I am not doing that" :)

**Review by TrueBrain — APPROVED** [review]
For sure this is an improvement :) Other nitpicks can be dealt with another time :) Tnx a bunch for this!
