### PR TITLE
Fix #10461, Fix #10280: Town actions GUI issues

### LINKED ISSUE #10280: [Bug]: Error message when performing town action with not enough cash does not say "not enough cash"
### Version of OpenTTD

a857ed8240 on Windows 10, 64-bit (via Steam)

### Expected result

The error message given when attempting to perform a town action while not having enough cash to do it should say that the company does not have enough cash to perform that action with the local authority.

Example: "Can't do this... Not enough cash, requires £102,539"

### Actual result

The error message given when attempting to perform a town action while not having enough cash to do it does not say that the company does not have enough cash to perform that action with the local authority.

Actual: "Can't do this..." without that second line saying "Not enough cash"

### Steps to reproduce

1. Start a new map.
2. Click on a town to open its town window.
3. Click "Local authority".
4. Double click on a greyed-out action to attempt to perform it.
5. The action fails (as expected), but the error message does not say that the company doesn't have enough cash to do it (as is typically the case if an action is greyed out).

### LINKED ISSUE #10461: [Crash]: Drawing town action's description as spectator
### Version of OpenTTD

13.0 windows 10

### Steps to reproduce

I clicked on the Local authority-Actions available

### Upload crash files

[crash20230209235859.zip](https://github.com/OpenTTD/OpenTTD/files/10702634/crash20230209235859.zip)

### PR DESCRIPTION
**Pull request by glx22**
Fix #10461
Fix #10280

## Motivation / Problem
A spectator is not a valid company, and `Company::GetIfValid(_local_company)->money` is not the correct validity check.
Double-click skipping doesn't check for town action availability.

## Description
Check for `_local_company` validity before even trying to access Company members.
Ignore double-click for unavailable town actions.

## Limitations
There are 2 options for the color, ~~I decided to go with yellow, as affordability doesn't matter for spectators.~~ using red is consistent with how it's displayed for valid companies.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by 2TallTyler — COMMENTED** [review]
I agree with your reasoning on leaving the text yellow and (I assume — I'm not near a computer) blocking a spectator's action with a disabled button below. But there should be a comment explaining this. Maybe:
`Cost doesn't matter to spectators, so show all actions as affordable and short-circuit before trying to get an invalid company.`

The inverse of a validity check is a bit of a double negative and threw me off, since I was expecting an `&&` short circuit instead.

**Comment by glx22** [comment]
`&&` short circuit would be for red (`affordable = IsValidCompanyID && company_has_enough_money`)

File: src/town_gui.cpp [hunk 1]
```diff
@@ -229,7 +229,7 @@ struct TownAuthorityWindow : Window {
 			case WID_TA_ACTION_INFO:
 				if (this->sel_index != -1) {
 					Money action_cost = _price[PR_TOWN_ACTION] * _town_action_costs[this->sel_index] >> 8;
-					bool affordable = action_cost < Company::GetIfValid(_local_company)->money;
+					bool affordable = !Company::IsValidID(_local_company) || action_cost < Company::Get(_local_company)->money;
```
Comment (2TallTyler) [inline src/town_gui.cpp]:
```suggestion
					/* Cost doesn't matter to spectators, so show all actions as affordable and short-circuit before trying to get an invalid company. */
					bool affordable = !Company::IsValidID(_local_company) || action_cost < Company::Get(_local_company)->money;
```

**Review by 2TallTyler — COMMENTED** [review]
Yeah, I figured it out after a few minutes, but I still think a comment in the code would be helpful to explain why invalid companies can afford all actions. 🙂 

Also, your second commit fixes #10280.

**Comment by glx22** [comment]
Maybe for consistency spectators (any invalid `_local_company`) should just get red cost for unavailable town actions, like actual players.

**Review by 2TallTyler — APPROVED** [review]
