### PR TITLE
Fix #14756: Invalidate nested focus before container is cleared.

### LINKED ISSUE #14756: [Crash]: Segmentation fault when using badges for stations.
### Version of OpenTTD

Master branch, Debian 12

### Steps to reproduce

1. Play game with NewGRF supporting badges for stations.
2. Open build station menu.
3. Open badge filter dropdown.
4. Move mouse out of the window to a place where lots of cargos are accepted/produced in order to make window too small and force it to update its size.
5. Click on another widget inside the window so the focussed widged is changed.
6. Game freezes.

https://github.com/user-attachments/assets/3336e88c-3ce0-421c-801f-03e197b4b5f3

### Upload crash files

The backtrace from the debugger

```
Thread 1 "openttd" received signal SIGSEGV, Segmentation fault.
0x0000555557528719 in Window::SetFocusedWidget (this=0x555559387b50, widget_index=65555) at /home/cyprian/openTTD/OpenTTD_SourceCode/src/window.cpp:495
495			this->nested_focus->SetDirty(this);
(gdb) backtrace
#0  0x0000555557528719 in Window::SetFocusedWidget (this=0x555559387b50, widget_index=65555) at /home/cyprian/openTTD/OpenTTD_SourceCode/src/window.cpp:495
#1  0x0000555557528d98 in DispatchLeftClickEvent (w=0x555559387b50, x=259, y=39, click_count=1) at /home/cyprian/openTTD/OpenTTD_SourceCode/src/window.cpp:659
#2  0x000055555752fcae in MouseLoop (click=MC_LEFT, mousewheel=0) at /home/cyprian/openTTD/OpenTTD_SourceCode/src/window.cpp:2918
#3  0x0000555557530095 in HandleMouseEvents () at /home/cyprian/openTTD/OpenTTD_SourceCode/src/window.cpp:3004
#4  0x0000555556e868a0 in VideoDriver_SDL_Base::PollEvent (this=0x55555852b870) at /home/cyprian/openTTD/OpenTTD_SourceCode/src/video/sdl2_v.cpp:444
#5  0x0000555556e8f389 in VideoDriver::Tick (this=0x55555852b870) at /home/cyprian/openTTD/OpenTTD_SourceCode/src/video/video_driver.cpp:137
#6  0x0000555556e87503 in VideoDriver_SDL_Base::LoopOnce (this=0x55555852b870) at /home/cyprian/openTTD/OpenTTD_SourceCode/src/video/sdl2_v.cpp:661
#7  0x0000555556e8753a in VideoDriver_SDL_Base::MainLoop (this=0x55555852b870) at /home/cyprian/openTTD/OpenTTD_SourceCode/src/video/sdl2_v.cpp:679
#8  0x00005555571e62aa in openttd_main (arguments=std::span of length 1 = {...}) at /home/cyprian/openTTD/OpenTTD_SourceCode/src/openttd.cpp:811
#9  0x0000555556719f1f in main (argc=1, argv=0x7fffffffdf88) at /home/cyprian/openTTD/OpenTTD_SourceCode/src/os/unix/unix_main.cpp:36
```

And the needed NewGRF 

[Polish_Stations_with_badges.grf.zip](https://github.com/user-attachments/files/23341379/Polish_Stations_with_badges.grf.zip)

### PR DESCRIPTION
**Pull request by Rito13**
## Motivation / Problem

When widget container is cleared (e.g. for the badge filter dropdowns) the window's nested_focus member isn't checked whether it points to one of the contained widgets. In some edge cases the nested_focus becomes invalid and points to the deleted widget. Then when a new widget is focused the window tries to unfocus deleted widget and access freed up memory. Reproduction of such edge case has been described in the #14756.

Fixes #14756.

## Description

Set the nested_focus to nullptr if it points to a widget inside the to be cleared container before clearing the container.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by 2TallTyler** [comment]
Is this a fix for #14756? If so, the commit and PR title should say so. 🙂

**Comment by Rito13** [comment]
> Is this a fix for #14756? If so, the commit and PR title should say so. 🙂 

It ought to be a fix for #14756, but now when I look at the code I don't think it is a good approach as it allows #14756 to reappear in the future.

File: src/widget.cpp [hunk 1]
```diff
@@ -3476,3 +3476,20 @@ std::unique_ptr<NWidgetBase> MakeCompanyButtonRows(WidgetID widget_first, Widget
 	if (hor != nullptr) vert->Add(std::move(hor));
 	return vert;
 }
+
+/**
+ * Unfocuses the focused widget of the window,
+ * if the focused widget is contained inside the container.
+ * @param parent_window Window which contains this container.
+ */
+void NWidgetContainer::UnFocusWidgets(Window *parent_window)
```
Comment (rubidium42) [inline src/widget.cpp]: Naming wise I'd argue `UnfocusWidgets` given there's already an `UnfocusFocusedWidget`, i.e. no capitalized 'F'.

**Review by rubidium42 — APPROVED** [review]
