### PR TITLE
Fix fd2949d: std::string can reallocate on insert()

### LINKED ISSUE #13578: [Crash]: when typing in the in-game console
### Version of OpenTTD

6283631155322059b73ab32317573552ab5e8d6b on Windows 10, 64-bit (via Steam)

### Steps to reproduce

Open the in-game console, then type a command or something else longer than a few words. The game crashes midway through (in my case when typing byte 16, 32, or 48 of the input, followed by increasingly sparse thresholds).

This is a regression, starting no earlier than the previous nightly (f620ba9d05).

### Upload crash files

[crash20250216132113.zip](https://github.com/user-attachments/files/18814808/crash20250216132113.zip)

### PR DESCRIPTION
**Pull request by TrueBrain**
## Motivation / Problem

Fixes #13578

## Description

Turns out MSVC can reallocate an std::string on `insert()` (when size gets above 16, by the looks). Luckily enough, the `insert()` returns the iterator too; and this one is always usable after the `insert()`.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by James103** [comment]
> when size gets above 16, by the looks

Actually (on my end), I crash when size (in bytes) gets above 16, 32, 48, 71, followed by increasingly sparse thresholds.

File: src/string_func.h [hunk 1]
```diff
@@ -166,9 +166,12 @@ inline const char *Utf8PrevChar(const char *s)
...
 {
-	auto *cur = &*s;
-	auto *prev = Utf8PrevChar(cur);
-	return s - (cur - prev);
+	auto cur = s;
+	while (true) {
+		cur = std::prev(cur);
+		if (!IsUtf8Part(*cur)) break;
+	}
+	return s - (s - cur);
```
Comment (glx22) [inline src/string_func.h]:
```suggestion
	do {
		cur = std::prev(cur);
	} while (IsUtf8Part(*cur));
	return cur;
```

**Review by glx22 — APPROVED** [review]
Works for me, but a second review could be a good idea.

**Review by LordAro — APPROVED** [review]
Are there any other usages of insert() that ignore the return value?
