### PR TITLE
Fix #12594: Give descriptive error when company takeover fails due to vehicle limit

### LINKED ISSUE #12594: [Bug]: No descriptive error when hostile takeover fails due to vehicle limit
### Version of OpenTTD

14.0

### Expected result

You can execute a hostile takeover of the company

### Actual result

A message saying "Can't buy company..." appears, with no additional information.

### Steps to reproduce

1. Load attached savegame.
2. Try and execute a hostile takeover of the "AAAHogEx" AI
3. You will see a message saying the cost will be around £12m but on attempting to execute the takeover you just see a message labelled "Can't buy company..."
[Wutborough Market Transport, 1963-05-28.sav.zip](https://github.com/OpenTTD/OpenTTD/files/15153940/Wutborough.Market.Transport.1963-05-28.sav.zip)

### PR DESCRIPTION
**Pull request by 2TallTyler**
## Motivation / Problem

As per #12594, company takeovers that fail due to vehicle limit do not explain why beyond an error, "Can't buy company..."

## Description

Clarify the reason with an existing error string and clarify the comment. Despite its broad name, `MayCompanyTakeOver()` only checks vehicle limits.

Closes #12594.

## Limitations

Does not strictly need backporting, but no languages are changed so I don't see a reason to exclude it.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/economy.cpp [hunk 1]
```diff
@@ -2066,8 +2066,8 @@ CommandCost CmdBuyCompany(DoCommandFlag flags, CompanyID target_company, bool ho
 	/* Do not allow companies to take over themselves */
 	if (target_company == _current_company) return CMD_ERROR;
 
-	/* Disable taking over when not allowed. */
-	if (!MayCompanyTakeOver(_current_company, target_company)) return CMD_ERROR;
+	/* Do not allow takeover if the resulting company would have too many vehicles. */
+	if (!MayCompanyTakeOver(_current_company, target_company)) return_cmd_error(STR_ERROR_TOO_MANY_VEHICLES_IN_GAME);
```
Comment (LordAro) [inline src/economy.cpp]: Are there no other possibilities that cause `MayCompanyTakeOver` to fail? In the future too?

It looks a bit unclear just from looking at this code, is all. Maybe a function rename?

Comment (2TallTyler) [reply src/economy.cpp]: Yes, that's all it does current. I've renamed the function so it doesn't get changed in the future without checking references.

**Review by LordAro — APPROVED** [review]
