### PR TITLE
Fix #11827: Make Layouter::GetCharPosition() aware of ligatures.

### LINKED ISSUE #11827: [Bug]: GetCharPosition does not work with ligatures
### Version of OpenTTD

master

### Expected result

Editing text and moving the text cursor should not crash ;)

### Actual result

Layouter::GetCharPosition() does not consider ligatures, which replaces (at least) a pair of characters with a single glyph.

These are used mostly by non-Latin script, but some Latin fonts also use them (e.g. Tahoma Bold has an 'fi' ligature)

### Steps to reproduce

1. Set medium font to "Tahoma, Bold" 12.
2. Open the console and enter "refit".
3. Use arrow keys to move cursor.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

When ligatures happen the precise individual character position is not known. This currently causes GetCharPosition() to crash.

## Description

Instead, return the previous position (which is that of the ligature). The cursor will appear to not move for each extra character combined into a ligature.

## Limitations

For ligatures of Latin characters this may look odd when editing, but that's better than crashing.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/gfx_layout.cpp [hunk 1]
```diff
@@ -259,7 +259,9 @@ Point Layouter::GetCharPosition(std::string_view::const_iterator ch) const
 
 		for (int i = 0; i < run.GetGlyphCount(); i++) {
 			/* Matching glyph? Return position. */
-			if ((size_t)charmap[i] == index) {
+			if ((size_t)charmap[i] >= index) {
+				/* If the index is passed then it's part of a ligature, so return the position of the combined glyph. */
+				if (i > 0 && (size_t)charmap[i] > index) i--;
```
Comment (rubidium42) [inline src/gfx_layout.cpp]: Might this need to be a loop when there are more than two character leading to a combined glyph/ligature? Like the ﬃ ligature.

Comment (PeterN) [reply src/gfx_layout.cpp]: No, I don't think so. With a two character ligature, `charmap` looks like this: `[0, 1, 2, 4]`
We're looking for index 3, but got to 4 which is higher, so we go back one and get the position of 2.
With three characters it would look like: `[0, 1, 2, 5]`
We'd be looking for 3 (or 4), but get to 5. So again we go back one and get the position of 2.

Comment (PeterN) [reply src/gfx_layout.cpp]: Hmm, it will fail if there's no character after the ligature though. I'll revise!

**Review by rubidium42 — APPROVED** [review]
