### PR TITLE
Fix #11016: Use after free in network invalid packet error path

### LINKED ISSUE #11016: [Bug]: Use after free in network invalid packet error path
### Version of OpenTTD

master

### Expected result

No bugs, etc

### Actual result

CloseConnection in NetworkGameSocketHandler::HandlePacket calls `delete this`.
`this` is still used afterwards in NetworkGameSocketHandler::HandlePacket.
In the case of clients, `this` then gets used to try to send an error to the server in `ClientNetworkGameSocketHandler::Receive` which fairly reliably causes a crash.

### Steps to reproduce

See above and/or inject a packet fault.

### PR DESCRIPTION
**Pull request by JGRennison**
## Motivation / Problem

ClientNetworkGameSocketHandler/ServerNetworkGameSocketHandler::CloseConnection called `delete this`.
However they could still be used afterwards, causing crashes, etc.

## Description

Instead of calling `delete this`, register the handler for deferred deletion, and do the deletions at a later safe point.

The logging in the path where this type of crash occurred was also incorrect/misleading (HandlePacket), so that is also fixed.

## Limitations

N/A

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by glx22 — DISMISSED** [review]

File: src/network/core/tcp_game.cpp [hunk 1]
```diff
@@ -197,3 +200,17 @@ NetworkRecvStatus NetworkGameSocketHandler::Receive_SERVER_MOVE(Packet *p) { ret
...
+	_deferred_deletions.push_back(this);
+	this->is_pending_deletion = true;
+}
+
+/* static */ void NetworkGameSocketHandler::ProcessDeferredDeletions()
+{
+	for (NetworkGameSocketHandler *cs : _deferred_deletions) {
+		delete cs;
+	}
+	_deferred_deletions.clear();
```
Comment (rubidium42) [inline src/network/core/tcp_game.cpp]: Can't `_deferred_deletions` be a `std::vector<std::unique_ptr<NetworkGameSocketHandler>>` so this becomes just a `_deferred_deletions.clear()` without manually deleting objects?

Comment (JGRennison) [reply src/network/core/tcp_game.cpp]: Wouldn't that be a bit confusing, as unique_ptr implies a different ownership model than what is actually used for the various socket handlers?

Comment (rubidium42) [reply src/network/core/tcp_game.cpp]: Not sure if it's confusing. To me it looks like `_deferred_deletions` owns the handlers once they are passed into it, but if it confuses others then keeping it pointers that are manually `delete`d is fine by me as well.

Comment (JGRennison) [reply src/network/core/tcp_game.cpp]: OK, I'll update the PR with this a bit later.

**Review by rubidium42 — APPROVED** [review]

File: src/network/core/tcp_admin.cpp [hunk 2]
```diff
@@ -47,7 +47,13 @@ NetworkRecvStatus NetworkAdminSocketHandler::HandlePacket(Packet *p)
 {
 	PacketAdminType type = (PacketAdminType)p->Recv_uint8();
```
Comment (PeterN) [inline src/network/core/tcp_admin.cpp:48]: If the client has quit, should we even receive the packet type? Maybe place the HasClientQuit() check above here?

File: src/network/core/tcp_game.cpp [hunk 3]
```diff
@@ -63,9 +65,15 @@ NetworkRecvStatus NetworkGameSocketHandler::HandlePacket(Packet *p)
 {
 	PacketGameType type = (PacketGameType)p->Recv_uint8();
 
+	if (this->HasClientQuit()) {
```
Comment (PeterN) [inline src/network/core/tcp_game.cpp:68]: Same as above

File: src/network/core/tcp_admin.cpp (hunk 2 above)
Comment (JGRennison) [reply src/network/core/tcp_admin.cpp:48]: Recv_uint8 itself can set HasClientQuit to true.
The result is 0 (i.e. not valid) whether HasClientQuit was set before or during the call.

Putting the check below is to avoid logging a "received invalid packet type 0" message, when no such packet was ever received.

Comment (PeterN) [reply src/network/core/tcp_admin.cpp:48]: Ah ha
