### PR TITLE
Fix: Various reliability and correctness improvements to MIDI on Windows

### LINKED ISSUE #7438: Music sets (including DOS music) broken after trying other music sets
## Version of OpenTTD
1.9.0RC1

## Expected result
Each music set should play back as its author intended, regardless of sample volume set by other music sets.

## Actual result
Sample volumes from one music set affect later sets chosen, or perhaps some samples are disabled.  If unfamiliar with the music in question, noticeable effects include odd gaps and a strange 'sparseness' which sounds like one-finger playing.

## Steps to reproduce
* Data files copied from DOS TTD CD-ROM, including music
* Get various music sets from Bananas (full list below)
* Load game
* Open Jukebox
* Turn off Shuffle
* Open Music Programme
* Use the Change Set button to change music set
* Play
* Skip some tracks
* Stop
* Repeat last 4 steps (from Change Set)

## List of sets:
Only marking "affected" when I'm sure.  It's hard to be sure without being familiar with each set, which would take me a long time.

* original_dos -- Affected
* [OpenMSX -- not tested]
* Holiday Island -- Affected, especially track 04 which has nothing but rhythm.  Probably also track 01
* Modern Motion
* Radio Monochrome Volume 1.
* Scott Joplin Anthology -- Probably affected; I used to be familiar with Scott Joplin's music and I'm sure it wasn't this sparse.

### PR DESCRIPTION
**Pull request by nielsmh**
- Improve use of locks in Win32 driver to prevent more race conditions
- Share the standard SysEx message data between Win32 and DMusic drivers
- Send the GM reset SysEx message before each song to ensure correct reset of device
- Remove the manual controller resets as they are included in the GM reset

I probably should try to split this into multiple commits.

The last point is tested on a Roland and a Yamaha synth, both behave as expected.

Should fix #7438 (by resetting correctly between tracks)

### CODE REVIEW

File: src/music/win32_m.cpp [hunk 1]
```diff
@@ -35,14 +35,14 @@ static struct {
 	CRITICAL_SECTION lock; ///< synchronization for playback status fields
 
 	bool playing;        ///< flag indicating that playback is active
-	bool do_start;       ///< flag for starting playback of next_file at next opportunity
+	int do_start;        ///< flag for starting playback of next_file at next opportunity
```
Comment (LordAro) [inline src/music/win32_m.cpp:39]: could be an enum?

File: src/music/dmusic.cpp [hunk 2]
```diff
@@ -572,27 +574,15 @@ static void TransmitNotesOff(IDirectMusicBuffer *buffer, REFERENCE_TIME block_ti
 		TransmitChannelMsg(_buffer, block_time + 10, MIDIST_CONTROLLER | ch, MIDICT_SUSTAINSW, 0);
 		TransmitChannelMsg(_buffer, block_time + 10, MIDIST_CONTROLLER | ch, MIDICT_MODE_RESETALLCTRL, 0);
 	}
+
+	TransmitStandardSysex(_buffer, block_time + 20, MidiSysexMessage::ResetGM);
+	TransmitStandardSysex(_buffer, block_time + 30, MidiSysexMessage::RolandSetReverb);
```
Comment (michicc) [inline src/music/dmusic.cpp:580]: Either these lines need to be in the spot where the old pitch bend reset was or the comment that follows is outdated, as there aren't any additional control messages.

File: src/music/win32_m.cpp [hunk 3]
```diff
@@ -52,6 +52,21 @@ static struct {
 
 static FMusicDriver_Win32 iFMusicDriver_Win32;
 
+struct CriticalSectionOptionalLock {
```
Comment (michicc) [inline src/music/win32_m.cpp]: Switch that stuff over to C++11/std::unique_lock? (Yes, more work :)

File: src/music/win32_m.cpp (hunk 1 above)
Comment (nielsmh) [reply src/music/win32_m.cpp:39]: The members would be StartStep1, StartStep2, StartStep3, etc., I don't see a way to make a meaningful enum of this.

Ideally MidiFile would scan for various different init sequences in a file, and if a known sequence is found then leave it, otherwise prepend an init sequence (GM reset + reverb settings) to the data so the driver doesn't need to do anything difficult. I have more plans for improving music support (also past MIDI) and this idea is probably better left for then.

File: src/music/win32_m.cpp [hunk 4]
```diff
@@ -342,7 +328,8 @@ void MusicDriver_Win32::PlaySong(const MusicSongInfo &song)
 	if (!new_song.LoadSong(song)) return;
 	DEBUG(driver, 2, "Win32-MIDI: PlaySong: Loaded song");
 
-	EnterCriticalSection(&_midi.lock);
+	std::scoped_lock mutex_lock(_midi.lock);
```
Comment (michicc) [inline src/music/win32_m.cpp]: `scoped_lock` is C++17, but fortunately doesn't do any anything that `lock_guard`/`unique_lock` doesn't do when used with a single lock.

File: src/music/win32_m.cpp [hunk 5]
```diff
@@ -356,17 +343,14 @@ void MusicDriver_Win32::PlaySong(const MusicSongInfo &song)
...
 	}
-
-	LeaveCriticalSection(&_midi.lock);
 }
 
 void MusicDriver_Win32::StopSong()
 {
 	DEBUG(driver, 2, "Win32-MIDI: StopSong: entry");
-	EnterCriticalSection(&_midi.lock);
+	std::scoped_lock mutex_lock(_midi.lock);
```
Comment (michicc) [inline src/music/win32_m.cpp]: Ditto.

File: src/music/win32_m.cpp [hunk 6]
```diff
@@ -376,17 +360,14 @@ bool MusicDriver_Win32::IsSongPlaying()
 
 void MusicDriver_Win32::SetVolume(byte vol)
 {
-	EnterCriticalSection(&_midi.lock);
+	std::scoped_lock mutex_lock(_midi.lock);
```
Comment (michicc) [inline src/music/win32_m.cpp]: Same.

File: src/music/win32_m.cpp [hunk 7]
```diff
@@ -421,7 +402,7 @@ const char *MusicDriver_Win32::Start(const char * const *parm)
 
 void MusicDriver_Win32::Stop()
 {
-	EnterCriticalSection(&_midi.lock);
+	std::scoped_lock mutex_lock(_midi.lock);
```
Comment (michicc) [inline src/music/win32_m.cpp]: Same.

**Review by michicc — CHANGES_REQUESTED** [review]

**Review by michicc — APPROVED** [review]
