### PR TITLE
Fix #7050: Missing guards around network chat message functions for compiling with networking disabled

### LINKED ISSUE #7050: Compiling with --disable-network yields error
I'm getting this error on Debian buster/testing, gcc 8.2.0, latest git head (96854b2b8bea85926113326e1fd37ee357f7e59e):
```
$ ./configure --with-sdl --disable-network
...
[SRC] Compiling waypoint_cmd.cpp
[SRC] Compiling waypoint_gui.cpp
[SRC] Compiling widget.cpp
[SRC] Compiling widgets/dropdown.cpp
[SRC] Compiling window.cpp
/home/nik/src/OpenTTD/src/window.cpp: In function ‘void UpdateWindows()’:
/home/nik/src/OpenTTD/src/window.cpp:3106:3: error: ‘NetworkChatMessageLoop’ was not declared in this scope                                                              
   NetworkChatMessageLoop();
   ^~~~~~~~~~~~~~~~~~~~~~
/home/nik/src/OpenTTD/src/window.cpp:3106:3: note: suggested alternative: ‘NetworkDrawChatMessage’                                                                       
   NetworkChatMessageLoop();
   ^~~~~~~~~~~~~~~~~~~~~~
   NetworkDrawChatMessage
make[1]: *** [Makefile:227: window.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/nik/src/OpenTTD/objs/release'
make: *** [Makefile:56: all] Error 1
(nik@alfalfa) :( 2 (16:38)
```

### PR DESCRIPTION
**Pull request by PeterN**

### CODE REVIEW

**Review by LordAro — DISMISSED** [review]

File: src/window.cpp [hunk 1]
```diff
@@ -3164,7 +3166,11 @@ void UpdateWindows()
 		/* Update viewport only if window is not shaded. */
 		if (w->viewport != NULL && !w->IsShaded()) UpdateViewportPosition(w);
 	}
+
+#ifdef ENABLE_NETWORKING
```
Comment (glx22) [inline src/window.cpp]: This one is not needed, NetworkDrawChatMessage() is an static empty function without network

**Review by LordAro — APPROVED** [review]
2 line PRs are great
