### PR TITLE
Fix #9243: [Network] For a dedicated server use a fallback client and server name

### LINKED ISSUE #9243: Cannot join server which has no playername
## Version of OpenTTD
9e7e87ce3e7a7a4f5373883550c6f05a5d023ab6

## Expected result
Be able to join a server no matter what his name is.

## Actual result
Client is silently disconnected because of malformed packet.

## Steps to reproduce
- Start a dedicated server with `-x -c empty.cfg` (assuming `empty.cfg` doesn't exist).
- Try to join this server; you won't be able to :P

The problem is that clients reject client-info packets where the client-name is invalid. A dedicated server with no config has an invalid name (it is empty). A regression from an earlier change.

### PR DESCRIPTION
**Pull request by rubidium42**
## Motivation / Problem

Closes #9243. For dedicated servers client name would not be set.

## Description

Check whether the client and server name have been set, and if not set them with some default value. Furthermore warn the user about this with pointer on how to resolve the issue. Next to that also complain when that default value is used as name.
It is not necessary for the non-dedicated server as the GUI already checks the client name, and the server name will also have some default.

## Limitations

The server can still set its client name to be invalid with some effort, though that is then to be considered their problem for now. When/once the validation of string settings can be done, the issue of the previous line including setting bad/invalid server names can be solved once and for all, as it would just reject the new value before writing instead of writing the value and then running a post-change callback that has no way to revert the value to the old (correct) one.
The fallback is "Unnamed Client"  and "Unnamed Server". This capitalization has been chosen as the server variant is the one currently used, so it would also warn on the current "unset" server names.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/network/network.cpp [hunk 1]
```diff
@@ -841,6 +841,27 @@ static void NetworkInitGameInfo()
...
+ */
+static void CheckClientAndServerName()
+{
+	static const char *fallback_client_name = "Unnamed Client";
+	if (StrEmpty(_settings_client.network.client_name) || strcmp(_settings_client.network.client_name, fallback_client_name) == 0) {
+		DEBUG(net, 0, "No \"client_name\" has been set, using \"%s\" instead. Please set this now using the \"name <new name>\" command.", fallback_client_name);
+		strecpy(_settings_client.network.client_name, fallback_client_name, lastof(_settings_client.network.client_name));
+	}
+
+	static const char *fallback_server_name = "Unnamed Server";
```
Comment (TrueBrain) [inline src/network/network.cpp:858]: Maybe we can use `<client_name>'s Server` as fallback? But maybe not for this PR (2 more places that could use that)

**Review by TrueBrain — APPROVED** [review]

File: src/network/network.cpp (hunk 1 above)
Comment (rubidium42) [reply src/network/network.cpp:858]: In the UI that could indeed be a decent default. For the dedicated server I'm fairly server you'll then usually get "Unnamed Client's Server" as server name.
The other place where the "Unnamed Server" is set now should go away once the pre-validation of string settings has been implemented.
