### PR TITLE
Fix #15511: vehicle passed to commands must be a company usable type

### LINKED ISSUE #15511: [Crash]: CheckOwnership calls on owner of vehicle ID received in command parameter can result in inappropriate assertion failures
### Version of OpenTTD

master

### Steps to reproduce

Various commands (most notably CmdSellVehicle) have a `Vehicle::GetIfValid` on a command parameter followed by `CheckOwnership` on `Vehicle::owner`.
If the vehicle is not owned by a valid company (e.g. an effect or disaster vehicle) then `CheckOwnership` causes an assertion failure. Some commands have an `IsPrimaryVehicle` test first which mitigates this, but this isn't always possible/appropriate.
In multiplayer, command delay and vehicle ID re-use can result (with very low probability) in commands being received after the intended vehicle has already been sold and the ID re-used for a different vehicle type. In any case commands should not assert when passed an unexpected vehicle type.

### Upload crash files

N/A

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

As per #15511, ownership checks of vehicles with `CheckOwnership()` requires a valid owner, which isn't the case for vehicles that companies cannot use, e.g. effect or disasters vehicles.

When calling `Vehicle::GetIfValid()` we check if the vehicle exists (compare with `nullptr`).

## Description

When getting vehicles in commands with `Vehicle::GetIfValid()`, additionally check that the vehicle type is a company usable vehicle type. This prevents doing things to those types of vehicles that shouldn't be done.

This does not change the behaviour of `CheckOwnership()` which is more general than just vehicle ownership.

## Limitations

Not properly tested the race condition that triggers this in the first place.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by LordAro** [comment]
Why shouldn't GetIfValid do the type check? Feels like a vehicle type beyond the end of the enum  makes the vehicle "invalid" ?

**Comment by PeterN** [comment]
Because `GetIfValid()` is a generic `PoolItem` method.

**Comment by LordAro** [comment]
Could it be overridden for Vehicle ?

**Comment by rubidium42** [comment]
> Why shouldn't GetIfValid do the type check? Feels like a vehicle type beyond the end of the enum makes the vehicle "invalid" ?

Only `VEH_COMPANY_END` isn't the end of the `VehicleType` enum, that'd be `VEH_END`. For sub-types, e.g. `Train::GetIfValid` it already does the vehicle type check. However, `Vehicle::GetIfValid` won't do that. 
One could consider adding a `CompanyVehicle` into the inheritance tree, but that'd be quite an undertaking.

**Comment by PeterN** [comment]
Now uses the existing `IsCompanyBuildableVehicleType()` method, which is cleaner and makes the intent clearer.

File: src/disaster_vehicle.cpp [hunk 1]
```diff
@@ -1003,6 +1003,7 @@ void ReleaseDisasterVehicle(VehicleID vehicle)
 	if (v == nullptr) return;
 
 	/* primary disaster vehicles that have chosen target */
+	assert(v->type == VEH_DISASTER);
```
Comment (rubidium42) [inline src/disaster_vehicle.cpp:1006]: This is kinda moot as `DisasterVehicle::GetIfValid` does to the `v->type` check (see `SpecializedVehicle`), though I do agree it reinforces the 'story' of the comment.

**Review by rubidium42 — APPROVED** [review]
