### PR TITLE
Fix #6574: Remove go to hangar orders when rebuilding airport

### LINKED ISSUE #6574: Heliport "hangar" can cause stuck helicopters if it replaced a helidepot/helistation.
**_ddm_ opened the ticket and wrote:**

> When replacing a helidepot or helistation with a heliport, if a helicopter has an order to go to the helidepot/helistation hangar immediately after landing at the helidepot/helistation, the helicopter gets stuck as it tries to path from the helipad to the hangar.
> 
> The helicopter can now no longer move at all. Changing it's orders does nothing (including telling it to land at another hangar).
> 
> The heliport can also not be destroyed or have any other helicopter land at it; because the helicopter is taking off/landing at it.
> 
> Note that if it just has an order to go to the hangar but not land at the station, it will land, take off, circle back, and repeat. (This doesn't cause it to fail to move, it just can't figure out how to get to the non-existent hangar.)
> 
> (Just for completeness, I'm using Windows 7 Pro SP1, though I'd assume this is a bug that will occur on any OS.)

**Attachments**
- [heliport bug.sav](https://bugs.openttd.org/task/6574/getfile/10721/heliport+bug.sav) (10.67 KiB)

**Reported version**: _1.7.1_
**Operating system**: _All_

---

### PR DESCRIPTION
**Pull request by SamuXarick**
When replacing an airport with another, cancel current orders of type 'go to depot' from aircraft still heading to it if the rebuilt airport doesn't have a hangar (helicopter vs heliport), or if the airplane can't land on the rebuilt airport (airplane vs helistation).

Invalidates 'go to hangar' orders from all aircraft when replacing an airport with hangar with another without hangar (heliport).

### CODE REVIEW

**Comment by PeterN** [comment]
You can perhaps remove the vehicle's current order, but orders defined in the order list should not be automatically removed. Maybe they can be marked as invalid like when a destination is removed.

**Comment by Eddi-z** [comment]
#7051 should solve this?

**Comment by SamuXarick** [comment]
nendington transport 2002-02-23
nendington transport 2002-02-23 1
nendington transport 2002-02-23 2

File: src/order_backup.cpp [hunk 1]
```diff
@@ -256,15 +256,18 @@ CommandCost CmdClearOrderBackup(TileIndex tile, DoCommandFlag flags, uint32 p1,
...
-/* static */ void OrderBackup::RemoveOrder(OrderType type, DestinationID destination)
+/* static */ void OrderBackup::RemoveOrder(OrderType type, DestinationID destination, bool hangar)
 {
 	OrderBackup *ob;
 	FOR_ALL_ORDER_BACKUPS(ob) {
 		for (Order *order = ob->orders; order != NULL; order = order->next) {
 			OrderType ot = order->GetType();
 			if (ot == OT_GOTO_DEPOT && (order->GetDepotActionType() & ODATFB_NEAREST_DEPOT) != 0) continue;
-			if (ot == OT_IMPLICIT || (IsHangarTile(ob->tile) && ot == OT_GOTO_DEPOT)) ot = OT_GOTO_STATION;
+			if (ot == OT_IMPLICIT || (IsHangarTile(ob->tile) && ot == OT_GOTO_DEPOT && !hangar)) ot = OT_GOTO_STATION;
```
Comment (nielsmh) [inline src/order_backup.cpp:270]: Why is the hangar argument needed? Isn't that already implied by `ot == OT_GOTO_DEPOT`?

Comment (SamuXarick) [reply src/order_backup.cpp:270]: The intention is to clear up (invalidate) the 'to go hangar' orders when replacing an airport with hangar with another without hangar, while still keeping the 'go to same airport' orders. Since I couldn't invalidate only the 'go to hangar' orders, I had to change this part of the code to let me keep the 'go to airport' orders. Otherwise, both 'go to hangar' and 'go to same airport' would be made invalid.

Comment (michicc) [reply src/order_backup.cpp:270]: The hanger argument is in fact needed, if not present order backups with service/goto depot orders are not deleted. A newly built helicopter will then have orders referring to a non-existing hangar.

**Review by michicc — APPROVED** [review]
