### PR TITLE
Fix #12280: Allow ships 90 degree turns if only choice

### LINKED ISSUE #12280: [Bug]: GetRandomFollowUpTrackdir forbids 90 degree turns even when they're the only choice
### Version of OpenTTD

OpenTTD 20240312-master-g1addeddc07

### Expected result

Allow 90 degree turns when they're the only choice.

### Actual result

`GetRandomFollowUpTrackdir` forbids 90 degree turns even when it's the only choice. An invalid trackdir is returned.

### Steps to reproduce

the ship pointing towards north can only turn 90 degrees to the left:
73d1c92b-3d94-4a27-8992-4422c3dc1855
[look at ship 4.zip](https://github.com/OpenTTD/OpenTTD/files/14574768/look.at.ship.4.zip)

### PR DESCRIPTION
**Pull request by SamuXarick**
## Motivation / Problem
If there is no path found, a random path is created which forbids 90 degrees.

## Description
Allow 90 degrees if they're the only choice. Fix #12280

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/pathfinder/yapf/yapf_ship.cpp [hunk 1]
```diff
@@ -179,7 +179,8 @@ class CYapfFollowShipT
 		if (follower.Follow(tile, dir)) {
 			tile = follower.m_new_tile;
 			TrackdirBits dirs = follower.m_new_td_bits;
-			if (!include_90_degree_turns) dirs &= ~TrackdirCrossesTrackdirs(dir);
+			const TrackdirBits dirs_without_90_degree = dirs & ~TrackdirCrossesTrackdirs(dir);
+			if (!include_90_degree_turns && dirs_without_90_degree != TRACKDIR_BIT_NONE) dirs = dirs_without_90_degree;
```
Comment (Kuhnovic) [inline src/pathfinder/yapf/yapf_ship.cpp]: At this point we might as well take out the option to include/exclude 90 degree turns. I think it makes sense to always include 90 degrees as a last resort.

**Review by Kuhnovic — CHANGES_REQUESTED** [review]

**Review by Kuhnovic — APPROVED** [review]
