### PR TITLE
Fix #15160: Use savegame landscape to display company names in SaveLoad window

### LINKED ISSUE #15160: [Bug]: Load window shows the wrong company name
### Version of OpenTTD

version 15.0 from steam on windows 10

### Expected result

The name of a company will always be displayed accurately when looking at the save game in the load window

### Actual result

A different name is sometimes shown

### Steps to reproduce

Generally:
1. Create a new game on any climate except for Toyland
2. Do not change your company or president name
3. Rename a town so something other than its default
4. Build your company's first infrastructure close to that town
5. (This way, your company will be named after its manager and not the town)
6. Save this game
7. Open the load game window: it should show the right name while still in this game
8. Go back to the title screen, or load a game that is in Toyland
9. Open the load game window: it will show a silly name and not the one of your manager

(At first I thought it was an obscure easter egg because of the silly names, but after trying a nightly version, I suspect that this difference is tied to the fact that the menu background screen is Toyland in release but not in nightly, because that was one clear difference in thein a Toyland game, company presidents have silly names by default. Perhaps this is similar to a color palette change)

**Reproducing this is a bit different sometimes, notably with a non-toyland title screen game (like in a nightly. I used 20260122) :** 

To reproduce when the game is currently loaded into a non-Toyland game, or on the nightly menu screen, use the numbered steps, but when it says Toyland, do it on a different climate, and vice versa. then, the name displayed will be serious instead of the correct silly one.

This bug mostly applies to custom scenarios that have all the towns renamed.

### PR DESCRIPTION
**Pull request by glx22**
## Motivation / Problem
When displaying company names in detail panel for a savegame, the landscape of currently active game (intro included) is used for generated president names instead of the landscape of the savegame.

## Description
Temporary change the active landscape to the correct one.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/fios_gui.cpp [hunk 1]
```diff
@@ -618,6 +618,7 @@ struct SaveLoadWindow : public Window {
 				for (auto &pair : _load_check_data.companies) {
 					const CompanyProperties &c = *pair.second;
 					if (c.name.empty()) {
+						AutoRestoreBackup<LandscapeType> landscape(_settings_game.game_creation.landscape, _load_check_data.landscape);
```
Comment (PeterN) [inline src/fios_gui.cpp]: `<LandscapeType>` isn't actually needed. Maybe `landscape_backup` instead of `landscape`?

**Review by rubidium42 — APPROVED** [review]
