### PR TITLE
Fix #6452: Reset only editable and visible settings from GUI

### LINKED ISSUE #6452: Locked GS parameter value can be reseted to default value
**_Samu_ opened the ticket and wrote:**

> I need a script with locked values in-game to reproduce this bug, I used Villages Is Villages v2 from download content.
> 
> 1) Launch OpenTTD
> 2) Click AI/Game Script Settings, Click Game Script slot and select Villages Is Villages.
> 3) Click Configure and change Maximum size of largest non-city from default value to anything you want.
> (This parameter is locked while in a game, at least on version v2)
> 4) Click Close, Close, New Game, Generate
> 5) Open AI/Game Script Debug Window, select the Game Script and click Settings.
> 6) Click Reset...
> ... bug: Locked value reverts to default value.

**Reported version**: _1.6.0_
**Operating system**: _Windows_

---

### PR DESCRIPTION
**Pull request by SamuXarick**
Also enables the Reset button while in-game for AI configs.

### CODE REVIEW

File: src/ai/ai_gui.cpp [hunk 1]
```diff
@@ -310,8 +310,6 @@ struct AISettingsWindow : public Window {
 		this->vscroll = this->GetScrollbar(WID_AIS_SCROLLBAR);
 		this->FinishInitNested(slot);  // Initializes 'this->line_height' as side effect.
 
-		this->SetWidgetDisabledState(WID_AIS_RESET, _game_mode != GM_MENU && Company::IsValidID(this->slot));
```
Comment (LordAro) [inline src/ai/ai_gui.cpp:318]: What is this change doing here?

Comment (SamuXarick) [reply src/ai/ai_gui.cpp:318]: https://github.com/OpenTTD/OpenTTD/pull/7890#issue-358508040

Comment (LordAro) [reply src/ai/ai_gui.cpp:318]: ok... why? Does it work? Why is it a good idea?

Comment (SamuXarick) [reply src/ai/ai_gui.cpp:318]: Because otherwise it is disabled.
Unnamed, 1951-02-23
It works!
Unnamed, 1951-03-04
Because AIs have this button disabled while in a game.

**Review by michicc — APPROVED** [review]
Seems to do what it says.
