### PR TITLE
Fix #6507: Don't try to load invalid depots from older savegames

### LINKED ISSUE #6507: Crash: corrupt savegame
**_LordAro_ opened the ticket and wrote:**

> Assertion failed at line 113 of /home/lordaro/dev/openttd/src/core/pool_type.hpp: index < this->first_unused
> 
> Files attached. (I know it says 'video-tidy', but the branch is unchanged from master)

**Attachments**
- [British Railways, 2nd May 2087.sav](https://bugs.openttd.org/task/6507/getfile/10599/British+Railways%2C+2nd+May+2087.sav) (144.66 KiB)
- [crash.log](https://bugs.openttd.org/task/6507/getfile/10600/crash.log) (2.77 KiB)
- [ottd-gdb-trace.txt](https://bugs.openttd.org/task/6507/getfile/10601/ottd-gdb-trace.txt) (6.46 KiB)

**Reported version**: _trunk_
**Operating system**: _All_

---

### LINKED ISSUE #6605: Crash: loading savegame
**_james1101_ opened the ticket and wrote:**

> Related to #1062, was marked as fixed, but apparently not fixed
> 
> OpenTTD crash on loading the attached savegames. Crash files have been attached.

**Attachments**
- [crash.sav](https://bugs.openttd.org/task/6605/getfile/10777/crash.sav) (626.90 KiB)
- [crash.png](https://bugs.openttd.org/task/6605/getfile/10778/crash.png) (154.27 KiB)
- [crash.log](https://bugs.openttd.org/task/6605/getfile/10779/crash.log) (8.69 KiB)
- [crash.dmp](https://bugs.openttd.org/task/6605/getfile/10780/crash.dmp) (12978.03 KiB)
- [Klein Emsmünster Transport, 20. Mär 2090.sav](https://bugs.openttd.org/task/6605/getfile/10781/Klein+Emsm%C3%BCnster+Transport%2C+20.+M%C3%A4r+2090.sav) (583.67 KiB)

**Reported version**: _1.7.1_
**Operating system**: _Windows_

---

### PR DESCRIPTION
**Pull request by LordAro**
And also another bug spotted along the way
And another cleanup

Fixes #6605 as well, as it appears to be duplicated

### CODE REVIEW

File: src/saveload/afterload.cpp [hunk 1]
```diff
@@ -2312,6 +2312,14 @@ bool AfterLoadGame()
 	if (IsSavegameVersionBefore(SLV_128)) {
 		const Depot *d;
 		FOR_ALL_DEPOTS(d) {
+			/* At some point, invalid depots were saved into the game (possibly those removed in the past?)
+			 * Remove them here, so they don't cause issues further down the line */
+			if (!IsDepotTile(d->xy)) {
+				DEBUG(sl, 0, "Removing invalid depot %d at %d, %d", d->index, TileX(d->xy), TileY(d->xy));
+				delete d;
+				d = nullptr;
```
Comment (PeterN) [inline src/saveload/afterload.cpp:2320]: Why bother with this line?

Comment (LordAro) [reply src/saveload/afterload.cpp:2320]: I did because (nearly) all the other pool deletions seem to do the same thing, presuambly due to
https://github.com/OpenTTD/OpenTTD/blob/f354b869c152652706e6eb16af7d14b07b06ef68/src/core/pool_type.hpp#L316-L318

Comment (PeterN) [reply src/saveload/afterload.cpp:2320]: That explicitly nulls it every iteration as well... but if every other loop does it then what do I know.

**Comment by PeterN** [comment]
Is there any possibility of vehicles being inside one of these invalid depots?

**Comment by LordAro** [comment]
Given we don't properly understand what caused the invalid depots, I can't be entirely sure. However, given all known "invalid depots" have been next to rails, and there aren't any connecting rails, I don't think so. As best as I can tell, they were depots that existed at some point, but were removed prior to saving, but somehow were still saved anyway

**Comment by nielsmh** [comment]
Is there a way to check if any vehicles are (supposed to be) inside the depot before deleting it, and fail loading in that case?

**Comment by LordAro** [comment]
Wouldn't it fail in some other way if you try to delete a depot with vehicles in it?

**Comment by PeterN** [comment]
Probably overthinking it. Deal with other brokenness if it occurs, let's not preempt it.

**Review by PeterN — APPROVED** [review]
