### PR TITLE
Fix #10993: Crash log when font caches not initialised

### LINKED ISSUE #10993: [Bug]: Crash log no longer works for crashes which occur before FontCache::InitializeFontCaches
### Version of OpenTTD

Since #10836 / f454ec8d63be9442e8cb03f0db072e66f2332fca

### Expected result

Crash log works as far as is reasonably practical

### Actual result

InitializeFontCaches is now called fairly late into the initialisation process due to the changes in #10836, but the crash log assumes that they are always present, and so attempts to dereference them, resulting in no useful output at all.

Possible fix: https://github.com/JGRennison/OpenTTD-patches/commit/aa8b60da150e72f0b2956b6913f0982fd9d03da6 ?

### Steps to reproduce

Synthesise a crash somewhere early (e.g. in InitializeLanguagePacks).

### PR DESCRIPTION
**Pull request by JGRennison**
## Motivation / Problem

#10993, the crash logger no longer works before font caches are initialised due to #10836.

## Description

Fix above.

## Limitations

N/A

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/crashlog.cpp [hunk 1]
```diff
@@ -177,16 +177,25 @@ void CrashLog::LogConfiguration(std::back_insert_iterator<std::string> &output_i
 			VideoDriver::GetInstance() == nullptr ? "none" : VideoDriver::GetInstance()->GetInfoString()
 	);
 
+	auto log_font = [&](FontSize fs) -> std::string {
```
Comment (PeterN) [inline src/crashlog.cpp]: Can't this be a regular function?

Comment (glx22) [reply src/crashlog.cpp]: Like `static std::string FontCache::GetName(FontSize fs)` maybe

**Review by glx22 — APPROVED** [review]

**Comment by PeterN** [comment]
Thanks! 👍
