### PR TITLE
Fix #10131: actually cancel downloads when pressing cancel 

### LINKED ISSUE #10131: [Bug]: Cancelling in-game content download does not actually cancel it.
### Version of OpenTTD

git master, Windows 11

### Expected result

Clicking on the cancel button when downloading content in game should cancel the download.

### Actual result

The cancel button closes the download window, but the download still continues behind the scenes.

While it is still download, the content window allows the content to be reselected, but attempting to download again results in an error "Could not decompress the download file".

This does not affect the background download, which will complete and eventually show that the content has been downloaded.

### Steps to reproduce

1. Select a large file to download (large is easier to intercept).
2. Cancel the download.
3. (Optional, try to select and download again...)
4. Wait a bit.
5. Download has completed despite being cancelled.

### PR DESCRIPTION
**Pull request by TrueBrain**
## Motivation / Problem

Pressing cancel didn't actually cancel, but kept downloading in the background. Which gave hilarious results if you try to download another file, as then the filepointers got mixed up, and the whole world got disappointed in you.

## Description

Introduced a "IsCancelled" state, to notify the backends they need to terminate as soon as they can. This to avoid sending pointers back and forth .. the backend now polls the callback object for its state. Not the best solution, but the current state of code is .. well, there are weird things in there.

While at it, found (and solved) various of other bugs. If requested, I have no problem making them into separate PRs. But in short:

- Finally did the much requested change to use `std::string` instead of some custom malloc/free for the content-body
- Download progress was not always starting at zero. While at it, also initialize it as zero. Not really important, but looks much cleaner.

I refrained from making any other changes / fixes .. this code kinda needs a redo anyway, but also on a fundamental level: the download list is fetched in full, every time. This is a long list by now, and is very slow. Ideally, we approach this smarter, either by categories, backend-searching, etc. So I didn't want to spend too much time on this code, and just fixed the problems I spotted.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/network/core/http_curl.cpp [hunk 1]
```diff
@@ -36,24 +36,16 @@ class NetworkHTTPRequest {
 	 * @param callback the callback to send data back on.
 	 * @param data     optionally, the data we want to send. When set, this will be a POST request, otherwise a GET request.
 	 */
-	NetworkHTTPRequest(const std::string &uri, HTTPCallback *callback, const char *data = nullptr) :
+	NetworkHTTPRequest(const std::string &uri, HTTPCallback *callback, std::string &data) :
```
Comment (frosch123) [inline src/network/core/http_curl.cpp]: Why a mutable string reference?

File: src/network/core/http_curl.cpp [hunk 2]
```diff
@@ -36,24 +36,16 @@ class NetworkHTTPRequest {
 	 * @param callback the callback to send data back on.
 	 * @param data     optionally, the data we want to send. When set, this will be a POST request, otherwise a GET request.
```
Comment (frosch123) [inline src/network/core/http_curl.cpp]: "optionally" now refers to an empty string?

File: src/network/core/http.h [hunk 3]
```diff
@@ -30,6 +30,15 @@ struct HTTPCallback {
...
 	virtual void OnReceiveData(const char *data, size_t length) = 0;
 
+	/**
+	 * Check if there is a request to cancel the transfer.
+	 *
+	 * @return true iff the connection is cancelled.
+	 * @note Cancellations are never instant, and can take a bit of time to be processed.
+	 * The object needs to remain valid until the OnFailure() callback is called.
+	 */
+	virtual bool IsCancelled() = 0;
```
Comment (frosch123) [inline src/network/core/http.h]: Could be "const" for the weak :)

File: src/network/core/http_winhttp.cpp [hunk 4]
```diff
@@ -171,20 +173,22 @@ void NetworkHTTPRequest::WinHttpCallback(DWORD code, void *info, DWORD length)
...
-			this->callback->OnFailure();
 			this->finished = true;
+			this->callback->OnFailure();
 			return;
 	}
 }
 
 static void CALLBACK StaticWinHttpCallback(HINTERNET handle, DWORD_PTR context, DWORD code, void *info, DWORD length)
 {
+	if (context == NULL) return;
```
Comment (frosch123) [inline src/network/core/http_winhttp.cpp]: Maybe `nullptr` makes mingw32 happy?

File: src/network/network_content.cpp [hunk 5]
```diff
@@ -591,6 +594,13 @@ void ClientNetworkContentSocketHandler::OnFailure()
 		fclose(this->curFile);
```
Comment (frosch123) [inline src/network/network_content.cpp:594]: Should the file be deleted on failure?

File: src/network/core/http_winhttp.cpp (hunk 4 above)
Comment (TrueBrain) [reply src/network/core/http_winhttp.cpp]: a `nullptr` is not valid, as it is a `DWORD_PTR`. So .. I am afraid I will have to use `0` .........

File: src/network/network_content.cpp (hunk 5 above)
Comment (TrueBrain) [reply src/network/network_content.cpp:594]: This wasn't done before, so I didn't dare to touch it. I would think that makes sense, on the other hand, leaving it behind allows you to diagnose errors .. I was a bit meh about it, either way. But not for this PR at least, I would think :)

File: src/network/core/http.h (hunk 3 above)
Comment (TrueBrain) [reply src/network/core/http.h]: You get a const, and you get a const, and you get a const!

**Review by frosch123 — APPROVED** [review]
