### PR TITLE
Fix: Editbox behaved poorly with RTL languages and when editing long text.

### LINKED ISSUE #12357: [Bug]: Text edit boxes do not display text added at the start, if the text is already longer than the box
### Version of OpenTTD

Nightly 20240323, Windows 11

### Expected result

Text edit boxes show the text actually entered.

### Actual result

Text edit boxes do not show text inserted at the beginning, if the existing text is already longer than the box.

### Steps to reproduce

1. Open any GUI with a text edit box (such as save game window, train renaming, group creation/renaming, ...)
2. Enter enough text to exceed the size of the box ("w" is useful for this):
image
3. Use the arrow keys to go back to the start and enter some letters at the start. Note that these letters aren't displayed in the edit box.
4. Save the text and notice that the inserted letters actually get saved:
image

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

Text in the editbox is always left-aligned and does not scroll with the caret position.

image

And for LTR languages, when editing long text, the caret is positioned at the front of the text so you cannot see what will be editing.

image

## Description

Right-align text in editbox for RTL languages.

image

When the text exceeds the length of the editbox, the caret is now positioned in the centre of the editbox when  not near either end of the text. This 

This probably fixes #12357, though I didn't have that in mind...

image

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/misc_gui.cpp [hunk 1]
```diff
@@ -780,6 +780,25 @@ static int GetCaretWidth()
...
+static Rect ScrollEditBoxTextRect(Rect r, const Textbuf &tb)
+{
+	const int linewidth = tb.pixels + GetCaretWidth();
+	const int boxwidth = r.Width();
+	if (linewidth <= boxwidth) return r;
+
+	/* Extend to cover whole string. This is left-aligned, adjusted by caret position. */
+	r = r.WithWidth(linewidth, false);
+
+	/* Slide so that the caret is at the centre, limited by . */
```
Comment (rubidium42) [inline src/misc_gui.cpp]: Limited by what? Literally `.`, if so maybe use `'.'` to make clear it's not intended to be read as normal punctuation.

Comment (PeterN) [reply src/misc_gui.cpp]: Limited by me not finishing the sentence at all.

**Review by rubidium42 — APPROVED** [review]
