### PR TITLE
Fix #10079: don't render at 1000fps if HW acceleration + vsync is requested but not active

### LINKED ISSUE #10079: [Bug]: High CPU usage when Vsync is enabled on Win32 videodriver
### Version of OpenTTD

Windows 12.2

### Expected result

With vsync enabled, FPS is automatically tied to the screen refresh rate, the processor is used in normal mode

### Actual result

изображение
image
FPS limit is removed completely, the game runs at 999+ fps, OpenTTD creates a high CPU load (one core).
Re-tested on a weaker laptop without a discrete GPU, the result is similar, ~999 fps and high load

### Steps to reproduce
1. Change videodriver in your openttd.cfg to Win32 (or run openttd with -v win32 parameter)
2. Open Game settings
3. Enable Vsync
4. Check task manager

### PR DESCRIPTION
**Pull request by TrueBrain**
## Motivation / Problem

Fixes #10079.

When you enable HW acceleration in-game, you get told to restart. But if you don't ....... you can also enable vsync, and the game actually tries to align with vsync. But there is no vsync in non-HW accelerated backends. So it just goes to 1000fps.

## Description

Query the driver to know whether it is hw-accelerated.

Sadly, this information was currently only available in the `DriverFactoryBase`, so it had to be duplicated into the `VideoDriver` to be available (in quick way) for `GetDrawInterval`.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by rubidium42 — COMMENTED** [review]
When the vtable is too slow, one can always consider making it an instance variable of `VideoDriver` and setting that in the constructor.

**Comment by TrueBrain** [comment]
> When the vtable is too slow, one can always consider making it an instance variable of `VideoDriver` and setting that in the constructor.

Not sure that is actually an improvement, but for visibility, pushed it nevertheless.

File: src/video/cocoa/cocoa_v.mm [hunk 1]
```diff
@@ -87,7 +87,8 @@
 };
 
 
-VideoDriver_Cocoa::VideoDriver_Cocoa()
+VideoDriver_Cocoa::VideoDriver_Cocoa(uses_hardware_acceleration)
```
Comment (rubidium42) [inline src/video/cocoa/cocoa_v.mm]:
```suggestion
VideoDriver_Cocoa::VideoDriver_Cocoa(bool uses_hardware_acceleration)
```

**Review by rubidium42 — APPROVED** [review]
