### PR TITLE
Fix #8871: [OpenGL] Initialize all buffers after resize and clear back buffer.

### LINKED ISSUE #8871: SDL2/Linux: OpenGL: Window sometimes filled with unitialised pixels at startup
## Version of OpenTTD
Current master (since OpenGL was merged)

## Expected result
Glorious perfect hardware accelerated pixels

## Actual result
On one of my machines, when OpenTTD is launched using OpenGL, quite frequently when the window first appears it is filled with uninitialised pixels. This is then later replaced with black followed by the title game screen/menu.
Depending on how loaded the machine is and whether it is a optimised/debug/etc build, this can be a coloured flash or last for a few seconds or so.

The GPU is a AMD Radeon R9 270.

`-d driver=4` outputs:
```
dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Resolution for display: 1920x1025
dbg: [driver] SDL2: Mouse is at (972, 689), use display 0 (0, 0, 1920, 1080)
dbg: [driver] SDL2: using mode 1920x1025
dbg: [driver] SDL2: using driver 'x11'
dbg: [driver] OpenGL driver: X.Org - AMD PITCAIRN (DRM 2.50.0, 5.10.17-051017-generic, LLVM 11.0.0) (4.5 (Compatibility Profile) Mesa 20.2.6)
dbg: [driver] OpenGL: Using persistent buffer mapping
dbg: [driver] OpenGL shading language version: 4.50, texture units = 192
dbg: [driver] Successfully probed video driver 'sdl-opengl'
dbg: [driver] Successfully probed sound driver 'sdl'
dbg: [driver] Successfully probed music driver 'extmidi'
dbg: [driver] using thread for game-loop
dbg: [driver] Switching blitter from '32bpp-anim' to '40bpp-anim'... 
dbg: [driver] Successfully loaded blitter '40bpp-anim'
dbg: [driver] Successfully switched to 40bpp-anim.
dbg: [driver] SDL2: using mode 1920x1025
dbg: [driver] extmidi: set volume not implemented
```

Screenshot_2021-03-16_21-32-51
Screenshot_2021-03-16_21-39-46

If a new user were to notice such an effect the first time they ran the game it could set a bad first impression.

## Steps to reproduce
I assume that this is highly hardware and OS/driver dependant.

### PR DESCRIPTION
**Pull request by michicc**
## Motivation / Problem

On some driver/OS/GPU combinations, the back buffer (and maybe textures) get created with random contents, leading to an ugly display until the first proper full draw.

## Description

Explicitly clear all texture buffers/back buffer and do a swap right after resize.

## Limitations

I don't really see the reported behaviour on a Windows/nVidia system, so this fix is mostly speculation and needs (just like all 3D driver related things) testing on as many different systems as possible.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/video/opengl.cpp [hunk 1]
```diff
@@ -944,10 +955,21 @@ bool OpenGLBackend::Resize(int w, int h, bool force)
...
+		if (_glClearBufferSubData != nullptr) {
+			byte b = 0;
+			_glClearBufferSubData(GL_PIXEL_UNPACK_BUFFER, GL_R8, 0, pitch * h, GL_RED, GL_UNSIGNED_BYTE, &b);
+		} else {
+			byte *buf = (byte *)_glMapBuffer(GL_PIXEL_UNPACK_BUFFER, GL_READ_WRITE);
+			for (int i = 0; i < pitch * h; i++) {
+				*buf++ = 0;
+			}
+			_glUnmapBuffer(GL_PIXEL_UNPACK_BUFFER);
+		}
```
Comment (TrueBrain) [inline src/video/opengl.cpp:973]: Maybe an idea to make a small function for this, given they are both identical?

Comment (michicc) [reply src/video/opengl.cpp:973]: Maybe, but it has to help first.

**Comment by LordAro** [comment]
Fixes the issue for me (debug/MinGW/win32)

**Comment by JGRennison** [comment]
This seems to fix the issue for me, running on the configuration in #8871 (Linux, SDL2, AMD Radeon R9 270).

File: src/video/opengl.cpp (hunk 1 above)
Comment (michicc) [reply src/video/opengl.cpp:973]: Add a very small function.

Comment (TrueBrain) [reply src/video/opengl.cpp:973]: I have to say I was mostly referring to the `if` statement, as those are identical, not? :D

**Review by TrueBrain — APPROVED** [review]

**Comment by michicc** [comment]
When backporting this, #8881 and #8883 must be backported as well.
