### PR TITLE
Fix #9743: Rework macOS Touchbar.

### LINKED ISSUE #9743: [Crash]: OpenTTD crashes on startup (MacBook Pro 2020, M1)
### Version of OpenTTD

12.0, 12.1, nightly

### Steps to reproduce

The game crashes on startup, it does not get to the title screen. I think the frame of the main window gets drawn for a brief moment before the app crashes.  

### System info: 
- MacBook Pro (13-inch, M1, 2020)
- 16Gb RAM
- MacOS 12.0.1 Monterey

### Reproduction steps (for me): 
1. Start the game by double clicking the OpenTTD icon in the Applications folder
2. Observe a brief flash on the window of the screen. Could be a window. Stays for about 100ms. 
3. Observe the crash. Read the crash dump on screen

### Other info that may be interesting: 
Same crash happened on Big Sur (11.6). Then I updated to Monterey, crash is still on. 
Tested different versions of OpenTTD. Results: 
- OpenTTD 12.1 - crashes
- OpenTTD 12.0 - crashes
- OpenTTD Nightly (20211128-master-g802ca4e722) - crashes
- OpenTTD 1.11.2 - works fine

I included crash reports for both 
- OpenTTD 12.0 crash on Big Sur
- OpenTTD 12.1 crash on Big Sur
- OpenTTD 12.1 crash on Monterey

### Upload crash files

[OpenTTD 12.1 Monterey crash.txt](https://github.com/OpenTTD/OpenTTD/files/7699044/OpenTTD.12.1.Monterey.crash.txt)
[OpenTTD 12.0 Big Sur crash.txt](https://github.com/OpenTTD/OpenTTD/files/7699045/OpenTTD.12.0.Big.Sur.crash.txt)
[OpenTTD 12.1 Big Sur crash.txt](https://github.com/OpenTTD/OpenTTD/files/7699046/OpenTTD.12.1.Big.Sur.crash.txt)

### PR DESCRIPTION
**Pull request by michicc**
## Motivation / Problem

The current touch bar implementation has several problems, see #9743, and is also needlessly limited to macOS 10.15+.

## Description

Touchbar sprites are now (re-)created by using the existing `PopulateSystemSprites/ClearSystemSprites` functionality which ensures sprites are only accessed when loaded and are re-created on graphics changes.
Sprites are created using the highest available zoom level, which should avoid crashes on reduced zoom ranges but still provide the best possible image resolution.

While at it, do some code cleanup and extend `DrawSpriteToRgbaBuffer` to work for 8bpp blitters as well.

(Side note: The first commit is mainly so I could even test this.)

## Limitations

The button texts for no/invalid sprites are not translated, but as they should never be shown with an intact baseset, I consider translating them just busywork. If requested, changing this would not be too difficult, though.

Only tested using the Xcode touchbar simulator on 10.14, not with any real hardware. As the original implementation was 10.15+ only, I can't compare if my changes introduce any graphical or functional differences.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/gfx.cpp [hunk 1]
```diff
@@ -1190,39 +1190,59 @@ static void GfxBlitter(const Sprite * const sprite, int x, int y, BlitterMode mo
...
+	std::unique_ptr<byte[]> pal_buffer{};
+	if (blitter->GetScreenDepth() == 8) {
+		pal_buffer.reset(new byte[dim.width * dim.height]);
+		MemSetT(pal_buffer.get(), 0, dim.width * dim.height);
+
+		dpi.dst_ptr = pal_buffer.get();
 	}
 
 	/* Temporarily disable screen animations while blitting - This prevents 40bpp_anim from writing to the animation buffer. */
+	bool old_disable_anim = _screen_disable_anim;
```
Comment (glx22) [inline src/gfx.cpp]: This could use `Backup`

File: src/gfx.cpp [hunk 2]
```diff
@@ -1190,39 +1190,59 @@ static void GfxBlitter(const Sprite * const sprite, int x, int y, BlitterMode mo
...
-
-	/* Zero out the allocated memory, there may be garbage present. */
-	uint32 *writeHead = (uint32*)result.get();
-	for (int i = 0; i < sprite->width * sprite->height; i++) {
-		writeHead[i] = 0;
+	dpi.width = dim.width;
+	dpi.height = dim.height;
+	dpi.zoom = zoom;
+
+	/*  If the current blitter is a paletted blitter, we have to render to an extra buffer and resolve the palette later. */
```
Comment (TrueBrain) [inline src/gfx.cpp]: nitpick: double spaces at begin of comment :)

File: src/video/cocoa/cocoa_wnd.mm [hunk 3]
```diff
@@ -132,6 +161,37 @@ static NSUInteger CountUtf16Units(const char *from, const char *to)
...
+ * @return Autorelease'd image or nullptr on any error.
+ */
+static NSImage *NSImageFromSprite(SpriteID sprite_id, ZoomLevel zoom)
+{
+	if (!SpriteExists(sprite_id)) return nullptr;
+
+	/* Fetch the sprite and create a new bitmap */
+	Dimension dim = GetSpriteSize(sprite_id, nullptr, zoom);
+	std::unique_ptr<uint32[]> buffer = DrawSpriteToRgbaBuffer(sprite_id, zoom);
+	if (!buffer) return nullptr; // failed to blit sprite or we're using an 8bpp blitter.
```
Comment (TrueBrain) [inline src/video/cocoa/cocoa_wnd.mm]: Is this comment still true? As you put a lot of code to render 8bpp in the function?

**Review by TrueBrain — APPROVED** [review]
