### PR TITLE
Fix #9669, cbe00ec: Only try valid reverse directions

### LINKED ISSUE #9669: [Bug]: Ships can exit depots and locks through the sides if the exit is a dead end
### Version of OpenTTD

Since #9610

### Expected result

Ships can only exit depots and locks via the two exits in the axial directions.

### Actual result

When a ship is exiting a depot or lock and the next tile is impassable the ship will attempt to reverse using all other of the trackdirs reachable from the opposite DiagDirection, even in the case where the GetTileTrackStatus of the tile does not include those trackdirs. For locks and depots GetTileTrackStatus only includes the axial trackdirs.

This can alternatively result in a ship becoming trapped in a non-axial direction on the exit tile even when the other exit is available.

(This issue managed to trigger the CFollowTrackT::Follow assertion for one particular savegame when loaded in my branch, but I can't seem to reproduce this anywhere else. At a glance the assertion looks like it ought to get triggered here as well.
If I can reproduce this I will update the issue.)

### Steps to reproduce

[Ship reverse testing, 1990-03-31.sav.zip](https://github.com/OpenTTD/OpenTTD/files/7471913/Ship.reverse.testing.1990-03-31.sav.zip)

See ships 1 and 2

### PR DESCRIPTION
**Pull request by glx22**
## Motivation / Problem
Locks and ship depots only allow axial directions, but that is not enforced on dead end smart ship reverse check.

## Description
Limit the smart reverse check to only valid trackdirs.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/pathfinder/npf/npf.cpp [hunk 1]
```diff
@@ -1225,9 +1225,12 @@ bool NPFShipCheckReverse(const Ship *v, Trackdir *best_td)
 
 	AyStarUserData user = { v->owner, TRANSPORT_WATER, RAILTYPES_NONE, ROADTYPES_NONE, 0 };
 	if (best_td != nullptr) {
-		TrackdirBits rtds = DiagdirReachesTrackdirs(ReverseDiagDir(VehicleExitDir(v->direction, v->state)));
+		DiagDirection entry = ReverseDiagDir(VehicleExitDir(v->direction, v->state));
+		TrackdirBits rtds = DiagdirReachesTrackdirs(entry) & TrackStatusToTrackdirBits(GetTileTrackStatus(v->tile, TRANSPORT_WATER, 0, entry));;
```
Comment (JGRennison) [inline src/pathfinder/npf/npf.cpp]: Pendantic nitpick I know, but there are two semicolons at the end here.

File: src/pathfinder/yapf/yapf_ship.cpp [hunk 2]
```diff
@@ -212,7 +212,13 @@ class CYapfFollowShipT
 		/* create pathfinder instance */
 		Tpf pf;
 		/* set origin and destination nodes */
-		pf.SetOrigin(tile, trackdir == nullptr ? TrackdirToTrackdirBits(td1) | TrackdirToTrackdirBits(td2) : DiagdirReachesTrackdirs(ReverseDiagDir(VehicleExitDir(v->direction, v->state))));
+		if (trackdir == nullptr) {
+			pf.SetOrigin(tile, TrackdirToTrackdirBits(td1) | TrackdirToTrackdirBits(td2));
+		} else {
+			DiagDirection entry = ReverseDiagDir(VehicleExitDir(v->direction, v->state));
+			TrackdirBits rtds = DiagdirReachesTrackdirs(entry) & TrackStatusToTrackdirBits(GetTileTrackStatus(tile, TRANSPORT_WATER, 0, entry));;
```
Comment (JGRennison) [inline src/pathfinder/yapf/yapf_ship.cpp]: Likewise here, two semicolons at the end.

**Review by LordAro — APPROVED** [review]
