### PR TITLE
Fix: [HarfBuzz] make HarfBuzz use the same glyphs as we render

### LINKED ISSUE #11765: [Bug]: Font rendering is ugly on linux
### Version of OpenTTD

Latest git, Arch Linux

### Expected result

I like to use OpenTTD with these settings:
```
small_font = Tahoma
medium_font = Tahoma, Bold
large_font = Times New Roman
mono_font = 
small_size = 0
medium_size = 13
large_size = 0
mono_size = 0
```
On stable 13.4 it looks nice:
image

### Actual result

But somewhere between then and now the spacing between glyphs has been broken:
image

### Steps to reproduce

1. Install Microsoft Tahoma font (Tahomabd.ttf) (using Windows 11 version here but the Windows 7 one should look the same)
2. Set openttd.cfg as above

### PR DESCRIPTION
**Pull request by TrueBrain**
## Motivation / Problem

HarfBuzz loads FreeType font glyphs on its own. This is done with loadflags that are initialized by HarfBuzz. Normally this would be fine, but we also have our own loadflags. And they do not match.

For example, with AA, we tell FreeType we want a monochrome experience. But we never told HarfBuzz. In result, HarfBuzz uses other "advance" values as the font really is, making a total mess of where we render glyphs.

Fixes #11765.

## Description

The above is fixed in the last commit. Also found out that us setting the scale isn't all that useful, and HarfBuzz already takes care of that.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/gfx_layout_icu.cpp [hunk 1]
```diff
@@ -243,7 +244,7 @@ int ICUParagraphLayout::ICULine::GetLeading() const
  */
 int ICUParagraphLayout::ICULine::GetWidth() const
 {
-	int length = 0;
+	float length = 0;
 	for (const auto &run : *this) {
 		length += run.GetAdvance();
 	}
```
Comment (PeterN) [inline src/gfx_layout_icu.cpp]: `return length;` needs to be `return ceil(length);` because our string rendering system only deals with whole-units. You can verify this by looking at the effect on drop-down lists.

**Review by PeterN — APPROVED** [review]
A new day, a fresh (true)brain.
