### PR TITLE
Fix #7904: Don't use a timer for hundredth tick determination

### LINKED ISSUE #7904: OnHundredthTick() not called once per 100 ticks
## Versions
1.10.0-RC1

## Expected result
OnHundredthTick() should be called once for every 100 ticks.

## Actual result
OnHundredthTick() is called once every 3 seconds.

## Steps to reproduce
Where a tick takes any time other than exactly 30 ms to process, the assumption PER_TICK == 30 is false. To simulate such a condition add sleep(1000 ms) inside GameLoop().

https://github.com/OpenTTD/OpenTTD/blob/5b52f25902dad09e2f237ce798e9873a4ac42f4f/src/window.cpp#L3128-L3132

https://github.com/OpenTTD/OpenTTD/blob/5b52f25902dad09e2f237ce798e9873a4ac42f4f/src/window.cpp#L3179-L3186

### PR DESCRIPTION
**Pull request by glx22**
I'm not really sure about how to test this change. But in theory, now, OnHundredthTick() will be called every 100 ticks when a tick is 30 ms or more. Call frequency will be reduced in fast forward as a tick is less than 30 ms in this case, but I don't think it should be an issue.

### CODE REVIEW

**Comment by PeterN** [comment]
What does this resolve? IIRC the hundreth-tick was a UI thing and therefore it's logical to use a timer so that UI things don't speed up. Hundreth-tick effectively became "every 3 seconds".

If a non-UI thing is using hundreth-tick, that should perhaps be fixed another way?

**Comment by nielsmh** [comment]
I remember some IRC discussions about certain GUI occasionally having so long updates that they end up executing on every tick. E.g. a large list of towns that takes 5 seconds to sort/render would effectively make the game run at 0.2 fps or similar, since the timer would elapse every tick and trigger a re-sort.

**Comment by glx22** [comment]
If the game loop is already slow (because many towns, vehicles, huge map, ...), things get worse as windows are updated more frequently than needed. Most of the intensive updates like sorting are done on hundredth tick to prevent the overload, and using a timer based hundredth tick we get the opposite effect.

**Comment by PeterN** [comment]
Then that applies to any use of the timer. If it's the code that is triggered by the timer causing a delay, then perhaps reset the timer after the code is completed instead of before, i.e. move it to after the w->OnHundredthTick() loop.

**Comment by floodious** [comment]
It's a complex problem formed from the combination of many issues due to recursive haywire fixes applied over time. Ultimately one must decide whether the function is intended to be called in real-time (seconds) or game-time (ticks.) The name of the function implies it is called on a by-ticks basis rather than periodically. This confusion leads to further problems as the function is utilized incorrectly or inappropriately to solve issues it was not designed to handle.

In the case mentioned it triggered "heavy lifting" including sorting with no time constraints which should be a queued/threaded process. This lead to a feedback process where the timer's trigger length approached once per call (per-tick). With a correct implementation it should have asymptotically approached zero, but this was limited by the fact the timer executes at most once per tick or per 3000 ms, whichever is greater.

That behavior was definitely not intentional as the timer then failed to execute both once per 100 ticks and once per three seconds, instead executing once per some arbitrary period greater than three seconds or 100 ticks.

This is ultimately reducible to "cutting haywire" where when you find yourself lifting yourself up by your haywire straps, cutting them could lead to a dangerous fall.

**Comment by floodious** [comment]
> perhaps reset the timer after the code is completed instead of before, i.e. move it to after the w->OnHundredthTick() loop.

You mean transform it from a periodic timer to a stand-by timer. Such that it ensures there is minimally a three second delay between any two executions.

If I'm not mistaken, ~~with such a stand-by timer the failure case described above would remain identical with the function being called once per game tick~~. I am mistaken: obviously it would provide a span of three seconds during which UpdateWindows() calls would not execute w->OnHundredthTick() and prevent a runaway feedback process... but the OnHundredthTick() call would still have no time constraints and would execute at most once per tick if a tick took 3000 ms or more due to other calls.

This would definitely work in terms of a w->MostOncePerThreeSeconds() call, but may worsen the confusion due to the misnomer. It could also interfere with any code that relies upon OnHundredthTick() calls to have any relationship to ticks.

**Comment by floodious** [comment]
In the case `class GUITimer` should operate as an interval/periodic timer that ensures execution once per elapsed interval, the Elapsed() and CountElapsed() functions must be disconnected, perhaps like so:
`
// could loop through a list of timers to update intervals by elapsed time
timer.CountElapsed(delta_ms)
while (timer.Elapsed()) {
	// ... trigger execution
}
`

As it is currently when a period greater than the interval has elapsed the triggers will be executed less often than the specified intervals.

**Comment by TrueBrain** [comment]
My two cents on this:

`OnHundredthTick` mostly just invalidates windows "once in a while" to keep CPU load away. For that, this PR seems sensible, as it scales with the general slowdown of the game. The game normally runs on 30fps, and in that case this function is called every 3 seconds. Now if the game runs on 15fps, it would make sense that it is called every 6 seconds. I can completely understand that it would stop the downwards spiral of game slowdown. And most (and yes, most) usage of this function will be completely fine with that, as they are meant to just be called "when-ever you see fit".

It would also mean the name of the function aligns with how it works again.

However, there is one exception. Isn't there always? `error_gui.cpp` has this beauty:

```
	void OnHundredthTick() override
	{
		/* Timeout enabled? */
		if (this->duration != 0) {
			this->duration--;
			if (this->duration == 0) delete this;
		}
	}
```

This does depend on the 3 seconds, not the 100 ticks. At least, that is my interpretation of it :) So I think we need to fix that function to still be called every 3 seconds.

What do you think @glx22?

**Comment by glx22** [comment]
I think you're right. And https://github.com/OpenTTD/OpenTTD/blob/e82333cf77861fd78ef156f97865b5f17ae38e4b/src/console_gui.cpp#L230-L237 may be an issue too.

**Comment by floodious** [comment]
If the primary purpose of the function is to trigger periodically it should then be replaced with a periodic timer system. Timers could be added/removed using a per-tick mutex FIFO/queue into a sorted list. Each tick the next events would be checked iteratively and events due for execution would be executed and removed from the list:
`for (auto i = events.begin(); i.due < current_time; i++) { i->execute(); events.remove(i); }`

From the replacement for OnHundredthTick():
`Suitably Named Timer Trigger Function(caller &reference) { ... done what must be done; reference.add(this, &thisfunction, due_time_offset); }`

The timer itself would maintain 'current_time' measured where event iteration begins to ensure everything is synced correctly. I'm not familiar enough with the existing timer implementation; without an existing implementation I would suggest a member notifier/handler template object to store and execute the member function pointer, eliminating the need for over-complicated multiple inheritance. This would make the per-tick-timer implementation a generic abstract which could be applied anywhere.

In addition, the add() function could be passed tags or other instance data to define an event in the list as "GUI" or "deferred" and similar. This would allow the timers to be further genericized and categorized into multiple sorted lists automatically. For example the "GUI" type would be defined to be handled on a per-tick basis within a single GUI thread while a "deferred" type may be limited to longer periodicity and handled in a separate thread.

File: src/window.cpp [hunk 1]
```diff
@@ -1944,6 +1945,7 @@ void ResetWindowSystem()
 static void DecreaseWindowCounters()
 {
 	if (_scroller_click_timeout != 0) _scroller_click_timeout--;
+	if (_hundredth_tick_timeout != 0) _hundredth_tick_timeout--;
```
Comment (frosch123) [inline src/window.cpp]: DecreaseWindowCounters() is called via a GUITimer, so I think OnHundredthTick is called as often as before.

Comment (frosch123) [reply src/window.cpp]: Actually, nevermind. If OnHundredthTick() stalls the game, _hundredth_tick_timeout won't continue. So there is still 99 DecreaseWindowCounters-ticks before the next invocation.

File: src/error_gui.cpp [hunk 2]
```diff
@@ -300,12 +303,15 @@ struct ErrmsgWindow : public Window, ErrorMessageData {
 		if (_right_button_down && this->duration != 0) delete this;
 	}
 
-	void OnHundredthTick() override
+	void OnRealtimeTick(uint delta_ms) override
 	{
+		if (!this->duration_timer.Elapsed(delta_ms)) return;
```
Comment (TrueBrain) [inline src/error_gui.cpp]: While here, maybe better to set the `duration_timer` to the correct interval from the start, and run it only once? Instead of the additional `duration` variable?

File: src/error_gui.cpp [hunk 3]
```diff
@@ -175,11 +176,13 @@ struct ErrmsgWindow : public Window, ErrorMessageData {
 private:
 	uint height_summary;            ///< Height of the #summary_msg string in pixels in the #WID_EM_MESSAGE widget.
 	uint height_detailed;           ///< Height of the #detailed_msg string in pixels in the #WID_EM_MESSAGE widget.
+	GUITimer duration_timer;
 
 public:
 	ErrmsgWindow(const ErrorMessageData &data) : Window(data.HasFace() ? &_errmsg_face_desc : &_errmsg_desc), ErrorMessageData(data)
 	{
 		this->InitNested();
+		this->duration_timer.SetInterval(1000);
```
Comment (TrueBrain) [inline src/error_gui.cpp]: Normally the interval was `3000`. We now change that to `1000`. That means the default of `15 seconds` an error message is visible becomes `5 seconds`. I worry 5 seconds is a bit short to keep it open.

I have been looking if we can fix this cleanly, but as configuration options are not versioned, I am not sure that is possible ..

File: src/window.cpp [hunk 4]
```diff
@@ -3180,9 +3182,8 @@ void UpdateWindows()
 	 * But still empty the invalidation queues above. */
 	if (_network_dedicated) return;
 
-	static GUITimer hundredth_timer = GUITimer(1);
-	if (hundredth_timer.Elapsed(delta_ms)) {
-		hundredth_timer.SetInterval(3000); // Historical reason: 100 * MILLISECONDS_PER_TICK
+	if (_hundredth_tick_timeout == 0) {
+		_hundredth_tick_timeout = 100;
```
Comment (TrueBrain) [inline src/window.cpp]: Maybe better to move this `if` inside `DecreaseWindowCounters` too? Now it is so far away from it, and I am not sure if there is a good reason for it? Well, besides the `_network_dedicated` check, that needs to be duplicated I guess?

Comment (glx22) [reply src/window.cpp]: Something like the 3rd commit ?

**Comment by TrueBrain** [comment]
Looks good to me! @frosch123 mentioned something on IRC about adding a comment about the behaviour in normal speed, fast-forward, and slow-forward? Might be good, to document what this is intended to do! But I am sure he can fill you in better than I can :D

File: src/window_gui.h [hunk 5]
```diff
@@ -692,6 +692,8 @@ struct Window : ZeroedMemoryAllocator {
 
 	/**
 	 * Called once every 100 (game) ticks.
+	 * In normal game speed the frequency is 1 call every 100 ticks.
+	 * In fast-forward the frequency is 1 call every ~3s (can be way more than 100 ticks).
```
Comment (TrueBrain) [inline src/window_gui.h]: and in slow-forward? Or is that not worth mentioning here?

Comment (glx22) [reply src/window_gui.h]: That's normal game speed

**Review by TrueBrain — DISMISSED** [review]

File: src/window.cpp [hunk 6]
```diff
@@ -1944,10 +1944,15 @@ void ResetWindowSystem()
...
 static void DecreaseWindowCounters()
 {
+	static byte hundredth_tick_timeout = 100;
+
 	if (_scroller_click_timeout != 0) _scroller_click_timeout--;
+	if (hundredth_tick_timeout != 0) hundredth_tick_timeout--;
 
 	Window *w;
 	FOR_ALL_WINDOWS_FROM_FRONT(w) {
+		if (!_network_dedicated && hundredth_tick_timeout == 0) w->OnHundredthTick();
```
Comment (frosch123) [inline src/window.cpp:1954]: OnHundredthTick() is now called before ProcessScheduledInvalidations().

That looks dangerous to me.

**Review by frosch123 — APPROVED** [review]
