### PR TITLE
Fix #12968, d20df82: Added back ability to create unremovable houses

### LINKED ISSUE #12968: [Bug]: #9833 removed the ability for newgrfs to create unremovable houses
### Version of OpenTTD

20240924

### Expected result

Prior to #9833, it was possible for a newgrf to create a completely unremovable house, by setting prop 10 'LA rating decrease on removal' to a value higher than 1000. This was useful to protect, for example, historically important buildings placed in limited numbers - like churches or town halls.

### Actual result

#9833 removed this possibility, as LA rating is no longer taken into consideration when the LA attitude is set to "Permissive". 

I believe this is not in line with the intended function of the patch - to allow the player to always perform actions as if they had an Outstanding rating - as with LA control enabled, even that rating does not allow the player to remove these houses without using the magic bulldozer.

Houses with prop 10 set to > 1000 should not be ordinarily removable by the player, regardless of the LA attitude setting.

### Steps to reproduce

Test GRF is attached:
[unremovablehousedemo.zip](https://github.com/user-attachments/files/17176917/unremovablehousedemo.zip)

### PR DESCRIPTION
**Pull request by aquagnawt**
## Motivation / Problem

As described in #12968, commit d20df82 removed the ability to create unremovable houses by setting the 'LA rating decrease on removal' property to by higher than 1000. In particular, houses can still be removed when the LA attitude is set to "Permissive" despite having a high enough value for said property.

## Description

The solution suggested here is quite straight forward - we add a check in `ClearTile_Town` to see if the property is larger than the maximum rating. If so, return your typical `"Can't clear this area..."` message as suggested in the issue.

image

~~We've also added a new bit in the extra house flags that serves as an alternative to marking a house indestructible, though we'd like to hear your thoughts on this.~~

Closes #12968

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/town_cmd.cpp [hunk 1]
```diff
@@ -227,6 +227,15 @@ Money HouseSpec::GetRemovalCost() const
 	return (_price[PR_CLEAR_HOUSE] * this->removal_cost) >> 8;
 }
 
+/**
+* Gets if house is destructible by the player
+* @return Boolean if the house is destructible
+ */
+bool HouseSpec::IsDestructible() const
```
Comment (2TallTyler) [inline src/town_cmd.cpp]: "Destructible" is an odd word, technically valid but rarely used. 🙂 

I might name this `CanBeDestroyedByPlayer` or similar to communicate what it's used for — especially since it's different than the `BUILDING_IS_PROTECTED` flag which protects houses from town growth and AI, but not players.

...or, since it's only called once, you could skip creating a new method and just check `rating > RATING_MAXIMUM` in `ClearTile_Town()`. 😉

File: src/town_cmd.cpp [hunk 2]
```diff
@@ -227,6 +227,15 @@ Money HouseSpec::GetRemovalCost() const
...
+{
+	return (remove_rating_decrease <= RATING_MAXIMUM) && !(extra_flags & BUILDING_IS_PERMANENT);
```
Comment (2TallTyler) [inline src/town_cmd.cpp]:
```suggestion
	return (this->remove_rating_decrease <= RATING_MAXIMUM) && !(extra_flags & BUILDING_IS_PERMANENT);
```

File: src/town_cmd.cpp [hunk 3]
```diff
@@ -728,10 +737,15 @@ static CommandCost ClearTile_Town(TileIndex tile, DoCommandFlag flags)
...
-		if (rating > t->ratings[_current_company] && !(flags & DC_NO_TEST_TOWN_RATING) &&
-				!_cheats.magic_bulldozer.value && _settings_game.difficulty.town_council_tolerance != TOWN_COUNCIL_PERMISSIVE) {
-			SetDParam(0, t->index);
-			return_cmd_error(STR_ERROR_LOCAL_AUTHORITY_REFUSES_TO_ALLOW_THIS);
+		if (!_cheats.magic_bulldozer.value) {
+			if (!hs->IsDestructible()) {
+				SetDParam(0, t->index);
+				return_cmd_error(CMD_ERROR);
+			}
+			else if (rating > t->ratings[_current_company] &&  _settings_game.difficulty.town_council_tolerance != TOWN_COUNCIL_PERMISSIVE && !(flags & DC_NO_TEST_TOWN_RATING)) {
```
Comment (2TallTyler) [inline src/town_cmd.cpp]: `else if` goes on the same line as the closing bracket, in our code style.

That said, if the previous branch is taken, the function returns, so no `else` is required. 😃

File: src/town_cmd.cpp [hunk 4]
```diff
@@ -728,10 +737,15 @@ static CommandCost ClearTile_Town(TileIndex tile, DoCommandFlag flags)
 	Town *t = Town::GetByTile(tile);
 
 	if (Company::IsValidID(_current_company)) {
-		if (rating > t->ratings[_current_company] && !(flags & DC_NO_TEST_TOWN_RATING) &&
-				!_cheats.magic_bulldozer.value && _settings_game.difficulty.town_council_tolerance != TOWN_COUNCIL_PERMISSIVE) {
-			SetDParam(0, t->index);
-			return_cmd_error(STR_ERROR_LOCAL_AUTHORITY_REFUSES_TO_ALLOW_THIS);
+		if (!_cheats.magic_bulldozer.value) {
```
Comment (2TallTyler) [inline src/town_cmd.cpp]: Magic bulldozer and the `DC_NO_TEST_TOWN_RATING` command flag always allow the house to be cleared, and should apply to both conditions, as in this psuedocode:

```
if (!magic_bulldozer && !DC_NO_TEST_TOWN_RATING) {
  /* Some houses cannot be removed by any player. */
  if (!rating > RATING_MAXIMUM) {
    return_cmd_error()
  }
  /* If town authority controls removal, check the company's rating. */
  if (tolerance != PERMISSIVE && rating > company) {
    return_cmd_error()
  }
}
```

**Review by 2TallTyler — COMMENTED** [review]
Thanks for the contribution! It's always nice to see a new face in the PR list. 😄 

Why create a second way to create an indestructible house? I don't see a need for another flag, if setting the rating above 1000 works the same way.

**Comment by aquagnawt** [comment]
Thank you for the suggestions! I've implemented the changes in the latest push. For the extra bit usage, I was thinking that it would provide a more clear-cut way to make houses indestructible. However, after further reflection, both approaches seem equally straightforward, so I've also removed this in the push.

File: src/town_cmd.cpp [hunk 5]
```diff
@@ -728,10 +728,17 @@ static CommandCost ClearTile_Town(TileIndex tile, DoCommandFlag flags)
 	Town *t = Town::GetByTile(tile);
 
 	if (Company::IsValidID(_current_company)) {
-		if (rating > t->ratings[_current_company] && !(flags & DC_NO_TEST_TOWN_RATING) &&
-				!_cheats.magic_bulldozer.value && _settings_game.difficulty.town_council_tolerance != TOWN_COUNCIL_PERMISSIVE) {
-			SetDParam(0, t->index);
-			return_cmd_error(STR_ERROR_LOCAL_AUTHORITY_REFUSES_TO_ALLOW_THIS);
+		if (!_cheats.magic_bulldozer.value && !(flags & DC_NO_TEST_TOWN_RATING)) {
+			/* Houses with high enough rating decrease upon removal cannot be removed by the player. */
```
Comment (2TallTyler) [inline src/town_cmd.cpp]:
```suggestion
			/* NewGRFs can add indestructible houses. */
```

**Review by 2TallTyler — COMMENTED** [review]
Hmm, I wonder if `CanDeleteHouse()` in `newgrf_house.cpp` is a better place for this check.
https://github.com/OpenTTD/OpenTTD/blob/master/src/newgrf_house.cpp#L612

File: src/town_cmd.cpp (hunk 5 above)
Comment (aquagnawt) [reply src/town_cmd.cpp:732]: In that case we would still have to check the `DC_NO_TEST_TOWN_RATING` flag in `ClearTile_Town()` right? I'm assuming we can't just wrap `if (!CanDeleteHouse(tile)) return CMD_ERROR;` with the flag check either, as the `CanDeleteHouse()` function originally skipped this check if `CBM_HOUSE_DENY_DESTRUCTION` or `BUILDING_IS_PROTECTED` are set.

**Comment by aquagnawt** [comment]
In that case we would still have to check the DC_NO_TEST_TOWN_RATING flag in ClearTile_Town() right? I'm assuming we can't just wrap if (!CanDeleteHouse(tile)) return CMD_ERROR; with the flag check either, as the CanDeleteHouse() function originally skipped this check if CBM_HOUSE_DENY_DESTRUCTION or BUILDING_IS_PROTECTED are set.

**Comment by 2TallTyler** [comment]
Hmm, I'm actually not sure how to apply that command flag. I might be wrong with my earlier assessment that it should always apply. Take a look at the other uses in the code and let me know what you think — maybe I just need more coffee but I can't fully wrap my head around it. 🙂

**Comment by aquagnawt** [comment]
After some searching, the main place where the flag seems to be utilized is for funding new industries:
https://github.com/OpenTTD/OpenTTD/blob/master/src/industry_cmd.cpp#L1960

Specifically, funding a bank requires the user to build it on top of existing houses, where the action ends up clearing the houses before placing the bank. Without the flag check, the program will proceed to build the bank anyways without clearing beforehand, leading to a crash.

**Comment by 2TallTyler** [comment]
Sorry, this one slipped through the cracks and I never reviewed it. We recently removed the `return_cmd_error` macro, instead returning a `CommandCost()` instead. See https://github.com/OpenTTD/OpenTTD/pull/13160 for more info.

If you update this PR with the necessary changes, I will approve this. Sorry for the delay. 🙂

**Comment by aquagnawt** [comment]
Sorry for the late response, I've updated the code to reflect the changes. Thanks.

**Review by 2TallTyler — APPROVED** [review]
Thanks!
