### PR TITLE
Fix #12154: Incorrect calendar day lengths with minutes per year setting

### LINKED ISSUE #12154: [Bug]: Wallclock mode minutes per year setting does not work correctly for values other than 0 and 12
### Version of OpenTTD

master

### Expected result

Wallclock mode minutes per year setting does what it says on the tin

### Actual result

At minutes per year = 12, a calendar day is 74 ticks
At minutes per year = 13, a calendar day is 153 ticks
At minutes per year = 24, a calendar day is 221 ticks

TimerGameCalendar::sub_date_fract counts from 0 to ((74 * min_per_year) / 12) - 1
then date_fract counts from 0 to 74

### Steps to reproduce

Use the minutes per year setting

### PR DESCRIPTION
**Pull request by JGRennison**
## Motivation / Problem

#12154: Calendar days were the wrong length for all non-trivial values of the minutes per year setting

## Description

Fix #12154.
Fix handling of TimerGameCalendar::sub_date_fract such that calendar days are the correct length.
e.g. 80 ticks at 13 minutes/year, 148 ticks at 24 minutes/year, 62160 ticks at 10080 minutes/year.

## Limitations

N/A

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by LordAro — COMMENTED** [review]
Possibly worth some unit tests?

File: src/timer/timer_game_calendar.cpp [hunk 1]
```diff
@@ -105,10 +105,13 @@ bool TimerManager<TimerGameCalendar>::Elapsed([[maybe_unused]] TimerGameCalendar
 
 	/* If we are using a non-default calendar progression speed, we need to check the sub_date_fract before updating date_fract. */
 	if (_settings_game.economy.minutes_per_calendar_year != CalendarTime::DEF_MINUTES_PER_YEAR) {
-		TimerGameCalendar::sub_date_fract++;
+		TimerGameCalendar::sub_date_fract += Ticks::DAY_TICKS;
```
Comment (TrueBrain) [inline src/timer/timer_game_calendar.cpp:108]: Do I read this right that `DAY_TICKS` is not really relevant here, but that it just defines the resolution of the sub-ticker? So it could also be, say, `1000`?

At least I have a hard time understanding what the relation with `DAY_TICKS` is here, but I might just not be understanding this :)

Comment (JGRennison) [reply src/timer/timer_game_calendar.cpp:108]: The sizing of sub_date_fract and the limit of the _settings_game.economy.minutes_per_calendar_year implicitly assume that this is DAY_TICKS. (This is what the comment for MAX_MINUTES_PER_YEAR is talking about). The increment needs to be an integral multiple of DAY_TICKS for the algorithm to make sense (additional ticks per day are spread over DAY_TICKS date fracts), and 1 x DAY_TICKS is the smallest/least surprising value to use.

In general I'm not trying to justify the design of the wall-clock timekeeping mode, I'm merely aiming to fix this aspect to match what was (to me at least) clearly the intended behaviour.

Comment (TrueBrain) [reply src/timer/timer_game_calendar.cpp:108]: Ah, that is why `DAY_TICKS` is used :) And yeah, I agree that this seemed to be the intended behaviour :)

Tnx!

**Review by TrueBrain — APPROVED** [review]
