### PR TITLE
Fix #8922: Show vehicle window for single vehicle in shared order grouping

### LINKED ISSUE #8922: NOT_REACHED() crash when selling shared vehicles
## Version of OpenTTD

1.11.0-RC1

## Expected result

Selling vehicles with shared orders does not crash the game.

## Actual result

crash_reproduction

`NOT_REACHED triggered at line 1719 of ..\src\vehicle_gui.cpp`

## Steps to reproduce

This is a tricky one to reproduce. 

1. In the attached savegame `autosave14` (not the emergency save), open the New Mills Airport station (just north of the starting location in the savegame) and look at the list of trains with that station in its orders.
2. Group the list by shared orders
3. Train 289 is in the list, currently lost and near a depot. Click on it and send it to the depot
4. In the depot, drag the last vehicle (an EMU) off the train onto a new line
5. Click the Sell All button
6. A NOT_REACHED error should trigger

[crash_stuff.zip](https://github.com/OpenTTD/OpenTTD/files/6243812/crash_stuff.zip)

### PR DESCRIPTION
**Pull request by btzy**
## Motivation / Problem

Fixes #8922 - shared order list could have only one vehicle, which leads to a crash later when that vehicle is deleted.

## Description

When viewing by shared order groups, if a vehicle is not shared, don't open the shared order list (of just a single vehicle).  Instead, open the vehicle window.

## Limitations

None

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by LordAro** [comment]
Does this fix the issue? If a shared group window is opened, then the list size is reduced from 2+ to none, it will still crash, no?

**Comment by btzy** [comment]
> If a shared group window is opened, then the list size is reduced from 2+ to none, it will still crash

Hmm, I'll check that later tonight.  However, if this was the case, then this bug would have been in OpenTTD for much longer than my PR for grouping by shared orders (and hence surprising that it was only discovered now).

**Comment by btzy** [comment]
> If a shared group window is opened, then the list size is reduced from 2+ to none, it will still crash, no?

I've just tested and it no longer crashes:  In the linked savegame, I bought a new vehicle and cloned the orders of vehicle 289 to it, then sold all vehicles in the depot (i.e. both of them).  The shared orders window disappears as expected; no crashes.

I believe the code that deletes the shared order window when there is only one vehicle left is this:
https://github.com/OpenTTD/OpenTTD/blob/799eb31ff199745888ffecf76a37e0d7cce437dd/src/vehicle.cpp#L2790-L2793

Presumably selling all vehicles in the depot will delete vehicles one-by-one, which is probably why it works.

**Comment by btzy** [comment]
Reworded the commit message to conform to the style guide.

**Review by LordAro — DISMISSED** [review]

File: src/group_gui.cpp [hunk 1]
```diff
@@ -892,7 +892,12 @@ class VehicleGroupWindow : public BaseVehicleListWindow {
 						/* We do not support VehicleClicked() here since the contextual action may only make sense for individual vehicles */
 
 						if (vindex == v->index) {
-							ShowVehicleListWindow(v);
+							if (vehgroup.NumVehicles() == 1) {
+								ShowVehicleViewWindow(v);
+							}
+							else {
```
Comment (LordAro) [inline src/group_gui.cpp]: Oh wait, codestyle - this and below should be on one line

Comment (btzy) [reply src/group_gui.cpp]: Fixed.

**Review by LordAro — APPROVED** [review]
