### PR TITLE
Fix #8886: Don't try to resolve folders within tars named '.'

### LINKED ISSUE #8886: Changelog button crashes the game if NewGRF contains relative folder
## Version of OpenTTD
20210322-master-gf9d24ff45e

## Expected result
Changelog button is disabled

## Actual result
Changelog button is enabled and crashes if I click it:
image

## Steps to reproduce
I recently updated [my NewGRF](https://github.com/KoreanGRF/KoreanTrainSet/releases/tag/2.0.0-beta1) and it contains a markdown file, which is named ``changelog.md``
It is awkward that Changelog button appears when ``changelog.md`` file exists, even though I refered a related codes at 
https://github.com/OpenTTD/OpenTTD/blob/e5c325364285b1e6e93afa2a0a79b1ec437f238e/src/textfile_gui.cpp#L385

1. Download [Korean Train Set 2.0.0-beta1](https://github.com/KoreanGRF/KoreanTrainSet/releases/tag/2.0.0-beta1)
2. Put it ``/newgrf`` or ``/content_download/newgrf`` folder
3. Open NewGRF Settings window, select Korean Train Set 2.0.0-beta1, and click changelog

### PR DESCRIPTION
**Pull request by LordAro**
## Motivation / Problem
Through mildly nefarious means, you can create a tar that has a "root folder" named `.`. In standard file systems, this is the current directory. But OTTD (without the tar filename to realise it's supposed to be within a tarfile, falls back to the standard directory resolving, which includes the the current directory, and can cause OTTD to try to load text files from that directory, rather than from within the tar

#8006 is beneficial here too, though no longer required for #8886

## Description
Resolve the `.` (by ignoring it). This causes OTTD to not be able to find the grf/content item, which means it can't try to access textfiles in the wrong directory.

## Limitations
Might want to add some sort of debug output for when this occurs? It's currently very unclear why a GRF has been silently rejected.
It should be noted that this cannot be "exploited" by bananas-downloaded content, as it would be rejected at that level.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/fileio.cpp [hunk 1]
```diff
@@ -429,6 +429,10 @@ FILE *FioFOpenFile(const std::string &filename, const char *mode, Subdirectory s
 			if (token == "..") {
 				if (tokens.size() < 2) return nullptr;
 				tokens.pop_back();
+			} else if (token == ".") {
+				/* Do nothing.
+				 * Useful if a tar contains a folder named '.', which then causes weird file resolving issues,
+				 * like changelog.txt from the current working directory, rather than within the tar. */
```
Comment (TrueBrain) [inline src/fileio.cpp]: This comment is a bit weird :P "Useful" seems to be misused here. And it continues on to a specific situation, which no future-us will understand. What has "changelog.txt" have to do with anything in this place in the code. That only makes sense if you come from the bug-report.

`/* Do nothing. "." means current folder, but you can create tar files with "." in the path. This confuses our file resolver. So, act like this folder doesn't exist. */`

Or something?

**Review by TrueBrain — APPROVED** [review]
