### PR TITLE
Fix #14561: Vehicle effects missing for vehicle on bridge.

### LINKED ISSUE #14561: [Bug]: Vehicle effects disappear on bridges
### Version of OpenTTD

Nightly, Windows 10

### Expected result

Vehicle emission effects (smoke, sparks) appear consistently while crossing a bridge that has another bridge crossing the bridgehead at the entrance of the bridge.

### Actual result

The vehicle produces no emission effects while it is on the bridge, after it passes under the other bridge at the beginning of the bridge. The effects reappear as soon as the vehicle reaches the end of the bridge.

Happens with both rail and road vehicles. Steam puffs are the most obvious because they should be produced continuously. Also tested with Road Hog as vanilla road vehicles do not produce effects.

### Steps to reproduce

1. Build a railway (or road) with a bridge 
2. Build another bridge over the bridgehead of the first bridge
3. Send a steam train (or road vehicle) across the bridge, entering on the side covered by the other bridge

[Fuston Transport, 0h 15m.zip](https://github.com/user-attachments/files/22066856/Fuston.Transport.0h.15m.zip)

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

As per #14561, vehicle effects are missing for a vehicle on bridge, if there is a bridge crossing the the bridge head tile.

## Description

Check if the vehicle is actually on a bridge, indicated by its visual position being a different tile. Given that (currently) bridges can't cross each other, if the vehicle is on a bridge tile then there is no bridge above.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by glx22 — DISMISSED** [review]

File: src/vehicle.cpp [hunk 1]
```diff
@@ -2754,6 +2754,20 @@ static void SpawnAdvancedVisualEffect(const Vehicle *v)
...
 }
 
+/**
+ * Test if a bridge is above a vehicle.
+ * @param v Vehicle to test.
+ * @return true iff a bridge is above the vehicle.
+ */
+static bool IsBridgeAboveVehicle(const Vehicle *v)
+{
+	if (IsBridgeTile(v->tile)) {
```
Comment (2TallTyler) [inline src/vehicle.cpp:2764]: Might be good to have a comment here explaining that this checks for the case of a bridge over a bridge end.

**Comment by JGRennison** [comment]
Might it be better to do the cheaper `IsBridgeAbove` test first?

**Review by rubidium42 — APPROVED** [review]

**Comment by PeterN** [comment]
> Might it be better to do the cheaper `IsBridgeAbove` test first?

Something like this...? But it feels a bit messier to me.

```c++
static bool IsBridgeAboveVehicle(const Vehicle *v)
{
	if (!IsBridgeAbove(v->tile)) return false;

	if (IsBridgeTile(v->tile)) {
		/* If the vehicle is 'on' a bridge tile, check the real position of the vehicle. If it's different then the
		 * vehicle is on the middle of the bridge, which cannot have a bridge above. */
		TileIndex tile = TileVirtXY(v->x_pos, v->y_pos);
		if (tile != v->tile) return false;
	}

	return true;
}
```

**Comment by rubidium42** [comment]
> > Might it be better to do the cheaper `IsBridgeAbove` test first?
> 
> Something like this...? But it feels a bit messier to me.

I'd say something like:
```c++
static bool IsBridgeAboveVehicle(const Vehicle *v)
{
	/* There is no bridge above the vehicle. */
	if (!IsBridgeAbove(v->tile)) return false;

	/* Vehicles 'on' bridge tiles are special, in all other cases there is a bridge above. */
	if (!IsBridgeTile(v->tile)) return true;

	/* Vehicles 'on' bridges are always placed on the tile of the ramp. So, check the real 
	 * position of the vehicle. If it's the same then the vehicle is on the ramp and has a
	 * bridge above it, otherwise the vehicle is on the middle of the bridge, which cannot
	 * have a bridge above. */
	TileIndex tile = TileVirtXY(v->x_pos, v->y_pos);
	return tile == v->tile;
}
```

But I have a hard time to make the comments flow clearly in that function, as the order of the logic is quite different from the best way to explain it.

**Comment by PeterN** [comment]
I think I'm going to with this as is for beta3. It can be tweaked some other time if desired.
