### PR TITLE
GDI engine for font glyph rendering as a replacement for FreeType (take 2)

### LINKED ISSUE #7511: Text rendering error under CJK system locale
## Version of OpenTTD
All version above 1.9.0-beta1

## Expected result
(Windows 10 RS5)
image

## Actual result
(Win7)
image

(Win8.1)
image

(Did't tested Win10 RTM ~ RS1 due to not supported by MS anymore)

(Win10 RS2)
image

(Win10 RS3)
image

(Win10 RS4)
image

## Steps to reproduce
Execute OpenTTD 1.9.1 on Korean version of Windows(below Win10 RS5)
All strings are corrupted, even english.lng is not displayed correctly.
OpenTTD 1.8.0 works well, but OpenTTD 1.9.0-beta1 or above doesn't works.

### PR DESCRIPTION
**Pull request by michicc**
Rebased PR #6980 which unfortunately can't be reopened. Might fix #7511.

Old description:
> This PR supplies a native Windows GDI font rendering back-end. It drops FreeType as a required lib, OTOH it is one more code path to maintain while FreeType isn't really causing problems.

> Building with FreeType is still possible and will take precedence over the GDI renderer, but
the project files don't include FreeType any more by default. Combining GDI rendering with ICU text layout is untested.

### CODE REVIEW

**Comment by YJSoft** [comment]
Looks like loading font file from path not works at this build.

### With `./fonts/NanumGothic.ttf` (with or without font installed)
vmware_PXVEeQaeRJ

### With `NanumGothic` (with font installed)
vmware_Y9qVgpGmlT

(I increased font size to see diff easily)

**Comment by glx22** [comment]
But at least the text is correct this time, even if the font is not the expected one. That's already a progress.

**Comment by michicc** [comment]
> Looks like loading font file from path not works at this build.

Try now?

**Comment by michicc** [comment]
As the PR is now, I can principally get OpenTTD to load a NanumGothic.ttf without it being installed. However, if I select Korean as game language, it will not use the font for me because it is missing characters. As I just randomly googled for the font file, it is very likely I just have a bad file though.

**Comment by YJSoft** [comment]
Tested it, works very well

okay

File: src/fontcache.cpp [hunk 1]
```diff
@@ -960,7 +963,51 @@ static void LoadWin32Font(FontSize fs)
...
+			static PFNGETFONTRESOURCEINFO GetFontResourceInfo = (PFNGETFONTRESOURCEINFO)GetProcAddress(GetModuleHandle(_T("Gdi32")), "GetFontResourceInfoW");
+#else
+			static PFNGETFONTRESOURCEINFO GetFontResourceInfo = (PFNGETFONTRESOURCEINFO)GetProcAddress(GetModuleHandle(_T("Gdi32")), "GetFontResourceInfoA");
+#endif
+
+			if (GetFontResourceInfo != nullptr) {
+				/* Try to query an array of LOGFONTs that describe the file. */
+				DWORD len = 0;
+				if (GetFontResourceInfo(fontPath, &len, nullptr, 2)) {
+					LOGFONT *buf = (LOGFONT *)AllocaM(byte, len);
```
Comment (nielsmh) [inline src/fontcache.cpp:993]: I guess it's not necessary to protect against len==0 here, since the AddFontResourceEx would have failed then?

Comment (michicc) [reply src/fontcache.cpp:993]: Good point. Can't be too careful with undocumented calls.

File: docs/Readme_Windows_MSVC.md [hunk 2]
```diff
@@ -41,8 +40,8 @@ the `static` versions, and OpenTTD currently needs the following dependencies:
 To install both the x64 (64bit) and x86 (32bit) variants, you can use:
 
 ```ps
-.\vcpkg install freetype:x64-windows-static liblzma:x64-windows-static libpng:x64-windows-static lzo:x64-windows-static zlib:x64-windows-static
-.\vcpkg install freetype:x86-windows-static liblzma:x86-windows-static libpng:x86-windows-static lzo:x86-windows-static zlib:x86-windows-static
```
Comment (LordAro) [inline docs/Readme_Windows_MSVC.md:45]: Do we want to update the CI to remove this as well?

Comment (nielsmh) [reply docs/Readme_Windows_MSVC.md:45]: Probably a good idea to check the CI can build without Freetype as well.

Comment (glx22) [reply docs/Readme_Windows_MSVC.md:45]: CI should already build this PR without Freetype as it's removed from the project files, and I tried locally after removing Freetype via vcpkg and it builds fine. But mingw will still build with Freetype as the detection code is untouched.

Comment (michicc) [reply docs/Readme_Windows_MSVC.md:45]: Windows dependencies come in via OpenTTD/CompileFarm, can't change that in this PR.

**Comment by michicc** [comment]
Added a change to config.lib to a899786, maybe @glx22 can have a look if it seems sane.

**Comment by glx22** [comment]
Freetype properly skipped with MinGW.

Many warnings in fontcache.cpp with MinGW:
```
[SRC] Compiling fontcache.cpp
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp: In member function 'virtual const Sprite* Win32FontCache::InternalGetGlyph(GlyphID, bool)':
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp:837:18: warning: operation on 'bmp' may be undefined [-Wsequence-point]
  byte *bmp = bmp = AllocaM(byte, size);
```
This one is fixable by removing one `bmp =`

```
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp: In function 'void LoadWin32Font(FontSize)':
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp:965:24: warning: missing initializer for member 'tagLOGFONTW::lfWidth' [-Wmissing-field-initializers]
  LOGFONT logfont = { 0 };
                        ^
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp:965:24: warning: missing initializer for member 'tagLOGFONTW::lfEscapement' [-Wmissing-field-initializers]
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp:965:24: warning: missing initializer for member 'tagLOGFONTW::lfOrientation' [-Wmissing-field-initializers]
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp:965:24: warning: missing initializer for member 'tagLOGFONTW::lfWeight' [-Wmissing-field-initializers]
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp:965:24: warning: missing initializer for member 'tagLOGFONTW::lfItalic' [-Wmissing-field-initializers]
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp:965:24: warning: missing initializer for member 'tagLOGFONTW::lfUnderline' [-Wmissing-field-initializers]
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp:965:24: warning: missing initializer for member 'tagLOGFONTW::lfStrikeOut' [-Wmissing-field-initializers]
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp:965:24: warning: missing initializer for member 'tagLOGFONTW::lfCharSet' [-Wmissing-field-initializers]
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp:965:24: warning: missing initializer for member 'tagLOGFONTW::lfOutPrecision' [-Wmissing-field-initializers]
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp:965:24: warning: missing initializer for member 'tagLOGFONTW::lfClipPrecision' [-Wmissing-field-initializers]
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp:965:24: warning: missing initializer for member 'tagLOGFONTW::lfQuality' [-Wmissing-field-initializers]
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp:965:24: warning: missing initializer for member 'tagLOGFONTW::lfPitchAndFamily' [-Wmissing-field-initializers]
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp:965:24: warning: missing initializer for member 'tagLOGFONTW::lfFaceName' [-Wmissing-field-initializers]
```
I have not tried to fix this one.

```
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp:972:41: warning: cast from type 'const void*' to type 'LPLOGFONT' {aka 'tagLOGFONTW*'} casts away qualifiers [-Wcast-qual]
   logfont = *(const LPLOGFONT)settings->os_handle;
                                         ^~~~~~~~~
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp:972:41: warning: type qualifiers ignored on cast result type [-Wignored-qualifiers]
```
Maybe a different cast, but don't know which one yet.

```
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp:983:147: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'PFNGETFONTRESOURCEINFO' {aka 'int (*)(const wchar_t*, long unsigned int*, void*, long unsigned int)'} [-Wcast-function-type]
    static PFNGETFONTRESOURCEINFO GetFontResourceInfo = (PFNGETFONTRESOURCEINFO)GetProcAddress(GetModuleHandle(_T("Gdi32")), "GetFontResourceInfoW");
                                                                                                                                                   ^
```
This one can be ignored, there are already similar warnings in win32.cpp and win32_v.cpp

```
D:/developpement/GitHub/glx22/OpenTTD/src/fontcache.cpp:1025:13: warning: format '%X' expects argument of type 'unsigned int', but argument 4 has type 'DWORD' {aka 'long unsigned int'} [-Wformat=]
   ShowInfoF("Unable to use '%s' for %s font, Win32 reported error 0x%X, using sprite font instead", settings->font, SIZE_TO_NAME[fs], GetLastError());
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                    ~~~~~~~~~~~~~~
```
Using %lX fixes it.

**Comment by michicc** [comment]
I _think_ I've addressed all the mentioned warnings.

**Comment by glx22** [comment]
Yup all warnings fixed (except the function cast one, but it's not fixable I think)

**Comment by PeterN** [comment]
I notice you add an #ifdef in uniscribe code for FreeType. Is it still possible to compile with FreeType on Windows? Is that desirable?

**Comment by michicc** [comment]
Yes, I didn't remove any FreeType stuff. After all, it is still needed for other platforms.

Whether it is desirable is debatable. Disabling it for Windows would complicate the #ifdef's because you'd have to explicitly exclude WIN32.

**Comment by orudge** [comment]
As an aside, I started work on a DirectWrite font renderer (based on this patch) with the intention that it could be used for an eventual UWP build, should we want to go down that route (it would primarily benefit ARM-based Windows 10 devices). FreeType is supported on UWP but GDI isn't, so retaining the possibility of FreeType support on Windows would have some benefit there. In general, I don't see that it would hurt to keep it anyway.

**Review by PeterN — APPROVED** [review]
