### PR TITLE
Fix: prevent useless pathfinder run for blocked vehicles

### LINKED ISSUE #7670: Road vehicle pathing cache does not always pick up changes in road network
## Version of OpenTTD
Custom one based on 20190722, https://github.com/SamuXarick/OpenTTD/tree/SamuPatchPackRebase
## Expected result
YAPF should have a lower average ms than NPF
## Actual result
YAPF has a higher average ms time than NPF
## Steps to reproduce
Load savegame and open framerate window, then switch to NPF and notice the difference.

[road vehicle ticks.zip](https://github.com/OpenTTD/OpenTTD/files/3438432/road.vehicle.ticks.zip)

YAPF: ~135 ms
NPF: ~35 ms

This system has windows 7, 4GB RAM, Celeron E1400, 2 cores @ 2.00 GHz

### PR DESCRIPTION
**Pull request by glx22**
Fix #7670 and supersede #7822.
## Motivation / Problem
As found in #7670, a road vehicle blocked by another vehicle may enter in an "loop" of intensive pathfinder calls.
This happens because starting tile for path search is not cached and as the vehicle did not move since previous call, the cached path is discarded and a new one has to be determined.

## Description
This solution is similar to the one in #7822, but a lot less invasive and does not require a savegame bump.
When a road vehicle is blocked by another one, just push its current location and the direction to follow found by pathfinder on top of the existing cache.
That way on next run it will just retrieve the heading instead of recalculating it.
While in the area I noticed the speed of the blocked vehicle was not updated, so I fixed it.

## Limitations
I only tested using the save from https://github.com/OpenTTD/OpenTTD/issues/7670#issuecomment-549088710 but I don't see how it could cause issues.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by LordAro — APPROVED** [review]
Fine by me

File: src/roadveh_cmd.cpp [hunk 1]
```diff
@@ -1389,7 +1389,16 @@ bool IndividualRoadVehicleController(RoadVehicle *v, const RoadVehicle *prev)
...
+			if (!v->path.empty()) {
+				/* Prevent pathfinding rerun as we already know where we are heading to. */
+				v->path.tile.push_front(v->tile);
+				v->path.td.push_front(dir);
+			}
+			return false;
+		}
 
 		uint32 r = VehicleEnterTile(v, v->tile, x, y);
 		if (HasBit(r, VETS_CANNOT_ENTER)) {
```
Comment (SamuXarick) [inline src/roadveh_cmd.cpp:1404]: I wondered if the pathfinder prevention checks should be also added to VETS_CANNOT_ENTER, but I wasn't able find a situation where `HasBit(r, VETS_CANNOT_ENTER)` is true for testing that.
