### PR TITLE
Fix #11055: Make saveload failure error messages consistent with others

### LINKED ISSUE #11055: [Bug]: "Game Load Failed" error message is shorter than other two-line messages
### Version of OpenTTD

Since c600158c1df336153eb6705eded718f0434fee75, tested on c316d9ecb7

### Expected result

When saving or loading the game to/from a file fails, the resulting error message should have some space between "Game Load Failed" (or "Game Save Failed") and the reason for the save/load failure.

Example: 
image

### Actual result

When saving or loading the game to/from a file fails, the resulting error message has no additional space between "Game Load Failed" (or "Game Save Failed") and the reason for the save/load failure, unlike other message where there is space.

Example:
image

### Steps to reproduce

1. Try to save (or load) the game, such that it fails.
2. Notice the resulting message has no extra space between "Game Save Failed" (or "Game Load Failed") and the reason for failure.
3. Perform any other action (in game) such that it fails.
4. Notice the resulting message has space between the two lines.

### PR DESCRIPTION
**Pull request by merni-ns**
## Motivation / Problem
Fixes #11055.

The "save/load failed" error messages were displayed by substituting the reason (`_sl.error_str`) with a parameter into `STR_ERROR_GAME_SAVE_FAILED`/`STR_ERROR_GAME_LOAD_FAILED`. This means the line separation is not the same as those formed by using the two parameters of `ShowErrorMessage`.

## Description
- Use the first parameter of `ShowErrorMessage` to show the initial string "Game save failed"/"Game load failed"
- Use the second parameter to show the reason that was originally the first parameter of `STR_ERROR_GAME_(SAVE|LOAD)_FAILED`.
- The `_sl.extra_msg`, an untranslated string returned by internal APIs, is untouched and used as the first parameter of reasons that require it (and thus the first parameter overall).
- Make the "Game save failed"/"Game load failed" more consistent by not Capitalising Each Word and adding an ellipsis at the end.

image

## Limitations

- Not tested, except for the case of a save file that the game has no permission to read. In particular the case of "internal error" or "broken savegame", which require one more parameter, are not tested.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/saveload/saveload.cpp [hunk 1]
```diff
@@ -2754,22 +2754,21 @@ void SetSaveLoadError(StringID str)
 	_sl.error_str = str;
 }
 
-/** Get the string representation of the error message */
-const char *GetSaveLoadErrorString()
-{
-	SetDParam(0, _sl.error_str);
-	SetDParamStr(1, _sl.extra_msg);
+/** Return the appropriate initial string for an error depending on whether we are saving or loading. */
+StringID GetSaveLoadErrorString() {
```
Comment (2TallTyler) [inline src/saveload/saveload.cpp]: Given that this and `GetSaveLoadErrorMessage()` are both dealing with StringIDs, I wonder if this might be a better name.

```suggestion
StringID GetSaveLoadErrorType() {
```

Comment (merni-ns) [reply src/saveload/saveload.cpp]: Sure.

File: src/saveload/saveload.cpp [hunk 2]
```diff
@@ -2754,22 +2754,21 @@ void SetSaveLoadError(StringID str)
 	_sl.error_str = str;
 }
 
-/** Get the string representation of the error message */
-const char *GetSaveLoadErrorString()
-{
-	SetDParam(0, _sl.error_str);
-	SetDParamStr(1, _sl.extra_msg);
+/** Return the appropriate initial string for an error depending on whether we are saving or loading. */
+StringID GetSaveLoadErrorType() {
```
Comment (rubidium42) [inline src/saveload/saveload.cpp]:
```suggestion
StringID GetSaveLoadErrorType()
{
```

File: src/saveload/saveload.cpp [hunk 3]
```diff
@@ -2754,22 +2754,21 @@ void SetSaveLoadError(StringID str)
...
+	return _sl.action == SLA_SAVE ? STR_ERROR_GAME_SAVE_FAILED : STR_ERROR_GAME_LOAD_FAILED;
+}
 
-	static std::string err_str;
-	err_str = GetString(_sl.action == SLA_SAVE ? STR_ERROR_GAME_SAVE_FAILED : STR_ERROR_GAME_LOAD_FAILED);
-	return err_str.c_str();
+/** Return the description of the error. **/
+StringID GetSaveLoadErrorMessage() {
```
Comment (rubidium42) [inline src/saveload/saveload.cpp]:
```suggestion
StringID GetSaveLoadErrorMessage()
{
```

File: src/saveload/saveload.cpp [hunk 4]
```diff
@@ -2803,8 +2802,7 @@ static SaveOrLoadResult SaveFileToDisk(bool threaded)
 		/* We don't want to shout when saving is just
 		 * cancelled due to a client disconnecting. */
 		if (_sl.error_str != STR_NETWORK_ERROR_LOSTCONNECTION) {
-			/* Skip the "colour" character */
-			Debug(sl, 0, "{}", GetSaveLoadErrorString() + 3);
+			Debug(sl, 0, "{}", GetString(GetSaveLoadErrorType()));
```
Comment (rubidium42) [inline src/saveload/saveload.cpp]: Why is the colour not stripped any more? Also in the next bit. For example using `.substr(3)`.

Comment (merni-ns) [reply src/saveload/saveload.cpp]: Hopefully I have fixed it in the current force-push, but I have no idea about how colour codes work.

**Review by rubidium42 — APPROVED** [review]
