### PR TITLE
Fix #7411: Use industry production callback (if used) on initial industry cargo generation.

### LINKED ISSUE #7411: Newgrf: using production CB for primary production cause industries to show 'Production last month: 0' at game start
## Version of OpenTTD

master at 43caef2968bccdab63896e816ee86f9d70f3c769

## Expected result

There are two mechanics for newgrf industries to produce cargo without any input.  For convenience I just refer to this as 'primary' industry production.

* 'default' primary production on 256 ticks, driven by action 0 prop 10 or prop 25 and prod_level and OpenTTD's built-in production algorithm
* primary production via production cb, on 256 ticks, driven by arbitrary calculations

At game start, each primary industry instance should show how much was produced in the previous month, even though the previous month didn't exist in the game timeline.  

This helps player understand the production rate at that industry instance, via the industry window, or the industry directory. 

## Actual result

At game start:

* for 'default' production OpenTTD simulates a month of production per industry instance, and the 'Production last month' value is displayed correctly
* for the production cb, 'Production last month' value is displayed as 0, after one month of game time this then resolves to show the correct value

If this is not resolvable, then there are workarounds within the newgrf spec, by combining both default production and production cb.  These workarounds are viable, they're just clunky.

## Steps to reproduce

The attached FIRS v4 development release will show this issue for industries like Coal Mines, Fishing Grounds etc. 
[firs-1.tar.zip](https://github.com/OpenTTD/OpenTTD/files/3003498/firs-1.tar.zip)

FIRS v3 releases or older do not show this behaviour, as they use a hybrid of default production behaviour and production cb.

## Screenshots

Using production cb, at game start, and after 1 month.
7411_game_start
7411_after_1_month

### PR DESCRIPTION
**Pull request by PeterN**
Industry production callback was not called for initial cargo generation when generating the world, so NewGRFs had to implement otherwise unused properties.

Fixes #7411

### CODE REVIEW

**Comment by andythenorth** [comment]
Tested, works as expected for me.

**Review by andythenorth — DISMISSED** [review]
Code makes sense to me. 

Tested as working for both callback and non-callback case.

* callback tested using the FIRS grf attached to #7411
* non-callback tested with default industries (no newgrf)

File: src/industry_cmd.cpp [hunk 1]
```diff
@@ -1751,8 +1751,16 @@ static void DoCreateNewIndustry(Industry *i, TileIndex tile, IndustryType type,
...
 	if (_generating_world) {
-		for (size_t ci = 0; ci < lengthof(i->last_month_production); ci++) {
-			i->last_month_production[ci] = i->production_rate[ci] * 8;
+		if (HasBit(indspec->callback_mask, CBM_IND_PRODUCTION_256_TICKS)) {
+			IndustryProductionCallback(i, 1);
+			for (size_t ci = 0; ci < lengthof(i->last_month_production); ci++) {
+				i->last_month_production[ci] = i->produced_cargo_waiting[ci] * 8;
+				i->produced_cargo_waiting[ci] = 0;
+			}
+		} else {
```
Comment (nielsmh) [inline src/industry_cmd.cpp]: The default production is added to the result of the callback result, they are not exclusive.

**Review by nielsmh — CHANGES_REQUESTED** [review]

File: src/industry_cmd.cpp (hunk 1 above)
Comment (PeterN) [reply src/industry_cmd.cpp]: Fixed!

**Review by nielsmh — APPROVED** [review]
