### PR TITLE
Fix #9802: Assertion failure in BuildRailWaypointWindow constructor

### LINKED ISSUE #9802: [Crash]: Assertion failure in BuildRailWaypointWindow constructor when _cur_waypoint_type >= _waypoint_count
### Version of OpenTTD

master

### Steps to reproduce

1. Load or start a game with many NewGRF waypoint types available
2. Open the waypoint selector and select the last one
3. Abandon game
4. Load or start a game with few but not zero NewGRF waypoint types available
5. Assertion failure

`bool Scrollbar::SetPosition(int): Assertion 'this->count <= this->cap ? (position == 0) : (position + this->cap <= this->count)' failed` via `matrix->SetClicked(_cur_waypoint_type);`

### Upload crash files

[issue-9802.zip](https://github.com/OpenTTD/OpenTTD/files/7963747/issue-9802.zip)

### PR DESCRIPTION
**Pull request by JGRennison**
## Motivation / Problem

Se: #9802

## Description

Fix assertion failure in BuildRailWaypointWindow constructor when _cur_waypoint_type >= _waypoint_count

## Limitations

N/A

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/rail_gui.cpp [hunk 1]
```diff
@@ -2011,7 +2011,7 @@ struct BuildRailWaypointWindow : PickerWindowBase {
 		this->FinishInitNested(TRANSPORT_RAIL);
 
 		matrix->SetCount(_waypoint_count);
-		matrix->SetClicked(_cur_waypoint_type);
+		matrix->SetClicked(_cur_waypoint_type < _waypoint_count ? _cur_waypoint_type : 0);
```
Comment (glx22) [inline src/rail_gui.cpp]: But `_cur_waypoint_type` will still contain an invalid value, and it's used again in `OnClick()`.

**Review by michicc — APPROVED** [review]
