### PR TITLE
Fix #9242: Tree tick handler did not scale by map size.

### LINKED ISSUE #9242: Tropical Lumber Mill doesn't work properly on large maps
## Version of OpenTTD
1.11.2, Windows 10

## Expected result
The production of a tropical lumber mill should be independent of the map size.

## Actual result
A 40x40 section of a rainforest on a 64x64 map can support up to about 80 lumber mills. The same area cannot support even one lumber mill on a 4096x4096 map (the lumber mill eventually runs out of trees to chop down).

In other words, the random tree growth does not scale with map size.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

Tree tick handler did not scale by map size.

This means that random tree generation density is higher on small maps and lower on large maps. This difference is enough to make the Lumber Mill impractical to use on large maps.

## Description

This change skips ticks on maps smaller than 256x256 and increases iterations or shortens the interval on maps larger than 256x256.

Although #9242 is primarily about the Lumber Mill, this issue affects all random tree generation after a game is started.

## Limitations

For simplicity the counter decrement function now triggers when the counter passes zero, instead of when the counter reaches zero. Slight timing difference but shouldn't affect much.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by PeterN** [comment]
Slightly wonky screenshot of the change. On the right is 1.11.2, on the left is with this change. Map size is 1024x1024 in both cases.
Screenshot 2021-05-11 135815

**Comment by PeterN** [comment]
~~Well I guess it majorly affects regression. Bum.~~ Only because the commit was broken.

File: src/tree_cmd.cpp [hunk 1]
```diff
@@ -803,6 +804,20 @@ static void TileLoop_Trees(TileIndex tile)
...
+ * The interval is scaled by map size to allow for the same density regardless of size.
+ * Adjustment for map sizes below the standard 256 * 256 are handled earlier.
+ * @return true if the counter was decremented past zero
+ */
+bool DecrementTreeCounter()
+{
+	/* byte underflow */
+	byte old_trees_tick_ctr = _trees_tick_ctr;
+	_trees_tick_ctr -= ScaleByMapSize(1);
+	return old_trees_tick_ctr <= _trees_tick_ctr;
```
Comment (rubidium42) [inline src/tree_cmd.cpp:821]: Might it be useful to add something like `static_assert(2 * (MAX_MAP_SIZE_BITS - MIN_MAP_SIZE_BITS) - 4 <= std::numeric_limits<byte>::digits);` here, so that when the map size gets bigger we get notified that this needs to be changed?

Comment (PeterN) [reply src/tree_cmd.cpp:821]: I wish I knew how this calculation worked!

Comment (rubidium42) [reply src/tree_cmd.cpp:821]: Well it's basically `ScaleByMapSize(1)` without the shifting with the maximum map size.
The 12 in ScaleByMapSize is actually 2*MIN_MAP_SIZE_BITS. The MapLogX/Y's maximum would be MAX_MAP_SIZE_BITS and it's dividing by `1 << 4`, which is where the subtraction of `4` comes from. You probably already figured out that with the current maximum map sizes that value gets to 8 which would be exactly one overflow of the byte.
Anything larger than that would overflow two times or more and mean too few trees would be planted.

**Review by rubidium42 — APPROVED** [review]
