### PR TITLE
Fix #9501: [Network] crash when more than one game-info query was pending

### LINKED ISSUE #9501: [Crash]: Crashes when Multiplayer Opened
### Version of OpenTTD

1.12.0 - Beta 2  Windows

### Steps to reproduce

1.Opened the Game
2.Pressed Multiplayer 
2.5.Pressed Ok on  "Assertion failed at line 146 of D:\a\OpenTTD\src\network\network_client.cpp:
ClientNetworkGameSocketHandler::my_client == nullptr"
Errorcrash
3.Fatal Application Failure
Errorcrash2

### Upload crash files

[crashDatathingsMatu.zip](https://github.com/OpenTTD/OpenTTD/files/7022914/crashDatathingsMatu.zip)
All of the Crash files

### PR DESCRIPTION
**Pull request by TrueBrain**
## Motivation / Problem

When you have more than one query-for-game-info pending, the game crashes. This is easiest reproduced by starting a local server, and adding `127.0.0.1` and `127.0.0.2` to your server-list. Close the game, restart it, click Multiplayer. Now two queries will be send out at the exact same time.

## Description

We piggy-backed on the client code to, after establishing a TCP connection, query the server. The client code only has a very weird and annoying to follow singleton called `my_client`. As it turns out, when it is being asked to query two different servers at the same time, it panics.

To resolve the situation in a more robust way, I cut out the game-info query part from the client code, and moved it to `network_query`. This part is now responsible solely for querying the game-info of a server, and can have as many parallel connection as needed. It self-registers and self-destroys.

As an additional bonus, this means we can also handle errors from servers in a bit nicer way for when a query fails. This is best seen about the code removed from the client code.

As the protocol reuses other packages to indicate issues, the server can send back 4 different packets depending on the situation on a game-info request:
- `game-info`, what we are after.
- `error`, when something weird went wrong. For example, when it never saw your game-info request packet .. it will hit a timeout and close your connection. But this is really unlikely to ever happen.
- `banned`, when your IP is banned (you won't be able to query the server in that case either; only seems fair).
- `full`, which is already a bug on our bugtracker, but currently at a very early moment in time we validate if the server has room for you. If not, you get this packet back, and refresh fails. This of course has to be resolved, but as for now, this is still happening.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/network/network_query.cpp [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+}
+
+/**
+ * Check if any query needs to send or receive.
+ */
+/* static */ void QueryNetworkGameSocketHandler::SendReceive()
+{
+	for (auto it = QueryNetworkGameSocketHandler::queries.begin(); it != QueryNetworkGameSocketHandler::queries.end(); /* nothing */) {
+		if (!(*it)->Receive()) {
+			QueryNetworkGameSocketHandler::queries.erase(it);
```
Comment (glx22) [inline src/network/network_query.cpp]: Missing update of `it` after `erase` ?

File: src/network/network_query.cpp [hunk 2]
```diff
@@ -0,0 +1,147 @@
...
+			continue;
+		}
+		if (!(*it)->CheckConnection()) {
+			QueryNetworkGameSocketHandler::queries.erase(it);
```
Comment (glx22) [inline src/network/network_query.cpp]: Same here.

File: src/network/network_query.h [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+
+/** @file network_query.h Query part of the network protocol. */
+
+#ifndef NETWORK_QUERY_H
+#define NETWORK_QUERY_H
+
+#include "network_internal.h"
+
+/** Class for handling the client side of quering a game server. */
+class QueryNetworkGameSocketHandler : public ZeroedMemoryAllocator, public NetworkGameSocketHandler {
```
Comment (rubidium42) [inline src/network/network_query.h:16]: Is the `ZeroedMemoryAllocator` really needed here? Only the `ClientNetworkGameSocketHandler` uses it but not the `ServerNetworkGameSocketHandler` so it is not something the `NetworkGameSocketHandler` intrinsicly needs. Since this has only one instance variable that gets in the constructor, I think there is no use for it.

Comment (TrueBrain) [reply src/network/network_query.h:16]: `ServerNetworkGameSocketHandler` also zero's the object, but this is done by the pool (`Tzero` is set to `true`). So there too `Calloc` is used. In other words: it currently is consistent in zero'ing the object on creation.

Of course these days we can just set the initial values of variables, and possibly get ride of this whole `ZeroedMemoryAllocator`, but that might be best for another PR. For now, I suggest we leave it consistent, and zero the object for all children using `NetworkGameSocketHandler`.

**Review by rubidium42 — APPROVED** [review]
