### PR TITLE
Fix #11696: Graphics set parameters missing from survey data

### LINKED ISSUE #11696: [Bug]: Survey result does not include base set grf parameters
### Version of OpenTTD

openttd-20240105-master-g34e8c8e1c1-windows-win64

### Expected result

OpenTTD survey JSON should include an array of base set grf parameters. Perhaps also palette?

### Actual result

Base graphics set is listed under `info.configuration.graphics_set`, seemingly `"<name>.<version>"`, but no other information is reported.

### Steps to reproduce

Game Options>Preview survey result `info.configuration` section.

### PR DESCRIPTION
**Pull request by JGRennison**
## Motivation / Problem

#11696

## Description

Add graphics set parameters which were previous missing from survey data.

## Limitations

N/A

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by TrueBrain — DISMISSED** [review]

File: src/survey.cpp [hunk 1]
```diff
@@ -248,6 +248,10 @@ void SurveyConfiguration(nlohmann::json &survey)
 	}
 	if (BaseGraphics::GetUsedSet() != nullptr) {
 		survey["graphics_set"] = fmt::format("{}.{}", BaseGraphics::GetUsedSet()->name, BaseGraphics::GetUsedSet()->version);
+		const GRFConfig *extra_cfg = BaseGraphics::GetUsedSet()->GetExtraConfig();
+		if (extra_cfg != nullptr && extra_cfg->num_params > 0) {
+			survey["graphics_set_parameters"] = span<const uint32_t>(extra_cfg->param.data(), extra_cfg->num_params);
+		}
```
Comment (TrueBrain) [inline src/survey.cpp:256]: To put Discord on GitHub: I think I prefer having this key always set, to make it more the same as how NewGRFs work. Makes analysing things just a bit easier (and always good to know things are deliberately empty)

**Review by TrueBrain — APPROVED** [review]
Tnx a lot for this!
