### PR TITLE
Fix #15039: Name and version can disappear from content list.

### LINKED ISSUE #15039: [Bug]: online content window: "Name" column not populated
### Version of OpenTTD

15.0, Windows 11

### Expected result

Just downloaded the 15.0 version, the online content window has two columns - "Type" and "Name". 

The "Type" column contains "AI", "Gamescript" etc.
The "Name" column should display the element name.

### Actual result

It looks like this:

Image

### Steps to reproduce

1. Run the OpenTTD
2. In the main menu, click the "Online Content" button.
3. You're there.

EDIT:
screenshot of info about my driver and graphics settings.

Image

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

As per #15039, the name and version can disappear from content list.

If the small font is set larger than the normal font, both name and version text disappear.

## Description

Take account of the height of the small font when setting the resize height.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by rubidium42 — APPROVED** [review]

File: src/network/network_content_gui.cpp [hunk 1]
```diff
@@ -603,7 +603,7 @@ class NetworkContentListWindow : public Window, ContentCallback {
 				break;
 
 			case WID_NCL_MATRIX:
-				fill.height = resize.height = std::max(this->checkbox_size.height, (uint)GetCharacterHeight(FS_NORMAL)) + padding.height;
+				fill.height = resize.height = std::max<uint>(std::max<uint>(this->checkbox_size.height, GetCharacterHeight(FS_NORMAL)), GetCharacterHeight(FS_SMALL)) + padding.height;
```
Comment (glx22) [inline src/network/network_content_gui.cpp:606]: Wouldn't 
```suggestion
				fill.height = resize.height = std::max<uint>(this->checkbox_size.height, GetCharacterHeight(FS_NORMAL), GetCharacterHeight(FS_SMALL)) + padding.height;
```
do the same?

Comment (PeterN) [reply src/network/network_content_gui.cpp:606]: No, it needs an initializer list to do that, so wrapped by {}

Comment (glx22) [reply src/network/network_content_gui.cpp:606]: Oh indeed.
