### PR TITLE
Change: Increase maximum number of orders from 64000 to ~16.7m.

### LINKED ISSUE #6968: No more space for orders
While testing multiple AIs on a 4096x4096 map, some kind of limit has been reached. I was seeing vehicles with no orders and AIs struggling to insert orders to their vehicles. ShipAI hinted me with the error message `ERR_ORDER_TOO_MANY`

I decided to play and right on my first bus service, I could only insert the first order. When attempting to insert the 2nd order it failed with this:

Savegame attached.
[no more space for orders.zip](https://github.com/OpenTTD/OpenTTD/files/2574356/no.more.space.for.orders.zip)

### PR DESCRIPTION
**Pull request by PeterN**
This fixes #6968. Turns out it is apparently trivial to increase the maximum number of orders, and doesn't even need a bump, though #7219 is useful in that case.

### CODE REVIEW

File: src/order_type.h [hunk 1]
```diff
@@ -25,7 +25,7 @@ static const VehicleOrderID INVALID_VEH_ORDER_ID = 0xFF;
 static const VehicleOrderID MAX_VEH_ORDER_ID     = INVALID_VEH_ORDER_ID - 1;
 
 /** Invalid order (sentinel) */
-static const OrderID INVALID_ORDER = 0xFFFF;
+static const OrderID INVALID_ORDER = 0xFFFFFF;
```
Comment (glx22) [inline src/order_type.h:28]: Doesn't this change require conversion on load ?

Comment (PeterN) [reply src/order_type.h:28]: Orders are stored as references which already does the magic. See 1fa98e169529b070c19a6bc0cff311ebc993b468 for a similar change, 9 years ago :-)

There would also be an issue if OrderID was passed in commands, but it seems VehicleOrderIDs are used instead.

**Review by LordAro — APPROVED** [review]

**Comment by J0anJosep** [comment]
What about merging this one?

**Comment by James103** [comment]
If this pull request is merged, the following limits and stats will change:
* If each order list has 255 orders, then the max number of order lists increases from 251 to 65,794. 
* If each company has 20,000 vehicles and there are 15 companies, then the maximum average number of orders per vehicle increases from 0.21 to 55.7 orders.
