### PR TITLE
Fix #8453: [Script] Don't truncate loan variation to 32bit

### LINKED ISSUE #8453: AIs can fail at requesting 170 years inflation loan with a 4% interest rate
maxloaninflation
The AI is setting loan amount to £1,641,693,900,000 and has a current loan of £82,050,000.
https://github.com/OpenTTD/OpenTTD/blob/edbb5f4f737e2670faa1ac392fe179b7278921ec/src/script/api/script_company.cpp#L207-L209
Following the code, `abs(1,641,693,900,000 - 82,050,000)` = 1,641,611,850,000 is passed to this function:
https://github.com/OpenTTD/OpenTTD/blob/edbb5f4f737e2670faa1ac392fe179b7278921ec/src/script/api/script_object.hpp#L69-L72
`uint32 p1` transforms the value to 934,342,928
This ends up failing to set the loan even to the bugged value:
https://github.com/OpenTTD/OpenTTD/blob/edbb5f4f737e2670faa1ac392fe179b7278921ec/src/misc_cmd.cpp#L57-L58
`p1 % LOAN_INTERVAL != 0` is true, returns `CMD_ERROR`

### PR DESCRIPTION
**Pull request by glx22**
## Motivation / Problem

Difference between requested new loan and current loan may not fit in 32 bits.

## Description

Replaced p1 with higher half of loan variation.
Used free bits in p2 to pass 30 highest bits of lower half of loan variation (assuming lower 2 bits are always 0)

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/misc_cmd.cpp [hunk 1]
```diff
@@ -25,14 +25,18 @@
...
+
 /**
  * Increase the loan of your company.
  * @param tile unused
  * @param flags operation to perform
- * @param p1 amount to increase the loan with, multitude of LOAN_INTERVAL. Only used when p2 == 2.
- * @param p2 when 0: loans LOAN_INTERVAL
- *           when 1: loans the maximum loan permitting money (press CTRL),
- *           when 2: loans the amount specified in p1
+ * @param p1 higher half of amount to increase the loan with, multitude of LOAN_INTERVAL. Only used when p2 == 2.
```
Comment (TrueBrain) [inline src/misc_cmd.cpp]: `when p2 == 2` is no longer a valid statement :D Sorry :)

**Review by LordAro — DISMISSED** [review]
Mm, bitstuffing. Code looks fine.

File: src/misc_cmd.cpp [hunk 2]
```diff
@@ -76,10 +80,11 @@ CommandCost CmdIncreaseLoan(TileIndex tile, DoCommandFlag flags, uint32 p1, uint
...
  * @param flags operation to perform
- * @param p1 amount to decrease the loan with, multitude of LOAN_INTERVAL. Only used when p2 == 2.
- * @param p2 when 0: pays back LOAN_INTERVAL
- *           when 1: pays back the maximum loan permitting money (press CTRL),
- *           when 2: pays back the amount specified in p1
+ * @param p1 higher half of amount to increase the loan with, multitude of LOAN_INTERVAL. Only used when (p2 & 3) == 2.
+ * @param p2 (bit 2-31) - lower half of amount (lower 2 bits assumed to be 0)
+ *           (bit 0-1)  - when 0: loans LOAN_INTERVAL
+ *                        when 1: loans the maximum loan permitting money (press CTRL),
+ *                        when 2: loans the amount specified in p1
```
Comment (SamuXarick) [inline src/misc_cmd.cpp]: The comments are about decreasing loan, not increasing loan.
EDIT: Also the amount specified is not only in p1 anymore

**Review by SamuXarick — CHANGES_REQUESTED** [review]

File: src/script/api/script_company.cpp [hunk 3]
```diff
@@ -204,8 +204,10 @@
 
 	if (loan == GetLoanAmount()) return true;
 
+	Money amount = abs(loan - GetLoanAmount());
+
```
Comment (SamuXarick) [inline src/script/api/script_company.cpp:208]:
```suggestion

	assert(amount >> 62 == 0);
```

**Review by SamuXarick — CHANGES_REQUESTED** [review]

File: src/script/api/script_company.cpp (hunk 3 above)
Comment (glx22) [reply src/script/api/script_company.cpp:208]: No, that suggestion is totally wrong.

Comment (SamuXarick) [reply src/script/api/script_company.cpp:208]: what about
`assert(GB((int64)amount, 62, 2) == 0);`

Comment (glx22) [reply src/script/api/script_company.cpp:208]: Checking highest 2 bits is useless.

Comment (TrueBrain) [reply src/script/api/script_company.cpp:208]: I am guessing he was trying to ensure the lower (not higher) bits were zero'd. This is pointless, as we already check that the modulo of the interval is zero, and the interval is validated to have its lower bits zero. And yes, you can make code too pedantic :D

**Review by TrueBrain — APPROVED** [review]
