### PR TITLE
Prevent sounds being produced by inactive industries

### LINKED ISSUE #7703: Inactive industries make inappropriate/unlogical sounds
## Version of OpenTTD
1.8.0

## Expected result
Industries make no sound effects if they are “inactive”. Inactive means:

- If the industry has a potential output: That output is 0
- If the industry has no output (e.g. power plant): Nothing has been delivered to it in the recent past (<3 months or so)

Example:
- A paper mill with 0 paper production
- A power plant with no coal input in the last 3 months

## Actual result
Several secondary industries make inappropriate/misleading sounds when they have no production / no input:

- Paper mill (saw sound)
- Sawmill in temperate climate (saw sound)
- Factory (factory line sound)
- Power plant (electricity sound)
- Food factory?
- Possibly others?

All these particular sounds suggests these industries are active, while in fact they aren't. For instance, the sawmill sounds don't make sense when there's no wood.

## Steps to reproduce
1. Play OpenTTD
2. Pan camera to any inactive industry and listen

### PR DESCRIPTION
**Pull request by abmyii**
Fixes #7703.

### CODE REVIEW

**Comment by nielsmh** [comment]
Hmm, all the regression tests are failing, and the reason must be because the consumption of random numbers has changed. Notice there is a `Chance16` call in the branch of the `if` no longer taken when production is zero. Since that gets skipped, the RNG for the rest of the game gets out of sync with the "expected". This isn't wrong, but it makes the output for the purpose of regression testing different.

Additionally, the commit checker is rejecting your commit because the commit message does not start with a keyword. ([See this](https://wiki.openttd.org/Coding_style#Commit_message) about commit messages.) Update the commit message with `git commit --amend` and force-push, Github handles that just fine.
Suggestion: `Fix #7703: Prevent sounds being produced by inactive industries`

**Comment by abmyii** [comment]
In that case should I let `Chance16` be called then check last_month_production before playing sounds?

**Comment by abmyii** [comment]
Sorry about the merge commit - I cloned the main repository (this) rather than my fork, so the merge took place when I pulled before amending. Still trying to find my way around with git!

**Comment by abmyii** [comment]
I tried `make test` to test my changes but I kept on getting this error despite everything I tried:
`
+Error: Failed to find a graphics set. Please acquire a graphics set for OpenTTD. See section 4.1 of README.md.
`

File: src/industry_cmd.cpp [hunk 1]
```diff
@@ -1125,7 +1125,7 @@ static void ProduceIndustryGoods(Industry *i)
 	if ((i->counter & 0x3F) == 0) {
 		uint32 r;
 		uint num;
-		if (Chance16R(1, 14, r) && (num = indsp->number_of_sounds) != 0 && _settings_client.sound.ambient) {
+		if (Chance16R(1, 14, r) && (num = indsp->number_of_sounds) != 0 && _settings_client.sound.ambient && *i->last_month_production > 0) {
```
Comment (glx22) [inline src/industry_cmd.cpp]: No need to dereference `i`

Comment (abmyii) [reply src/industry_cmd.cpp]: I'm fairly new to C and not very familiar with pointers. How would I do that? Without the & (`&& i->last_month_production > 0`) I get a warning message: `warning: ordered comparison of pointer with integer zero [-Wextra]`. I'm probably not doing the right thing.

Comment (glx22) [reply src/industry_cmd.cpp]: Oh my bad, `i->last_month_production` is an array (= a pointer) so by dereferencing you effectively access `i->last_month_production[0]`

**Comment by J0anJosep** [comment]
El ds. 28 de set. de 2019 15.50, glx22 <notifications@github.com> va
escriure:

File: src/industry_cmd.cpp (hunk 1 above)
Comment (abmyii) [reply src/industry_cmd.cpp]: Right, I just tried different things until I found what worked! That seems like the correct explanation. Thanks!

**Comment by andythenorth** [comment]
Is it defined what 'inactive' is for a newgrf industry? :)

**Comment by abmyii** [comment]
@andythenorth
> Is it defined what 'inactive' is for a newgrf industry? :)

I assume so, but I haven't tested it yet. I take it you have already done so?

**Comment by abmyii** [comment]
I tried with FIRS Replacement Set 3, however it doesn't seem to have any industry sounds - I didn't hear anything anyway.

**Comment by andythenorth** [comment]
For newgrf industry, there is simply no way to know in advance what behaviour is defined 'inactive'.  

I don't think industry sounds are particularly important for newgrf, but I am just one opinion.

But if this PR is merged, it would be worth noting in the newgrf docs (nfo and nml) that sound effects aren't purely random, and may never trigger for newgrf industries.  Potentially a newgrf author could spend a long time investigating why sound effects don't work / no longer work as expected.

**Comment by abmyii** [comment]
True, I never thought of that - being new to the inner workings of OpenTTD. Where/how would that be documented? Also, surely the definition of inactivity chosen (last month's production) should be fairly ubiquitously applicable?
Thanks for all of the insight you have provided!

**Comment by andythenorth** [comment]
Relevant newgrf docs are:
* 'random_sound_effects' https://newgrf-specs.tt-wiki.net/wiki/NML:Industries#Industry_properties
* property 15 'Random sound effects' https://newgrf-specs.tt-wiki.net/wiki/Action0/Industries#Random_sound_effects_.2815.29

They don't promise more than sound is played 'sometimes', and just need a note explaining the conditions under which sounds won't be played.  That wouldn't need doing unless the PR is accepted.

I would not mind never hearing the sawmill noise ever again, but maybe that's just me 😃

**Comment by abmyii** [comment]
Should that be part of this PR? Also, is there a repo for the wiki or should the editions be done on the wiki itself (I expect this is the correct method)?

**Comment by abmyii** [comment]
> I would not mind never hearing the sawmill noise ever again, but maybe that's just me smiley

Haha! Funnily enough I've always played without sound since I never could be bothered to take the extra steps of downloading and enabling the sounds.

**Comment by abmyii** [comment]
Any updates on what else needs to be done to this PR?

**Comment by abmyii** [comment]
Any follow-up?

**Comment by glx22** [comment]
I still fail to understand why the commit checker was successful, but you'll need to use `git rebase -i HEAD~6` to squash all your commits into one.

**Comment by abmyii** [comment]
Thanks for that. I've applied it and pushed. Hopefully it works this time!

File: src/industry_cmd.cpp (hunk 1 above)
Comment (nielsmh) [reply src/industry_cmd.cpp]: Really, don't use the * operator to get the first element of an array, use array indexing for that.
But I'd strongly prefer if the entire array was checked for any non-zero values. It's very much possible to have a NewGRF industry with multiple outputs, and only some of them are active depending on the inputs provided.

Comment (abmyii) [reply src/industry_cmd.cpp]: As is probably obvious, I'm pretty new to C, and I didn't realise that it was an array - I'll fix and push that. Thanks for the tips!

**Comment by abmyii** [comment]
Changes made to check all of the industry's outputs.

**Comment by abmyii** [comment]
I can't seem to fix this tab indentation (of all things) despite my efforts. Any ideas?

**Comment by glx22** [comment]
You need to fix it in the commit introducing the wrong indentation, as the commit checker checks the diffs individually

**Comment by abmyii** [comment]
Oh my, may I ask what the easiest way to do that would be? Sorry for my basic questions and thanks for all your help!

**Comment by glx22** [comment]
The easiest way is to rebase, but it seems your previous rebase somehow failed. I can force push a rebase on your branch if you want.

**Comment by abmyii** [comment]
Yes, please!

File: src/industry_cmd.cpp [hunk 2]
```diff
@@ -1126,9 +1126,18 @@ static void ProduceIndustryGoods(Industry *i)
...
+				if (i->last_month_production[j] > 0) {
+					playsound = true;
+					break;
+				}
+			}
+
+			if (playsound)
+				SndPlayTileFx(
+					(SoundFx)(indsp->random_sounds[((r >> 16) * num) >> 16]),
+					i->location.tile);
```
Comment (PeterN) [inline src/industry_cmd.cpp]: Missing { } for the if-block, but the SndPlayTileFx() call could just be before the break; above.

Comment (abmyii) [reply src/industry_cmd.cpp]: Your observation is correct - thank you! As for the lack of braces, they aren't required if the `if` statement only has one line inside. I don't think that is a style requirement for OpenTTD since I have seen it being done elsewhere in the code.

**Comment by abmyii** [comment]
Thank you for resolving that problem @glx22! I believe that now the PR should be complete (hopefully!).

File: src/industry_cmd.cpp (hunk 2 above)
Comment (Eddi-z) [reply src/industry_cmd.cpp]: According to our codestyle, the braces are required whenever the if spans more than one line.

File: src/industry_cmd.cpp [hunk 3]
```diff
@@ -1126,9 +1126,15 @@ static void ProduceIndustryGoods(Industry *i)
 		uint32 r;
 		uint num;
 		if (Chance16R(1, 14, r) && (num = indsp->number_of_sounds) != 0 && _settings_client.sound.ambient) {
-			SndPlayTileFx(
-				(SoundFx)(indsp->random_sounds[((r >> 16) * num) >> 16]),
-				i->location.tile);
+			for (size_t j = 0; j < lengthof(i->last_month_production); j++) {
+				if (i->last_month_production[j] > 0) {
+					// Play sound since last month had production
```
Comment (glx22) [inline src/industry_cmd.cpp]: Coding style for single line comments (see [Coding style](https://wiki.openttd.org/Coding_style#Other_important_rules))
```suggestion
					/* Play sound since last month had production */
```

**Comment by abmyii** [comment]
Sorry for tiring you with such trivial problems throughout @glx22. You've been a great help!

**Comment by glx22** [comment]
Arg, github commits don't follow our style. But it's easily fixable with `git commit --amend` and a forced push. Do you want to try it ?

**Comment by abmyii** [comment]
Done, thanks for the tip.

**Comment by planetmaker** [comment]
I've one question regarding black-hole industries (that is industries which only receive cargo but don't produce anything like power plants): I don't see how they will be able to make sounds with this patch. Do I miss something?
If not, please also add as an or-condition a check for received cargo :)

**Comment by abmyii** [comment]
It doesn't apply to them, since I can hear their sounds despite no cargo being transported to them. I never bothered checking why, but I expect the `i->last_month_production` is never 0 for them.
Thanks for your input!

**Comment by abmyii** [comment]
Haha, you made me curious and I couldn't help but check. As was mentioned in the issue, the code for the power station sound is here:
https://github.com/OpenTTD/OpenTTD/blob/b50aeff0a5bd8d636e4f3a3ca8502401b0867744/src/industry_cmd.cpp#L893-L898

Whereas the code for the production sounds is in the function `ProduceIndustryGoods`:
https://github.com/OpenTTD/OpenTTD/blob/b50aeff0a5bd8d636e4f3a3ca8502401b0867744/src/industry_cmd.cpp#L1120-L1139

This does raise another question though - are there any NewGRF/extension packs with black-hole industries that play their sounds through the `ProduceIndustryGoods` function? I doubt it but I am not very familiar with how they work. If it was the case, what would be checked to identify one?

**Comment by planetmaker** [comment]
ah, right. Looking at the broader context (that is beyond the patch), that function is only called for producing industries. :) And the accepting default industries are handled via the tile loop separately :) Cheers!

EDIT: NewGRFs can also make use of the tile loop. or run callback on receiving cargo at which time they can play a sound.

But you actually pointed out the place an additional patch might go: making the blackhole industries kinda inactive unless they actually receive something to eat :D (But if so: that's for a separate PR)

**Comment by abmyii** [comment]
Great, thanks again!

**Comment by abmyii** [comment]
@planetmaker With regards to the point you added, that'd have to be done by someone with a better idea of how the engine works since I expect that a new attribute will have to be added, unless there is a more obvious way that I don't know?

**Comment by abmyii** [comment]
Anything else required for this PR?

File: src/industry_cmd.cpp [hunk 4]
```diff
@@ -1126,9 +1126,15 @@ static void ProduceIndustryGoods(Industry *i)
 		uint32 r;
 		uint num;
 		if (Chance16R(1, 14, r) && (num = indsp->number_of_sounds) != 0 && _settings_client.sound.ambient) {
```
Comment (LordAro) [inline src/industry_cmd.cpp]: not strictly your issue, but i'd want to see num (and it's declaration) moved inside the if statement

Comment (abmyii) [reply src/industry_cmd.cpp]: Should I do that as part of my PR?

Comment (abmyii) [reply src/industry_cmd.cpp]: Also, why should it be moved inside? Is it because it is bad practice to declare in the statement?

Comment (LordAro) [reply src/industry_cmd.cpp]: Bad practice to declare variables in a scope above where they're used. Also, assignment in if statements is unpleasant in all but the simplest of cases.

Not sure why an extra variable is needed at all, `indsp->random_sounds[((r >> 16) * indsp->number_of_sounds) >> 16]` would work just fine, though I can't say I understand what it's actually doing with all the bitshifts. Probably some remnant of the original TTD ASM.

Comment (abmyii) [reply src/industry_cmd.cpp]: Is `indsp->number_of_sounds` a constant? I assumed it was defined by the industry, and it's set here:
https://github.com/OpenTTD/OpenTTD/blob/04f659e768486da4fc73a97a633f140d9733bf78/src/newgrf.cpp#L3636
It may just be the same for them all though.

Comment (LordAro) [reply src/industry_cmd.cpp]: regardless, it's not modified in this function

Comment (abmyii) [reply src/industry_cmd.cpp]: Push a commit removing it. Could you please verify it is what you wanted?

**Review by LordAro — APPROVED** [review]

**Comment by abmyii** [comment]
Thanks for the approval! What else is remaining?

**Comment by LordAro** [comment]
Patience :p

**Comment by abmyii** [comment]
Haha, and I thought it would only require changing one or two lines and be done in a day!
I'm still not used to the PRing and I expect this isn't an abnormally long time to wait, but my preconceived expectations will obviously need adjusting. Pardon my impatience!

**Comment by abmyii** [comment]
Have I been patient long enough (*wink*)?

**Comment by abmyii** [comment]
Great, thanks a lot!
