### PR TITLE
Fix #7644: (Cocoa) Manually set colorspace to sRGB

### LINKED ISSUE #7644: Mysteriously poor performance on macOS
## Version of OpenTTD
1.9.0 and later, at least

## Expected result
All operating systems have comparable performance when running on comparable hardware.

## Actual result
Several people are reporting that the macOS version of OpenTTD has unreasonably poor performance, and the framerate window does not reveal any obvious reason.

This bug covers the situation when all of the following occur at the same time:
- Game is running on macOS
- Frame rate on a new game (256x256) with no mods is below 30 fps (typically even below 10 fps)
- Sum of "Game loop", "Drawing" and "Video output" times in the Frame rate window is below 10 ms
- Toggling "Full animation" does not have a significant impact on performance

Reported [on TT-Forums](https://www.tt-forums.net/viewtopic.php?f=31&t=85063) and [this comment](https://github.com/OpenTTD/OpenTTD/issues/7247#issuecomment-505035209) on bug #7247.

Note that this is _not_ related to #7247, as this bug manifests even when there are zero vehicles in game. The poor performance is also caused by something not being measured, since the sum of the game loop, drawing, and video output times do not add up to the time it should to cause the total frame rate.

## Steps to reproduce
Run official OpenTTD builds on a macOS 10.14 system.

### PR DESCRIPTION
**Pull request by spauka**
This commit manually sets the colorspace for the window to sRGB, as suggested in #7644 by @SoothedTau, to fix performance issues on OSX when using devices that use the P3 colorspace by default. This makes the game run smoothly on my laptop, with the full 33fps rate.

Screen Shot 2020-02-26 at 3 49 03 pm

### CODE REVIEW

**Comment by nielsmh** [comment]
Crashes for me on macOS 10.13.6 (Macbook Pro, late 2010 model). I haven't looked into the details of the crash yet.
Tested master and this PR rebased onto master, builds of master do work normally.

```
Assertion failed: (this->cgcontext != NULL), function WindowResized, file /Users/nielsm/dev/OpenTTD/src/video/cocoa/wnd_quartz.mm, line 588.
 
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff52bdab66 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff52da5080 pthread_kill + 333
2   libsystem_c.dylib             	0x00007fff52b361ae abort + 127
3   org.openttd.openttd           	0x000000010cb53e5c HandleCrash(int) + 316 (crashlog_osx.cpp:249)
4   libsystem_platform.dylib      	0x00007fff52d98f5a _sigtramp + 26
5   ???                           	0x000000011cad3088 initialPool + 40
6   libsystem_c.dylib             	0x00007fff52b361ae abort + 127
7   libsystem_c.dylib             	0x00007fff52afe1ac __assert_rtn + 320
8   org.openttd.openttd           	0x000000010cd276e9 WindowQuartzSubdriver::WindowResized() + 345
9   org.openttd.openttd           	0x000000010cd268e5 WindowQuartzSubdriver::SetVideoMode(int, int, int) + 1109 (wnd_quartz.mm:349)
10  org.openttd.openttd           	0x000000010cd277eb QZ_CreateWindowQuartzSubdriver(int, int, int) + 251 (wnd_quartz.mm:486)
11  org.openttd.openttd           	0x000000010cd21e03 VideoDriver_Cocoa::Start(char const* const*) + 659 (cocoa_v.mm:405)
12  org.openttd.openttd           	0x000000010c9d53cc DriverFactoryBase::SelectDriverImpl(char const*, Driver::Type) + 924 (driver.cpp:120)
13  org.openttd.openttd           	0x000000010c9d4fe1 DriverFactoryBase::SelectDriver(char const*, Driver::Type) + 17 (driver.cpp:87)
14  org.openttd.openttd           	0x000000010cb4245b openttd_main(int, char**) + 4075 (openttd.cpp:770)
15  org.openttd.openttd           	0x000000010cb574d7 main + 151 (unix.cpp:261)
16  libdyld.dylib                 	0x00007fff52a8a015 start + 1
```

**Comment by nielsmh** [comment]
I tested from a clean starting point. Just adding the `[ this->window setColorSpace:[ NSColorSpace sRGBColorSpace ] ];` after window creation in WindowQuartzSubdriver::SetVideoMode() seems to improve the performance a lot. All the other moving the color_space around and trying to make it a member variable seems unnecessary.

**Comment by spauka** [comment]
@nielsmh Thanks for checking, I was running without assertions which hid this error!

Latest commit fixes the crash you experienced, WindowResized was being called before the colorspace was set. Although if you feel it's cleaner I/you can also remove the color_space member variable...

File: src/video/cocoa/cocoa_v.h [hunk 1]
```diff
@@ -84,6 +84,7 @@ class CocoaSubdriver {
 	int buffer_depth;     ///< Colour depth of used frame buffer
 	void *pixel_buffer;   ///< used for direct pixel access
 	void *window_buffer;  ///< Colour translation from palette to screen
+	CGColorSpaceRef color_space; // Window color space
```
Comment (LordAro) [inline src/video/cocoa/cocoa_v.h]: Should use ///< doc-comment format

File: src/video/cocoa/wnd_quartz.mm [hunk 2]
```diff
@@ -346,6 +346,10 @@ - (void)drawRect:(NSRect)invalidRect
 		[ this->window makeKeyAndOrderFront:nil ];
 	}
 
+	// Set the window colorspace
```
Comment (LordAro) [inline src/video/cocoa/wnd_quartz.mm]: Comments on their own line should use /* */ form, but this comment is useless as is. Comments should say *why*, not what

**Review by LordAro — DISMISSED** [review]

**Comment by spauka** [comment]
Thanks for the review, I've implemented both requested changes.

**Comment by orudge** [comment]
Seems to work better for me on 10.14.6 (MacBook Pro 15-inch 2019)

**Review by LordAro — APPROVED** [review]
good enough

**Comment by andythenorth** [comment]
Performance is measurably better with this PR versus 1.10.0 beta 2 (using in-game FPS).

This PR re-introduces the unfortunate magenta cast per https://github.com/OpenTTD/OpenTTD/issues/7644#issuecomment-528875224 

Without wanting to be dramatic about it, that makes the game very visually unappealing, the magenta sprites are unpleasant and the contrast is significantly reduced.

I guess there might just be no remedy for that.
