### PR TITLE
Fix #11413: Sort industry list by production order was incorrect.

### LINKED ISSUE #11413: [Bug]: Wrong industries sort by production in industry window
### Version of OpenTTD

n20231004

### Expected result

Industries sorted according production

### Actual result

image
image

### Steps to reproduce

Start a new game, open industries window and sort them by production

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

As per #11413, sorting the industry list by production order is incorrectly sorted.

This was due to a single incorrect character. Comparing a with a instead of a with b.

## Description

Fix by comparing a with b as intended.

Additionally the code is rewritten to no longer be prone to this mistake, and is more efficient when a cargo filter specified.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/industry.h [hunk 1]
```diff
@@ -138,12 +138,30 @@ struct Industry : IndustryPool::PoolItem<&_industry_pool> {
 		return IsTileType(tile, MP_INDUSTRY) && GetIndustryIndex(tile) == this->index;
 	}
 
+	/** Get produced cargo slot for a specific cargo type.
```
Comment (LordAro) [inline src/industry.h]: `/**` usually goes on its own line

Comment (PeterN) [reply src/industry.h]: Fixed, and fixed the existing comments in that file.

**Review by 2TallTyler — APPROVED** [review]
