### PR TITLE
Change: Make order window hotkeys toggle for load & unload variants

### LINKED ISSUE #8661: Orders not showing correctly in the UI
## Version of OpenTTD
1.10.x 1.11.0-beta

## Expected result
Options stick in the UI

## Actual result
Options are working but not stick in the UI.

## Steps to reproduce
Select train / Orders / Full load any cargo, Full load all cargo, No loading

The three types are selectable but doesn't stick in the UI. It prevents using shortcuts to select unselect them.

### PR DESCRIPTION
**Pull request by LordAro**
## Motivation / Problem
Closes #8661 
Order window hotkeys for load & unload behave unexpectedly - most of them only set, not toggle

## Description
Makes all the variants toggle between the default (load - "load if possible", unload - "unload if possible") and whatever setting is desired

## Limitations
* Transfer orders set "no loading" as well as its unload state, so this also alters load state (#3905). Might be unexpected (but is unchanged from current behaviour)
* No changes to the UI. Still only shows the 'primary' load/unload variant on the buttons.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/order_gui.cpp [hunk 1]
```diff
@@ -576,29 +576,21 @@ struct OrdersWindow : public Window {
 
 	/**
 	 * Handle the click on the full load button.
-	 * @param load_type the way to load.
+	 * @param load_type the way to load. If the selected order already has this mode set, revert back to 'load if possible'
```
Comment (TrueBrain) [inline src/order_gui.cpp]: missing dot at end of line

File: src/order_gui.cpp [hunk 2]
```diff
@@ -1434,17 +1411,17 @@ struct OrdersWindow : public Window {
...
-			case OHK_UNLOAD:         this->OrderClick_Unload(-1);      break;
-			case OHK_NEAREST_DEPOT:  this->OrderClick_NearestDepot();  break;
-			case OHK_ALWAYS_SERVICE: this->OrderClick_Service(-1);     break;
-			case OHK_TRANSFER:       this->OrderHotkey_Transfer();     break;
-			case OHK_NO_UNLOAD:      this->OrderHotkey_NoUnload();     break;
-			case OHK_NO_LOAD:        this->OrderHotkey_NoLoad();       break;
+			case OHK_SKIP:           this->OrderClick_Skip();                   break;
+			case OHK_DELETE:         this->OrderClick_Delete();                 break;
+			case OHK_GOTO:           this->OrderClick_Goto(OPOS_GOTO);          break;
+			case OHK_NONSTOP:        this->OrderClick_Nonstop(-1);              break;
```
Comment (TrueBrain) [inline src/order_gui.cpp]: Just to check, a similar fix is not needed for the other `-1` entries in this enum?

Comment (LordAro) [reply src/order_gui.cpp]: "Probably not needed"
* Nonstop uses a "toggle to the next" (its own words) rather than on/off
* Service ... I suppose it could, but there's only 2 options anyway, so nothing noticable

File: src/order_gui.cpp [hunk 3]
```diff
@@ -1434,17 +1411,17 @@ struct OrdersWindow : public Window {
...
+			case OHK_FULLLOAD:       this->OrderClick_FullLoad(OLFB_FULL_LOAD); break;
```
Comment (TrueBrain) [inline src/order_gui.cpp]: Should be `OLF_FULL_LOAD_ANY `

**Comment by TrueBrain** [comment]
Basically, before this PR:
When you selected any `load` option, the button/hotkey would first remove the `load` option; on next click select the value.

With this PR:
Clicking the button/hotkey now always sets `load` to what-ever the hotkey does / button says.

This makes a lot more sense to me, especially as the button isn't pressed if you select anything not on the button.

In general, really funky mechanics here, but okay .. that is old news :D

**Comment by TrueBrain** [comment]
Some more testing, two observations:

1) if you don't have a `load` selected, and you click in the dropdown the top entry, you get an error.
2) if you select any other, you open the dropdown again and select it again, it unselects.

Both changes are introduced by this PR. 1) is a bug, and about 2) I am not sure that makes sense. It feels a bit odd, honestly. Wouldn't it be better to only have this behaviour for hotkeys, and not do this for the dropdown? Would be easy enough in the code by adding a parameter to "force" or to "toggle" (depending if you make the dropdown or the hotkey the exception).

Was 2) intended, and what do you think about it yourself?

File: src/order_gui.cpp [hunk 4]
```diff
@@ -1262,15 +1244,15 @@ struct OrdersWindow : public Window {
 
 			case WID_O_FULL_LOAD:
 				if (this->GetWidget<NWidgetLeaf>(widget)->ButtonHit(pt)) {
-					this->OrderClick_FullLoad(-1);
+					this->OrderClick_FullLoad(OLF_FULL_LOAD_ANY);
```
Comment (TrueBrain) [inline src/order_gui.cpp]: these should be `toggle=true` too I think (and the one with `UNLOAD` too, ofc :P)

**Review by TrueBrain — APPROVED** [review]
