### PR TITLE
Fix #13955: Make graphs respect RTL

### LINKED ISSUE #13955: [Bug]: Plots do not respect right-to-left text direction
### Version of OpenTTD

14.1

### Expected result

When using a right-to-left language, plots should be drawn from right to left as well:
* Y axis on the right.
* X values mirrored.
Image

### Actual result

The plot looks the same for left-to-right and right-to-left languages:
Image

### Steps to reproduce

1. Start a new game.
2. Wait 3 quarters for data.
3. View graphs: company profit, cargo payment rate, industry production history.

### PR DESCRIPTION
**Pull request by xJayMorex**
## Motivation / Problem

Fixes #13955.

## Description

Fixed graphs to respect RTL.

## Limitations

None.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/graph_gui.cpp [hunk 1]
```diff
@@ -409,24 +428,36 @@ struct BaseGraphWindow : Window {
 		y = r.top - GetCharacterHeight(FS_SMALL) / 2;
 
 		for (int i = 0; i < (num_hori_lines + 1); i++) {
-			DrawString(r.left - label_width - ScaleGUITrad(4), r.left - ScaleGUITrad(4), y,
-				GetString(STR_GRAPH_Y_LABEL, this->format_str_y_axis, y_label),
-				GRAPH_AXIS_LABEL_COLOUR, SA_RIGHT);
+			if (rtl) {
+				DrawString(r.right + ScaleGUITrad(4), r.right + label_width + ScaleGUITrad(4), y,
+					GetString(STR_GRAPH_Y_LABEL, this->format_str_y_axis, y_label),
+					GRAPH_AXIS_LABEL_COLOUR, SA_LEFT);
```
Comment (frosch123) [inline src/graph_gui.cpp]: Arabic numbers are right-aligned in all languages.
```suggestion
					GRAPH_AXIS_LABEL_COLOUR, SA_RIGHT);
```

Comment (frosch123) [reply src/graph_gui.cpp]: Sorry, I forgot that `DrawString` inverts the alignment depending on text direction.
I fixed it myself, and added `SA_FORCE` to prevent the inversion.

**Review by frosch123 — APPROVED** [review]
