### PR TITLE
Fix #14945: Hang when deleting implicit orders during vehicle loading.

### LINKED ISSUE #14945: [Crash]: OpenTTD becomes unresponsive
### Version of OpenTTD

OpenTTD15-RC3, Windows 11

### Steps to reproduce

Unpause the attached game and OpenTTD becomes unresponsive with high CPU usage on one core. Doesn't crash and give crash report, but interaction with the window leads to detection as unresponsive by the OS.

I'm not clear exactly what change in-game is triggering the crash. Nothing particularly unusual about the save: vanilla Arctic game, only a few monorail and bus routes in one town, no NewGRFs etc.

Only guess at possible oddities is that cargo distribution is enabled and the monorails don't have orders. Some infinite loop working out the cargodist? But I am totally guessing.

[Tunninghall Transport, 2001-06-02.zip](https://github.com/user-attachments/files/24274637/Tunninghall.Transport.2001-06-02.zip)

### Upload crash files

Hangs rather than crashing.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

As per #14945, game can crash when a train with only implicit orders begins loading, due to incorrect handling of orders.

## Description

Code was changed to access order list directly in a loop to avoid lookups. However during the loop, the order list is modified, so it can access wrong or invalid items.

Reimplement the loop using logic that more closely matches the original behaviour before the order list change, avoiding direct access to orders.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/vehicle.cpp [hunk 1]
```diff
@@ -2248,22 +2248,22 @@ void Vehicle::BeginLoading()
...
+								++this->cur_implicit_order_index;
 							}
+							order = this->GetOrder(this->cur_implicit_order_index);
+
+							/* Wrapped around. */
+							if (order == nullptr) {
+								this->cur_implicit_order_index = 0;
+								order = this->GetOrder(this->cur_implicit_order_index);
+							}
+							assert(order != nullptr);
```
Comment (glx22) [inline src/vehicle.cpp:2266]: I think it could still be `nullptr` if OrderList size is 0.

Comment (PeterN) [reply src/vehicle.cpp:2266]: If there are no orders then it wouldn't find something to delete, and wouldn't have set `found` to true. So it wouldn't get here.

**Review by rubidium42 — APPROVED** [review]
