### PR TITLE
Fix #10331: Starting new company during load must happen after AI start.

### LINKED ISSUE #10331: [Crash]: Loading old savegame with only an AI in it
### Version of OpenTTD

13.0-RC1, Windows 11 Pro

### Steps to reproduce

Load attached savegame.

### Upload crash files

[crash20230108142944.zip](https://github.com/OpenTTD/OpenTTD/files/10368645/crash20230108142944.zip)

The savegame I tried to load was this:
[Trans v130722, 1st Jan 2151.zip](https://github.com/OpenTTD/OpenTTD/files/10368648/Trans.v130722.1st.Jan.2151.zip)

Emergency save also crashes with:

Assertion failed at line 284 of D:\a\OpenTTD\OpenTTD\src\ai\ai_core.cpp: c != nullptr && c->ai_instance != nullptr

PS: It loads fine on 12.2

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

As per #10331, Loading old savegame with only an AI in it

Starting new company during load must happen after AI start. This situation occurs when loading a savegame in single-player which only has AI companies.

## Description

This is resolved by moving the section that creates the new player to the end of the AfterLoadGame() function, just after AI/scripts are started.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/saveload/afterload.cpp [hunk 1]
```diff
@@ -3235,6 +3223,18 @@ bool AfterLoadGame()
 	/* Start the scripts. This MUST happen after everything else. */
```
Comment (rubidium42) [inline src/saveload/afterload.cpp]: Maybe this comment needs some tiny amendment, since it's not the last thing anymore?

**Review by glx22 — APPROVED** [review]
Yet another `AfterLoadGame()` hit.

**Comment by rubidium42** [comment]
Tested with only AI companies; works fine in 13-RC1 and with this fix.
Tested with 14 AI companies and 1 empty slot: crashes in 13-RC1 and works fine with this fix.

**Comment by James103** [comment]
> Tested with only AI companies

Did you mean "tested with 15 AI companies and no empty slots"?
