### PR TITLE
Issue 7513: stack overflow due to recursive GC marking and release

### LINKED ISSUE #7513: Squirrel can stack overflow when GCing deep structures, leading to crash
## Version of OpenTTD
1.9.1
## Expected result
crash with a dump/not crash
## Actual result
OpenTTD closes itself without a dump.
## Steps to reproduce
Configure one NoCAB v499 to start.
Set up opcodes to 250000 to speed things up.
Start a 4096x4096 map with high number of towns and industries.
Wait for no more than 30 minutes, for a crash/poof.

### PR DESCRIPTION
**Pull request by rubidium42**
## Motivation / Problem

Fixes #7513 which is a stack overflow due to recursive marking for garbage collection. Whacking that mole yields a stack overflow due to recursive releasing, so that's tackled here as well.

## Description

The bug is solved by rewriting bits of code to go from a recursive marking and releasing to an approach that is more iterative, which is done by having a queue of objects that need to be processed and going through that queue iteratively. Whenever the iterative step on an object requires the same step to be taken on another object (release or GC marking), then that object is added to the queue so it will be processed at a later stage.

## Limitations

Depending on the code, now you might hit out of memory issues instead of the game crashing due to a stack overflow. I intentionally tried to make a few changes to the rest of the squirrel code, so it's probably not all according to coding style. I rather leave the coding style fixes for Squirrel for another time, as not doing those makes it easier to see the differences between stock and our version of squirrel.
Freeing and GC marking can cause lags with such large amounts of elements, but that's inherent to such massive amounts of elements; millions in my test cases in debug builds. This makes both freeing and GC marking slightly slower, but the benefit is the game not crashing.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by LordAro** [comment]
Some warnings that need fixing (`override`), other than that, looks good

File: src/3rdparty/squirrel/squirrel/sqobject.h [hunk 1]
```diff
@@ -344,13 +345,48 @@ struct SQCollectable : public SQRefCounted {
...
 	static void AddToChain(SQCollectable **chain,SQCollectable *c);
 	static void RemoveFromChain(SQCollectable **chain,SQCollectable *c);
 };
 
+/**
+ * Helper container for state to change the garbage collection from a recursive to an iterative approach.
+ * The iterative approach provides effectively a depth first search approach.
+ */
+class SQGCMarkerQueue {
+	std::forward_list<SQCollectable*> queue; ///< The queue of elements to still process.
```
Comment (nielsmh) [inline src/3rdparty/squirrel/squirrel/sqobject.h]: I'd suggest benchmarking using a std::vector instead here. A linked list might have poor memory locality performance with lots of tiny allocations like this.

Comment (rubidium42) [reply src/3rdparty/squirrel/squirrel/sqobject.h]: Implementing the same logic as with the forward list decreases the performance of the GC marking by a factor of about ~2. Rethinking the logic to better suit the vector, i.e. the most recent elements are at the end instead of the begin, improves the performance by about a factor of ~2. This all in a debug build, but I would reckon the same effect holds for the release builds.

Going from a deque to a vector for the "free" queue is more cumbersome as it now requires some extra state information whether processing is happening or not (to prevent removing an element somewhere in the middle of the vector), though there the factor of ~2 improvement could be observed as well. So this suggestion definitely helped.

Testing was done with a custom AI that created a linked list of 500 000 elements, and a stacked array and table of depth 500 000, so 1.5 million objects in total. Then the average of 5 GC runs was taken (begin of CollectGarbage until the queue was empty), and for the Release just from setting _collectable_free_processing to true until setting it to false. All with a debug build on not sure powerful machine. 

GC marking:
* Forward list: 1676 ms
* Vector insert front, remove front: 3257 ms (~194% of original)
* Vector push back, pop back: 688 ms (~41% of original)

Free:
* Forward list: 2577
* Vector push back, pop back: 1466 (~57% of original)

**Review by LordAro — APPROVED** [review]
LGTM
