### PR TITLE
Switch town growth rate and counter to actual game ticks

### LINKED ISSUE #5827: Incorrect town growth rate ticks to days conversion
**__dp__ opened the ticket and wrote:**

> Formula used for days to ticks conversion is wrong ((growth_rate * TOWN_GROWTH_TICKS + DAY_TICKS) / DAY_TICKS) 
> It produces plausible result in most cases, but only because TOWN_GROWTH_TICKS is almost equal to DAY_TICKS.
> 
> Correct one will be ((growth_rate + 1) * TOWN_GROWTH_TICKS + DAY_TICKS / 2) / DAY_TICKS)
> Thus adding TOWN_GROWTH_TICKS instead of DAY_TICKS because that's how town growing works and extra DAY_TICKS / 2 for rounding.
> 
> That incorrect formula is also used in ScriptTown::GetGrowthRate and inverse(almost) formula in ScriptTown::SetGrowthRate is not quite correct too.

**Reported version**: _1.3.3_
**Operating system**: _All_

---

### PR DESCRIPTION
**Pull request by ldpl**
This is more of a groundwork type patch rather one doing something particularly useful. It's needed to be settled first as it changes inner workings of town growth and my other town patches are obviously affected by that. But to keep it simple I actually tried to make this patch change as little as possible and not focus on GS API or gameplay changes. Though some stuff still got fixed along the way.

There are three main reasons for this tick conversion
1. To allow towns to grow faster than 1 hous / 70 ticks
1. To allow more granularity of town growth speed where it matters (<30 days/house)
1. To make town growth more smooth and not affected by 70 tick steps or tick overflow.

So what it actually changes:
1. growth_rate and grow_counter now use actual game ticks instead of big town ticks (70 ticks). That makes effective range of growth speed 1-65100 ticks instead of 70-~2219980 (with step 70). So instead of 30000 days slowest growth speed is now 880 which is still plenty (and unreachable without GS as it only goes to about 400 normally).
1. Moves TOWN_GROWTH_RATE_CUSTOM to town flags. Just a nice thing to do as it frees one more bit for growth_rate and gets rid of &~TOWN_GROWTH_RATE_CUSTOM everywhere.
1. Fixes sligthly uneven growth of towns due to tick overflow issue (since 2**16 % 70 != 0 for some towns tick handlers were not called).
1. Fixes #5827 because, well, if in needs to be changed anyway why not do it right.
1. Makes days to ticks conversion in GS growth methods more precise. Had my doubts about this one, but technically it's just a bugfixing not API change since it just didn't do it right before. Having to emulate completely wrong old behaviour here seems even more weird to me.

What it does NOT change:
1. Does not significantly change normal town growth mechanics (without GS) including funding. In fact, except for a few minor things it should be tick-perfectly the same.
1. Does not really address #6378, as most of that code is still intact despite the tick switch.
1. Does not provide GS methods to fully take advantage of the new range to separate GS API stuff from this issue.
1. Still updates growth rate on monthly tick, so no #6397 for now.

### CODE REVIEW

File: src/saveload/saveload.cpp [hunk 1]
```diff
@@ -266,7 +266,7 @@
  *  196   27778   1.7.x
  *  197   27978   1.8.x
  */
```
Comment (LordAro) [inline src/saveload/saveload.cpp]: add PR# to comment when bumping revision? Probably needs some discussion

Comment (TrueBrain) [reply src/saveload/saveload.cpp]: `git blame` ftw? :)

Comment (ldpl) [reply src/saveload/saveload.cpp]: `git log -U0 -G "SAVEGAME_VERSION =" src/saveload/saveload.cpp`
And get rid of this pointless comment altogether

Comment (LordAro) [reply src/saveload/saveload.cpp]: Eh, loses a lot of otherwise easily findable history that way

Comment (ldpl) [reply src/saveload/saveload.cpp]: You mean openttd version history? Yeah, will be a bit trickier to get, but saves from the need for someone to constantly update the comment. Like how the hell am I even supposed to know what's next OpenTTD version is going to be?

Comment (frosch123) [reply src/saveload/saveload.cpp]: The important part here are the savegame versions of the stable branches.
The revisions are not important.

File: src/saveload/afterload.cpp [hunk 2]
```diff
@@ -2969,6 +2969,19 @@ bool AfterLoadGame()
...
+		/* Convert towns growth_rate and grow_counter to ticks */
+		Town *t;
+		FOR_ALL_TOWNS(t) {
+			/* 0x8000 = TOWN_GROWTH_RATE_CUSTOM previously */
+			if (t->growth_rate & 0x8000) SetBit(t->flags, TOWN_CUSTOM_GROWTH);
+			if (t->growth_rate != TOWN_GROWTH_RATE_NONE) {
+				t->growth_rate = TownTicksToGameTicks(t->growth_rate & ~0x8000);
+			}
+			/* Offset t->grow_counter by t->index to emulate original behaviour of spreading tick calls. */
+			t->grow_counter = TownTicksToGameTicks(t->grow_counter) + ((uint32)_tick_counter + t->index) % TOWN_GROWTH_TICKS;
```
Comment (frosch123) [inline src/saveload/afterload.cpp]: I would drop "_tick_counter" here.
It rather confuses than affects stuff.

File: src/town_cmd.cpp [hunk 3]
```diff
@@ -1565,8 +1563,10 @@ static void DoCreateTown(Town *t, TileIndex tile, uint32 townnameparts, TownSize
 	UpdateTownRadius(t);
 	t->flags = 0;
 	t->cache.population = 0;
-	t->grow_counter = 0;
-	t->growth_rate = 250;
+	/* Spread growth across ticks so even if there are many
+	 * similar towns they're unlikely to grow all at once */
+	t->grow_counter = ((uint32)_tick_counter + t->index) % TOWN_GROWTH_TICKS;
```
Comment (frosch123) [inline src/town_cmd.cpp]: Again, I would drop "_tick_counter" here.
It rather confuses than affects stuff.

**Review by frosch123 — CHANGES_REQUESTED** [review]

File: src/town.h [hunk 4]
```diff
@@ -284,6 +284,14 @@ void MakeDefaultName(T *obj)
 	obj->town_cn = (uint16)next; // set index...
 }
 
+/*
+ *
+ */
```
Comment (michicc) [inline src/town.h]: Some missing comment contents?

File: src/town_cmd.cpp (hunk 3 above)
Comment (ldpl) [reply src/town_cmd.cpp]: I actually don't like it from competitive CB perspective, but it makes sense since if you create a big map with a lot of towns many of them will have exact same growth_rate so will be growing in same tick which I assume can even be a bit laggy in some cases (haven't tested though). I was thinking of making default growth rate calculation to be smooth rather than jump in 50-house steps then it will probably be ok to remove this part but before that I'd leave it be.

Comment (ldpl) [reply src/town_cmd.cpp]: @frosch123 or did you mean drop _tick_counter but leave t->index? Yeah, that would probably work.

Comment (frosch123) [reply src/town_cmd.cpp]: Yes, leave t->index for the spreading of CPU resources.
But remove _tick_counter since it does not do anything.

File: src/town_cmd.cpp [hunk 5]
```diff
@@ -785,8 +785,8 @@ static void TownTickHandler(Town *t)
 			if (GrowTown(t)) {
 				i = t->growth_rate;
 			} else {
-				/* If growth failed wait TOWN_GROWTH_TICKS before retrying */
-				i = TOWN_GROWTH_TICKS - 1;
+				/* If growth failed wait a bit before retrying */
+				i = min(t->growth_rate, TOWN_GROWTH_TICKS - 1);
```
Comment (ldpl) [inline src/town_cmd.cpp]: Also reduced retry time as it was growing in waves on fast speeds.

File: src/saveload/saveload.cpp (hunk 1 above)
Comment (frosch123) [reply src/saveload/saveload.cpp]: Please don't add the 1.8.x. That's wrong.

**Comment by frosch123** [comment]
Please don't add the "1.8.x" to the savegame version. It won't be 1.8.x.

**Review by frosch123 — APPROVED** [review]
