### PR TITLE
Fix #15116: old cargo/industry sets without cargo translation table broken

### LINKED ISSUE #15116: [Bug]: Old industry sets without Cargo Translation Table are broken in OpenTTD 15
### Version of OpenTTD

master 20260116

### Expected result

As per https://www.tt-forums.net/viewtopic.php?t=92633 , the ancient 'Pikka's Basic Industry' newgrf no longer works properly.

### Actual result

Specifically, the cargos 'plastic' and 'fuel oil' - two non-default cargos - are not produced nor accepted by the industries they ought to be produced and accepted by. The 'UKRS Industries Brick Chain' newgrf has similar problems.

### Steps to reproduce

This is a very old newgrf and does not have a Cargo Translation Table. The issue is possibly caused by #12646 - and may not (imo) be worth trying to fix.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

As per #15116 and #15149, old cargo/industry NewGRFs that don't set up a cargo translation table are broken by the changes to translation tables since 14.1.

This results in a regression and savegames using these NewGRFs are no longer playable.

image

## Description

When a NewGRF sets cargo labels, install a fallback table if the NewGRF does not install one to give them a better chance of working.

image

## Limitations

Not heavily tested, but the industry chain in Pikka's Basic Industries looks correct.

Won't help really old sets that don't even set labels.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/newgrf/newgrf_act0_globalvar.cpp [hunk 1]
```diff
@@ -110,6 +110,8 @@ static ChangeInfoResult GlobalVarChangeInfo(uint first, uint last, int prop, Byt
 	/* Properties which are handled as a whole */
 	switch (prop) {
 		case 0x09: // Cargo Translation Table; loading during both reservation and activation stage (in case it is selected depending on defined cargos)
+			/* Explcitly defined cargo translation table means it's no longer a fallback list. LoadTranslationTable erases any existing list. */
```
Comment (michicc) [inline src/newgrf/newgrf_act0_globalvar.cpp]:
```suggestion
			/* Explicitly defined cargo translation table means it's no longer a fallback list. LoadTranslationTable erases any existing list. */
```

File: src/newgrf/newgrf_act0_globalvar.cpp [hunk 2]
```diff
@@ -336,6 +338,8 @@ static ChangeInfoResult GlobalVarReserveInfo(uint first, uint last, int prop, By
...
```
Comment (michicc) [inline src/newgrf/newgrf_act0_globalvar.cpp]:
```suggestion
			/* Explicitly defined cargo translation table means it's no longer a fallback list. LoadTranslationTable erases any existing list. */
```

**Review by michicc — APPROVED** [review]
