### PR TITLE
Fix #7625: Road infrastructure cost is correctly updated when upgrading your own roads.

### LINKED ISSUE #7625: Road infrastructure counts are not updated properly, free money exploit with infrastructure maintenance
## Version of OpenTTD
20190603-master-g846fc8fe09

## Expected result
Like rail infrastructure, road infrastructure counts should be updated properly when converting to different road types.

## Actual result
When you convert road types, the game does not properly change the numbers on the infrastructure piece counts for road, unlike rail. This can lead to:
* You don't have any infrastructure built but are paying thousands in infrastructure maintenance per year
* You have some infrastructure built but are not paying anything towards infrastructure maintenance or even getting an idle net profit from infrastructure maintenance. 
* Detailed infrastructure says that you have, for example, "Dirt Road: **-100**"

Note that all infrastructure counts are fixed on savegame load, so any server where one or more companies fell victim to this exploit just has to 1. save game, 2. load game, 3. reset affected bank balances (optional).

## Steps to reproduce
1. Load any NewGRF providing extra road types (examples: Unspooled, Docklands, RattRoads).
2. Start new game, with infrastructure maintenance enabled.
The following steps assume you have RattRoads loaded in your game.
3. Build some dirt roads.
4. Convert the dirt roads to highways.
5. Demolish the highways.
6. Repeat steps 3 through 5, but on a larger scale each time.
7. You should be getting lots of money despite having no infrastructure, no vehicles, and a nonnegative loan.

If you repeat steps 3 through 5 **in reverse order**, then you'll actually end up losing much more than the background loss rate of £300/yr (£25/mo) despite having nothing built, no vehicles, and no loan.

### PR DESCRIPTION
**Pull request by ddm999**
This fixes the road infrastructure cost issues, while still allowing the player to not have to pay maintenance on roads that are part of towns or scenarios (presumably this was the intent).

Also changes `CanConvertRoadType`'s name to `CanConvertUnownedRoadType` to make more sense for what it does. The odd name choice is probably how the bug originated in the first place.

(ignore the previous commit visible in the issue which previously fixed this, which I can't get rid of because I deleted the branch - thanks GitHub)

### CODE REVIEW

File: src/road_cmd.cpp [hunk 1]
```diff
@@ -2404,7 +2404,7 @@ CommandCost CmdConvertRoad(TileIndex tile, DoCommandFlag flags, uint32 p1, uint3
 
 			if (flags & DC_EXEC) { // we can safely convert, too
 				/* Update the company infrastructure counters. */
-				if (!IsRoadStopTile(tile) && CanConvertRoadType(owner, rtt) && owner != OWNER_TOWN) {
+				if (owner == _current_company) {
```
Comment (LordAro) [inline src/road_cmd.cpp]: is removing the `!IsRoadStopTile` check a good idea here?

Comment (nielsmh) [reply src/road_cmd.cpp]: Ping @ddm999, can you take a look at this again?

**Comment by andythenorth** [comment]
Thanks for this!

As there has been no activity on this PR for some, I'm proposing closing it in a few weeks if nothing more has changed, as we try to keep the PR count low. Thanks for contributing!

**Review by michicc — APPROVED** [review]
