### PR TITLE
Change: always allow to click on the toolbar icons for road/rail/dock/airport

### LINKED ISSUE #8055: Road Construction UI unavailable
If you start the game with Maximum number of road vehicles per company: 0, u cannot build any road, the button is just greyed out and disabled. If you go into settings while in that game and set the number of vehicles to 100, the road construction becomes available and u can build road, but if you go back into settings set the road vehicle limit back to 0 WITHOUT closing the ROAD CONSTRUCTION UI the game just crashes.

## Version of OpenTTD
openttd-1.10.0-windows-win64.exe

## Expected result
To be able to do road construction even tho the allowed road vehicle per company is set to 0

## Actual result
The road construction is greyed out, if road vehicle per company is set to 0. Also crashes OpenTTD if you leave the Road Construction UI on, while going into Settings to change road vehicles per company 100 -> 0.

## Steps to reproduce
1. Create any game with Limitations -> Maximum number of road vehicles per company: 0
2. Go into Settings while in the created game.
3. Find Limitations -> Maximum Number of road vehicles per company, set it to 100
4. Road Construction becomes available, select it, build some road whatever doesnt matter.
5. Do not close Road Construction UI.
6. Go back into Settings -> Limitations -> Maximum number of road vehicles per company, set it back 100 -> 0.
7. Game crashes.

### PR DESCRIPTION
**Pull request by TrueBrain**
Fixes #8055.
Closes #8063.

## Motivation / Problem

This is my take on #8055. I somewhat disagree with comments made in #8063, and I think not allowing people to build roads when the server has max-road-vehicles set to zero is silly. Expecting the user to change a GUI setting before he can, I do not see the point in that.

## Description

This change allows a user to see what is available and what will become
available before it is available, instead of only disabling the button
with no further explanation. It also always allows building roads and
canals, even if no vehicles are available for road / water.

For rail/road/tram, a dropdown with available types is shown. If
none are available, it reads "None". If the type is not yet available,
it is greyed out.

For dock/airport, this always open the toolbar, but building airports,
docks, and depots buttons are disabled till vehicles are available
for those.

Road is the only exception, with the primary road always being
available. Here too, stations and depots are disabled till vehicles
become available. It does mean you can now always build roads to
for example help towns grow.

Disabled buttons show on their tooltip why they are disabled.

Imported 2 commits from #8063. With the removing of `disable_unsuitable_building` setting, `CanBuildVehicleInfrastructure()` now does much more what the name suggest, and how it is, with this PR, used in the code.

image

## Limitations

- I did make this consistent, which means that for airports this is slightly weird.
- Removing the `disable_unsuitable_building` setting means there is now no way to already start building rail before engines are available. This might result in some people complaining about that.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/dock_gui.cpp [hunk 1]
```diff
@@ -125,6 +125,15 @@ struct BuildDocksToolbarWindow : Window {
 		if (!can_build) {
 			DeleteWindowById(WC_BUILD_STATION, TRANSPORT_WATER);
 			DeleteWindowById(WC_BUILD_DEPOT, TRANSPORT_WATER);
+
+			/* Show in the tooltip why this button is disabled. */
+			this->GetWidget<NWidgetCore>(WID_DT_DEPOT)->SetDataTip(SPR_IMG_AIRPORT, STR_TOOLBAR_DISABLED_NO_VEHICLE_AVAILABLE);
```
Comment (frosch123) [inline src/dock_gui.cpp]: docks are not airports :)

Comment (TrueBrain) [reply src/dock_gui.cpp]: haha, ooopppsssss ... did it show where I copy/pasted? :D :D

**Comment by hpiirai** [comment]
I can see one problem with this change: Road stops can be useful for extending the coverage area of a station. This version removes that functionality when, for example, ships are available, but road vehicles are not.

**Comment by TrueBrain** [comment]
> 
> 
> I can see one problem with this change: Road stops can be useful for extending the coverage area of a station. This version removes that functionality when, for example, ships are available, but road vehicles are not.

So your complaint is that you can no longer by cheesy with road stations? :D

I guess what you mention is true, if you knew the GUI option, you could profit from this. Not sure it is a bad thing that we put everyone on the same level here. From a gameplay perspective, do you think this is a loss of functionality? Or more in the lines of fixing a way you could somewhat abuse the game? (honest question, looking for opinions)

**Comment by hpiirai** [comment]
I don’t really have an opinion on this. I can live without this slight abuse of the game, but I might believe that there are people who think otherwise.

File: src/airport_gui.cpp [hunk 2]
```diff
@@ -71,6 +71,7 @@ struct BuildAirToolbarWindow : Window {
 	BuildAirToolbarWindow(WindowDesc *desc, WindowNumber window_number) : Window(desc)
 	{
 		this->InitNested(window_number);
+		this->OnInvalidateData();
```
Comment (LordAro) [inline src/airport_gui.cpp:74]: why is this necessary?

Comment (TrueBrain) [reply src/airport_gui.cpp:74]: 1) consistency with all the other Toolbar GUIs
2) without it, `OnInvalidateData` is not called when opening the toolbar, not updating properly

Not sure if there are better ways, I just stole it from the other Toolbar GUIs honestly :)

**Comment by frosch123** [comment]
For that purpose there are station NewGRF which add station tiles that look like regular houses. Point them to those instead.

File: src/road_gui.cpp [hunk 3]
```diff
@@ -303,8 +303,28 @@ struct BuildRoadToolbarWindow : Window {
...
+			DeleteWindowById(WC_BUS_STATION, TRANSPORT_ROAD);
+			DeleteWindowById(WC_TRUCK_STATION, TRANSPORT_ROAD);
+			DeleteWindowById(WC_BUILD_DEPOT, TRANSPORT_ROAD);
+
+			/* Show in the tooltip why this button is disabled. */
+			this->GetWidget<NWidgetCore>(WID_ROT_DEPOT)->SetDataTip(SPR_IMG_ROAD_DEPOT, STR_TOOLBAR_DISABLED_NO_VEHICLE_AVAILABLE);
+			this->GetWidget<NWidgetCore>(WID_ROT_BUS_STATION)->SetDataTip(SPR_IMG_BUS_STATION, STR_TOOLBAR_DISABLED_NO_VEHICLE_AVAILABLE);
+			this->GetWidget<NWidgetCore>(WID_ROT_TRUCK_STATION)->SetDataTip(SPR_IMG_TRUCK_BAY, STR_TOOLBAR_DISABLED_NO_VEHICLE_AVAILABLE);
+		} else {
+			this->GetWidget<NWidgetCore>(WID_ROT_DEPOT)->SetDataTip(SPR_IMG_ROAD_DEPOT, rtt == RTT_ROAD ? STR_ROAD_TOOLBAR_TOOLTIP_BUILD_ROAD_VEHICLE_DEPOT : STR_ROAD_TOOLBAR_TOOLTIP_BUILD_TRAM_VEHICLE_DEPOT);
```
Comment (frosch123) [inline src/road_gui.cpp]: The depot sprite is roadtype specific. See SetupRoadToolbar().

**Comment by 2TallTyler** [comment]
Station tiles would require trains to be available. In my experience, the most common edge case where only ships and/or aircraft are available is a year 1700 start game using the Sailing Ships NewGRF. But there are several road vehicle sets which offer horse-drawn road vehicles at these early dates, including eGRVTS and Timberwolf's Road Vehicles, so I'm not sure this is a huge concern. I can't think of any scenarios where only aircraft would be available!

**Review by frosch123 — APPROVED** [review]

**Comment by James103** [comment]
@2TallTyler An example would be if you load up the following newgrf (and nothing else) and start in 1700:
```
[game_creation]
starting_year = 1700

[newgrf]
54540101|E8E0A1499127415BF8D2F6AA0B065083|kaaskrokets_fictional_aircraft-1.0.2\kaas_planes.grf = 16777215
```
