### PR TITLE
Fix #10161: Ignore ascender in FallbackLayouter for non-built-in fonts.

### LINKED ISSUE #10161: [Bug]: The texts are out of place with true type fonts
### Version of OpenTTD

OpenTTD 20221112-master-gced4258969

### Expected result

The text are readable like with the sprite fonts.

Something like this:
sprite_font

### Actual result

The texts are unreadable with true type fonts.

tt_font

### Steps to reproduce

- Set system fonts in openttd.cfg.
- Start OpenTTD

### Additional info

Os: Fedora 36

./openttd -d driver=3:
dbg: [driver] Successfully loaded blitter '32bpp-anim'
dbg: [driver] Resolution for display: 1920x1057
dbg: [driver] SDL2: Mouse is at (684, 655), use display 0 (0, 0, 1920, 1080)
dbg: [driver] SDL2: using mode 1920x1057
dbg: [driver] SDL2: using driver 'x11'
dbg: [driver] OpenGL driver: NVIDIA Corporation - NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 (4.6.0 NVIDIA 520.56.06)
dbg: [driver] OpenGL: Using persistent buffer mapping
dbg: [driver] OpenGL shading language version: 4.60 NVIDIA, texture units = 192
dbg: [driver] Successfully probed video driver 'sdl-opengl'
dbg: [misc] String too long for destination buffer
dbg: [driver] Successfully probed sound driver 'sdl'
dbg: [driver] Successfully probed music driver 'extmidi'
dbg: [driver] using thread for game-loop
dbg: [driver] Switching blitter from '32bpp-anim' to '40bpp-anim'... 
dbg: [driver] Successfully loaded blitter '40bpp-anim'
dbg: [driver] Successfully switched to 40bpp-anim.
dbg: [driver] SDL2: using mode 1920x1057
dbg: [driver] extmidi: set volume not implemented

openttd.cfg snippet:
small_font = Liberation Sans
medium_font = DejaVu Sans
large_font = Liberation Serif
mono_font = Liberation Mono
small_size = 12
medium_size = 16
large_size = 26
mono_size = 14
small_aa = true
medium_aa = true
large_aa = true
mono_aa = true

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

Font "ascender" was incorrect applied for FreeType fonts.

This is because, unlike Windows and OS X layouters, fallback layouters is used for both FreeType and sprite fonts, and doesn't know the difference between the two.

## Description

This is resolved by checking if the FontCache in use is built in, and applying adjustments based on the ascender appropriately.

This also aligns the sprite font with the bottom of TrueType fonts for FreeType, as is already done in Windows but was missing with FreeType.

## Limitations

This is a bit hacky as really the adjustment to be used should be provided by the FontCache directly but the FontCache inheritence doesn't really allow that.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/gfx_layout.cpp [hunk 1]
```diff
@@ -333,18 +333,25 @@ class FallbackParagraphLayoutFactory {
...
 		this->glyphs[i] = font->fc->MapCharToGlyph(chars[i]);
+		if (isbuiltin) {
+			this->positions[2 * i + 1] = font->fc->GetAscender();                                                   // Apply sprite font's ascender.
+		} else if (chars[i] >= SCC_SPRITE_START && chars[i] <= SCC_SPRITE_END) {
+			this->positions[2 * i + 1] = font->fc->GetAscender() - font->fc->GetGlyph(this->glyphs[i])->height - 1; // Align sprite glyphs to font baseline.
+		} else {
+			this->positions[2 * i + 1] = 0;                                                                         // No ascender adjustment.
+		}
 		this->positions[2 * i + 2] = this->positions[2 * i] + font->fc->GetGlyphWidth(this->glyphs[i]);
-		this->positions[2 * i + 3] = font->fc->GetAscender();
```
Comment (michicc) [inline src/gfx_layout.cpp:347]: The previous code wrote the ascender info to `2 * this->glyph_count + 1`, but the new code doesn't.

Admittedly, I haven't look at the uses of this info, so maybe that one-after-the end is unused anyway and was just a loop artifact.

Comment (PeterN) [reply src/gfx_layout.cpp:347]: It previously just wrote all 0s there, but now that it can vary it does matter that it's in the right place.

In `DrawLayoutLine()` there's no +3 when `GetPositions()` is called.

**Review by michicc — APPROVED** [review]
