### PR TITLE
Fix #14723: Set force proceed to TFP_SIGNAL if next tile has signals.

### LINKED ISSUE #14721: [Bug]: Force no stop on signals button does not change after pressed
### Version of OpenTTD

https://github.com/OpenTTD/OpenTTD/commit/9f7f314f8152e4a67202ad0a8d02d5a5ea8b2908  Debian 12

### Expected result

Train 17 should behave the same as the train 18.

### Actual result

https://github.com/user-attachments/assets/e32d7047-ecd7-489f-8c33-11fd60497c55

### Steps to reproduce

1. Pause game
2. Press the button on train that is waiting before signal

[Train loads at diffrent station than it should.zip](https://github.com/user-attachments/files/23001945/Train.loads.at.diffrent.station.than.it.should.zip)

### LINKED ISSUE #14723: [Bug]: Skip signal on PBS is inconsistent when train is waiting
### Version of OpenTTD

15.0 beta-3, windows 10

### Expected result

When train is waiting on PBS, skip signal button on the first click (same as with the block signal)

### Actual result

To actually skip the signal, you need to click it at least twice. At first click, train will change it's "current action" from orange "waiting on signal" to blue "heading to X" for some time before changing back to "waiting on signal". You need to press the button a second time while the train is in the "heading to X" state. The faster/more powerful the train, the more difficult this is. It somewhat doable on monorail, but Maglev Lev1 already requires macro/autoclick to skip signal

https://github.com/user-attachments/assets/138f6e90-9a26-476a-a0d5-31098ed07421

It works as expected only if you press this button while the train is already moving.

https://github.com/user-attachments/assets/eb6cc03f-fe65-4cef-a810-661c47f15945

The problem initially appears in #14721 as an interface defect, but it seems to me that the interface in this case works more or less as expected, and the problem is in the action itself.

### Steps to reproduce

[skip on pbs bugreport.zip](https://github.com/user-attachments/files/23006427/skip.on.pbs.bugreport.zip)

1. Create a closed PBS. Self-crossign loop or just a train in front – does not matter.
2. Send a train on this closed pbs
4. Try to skip it with "skip signal" button

### PR DESCRIPTION
**Pull request by Rito13**
## Motivation / Problem

Fixes #14723 and Fixes #14721

`t->force_proceed` is being set to TFP_STUCK whenever the train is marked as stuck.
But when train stops before signal it is also marked as stuck.
Setting `t->force_proceed` to TFP_STUCK in such situation does not allow train to proceed,
because it needs `t->force_proceed == TFP_SIGNAL` in order to skip red/oneway signals.

## Description

Check if the next tile has signals. 
If yes consider the train to be stuck because of signal. Set then the `t->force_proceed` to TFP_SIGNAL. 

## Limitations

The train gets TFP_SIGNAL even if the signal is not on the track that train will follow.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by PeterN** [comment]
Your commit title/description says the what, but not the why.

File: src/train_cmd.cpp [hunk 1]
```diff
@@ -2160,7 +2160,17 @@ CommandCost CmdForceTrainProceed(DoCommandFlags flags, VehicleID veh_id)
 		 * to proceed to the next signal. In the other cases we
 		 * would like to pass the signal at danger and run till the
 		 * next signal we encounter. */
-		t->force_proceed = t->force_proceed == TFP_SIGNAL ? TFP_NONE : t->flags.Test(VehicleRailFlag::Stuck) || t->IsChainInDepot() ? TFP_STUCK : TFP_SIGNAL;
+		if (t->force_proceed == TFP_SIGNAL) {
+			t->force_proceed = TFP_NONE;
+		} else if (t->flags.Test(VehicleRailFlag::Stuck)) {
+			TileIndex next_tile = TileAddByDiagDir(t->tile, TrackdirToExitdir(t->GetVehicleTrackdir()));
+			if (next_tile == INVALID_TILE) t->force_proceed = TFP_STUCK;
+			else {
```
Comment (rubidium42) [inline src/train_cmd.cpp]: Coding style: if using an else, then you may not use the `if` without brackets.
```suggestion
			if (next_tile == INVALID_TILE) {
				t->force_proceed = TFP_STUCK;
			} else {
```

Alternatively, if you move this code to a separate function, you can reduce the number of brackets significantly and eliminate the else branches. If you choose to go this path, please do incorporate the preceding comments in the Doxygen-documentation of the function.
```
static TrainForceProceeding DetermineNextTrainForceProceeding(const Train *t)
{
    if (t->force_proceed == TFP_SIGNAL) return TFP_NONE;
    if (!t->flags.Test(VehicleRailFlag::Stuck)) return t->IsChainInDepot() ? TFP_STUCK : TFP_SIGNAL;
    
    TileIndex next_tile = TileAddByDiagDir(t->tile, TrackdirToExitdir(t->GetVehicleTrackdir()));
    if (next_tile == INVALID_TILE) return t->force_proceed = TFP_STUCK;
    return IsTileType(next_tile, MP_RAILWAY) && HasSignals(next_tile) ? TFP_SIGNAL : TFP_STUCK;
}
```

Comment (Rito13) [reply src/train_cmd.cpp]: I went for the helper function, because in my opinion it is more readable.

**Review by rubidium42 — DISMISSED** [review]

**Review by rubidium42 — DISMISSED** [review]

File: src/train_cmd.cpp [hunk 2]
```diff
@@ -2137,6 +2137,26 @@ CommandCost CmdReverseTrainDirection(DoCommandFlags flags, VehicleID veh_id, boo
...
+ * @return The next state of force_proceed.
+ */
+static TrainForceProceeding DetermineNextTrainForceProceeding(const Train *t)
+{
+	if (t->force_proceed == TFP_SIGNAL) return TFP_NONE;
+	if (!t->flags.Test(VehicleRailFlag::Stuck)) return t->IsChainInDepot() ? TFP_STUCK : TFP_SIGNAL;
+
+	TileIndex next_tile = TileAddByDiagDir(t->tile, TrackdirToExitdir(t->GetVehicleTrackdir()));
+	if (next_tile == INVALID_TILE) return TFP_STUCK;
+	return IsTileType(next_tile, MP_RAILWAY) && HasSignals(next_tile) ? TFP_SIGNAL : TFP_STUCK;
```
Comment (michicc) [inline src/train_cmd.cpp]: This would return TPF_SIGNAL on any straight tile with two parallel tracks, even if the signal is on the wrong parallel track, wouldn't it?

YMMV if that is a problem, but some new function that checks only the tracks reachable from a certain enter/exitdir would solve that. Might be too much effort for the use though 🤷

Comment (Rito13) [reply src/train_cmd.cpp]: > This would return TPF_SIGNAL on any straight tile with two parallel tracks, even if the signal is on the wrong parallel track, wouldn't it?

Yes, it was already noticed in the "Limitations".

> YMMV if that is a problem, but some new function that checks only the tracks reachable from a certain enter/exitdir would solve that. Might be too much effort for the use though 🤷

It is a problem in the following situation, consider the purple train to be stopped and the red one to be moving.
Red train is going to enter the depot and get stuck there, when force proced is send to it, it will go out, skip the first signal and crash into the purple one.
Zrzut ekranu z 2025-12-06 11-56-52
The problem does not appear when the rightmost signal does not exist.

Comment (michicc) [reply src/train_cmd.cpp]: Something like this maybe (fully untested, written purely from memory):
```c++
return IsTileType(next_tile, MP_RAILWAY) && HasSignals(next_tile) && HasSignalOnTrack(FindFirstTrack(DiagdirReachesTracks(exitdir))) ? TFP_SIGNAL : TFP_STUCK;
```

Relies on the fact that tiles with signals will only ever have one reachable signal.

EDIT: On second though, `FindFirstTrack` results needs to be validated in case the train somehow got marked stuck with no track actually exiting the tile in the right direction.

Comment (Rito13) [reply src/train_cmd.cpp]: Yes, that fixes the problem.

File: src/train_cmd.cpp [hunk 3]
```diff
@@ -2137,6 +2137,27 @@ CommandCost CmdReverseTrainDirection(DoCommandFlags flags, VehicleID veh_id, boo
...
+ */
+static TrainForceProceeding DetermineNextTrainForceProceeding(const Train *t)
+{
+	if (t->force_proceed == TFP_SIGNAL) return TFP_NONE;
+	if (!t->flags.Test(VehicleRailFlag::Stuck)) return t->IsChainInDepot() ? TFP_STUCK : TFP_SIGNAL;
+
+	TileIndex next_tile = TileAddByDiagDir(t->tile, TrackdirToExitdir(t->GetVehicleTrackdir()));
+	if (next_tile == INVALID_TILE || !IsTileType(next_tile, MP_RAILWAY) || !HasSignals(next_tile)) return TFP_STUCK;
+	TrackBits new_tracks = DiagdirReachesTracks(TrackdirToExitdir(t->GetVehicleTrackdir())) & GetTrackBits(next_tile);
+	return HasSignalOnTrack(next_tile, FindFirstTrack(new_tracks)) ? TFP_SIGNAL : TFP_STUCK;
```
Comment (michicc) [inline src/train_cmd.cpp]: Not sure if this is actually possible, but maybe a just-in-case check for a train sitting at a dead end:
```suggestion
	return new_tracks != TRACK_BIT_NONE && HasSignalOnTrack(next_tile, FindFirstTrack(new_tracks)) ? TFP_SIGNAL : TFP_STUCK;
```

Comment (Rito13) [reply src/train_cmd.cpp]: > Not sure if this is actually possible, but maybe a just-in-case check for a train sitting at a dead end:

Train does not get stuck at dead end.
When tracks are removed before a stuck train it automatically gets unstuck and reversed.

Although it does not do that when the game is paused, and yes, then I get a assert failure.

**Review by michicc — DISMISSED** [review]

**Review by PeterN — APPROVED** [review]
