### PR TITLE
Add: make modal windows update more smooth and fix "closing the app" issues closely related to this.

### LINKED ISSUE #8760: Game asserts/crashes when closed during newgrf scan
## Version of OpenTTD

master(4fd2eecb8b21f59b986b9738fd208bcd6f668448)

## Expected result

ehm... may be not crash?

## Actual result
```
openttd: /home/pavels/Projects/OpenTTD/src/fileio.cpp:97: void FioSeekToFile(uint8, size_t): Assertion `f != nullptr' failed.

Thread 5 "openttd" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff0f89700 (LWP 2977492)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7271859 in __GI_abort () at abort.c:79
#2  0x00007ffff7271729 in __assert_fail_base (fmt=0x7ffff7407588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x55555642e96d "f != nullptr", 
    file=0x55555642e940 "/home/pavels/Projects/OpenTTD/src/fileio.cpp", line=97, function=<optimized out>) at assert.c:92
#3  0x00007ffff7282f36 in __GI___assert_fail (assertion=0x55555642e96d "f != nullptr", file=0x55555642e940 "/home/pavels/Projects/OpenTTD/src/fileio.cpp", line=97, 
    function=0x55555642e918 "void FioSeekToFile(uint8, size_t)") at assert.c:101
#4  0x0000555555d698c0 in FioSeekToFile (slot=2 '\002', pos=1879496) at /home/pavels/Projects/OpenTTD/src/fileio.cpp:97
#5  0x0000555555cbd4f5 in LoadSpriteV2 (sprite=0x7ffff0f87a60, file_slot=2 '\002', file_pos=1879496, sprite_type=ST_FONT, load_32bpp=true)
    at /home/pavels/Projects/OpenTTD/src/spriteloader/grf.cpp:252
#6  0x0000555555cbd916 in SpriteLoaderGrf::LoadSprite (this=0x7ffff0f87a50, sprite=0x7ffff0f87a60, file_slot=2 '\002', file_pos=1879496, sprite_type=ST_FONT, load_32bpp=true)
    at /home/pavels/Projects/OpenTTD/src/spriteloader/grf.cpp:323
#7  0x0000555555f870a3 in ReadSprite (sc=0x55555b7ee990, id=53, sprite_type=ST_FONT, allocator=0x555555f87d91 <AllocSprite(size_t)>, encoder=0x555558a81390)
    at /home/pavels/Projects/OpenTTD/src/spritecache.cpp:441
#8  0x0000555555f8816c in GetRawSprite (sprite=53, type=ST_FONT, allocator=0x0, encoder=0x0) at /home/pavels/Projects/OpenTTD/src/spritecache.cpp:897
#9  0x0000555555f87ef3 in HandleInvalidSpriteRequest (sprite=53, requested=ST_FONT, sc=0x55555b7ee990, allocator=0x0) at /home/pavels/Projects/OpenTTD/src/spritecache.cpp:841
#10 0x0000555555f8810e in GetRawSprite (sprite=53, type=ST_FONT, allocator=0x0, encoder=0x0) at /home/pavels/Projects/OpenTTD/src/spritecache.cpp:888
#11 0x0000555555d7d087 in GetSprite (sprite=53, type=ST_FONT) at /home/pavels/Projects/OpenTTD/src/spritecache.h:43
#12 0x0000555555d7d937 in SpriteFontCache::GetGlyphWidth (this=0x5555583ed7d0, key=1073741907) at /home/pavels/Projects/OpenTTD/src/fontcache.cpp:193
#13 0x0000555555da22be in FallbackParagraphLayout::FallbackVisualRun::FallbackVisualRun (this=0x7fffbc34f7a0, font=0x7fffbc351780, chars=0x7fffbc3626d0 U"Scanning NewGRFs", 
    char_count=16, x=0) at /home/pavels/Projects/OpenTTD/src/gfx_layout.cpp:346
#14 0x0000555555da8518 in __gnu_cxx::new_allocator<FallbackParagraphLayout::FallbackVisualRun>::construct<FallbackParagraphLayout::FallbackVisualRun, Font*&, char32_t const*&, long, int&> (this=0x7fffbc350298, __p=0x7fffbc34f7a0) at /usr/include/c++/9/ext/new_allocator.h:147
#15 0x0000555555da6712 in std::allocator_traits<std::allocator<FallbackParagraphLayout::FallbackVisualRun> >::construct<FallbackParagraphLayout::FallbackVisualRun, Font*&, char32_t const*&, long, int&> (__a=..., __p=0x7fffbc34f7a0) at /usr/include/c++/9/bits/alloc_traits.h:484
#16 0x0000555555da684b in std::vector<FallbackParagraphLayout::FallbackVisualRun, std::allocator<FallbackParagraphLayout::FallbackVisualRun> >::_M_realloc_insert<Font*&, char32_t const*&, long, int&> (this=0x7fffbc350298, __position=non-dereferenceable iterator for std::vector) at /usr/include/c++/9/bits/vector.tcc:449
#17 0x0000555555da4f74 in std::vector<FallbackParagraphLayout::FallbackVisualRun, std::allocator<FallbackParagraphLayout::FallbackVisualRun> >::emplace_back<Font*&, char32_t const*&, long, int&> (this=0x7fffbc350298) at /usr/include/c++/9/bits/vector.tcc:121
#18 0x0000555555da2c50 in FallbackParagraphLayout::NextLine (this=0x7fffbc350100, max_width=2147483647) at /home/pavels/Projects/OpenTTD/src/gfx_layout.cpp:588
#19 0x0000555555da2e62 in Layouter::Layouter (this=0x7ffff0f87fe0, str=0x7ffff0f88054 "", maxw=2147483647, colour=TC_BEGIN, fontsize=FS_NORMAL)
    at /home/pavels/Projects/OpenTTD/src/gfx_layout.cpp:735
#20 0x0000555555d95af9 in GetStringBoundingBox (str=0x7ffff0f88040 "Scanning NewGRFs", start_fontsize=FS_NORMAL) at /home/pavels/Projects/OpenTTD/src/gfx.cpp:844
#21 0x0000555555d95baf in GetStringBoundingBox (strid=2611) at /home/pavels/Projects/OpenTTD/src/gfx.cpp:859
#22 0x00005555560a0c12 in NWidgetLeaf::SetupSmallestSize (this=0x7fffbc3503d0, w=0x7fffbc3502f0, init_array=true) at /home/pavels/Projects/OpenTTD/src/widget.cpp:2362
#23 0x000055555609cb86 in NWidgetVertical::SetupSmallestSize (this=0x7fffbc07d4e0, w=0x7fffbc3502f0, init_array=true) at /home/pavels/Projects/OpenTTD/src/widget.cpp:1318
#24 0x00005555560a68ec in Window::InitializeData (this=0x7fffbc3502f0, window_number=1) at /home/pavels/Projects/OpenTTD/src/window.cpp:1480
#25 0x00005555560a7a3f in Window::FinishInitNested (this=0x7fffbc3502f0, window_number=1) at /home/pavels/Projects/OpenTTD/src/window.cpp:1850
#26 0x00005555560a7b4d in Window::InitNested (this=0x7fffbc3502f0, window_number=1) at /home/pavels/Projects/OpenTTD/src/window.cpp:1864
#27 0x0000555555ea1fac in ScanProgressWindow::ScanProgressWindow (this=0x7fffbc3502f0) at /home/pavels/Projects/OpenTTD/src/newgrf_gui.cpp:2186
#28 0x0000555555e97e55 in UpdateNewGRFScanStatus (num=478, name=0x7fffbc34fe38 "TIAS 1.7-alpha") at /home/pavels/Projects/OpenTTD/src/newgrf_gui.cpp:2271
#29 0x0000555555e7d94c in GRFFileScanner::AddFile (this=0x7ffff0f88bb0, filename="toei_interconnection_addon_set-1.7alpha/tias.grf", basepath_length=0, 
    tar_filename="/home/pavels/.openttd/content_download/newgrf/54420101-Toei_Inter_connection_Add_on_Se-1.7_al.tar") at /home/pavels/Projects/OpenTTD/src/newgrf_config.cpp:647
#30 0x0000555555d6e0cb in ScanTar (fs=0x7ffff0f88bb0, extension=0x5555564f6249 ".grf", Python Exception <class 'AttributeError'> 'NoneType' object has no attribute 'pointer': 
tar=...) at /home/pavels/Projects/OpenTTD/src/fileio.cpp:1353
#31 0x0000555555d6e280 in FileScanner::Scan (this=0x7ffff0f88bb0, extension=0x5555564f6249 ".grf", sd=NEWGRF_DIR, tars=true, recursive=true)
    at /home/pavels/Projects/OpenTTD/src/fileio.cpp:1385
#32 0x0000555555e7e740 in GRFFileScanner::DoScan () at /home/pavels/Projects/OpenTTD/src/newgrf_config.cpp:596
#33 0x0000555555e7da84 in DoScanNewGRFFiles (callback=0x555558401410) at /home/pavels/Projects/OpenTTD/src/newgrf_config.cpp:685
#34 0x0000555555e7effa in StartNewThread<void (*)(NewGRFScanCallback*), NewGRFScanCallback*>(std::thread*, char const*, void (*&&)(NewGRFScanCallback*), NewGRFScanCallback*&&)::{lambda(char const*, void (*&&)(NewGRFScanCallback*), NewGRFScanCallback*&&)#1}::operator()(char const*, void (*&&)(NewGRFScanCallback*), NewGRFScanCallback*&&) const (this=0x55555b95fbd8, 
    name=0x5555564f6281 "ottd:newgrf-scan", F=@0x55555b95fbe0: 0x555555e7da14 <DoScanNewGRFFiles(NewGRFScanCallback*)>, A#0=@0x55555b95fbd8: 0x555558401410)
    at /home/pavels/Projects/OpenTTD/src/thread.h:56
#35 0x0000555555e83840 in std::__invoke_impl<void, StartNewThread<void (*)(NewGRFScanCallback*), NewGRFScanCallback*>(std::thread*, char const*, void (*&&)(NewGRFScanCallback*), NewGRFS--Type <RET> for more, q to quit, c to continue without paging-- 
canCallback*&&)::{lambda(char const*, void (*&&)(NewGRFScanCallback*), NewGRFScanCallback*&&)#1}, char const*, void (*)(NewGRFScanCallback*), NewGRFScanCallback*>(std::__invoke_other, StartNewThread<void (*)(NewGRFScanCallback*), NewGRFScanCallback*>(std::thread*, char const*, void (*&&)(NewGRFScanCallback*), NewGRFScanCallback*&&)::{lambda(char const*, void (*&&&&)(NewGRFScanCallback*), NewGRFScanCallback*&&)#1}, char const*&&, void (*&&)(NewGRFScanCallback*), NewGRFScanCallback*&&) (__f=...) at /usr/include/c++/9/bits/invoke.h:60
#36 0x0000555555e83718 in std::__invoke<StartNewThread<void (*)(NewGRFScanCallback*), NewGRFScanCallback*>(std::thread*, char const*, void (*&&)(NewGRFScanCallback*), NewGRFScanCallback*&&)::{lambda(char const*, void (*&&)(NewGRFScanCallback*), NewGRFScanCallback*&&)#1}, char const*, void (*)(NewGRFScanCallback*), NewGRFScanCallback*> (__fn=...)
    at /usr/include/c++/9/bits/invoke.h:95
#37 0x0000555555e835f7 in std::thread::_Invoker<std::tuple<StartNewThread<void (*)(NewGRFScanCallback*), NewGRFScanCallback*>(std::thread*, char const*, void (*&&)(NewGRFScanCallback*), NewGRFScanCallback*&&)::{lambda(char const*, void (*&&)(NewGRFScanCallback*), NewGRFScanCallback*&&)#1}, char const*, void (*)(NewGRFScanCallback*), NewGRFScanCallback*> >::_M_invoke<0ul, 1ul, 2ul, 3ul>(std::_Index_tuple<0ul, 1ul, 2ul, 3ul>) (this=0x55555b95fbd8) at /usr/include/c++/9/thread:244
#38 0x0000555555e83576 in std::thread::_Invoker<std::tuple<StartNewThread<void (*)(NewGRFScanCallback*), NewGRFScanCallback*>(std::thread*, char const*, void (*&&)(NewGRFScanCallback*), NewGRFScanCallback*&&)::{lambda(char const*, void (*&&)(NewGRFScanCallback*), NewGRFScanCallback*&&)#1}, char const*, void (*)(NewGRFScanCallback*), NewGRFScanCallback*> >::operator()() (this=0x55555b95fbd8) at /usr/include/c++/9/thread:251
#39 0x0000555555e83556 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<StartNewThread<void (*)(NewGRFScanCallback*), NewGRFScanCallback*>(std::thread*, char const*, void (*&&)(NewGRFScanCallback*), NewGRFScanCallback*&&)::{lambda(char const*, void (*&&)(NewGRFScanCallback*), NewGRFScanCallback*&&)#1}, char const*, void (*)(NewGRFScanCallback*), NewGRFScanCallback*> > >::_M_run() (this=0x55555b95fbd0) at /usr/include/c++/9/thread:195
#40 0x00007ffff7680d84 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#41 0x00007ffff7794609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#42 0x00007ffff736e293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

## Steps to reproduce

0. Download everything from bananas ;)
1. Start the game
2. Quickly close the window before newgrf scan finishes

### LINKED ISSUE #8833: Crash when closing game when manually triggered NewGRF scan in operation
## Version of OpenTTD
master (b21ba566a)

SDL2 on Linux (with default OpenGL driver and blitter)

## Expected result
No crash when closing game when manually triggered NewGRF scan in operation

## Actual result
```
Thread 1 "openttd" received signal SIGSEGV, Segmentation fault.
0x00005555663e48eb in VideoDriver_SDL_OpenGL::ClearSystemSprites (this=0x61a000000680) at /home/jgr/misc/openttd-6/src/video/sdl2_opengl_v.cpp:120
120		OpenGLBackend::Get()->ClearCursorCache();
(gdb) bt
#0  0x00005555663e48eb in VideoDriver_SDL_OpenGL::ClearSystemSprites (this=0x61a000000680) at /home/jgr/misc/openttd-6/src/video/sdl2_opengl_v.cpp:120
#1  0x0000555566a0ae66 in GfxLoadSprites () at /home/jgr/misc/openttd-6/src/gfxinit.cpp:335
#2  0x00005555661e94c9 in ReloadNewGRFData () at /home/jgr/misc/openttd-6/src/saveload/afterload.cpp:3165
#3  0x0000555567070d5f in NewGRFWindow::~NewGRFWindow (this=0x616001ab6280, __in_chrg=<optimised out>) at /home/jgr/misc/openttd-6/src/newgrf_gui.cpp:669
#4  0x0000555567071280 in NewGRFWindow::~NewGRFWindow (this=0x616001ab6280, __in_chrg=<optimised out>) at /home/jgr/misc/openttd-6/src/newgrf_gui.cpp:674
#5  0x0000555567e65bde in UnInitWindowSystem () at /home/jgr/misc/openttd-6/src/window.cpp:1923
#6  0x000055556727021b in ShutdownGame () at /home/jgr/misc/openttd-6/src/openttd.cpp:310
#7  0x0000555567275977 in openttd_main (argc=2, argv=0x7fffffffdbd8) at /home/jgr/misc/openttd-6/src/openttd.cpp:865
#8  0x000055556604b9eb in main (argc=2, argv=0x7fffffffdbd8) at /home/jgr/misc/openttd-6/src/os/unix/unix.cpp:265
```
I get an identical crash with #8830 applied, so that PR doesn't fix this sadly.

## Steps to reproduce
1. Open the game.
2. Wait for the NewGRF scan to complete.
3. Go to the NewGRF settings window
4. Manually trigger another scan
5. Close the window to exit the game

### PR DESCRIPTION
**Pull request by TrueBrain**
- This invalidates the first three commits in #8828, but not the fourth. That is, this also fixes the bug mentioned, but not in the way you think: it simply continues the NewGRF scan till it is finished, while the window is closed.
- EXTRA EXTRA EXTRA: the second commit in this PR also fixes #8760, and stops the NewGRF scan as soon as possible, similar to #8828 (but without all the complex thread-stuff, as it is now running in the game-thread anyway).
- And while at it, fixed similar issue for world-gen: that is now also aborted when you close the game.
- #8833 was closely related to all this, and now also part of this PR

(okay, this might be growing a bit too much; if it is easier if I PR them separately (a few depend on each other, but I can deal with that), just let me know!)

Closes #8828
Fixes #8760
Fixes #8833

## Motivation / Problem

With the gameloop now threaded, we can get ride of the ugliness that the NewGRFScan and GenerateWorld threads are. They are a huge hack dating back when threads were still scary and not many people had more than one core. Pretty sure those days are over :P

By removing the special code for those two modal windows, the code becomes a lot simpler. Having such massive chunks of code not running in different threads makes things easier to debug and understand.

Purely by accident, this solves most issues mentioned in #8712, with the exception of the palette.

But mostly ... it now looks so much more smooth to generate a world ...

https://user-images.githubusercontent.com/1663690/110473423-cb7d1780-80de-11eb-947c-d22d4344ea0c.mp4

## Description

```
Basically, modal windows had their own thread-locking for what
drawing was possible. This is a bit nonsense now we have a
game-thread. And it makes much more sense to do things like
NewGRFScan and GenerateWorld in the game-thread, and not in a
thread next to the game-thread.

This commit changes that: it removes the threads for NewGRFScan
and GenerateWorld, and just runs the code in the game-thread.
On regular intervals it allows the draw-thread to do a tick,
which gives a much smoother look and feel.

It does slow down NewGRFScan and GenerateWorld ever so slightly
as it spends more time on drawing. But the slowdown is not
measureable on my machines (with 700+ NewGRFs / 4kx4k map and
a Debug build).

Running without a game-thread means NewGRFScan and GenerateWorld
are now blocking.
```

All the extra `MarkDirty` calls are because formally it just made the whole screen dirty every time, but that is very expensive. So now only that what changed is marked dirty, which is a lot nicer on the CPU.

## Limitations

- Slightly slower NewGRF scanning and map generation, because time is spend on drawing (and not on scanning). On my machine it is so small, I could not measure this outside the noise. I would estimate it at: 0.05ms per frame, 60 frames per second, 3ms per 1000ms, so 0.3% speed loss.
- Running with `-vwin32-opengl:no_threads` means you don't see those two modals; similar to running without threads before this commit. I think this is reasonable, to make it work this way.
- The game used to mark the whole screen dirty during map generation; but doing that now would be dreadfully slow. So instead I tried to find all the places that modify the map, and mark the files dirty. To me it seems I found them all, but I might have missed some. Nothing we can't fix over time. (Basically, the old implementation was lazy and just did EVERYTHING, instead of what is needed).

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by ldpl** [comment]
Some stuff I noticed after testing (some may not be related to this pr but whatever):

- Doesn't crash if closed during newgrf scan
- Reaches 100% way before finishing the scan. Few times I've seen it starting with 100% and doing entire scan on there.
- Landscape generation part of mapgen still lags as before
- Sleeping cloud cursor is still quite confusing to use (when clicking abort button).
- Mapgen seems to count as world tick for frame rate window so it initializes avg with some insanely high number.

**Comment by TrueBrain** [comment]
Tnx for testing!

>     * Doesn't crash if closed during newgrf scan
> 

Good! That is the important bit :D

>     * Reaches 100% way before finishing the scan. Few times I've seen it starting with 100% and doing entire scan on there.
> 

Are you sure it is doing the scan at 100%? How do you tell?

For me it is working as expected, but one important observation: at the end of the NewGRF Scan, it stalls for a bit of time. There is a pretty hefty function being called when the Scan is complete, which stalls for anywhere between 300ms up to 2seconds for me.

>     * Landscape generation part of mapgen still lags as before
> 

The first 5 steps are indeed laggy. This is because TGP does a massive calculation at once, and prints that on the map. There are no in-betweens there, and it doesn't allow mouse movement while doing. I think future-extensions can be to allow mouse movements, even during times game-tick has a lock on the game-state. But we are a bit away from that :)

>     * Sleeping cloud cursor is still quite confusing to use (when clicking abort button).
> 

*shrug*. Not disagreeing, but indeed out of scope of this PR. Maybe worth an issue on its own?

>     * Mapgen seems to count as world tick for fps so it initializes avg with some insanely high number.
>

Haha, I noticed that too :D I will fix this one, as it is really silly :P

**Comment by TrueBrain** [comment]
>     * Reaches 100% way before finishing the scan. Few times I've seen it starting with 100% and doing entire scan on there.
> 

Basically, the game remembers how many NewGRFs you had last round, and assumes you will have that again. So the 100% is at the last known amount you had (`last_newgrf_count` in the config). My PR used to store the value when you closed the window, but in the next push it will no longer do that, and only remember the number of a finished scan.

File: src/openttd.h [hunk 1]
```diff
@@ -81,4 +81,13 @@ void HandleExitGameRequest();
 
 void SwitchToMode(SwitchMode new_mode);
 
+/**
+ * Request a new NewGRF scan. This will be executed on the next game-tick.
+ * This is mostly needed to ensure NewGRF scans (which are blocking) are
+ * done in the game-thread, and not in the draw-thread (which most often
+ * triggers this request).
+ * @param callback Optional callback to call when NewGRF scan is completed.
+ */
```
Comment (LordAro) [inline src/openttd.h]: Shouldn't this go on the definition, rather than the declaration?

File: src/video/video_driver.cpp [hunk 2]
```diff
@@ -56,6 +56,20 @@ void VideoDriver::GameThread()
...
+	if (std::this_thread::get_id() != this->game_thread.get_id()) return;
+
+	this->game_state_mutex.unlock();
+
+	{
+		std::lock_guard<std::mutex> lock(this->game_thread_wait_mutex);
+	}
+
+	this->game_state_mutex.lock();
+}
```
Comment (LordAro) [inline src/video/video_driver.cpp]: unlocking, then locking & immediately unlocking, then locking again without doing anything else inbetween looks really  weird :)

File: src/video/video_driver.hpp [hunk 3]
```diff
@@ -179,6 +179,12 @@ class VideoDriver : public Driver {
 		this->change_blitter = new_blitter;
 	}
 
+	/**
+	 * Pause the game-loop for a bit, releasing the game-state locks, so
+	 * drawing can happen.
```
Comment (LordAro) [inline src/video/video_driver.hpp]: weird linebreak

**Review by LordAro — COMMENTED** [review]
I like the look of the code in general, all sorts of mutex & global removals. As for it's correctness...

File: src/video/video_driver.cpp (hunk 2 above)
Comment (TrueBrain) [reply src/video/video_driver.cpp]: That is what you get if OSes decide to optimize mutexes, and don't give other locks priority when you unlock :P Really stupid. Added a comment about it.

**Review by LordAro — APPROVED** [review]
It's been tested reasonably thoroughly, and removing mutexes & global variables is always nice

YOLO
