### PR TITLE
Fix #9028: [OpenGL] Clear cursor cache on destroying the OpenGL backend.

### LINKED ISSUE #9028: Memory leak when destructing OpenGLBackend
## Version of OpenTTD
Anything at or after 436cdf1fc898097a8cbe6226ad32a4055a6ca4d9 (between 1.11.0-beta2 and 1.11.0-RC1)

## Expected result
No memory leak (no definitely lost bytes in the leak summary)

## Actual result
==27199== 24 bytes in 1 blocks are definitely lost in loss record 383 of 684
==27199==    at 0x483877F: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==27199==    by 0xAECE1C: unsigned char* MallocT<unsigned char>(unsigned long) (alloc_func.hpp:69)
==27199==    by 0xAEC4C9: SimpleSpriteAlloc(unsigned long) (spritecache.cpp:819)
==27199==    by 0x84FD6B: OpenGLBackend::Encode(SpriteLoader::Sprite const*, void* (*)(unsigned long)) (opengl.cpp:1248)
==27199==    by 0xAEBB2D: ReadSprite(SpriteCache const*, unsigned int, SpriteType, void* (*)(unsigned long), SpriteEncoder*) (spritecache.cpp:498)
==27199==    by 0xAEC7CF: GetRawSprite(unsigned int, SpriteType, void* (*)(unsigned long), SpriteEncoder*) (spritecache.cpp:904)
==27199==    by 0x84F710: OpenGLBackend::PopulateCursorCache() (opengl.cpp:1103)
==27199==    by 0x8573C4: VideoDriver_SDL_OpenGL::PopulateSystemSprites() (sdl2_opengl_v.cpp:125)
==27199==    by 0x858EBE: VideoDriver::Tick() (video_driver.cpp:175)
==27199==    by 0x85605C: VideoDriver_SDL_Base::LoopOnce() (sdl2_v.cpp:642)
==27199==    by 0x85609C: VideoDriver_SDL_Base::MainLoop() (sdl2_v.cpp:660)
==27199==    by 0xA44F07: openttd_main(int, char**) (openttd.cpp:837)

## Steps to reproduce
valgrind ./openttd -d sdl-opengl and then exiting the game.
Starting a game from the main menu doubles the loss and then exiting doubles the loss.

##Notes
#9027 solves some uninitialised memory issues that valgrind complains about.
The mentioned commit tries to fix a threading issue, but breaks this case. However, I am not sure whether calling the actual clearing logic in the destructor is safe for the threading issue solved in that commit.

### PR DESCRIPTION
**Pull request by michicc**
## Motivation / Problem

Since [436cdf1](https://github.com/OpenTTD/OpenTTD/commit/436cdf1fc898097a8cbe6226ad32a4055a6ca4d9) destroying the OpenGL backend only requested a clear of the cursor cache but didn't actually perform.

## Description

Split the cache clear into an internal function so that it can be used on destruction without the request queue logic.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/video/opengl.cpp [hunk 1]
```diff
@@ -510,7 +510,7 @@ OpenGLBackend::~OpenGLBackend()
 		_glDeleteBuffers(1, &this->anim_pbo);
 	}
 	if (_glDeleteTextures != nullptr) {
-		ClearCursorCache();
+		InternalClearCursorCache();
```
Comment (TrueBrain) [inline src/video/opengl.cpp]: OCD: no `this->` here?

**Review by TrueBrain — APPROVED** [review]
