### PR TITLE
Fix #11646: Non-thread safe shared buffer returned from GetLogPrefix().

### LINKED ISSUE #11646: [Bug]: GetLogPrefix function static state is not thread-safe
### Version of OpenTTD

master

### Expected result

No thread safety issues.

### Actual result

`GetLogPrefix` is called via the `Debug` macro, and other routes.
It returns a pointer to a static std::string buffer.
Other threads may concurrently modify/reallocate that state (particularly when _settings_client.gui.show_date_in_logs is set).

### Steps to reproduce

Do something which calls Debug in multiple threads.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

GetLogPrefix reuses a static std::string, and returns its buffer after updating it. This is not thread safe.

This is probably a left-over from using C-style strings.

## Description

Return string from GetLogPrefix instead of shared string's buffer.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/debug.cpp [hunk 1]
```diff
@@ -235,15 +235,13 @@ std::string GetDebugString()
  * the date, otherwise it returns nothing.
  * @return the prefix for logs (do not free), never nullptr
```
Comment (rubidium42) [inline src/debug.cpp]: This comment seems outdated now.

**Review by glx22 — DISMISSED** [review]

File: src/console.cpp [hunk 2]
```diff
@@ -51,8 +51,8 @@ static void IConsoleWriteToLogFile(const std::string &string)
 {
 	if (_iconsole_output_file != nullptr) {
 		/* if there is an console output file ... also print it there */
-		const char *header = GetLogPrefix();
-		if ((strlen(header) != 0 && fwrite(header, strlen(header), 1, _iconsole_output_file) != 1) ||
+		std::string header = GetLogPrefix();
+		if ((!header.empty() && fwrite(header.c_str(), header.size(), 1, _iconsole_output_file) != 1) ||
 				fwrite(string.c_str(), string.size(), 1, _iconsole_output_file) != 1 ||
 				fwrite("\n", 1, 1, _iconsole_output_file) != 1) {
```
Comment (rubidium42) [inline src/console.cpp]:
```suggestion
		try {
			fmt::print(_iconsole_output_file, "{}{}\n", GetLogPrefix(), string);
		} catch (const std::system_error &e) {
```
What about this solution to writing the output? I checked `format-inl.h`, and that seems to be throwing `std::system_error` when `fwrite` does not write everything.

**Review by rubidium42 — APPROVED** [review]
