### PR TITLE
Fix #14377: Make house picker window remember house protection state when closed

### LINKED ISSUE #14377: House placer should remember "prevent upgrades" choice
### Version of OpenTTD

15.0-beta2

### Expected result

On the house picker, the player can choose whether the next house will be protected from the town rebuilding it when growing.

It would be nice if their choice was remembered while OpenTTD is running, instead of being reset each time the window is closed and re-opened.

### Actual result

Their choice is reset each time the window is closed and re-opened.

### Steps to reproduce

1. Enable house placement in settings (or use Scenario Editor)
2. Open the house placer
3. Change the "Prevent upgrades" from Off to On
4. Close the window and re-open it
5. Notice that "Prevent upgrades" has been reset to Off

### PR DESCRIPTION
**Pull request by 2TallTyler**
## Motivation / Problem

On the house picker, the player can choose whether the next house will be protected from the town rebuilding it when growing.

It would be nice if their choice was remembered while OpenTTD is running, instead of being reset each time the window is closed and re-opened.

## Description

Remember the state instead of discarding it when the window is closed.

Closes #14377.

## Limitations

~~More code than simply changing the existing storage to `static inline bool house_protected`, but I like having it kept with other window state. I'm happy to change it if requested.~~ Changed to the simple version. 🙂 

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/town_gui.cpp [hunk 1]
```diff
@@ -1511,6 +1513,9 @@ class HousePickerCallbacks : public PickerCallbacks {
 	int GetSelectedType() const override { return sel_type; }
 	void SetSelectedType(int id) const override { sel_type = id; }
 
+	bool GetHousePickerProtected() { return house_protected; }
+	void SetHousePickerProtected(bool make_protected) const { house_protected = make_protected; }
```
Comment (rubidium42) [inline src/town_gui.cpp]:
```suggestion
	bool IsHousePickerProtected() { return this->house_protected; }
	void SetHousePickerProtected(bool make_protected) const { this->house_protected = make_protected; }
```
Definitely missing `this->`. Maybe `Is...` is better naming wise than `Get...`, as that kinda tells you it returns a boolean value.

**Review by rubidium42 — COMMENTED** [review]
I'd personally keep it simple and avoid the extra wrapper functions. But that's more a taste thing than anythingelse.

That `Get/SetSelectedType` exist is due to them being `virtual` functions that are overridden in the class hierarchy.

File: src/town_gui.cpp (hunk 1 above)
Comment (PeterN) [reply src/town_gui.cpp]: `house_protected` is static so it shouldn't have `this->`. (It doesn't need to be static, because the picker callback instance is already static...)

**Comment by 2TallTyler** [comment]
Changed to the simple version. 🙂

File: src/town_gui.cpp [hunk 2]
```diff
@@ -1628,7 +1628,7 @@ static CargoTypes GetProducedCargoOfHouse(const HouseSpec *hs)
 
 struct BuildHouseWindow : public PickerWindow {
 	std::string house_info{};
-	bool house_protected = false;
+	static inline bool house_protected;
```
Comment (PeterN) [inline src/town_gui.cpp:1631]: A bit of an annoyance in what's accepted by C++, but all `this->house_protected` now don't follow our code style. They should be `BuildHouseWindow::house_protected` instead.

**Review by PeterN — APPROVED** [review]
