### PR TITLE
Fix #9147: Asynchronously do screenshots during draw tick.

### LINKED ISSUE #9147: MakeScreenshot locking is broken when called from outside of VideoDriver::Tick
## Version of OpenTTD
master, 49aa392

## Steps to reproduce
1. Set rcon password
2. Launch one instance (with real video driver, not dedicated) and start server
3. Launch second instance and connect to the server
4. Type `rcon <password> screenshot` few times until first instance crashes

### PR DESCRIPTION
**Pull request by michicc**
## Motivation / Problem

Screenshots can be triggered from the game thread (e.g. by using rcon). If an accelerated video driver is in use, this causes an illegal OpenGL access as the game thread has no OpenGL context.

## Description

Due to a similar problem, changing blitters was already delayed to be execute by the draw tick later on. This PR generalises this delay and uses it to move the actual screenshoting into the draw tick as well.

PR #9140 should be safe after this PR.

## Limitations

The screenshot contents will be the screen after the current game tick has computed. Before, if the screenshot was triggered by GUI input, it would capture the state before the game tick.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by PeterN** [comment]
Like and agree with the principle of a generic queue, Unable to comment on "correctness" of implementation other than it looks fine to me.

**Comment by LordAro** [comment]
issue number in the commit message is wrong :>

File: src/gfxinit.cpp [hunk 1]
```diff
@@ -309,7 +331,7 @@ static bool SwitchNewGRFBlitter()
 		if (BlitterFactory::GetBlitterFactory(repl_blitter) == nullptr) continue;
 
 		/* Inform the video driver we want to switch blitter as soon as possible. */
-		VideoDriver::GetInstance()->ChangeBlitter(repl_blitter);
+		VideoDriver::GetInstance()->QueueOnMainThread(std::bind(&RealChangeBlitter, repl_blitter));
```
Comment (TrueBrain) [inline src/gfxinit.cpp:334]: Shouldn't this also be a Lambda similar as screenshot?

Comment (michicc) [reply src/gfxinit.cpp:334]: That is purely a matter of style opinion. Formulating this with a lambda is just as possible, but there's not any functional difference.

**Review by PeterN — DISMISSED** [review]

**Review by TrueBrain — APPROVED** [review]
