### PR TITLE
Fix #10206: Disable scripts in intro game

### LINKED ISSUE #10206: Assert when loading titlegame with AI
### Version of OpenTTD

13.0-beta2

### Expected result

According to our longtime Title Game Competition rules, AI, GS, and NewGRFs used in a title game are automatically disabled.

I would expect if an AI is present, the AI company is deleted or the game loads the all-water fallback instead, like when a NewGRF is present.

### Actual result

If an AI is used, we get an assertion failure:
`Assertion failed at line 94 of src\ai\ai_config.cpp: strcmp("start_date", name) == 0`

Logs and emergency save:
[crash20221201165815.zip](https://github.com/OpenTTD/OpenTTD/files/10134454/crash20221201165815.zip)

### Steps to reproduce

1. Download the attached savegame and `opntitle.dat` of the same savegame
2. Place `opntitle.dat` in your baseset folder, replacing the file that's already there
3. Start OpenTTD

[title.zip](https://github.com/OpenTTD/OpenTTD/files/10134482/title.zip)

### PR DESCRIPTION
**Pull request by glx22**
Fixes #10206

## Motivation / Problem
Using scripts in intro game can cause crashes.
We always said intro should not use scripts or newgrfs, but we only enforced the newgrf part (with broken save error because disabling newgrf in a running game is never a good idea).
Dedicated servers may also crash because of scripts during the load test as it's done in `GM_MENU` (unrelated but it's funny to see the broken save error when starting a dedicated server with `-g` and a save containing newgrf)

## Description
Discard script data on load and skip starting of scripts (like it's done for network games).
As OpenTTD requires a script to be started for `is_ai` companies, prevent using any random ones (that may cause crash by accessing settings) by forcing Dummy AI for intro.
And don't show AIDebugWindow when an AI dies in intro (as Dummy AI will instant die).

## Limitations
This also solves the crash reported in #9720 but starting scripts before the gamestate is ready is still an issue, and #9745 should handle that when done.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/ai/ai_scanner.cpp [hunk 1]
```diff
@@ -65,7 +66,7 @@ AIInfo *AIScannerInfo::SelectRandomAI() const
 		if (i->UseAsRandomAI()) num_random_ais++;
 	}
 
-	if (num_random_ais == 0) {
+	if (_game_mode == GM_MENU || num_random_ais == 0) {
 		Debug(script, 0, "No suitable AI found, loading 'dummy' AI.");
```
Comment (LordAro) [inline src/ai/ai_scanner.cpp]: This debug message doesn't really fit now

**Review by 2TallTyler — APPROVED** [review]
