### PR TITLE
Fix #14240: Remember previous GUI scale when toggling auto-detect

### LINKED ISSUE #14240: [Bug]: Auto-detect doesn't remember the previous interface size when turned on, then back off
### Version of OpenTTD

latest

### Expected result

Perhaps not an actual bug, but more like something I would intuitively expect.

I would expect that the auto-detect interface size toggle in the Graphics tab remembers the previously selected custom size after being turned on, then back off, instead of having to manually choose it again.

### Actual result

The interface remains at 1x after switching the auto-detect toggle off.

### Steps to reproduce

Just set an interface size to other than 1x, toggle the Auto-detect switch on, then toggle off. The size remains at 1x.

### PR DESCRIPTION
**Pull request by OllieBechstein**
## Motivation / Problem

Fixes #14240 

When a user chooses a UI scale via the slider, then toggles Auto-detect size, the previously set UI scale is lost, which is unintuitive and forces the user to re-configure the setting.

## Description

This change stores the previously selected scale, so that it can be restored if Auto-detect is disabled. 
A static variable to store the selected scale. When Auto-detect is toggled off, the previously set scale is restored on the slider. The logic is contained within settings_gui.cpp.

## Limitations

- The scale will not be remembered if the user quits OpenTTD, as this would require saving the value.

### CODE REVIEW

File: src/settings_gui.cpp [hunk 1]
```diff
@@ -1066,9 +1067,13 @@ struct GameOptionsWindow : Window {
...
 			{
 				if (_gui_scale_cfg == -1) {
-					_gui_scale_cfg = _gui_scale;
+					_gui_scale_cfg = previous_gui_scale; // Store the previous GUI scale value
 					this->SetWidgetLoweredState(WID_GO_GUI_SCALE_AUTO, false);
+					if (AdjustGUIZoom(false))
+					    ReInitAllWindows(true);
+					this->gui_scale = _gui_scale;
 				} else {
+					previous_gui_scale = _gui_scale;	// Set the previous GUI scale value as the current one
```
Comment (2TallTyler) [inline src/settings_gui.cpp]:
```suggestion
					this->previous_gui_scale = _gui_scale; // Store the current GUI scale for later
```

Missing `this->`, and we use spaces, not tabs.

File: src/settings_gui.cpp [hunk 2]
```diff
@@ -1066,9 +1067,13 @@ struct GameOptionsWindow : Window {
 			case WID_GO_GUI_SCALE_AUTO:
 			{
 				if (_gui_scale_cfg == -1) {
-					_gui_scale_cfg = _gui_scale;
+					_gui_scale_cfg = previous_gui_scale; // Store the previous GUI scale value
 					this->SetWidgetLoweredState(WID_GO_GUI_SCALE_AUTO, false);
+					if (AdjustGUIZoom(false))
+					    ReInitAllWindows(true);
```
Comment (2TallTyler) [inline src/settings_gui.cpp]:
```suggestion
					if (AdjustGUIZoom(false)) ReInitAllWindows(true);
```
This is fine on one line, and we use {} for multiline.

File: src/settings_gui.cpp [hunk 3]
```diff
@@ -1066,9 +1067,13 @@ struct GameOptionsWindow : Window {
 			case WID_GO_GUI_SCALE_AUTO:
 			{
 				if (_gui_scale_cfg == -1) {
-					_gui_scale_cfg = _gui_scale;
+					_gui_scale_cfg = previous_gui_scale; // Store the previous GUI scale value
```
Comment (2TallTyler) [inline src/settings_gui.cpp]:
```suggestion
					_gui_scale_cfg = this->previous_gui_scale; // Load the previous GUI scale
```

**Review by 2TallTyler — COMMENTED** [review]
Thanks for the contribution!

You will need to squash your commits in order to pass our automatic commit checker. I suggest an interactive rebase (`git rebase -i head~4` should do). 

The commit name should be `Fix #14240: Remember previous GUI scale when toggling auto-detect` or similar, so that the linked issue is associated with the commit.

**Comment by OllieBechstein** [comment]
Thanks for the suggestions! I believe everything has been fixed now, and I have squashed the commits. Let me know if there are any further issues, and apologies for the delay!

**Review by 2TallTyler — APPROVED** [review]
