### PR TITLE
Fix #10395: When loading old saves, don't forcibly bar level crossings

### LINKED ISSUE #10395: [Bug]: Loading a pre-#9931 savegame bars all level crossings, even when no train nearby
### Version of OpenTTD

13.0-RC1 linux

### Expected result

Sometimes/some level crossings are blocked, without any train around, even when not connected to anything.
I did not see this in v12.

Example in the middle:
Tennville Transport, 2157-07-27

Another one:
Tennville Transport, 2172-06-19-crop

### Actual result

should not block

### Steps to reproduce

unknown :/

### PR DESCRIPTION
**Pull request by 2TallTyler**
## Motivation / Problem

The savegame conversion in #9931 iterates through all level crossings and updates them, in case the savegame had only one track of a multi-track crossing barred. I erroneously forced every level crossing tile on the map to be barred instead of checking for a closed tile on the same axis. Reported as #10395.

## Description

Check the crossing for barred tiles instead of forcing all tiles to be barred.

Closes #10395.

To make review a bit easier, the parameter being changed is `force_bar`:
```
/**
 * Update a level crossing to barred or open (crossing may include multiple adjacent tiles).
 * @param tile Tile which causes the update.
 * @param sound Should we play sound?
 * @param force_bar Should we force the crossing to be barred?
 */
void UpdateLevelCrossing(TileIndex tile, bool sound, bool force_bar)
```

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/saveload/afterload.cpp [hunk 1]
```diff
@@ -3196,9 +3196,9 @@ bool AfterLoadGame()
 			}
 		}
 
-		/* Refresh all level crossings to bar adjacent crossing tiles. */
+		/* Refresh all level crossings to bar adjacent crossing tiles, if needed. */
 		for (TileIndex tile = 0; tile < Map::Size(); tile++) {
-			if (IsLevelCrossingTile(tile)) UpdateLevelCrossing(tile, false, true);
+			if (IsLevelCrossingTile(tile)) UpdateLevelCrossing(tile, false, false);
```
Comment (glx22) [inline src/saveload/afterload.cpp]:
```suggestion
			if (IsLevelCrossingTile(tile)) UpdateLevelCrossing(tile, false);
```
And I think you can also remove the conversion in 1988-1993.

**Review by glx22 — APPROVED** [review]
