### PR TITLE
Fix #7704: [OSX] Handle malformed UTF8 strings

### LINKED ISSUE #7704: Crash on MacOS when server has invalid UTF8 name string
## Version of OpenTTD
1.9.2

## Expected result
Not to crash when "Find servers" button is pressed

## Actual result
Crash when "Find servers" button is pressed

## Steps to reproduce
Open game and press "find servers" button. It only crashes if any server has invalid UTF8 characters. Current server giving problems is "CzechServer(01) Mirne podnebi? [1950-2100]" which have "437A65636853657276657228303129204D69726E6520706F646E656269FFFFFFAD205B313935302D323130305D" hexadecimal UTF8 name string.

### PR DESCRIPTION
**Pull request by uvealonso**

### CODE REVIEW

**Comment by glx22** [comment]
To make the commit checker happy, you'll need to fix your commit messages following https://wiki.openttd.org/Coding_style#Commit_message
I think you could also squash all your commits into one, and your latest commit adds an unneeded space in the comment.

File: src/os/macosx/string_osx.cpp [hunk 1]
```diff
@@ -306,6 +306,9 @@ int MacOSStringCompare(const char *s1, const char *s2)
 	CFStringRef cf1 = CFStringCreateWithCString(kCFAllocatorDefault, s1, kCFStringEncodingUTF8);
 	CFStringRef cf2 = CFStringCreateWithCString(kCFAllocatorDefault, s2, kCFStringEncodingUTF8);
 
+	/* Don't know why add  '+ 2', but it's added because it already existed in the final function's return */
+	if (cf1 == nullptr or cf2 == nullptr) return (int)kCFCompareEqualTo + 2;
```
Comment (nielsmh) [inline src/os/macosx/string_osx.cpp]: Use the `||` operator instead of `or` as keyword (does that even compile?)
```suggestion
	if (cf1 == nullptr || cf2 == nullptr) return (int)kCFCompareEqualTo + 2;
```
I don't like that the +2 is added for unknown reasons, if it's necessary it needs an explanation for why.

Comment (michicc) [reply src/os/macosx/string_osx.cpp]: One would only have to look at the function comment to know why the return values are what they are:
`@return 1 if s1 < s2, 2 if s1 == s2, 3 if s1 > s2, or 0 if not supported by the OS.`

Having said that, I'd say that a return value of 0 would be the correct return. It will make OpenTTD fall back to a simple string compare, which is not as bad as just pretending the strings are equal.

**Review by michicc — DISMISSED** [review]

File: src/os/macosx/string_osx.cpp (hunk 1 above)
Comment (uvealonso) [reply src/os/macosx/string_osx.cpp]: Oh, you both are right. I was tired of debugging (was late) when I made the code change, after I discovered where was the segfault, and I didn't realise on the function comments neither I was writing pythonic "or" style :(

**Comment by uvealonso** [comment]
> To make the commit checker happy, you'll need to fix your commit messages following https://wiki.openttd.org/Coding_style#Commit_message
> I think you could also squash all your commits into one, and your latest commit adds an unneeded space in the comment.

Done!

**Comment by nielsmh** [comment]
You forgot the colon after the ticket number in the commit message.
`Fix #7704: [OSX] Handle malformed UTF8 strings`

**Comment by LordAro** [comment]
Note that the commit message itself must be amended, not just the PR title

Sorry about this, we're very particular about our commit history :)

**Comment by uvealonso** [comment]
> Note that the commit message itself must be amended, not just the PR title
> 
> Sorry about this, we're very particular about our commit history :)

Oh sure. I'll fix it now

**Comment by uvealonso** [comment]
Done!

File: src/os/macosx/string_osx.cpp [hunk 2]
```diff
@@ -306,6 +306,9 @@ int MacOSStringCompare(const char *s1, const char *s2)
 	CFStringRef cf1 = CFStringCreateWithCString(kCFAllocatorDefault, s1, kCFStringEncodingUTF8);
 	CFStringRef cf2 = CFStringCreateWithCString(kCFAllocatorDefault, s2, kCFStringEncodingUTF8);
 
+	/* If any CFString could not be created (e.g., due to UTF8 invalid chars), return OS unsupported functionality */
+	if (cf1 == nullptr || cf2 == nullptr) return 0;
```
Comment (michicc) [inline src/os/macosx/string_osx.cpp]: Unfortunately, this if has to get a bit longer. If just one string is `nullptr`, you'd still have to `CFRelease` the other one. For some obscure reason, `CFRelease` crashes on `nullptr`, which means nested if's to see what the release.

No release means memory leak, and if one of the strings is e.g. a town or station name, the comparer could be called many times.

**Review by michicc — CHANGES_REQUESTED** [review]

File: src/os/macosx/string_osx.cpp (hunk 2 above)
Comment (uvealonso) [reply src/os/macosx/string_osx.cpp]: Oh! That's completely right. I don't know how I didn't even realise about that!

**Comment by uvealonso** [comment]
This is  a fix that prevents crash on OSX, but this doesn't fix the real origin of the problem, which is permitting servers to have badformed UTF8 strings... :-/

File: src/os/macosx/string_osx.cpp (hunk 2 above)
Comment (uvealonso) [reply src/os/macosx/string_osx.cpp]: Done

**Review by michicc — APPROVED** [review]

**Review by michicc — APPROVED** [review]

**Comment by nielsmh** [comment]
It would be impossible to prevent anyone from making a patched game that intentionally sends bad UTF8 to network clients, but the master server possibly should reject servers registering with invalid text.

**Comment by uvealonso** [comment]
> It would be impossible to prevent anyone from making a patched game that intentionally sends bad UTF8 to network clients, but the master server possibly should reject servers registering with invalid text.

Yeah, a patched game can intentionally send bad UTF8, that's right. But I think that the server that currently have bad UTF8 that makes my OpenTTD client to crash didn't make it intentionally. The server with which I detected the error was an czech server that has no intention of creating any issue to clients.

Btw, when is this patch going to be integrated in official compiled game? I can not play until servers stop of using bad UTF8 strings :(

**Comment by uvealonso** [comment]
> Btw, when is this patch going to be integrated in official compiled game? I can not play until servers stop of using bad UTF8 strings :(

@michicc , @LordAro

**Comment by nielsmh** [comment]
I think the best short-term solution is to patch the master server so it delists servers with invalid text in any field.

**Comment by uvealonso** [comment]
> It would be impossible to prevent anyone from making a patched game that intentionally sends bad UTF8 to network clients, but the master server possibly should reject servers registering with invalid text.

> I think the best short-term solution is to patch the master server so it delists servers with invalid text in any field.

I've made a quick check of master server's code, and I have not seen any message that implies server-name info at the time of registration. Am I ok?

**Comment by uvealonso** [comment]
> > It would be impossible to prevent anyone from making a patched game that intentionally sends bad UTF8 to network clients, but the master server possibly should reject servers registering with invalid text.
> 
> > I think the best short-term solution is to patch the master server so it delists servers with invalid text in any field.
> 
> I've made a quick check of master server's code, and I have not seen any message that implies server-name info at the time of registration. Am I ok?

Well... I think that payload on packet `PACKET_UDP_SERVER_RESPONSE` is not analysed in function `QueryNetworkUDPSocketHandler::Receive_SERVER_RESPONSE`  (masterserver/src/masterserver/udp.cpp), but info is sent.

I have to make it to compile and run, and then make some testings.

Buuuuuut, there's no possibility of creating issues on masterserver repo :(

**Comment by nielsmh** [comment]
This seems to be the code that receives the server data response:
https://github.com/OpenTTD/MasterServer/blob/a6be9858f385fd0e092836682a25c5142cf9923e/src/updater/udp.cpp#L21-L65

It doesn't do much validation of the data, which would need to be added.

**Comment by uvealonso** [comment]
> This seems to be the code that receives the server data response:
> https://github.com/OpenTTD/MasterServer/blob/a6be9858f385fd0e092836682a25c5142cf9923e/src/updater/udp.cpp#L21-L65
> 
> It doesn't do much validation of the data, which would need to be added.

Yep, that's interesting. I think there's something that can be done...
