### PR TITLE
Fix #12465: Click/tooltip alignment of industry chain cargo lines

### LINKED ISSUE #12465: [Bug]: Click/tooltip vertical misalignment for cargo line (CFT_CARGO) in industry chain window
### Version of OpenTTD

Since #12370

### Expected result

No alignment issues, etc

### Actual result

#12370 fixed the click/tooltip vertical alignment for the text fields, however this has increased the misalignment for the cargo line columns (CFT_CARGO).

Screenshot_2024-04-09_19-32-38

### Steps to reproduce

See above

### PR DESCRIPTION
**Pull request by JGRennison**
## Motivation / Problem

#12465

## Description

Fix click/tooltip alignment of industry chain cargo lines.

## Limitations

N/A

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/industry_gui.cpp [hunk 1]
```diff
@@ -2297,16 +2297,16 @@ struct CargoesField {
...
 
-		int vpos = vert_inter_industry_space / 2 + CargoesField::cargo_border.width;
+		int vpos = (vert_inter_industry_space / 2) + (CargoesField::cargo_border.width / 2);
 		uint row;
 		for (row = 0; row < MAX_CARGOES; row++) {
 			if (pt.y < vpos) return INVALID_CARGO;
-			if (pt.y < vpos + GetCharacterHeight(FS_NORMAL)) break;
+			if (pt.y < vpos + static_cast<int>(CargoesField::cargo_line.width)) break;
 			vpos += GetCharacterHeight(FS_NORMAL) + CargoesField::cargo_space.width;
 		}
```
Comment (rubidium42) [inline src/industry_gui.cpp:2311]: Shouldn't all the `.width`s in here actually be `.height`s? It doesn't make any practical difference because the width and height of `cargo_border` and `cargo_space` are the same. Though conceptually we are talking about the 'height' axis here, right?

Comment (JGRennison) [reply src/industry_gui.cpp:2311]: cargo_border is not actually the same in the width and height axes.
I've adjusted it to not use horizontal values.

**Review by rubidium42 — APPROVED** [review]
