### PR TITLE
Fix #14234, 5aa4ad5135: Crash due to NUL chars in external strings.

### LINKED ISSUE #14234: [Crash]: Placing goods station next to police station
### Version of OpenTTD

15.0-beta2, Debian 12 stable

### Steps to reproduce

1. Placed a goods station next to police station
2. Game crashed
3. It is reproducible, crashed 3 times in a row

### Upload crash files

[crashreport.zip](https://github.com/user-attachments/files/20093360/crashreport.zip)

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

As per #14234, the game can crash when formatting a string (in this case, related to a station)

5aa4ad5135 added an assert to ensure that NUL characters are not present in strings. However, some strings are from external sources.

## Description

Instead of asserting, replace the assert with an error message in the formatted string, similar to other errors.

This does not address the underlying issue of why a NUL character made its way into the string system in the first place, but does prevent a crash.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by PeterN** [comment]
This is merely working around a symptom of another issue, and may or may not be appropriate.

**Comment by LordAro** [comment]
I say go for it - in an ideal world user inputs (no matter how invalid) should not be able to crash the game even with a debug build. The invalidity is still flagged with the "unexpected NUL"

**Comment by PeterN** [comment]
> I say go for it - in an ideal world user inputs (no matter how invalid) should not be able to crash the game even with a debug build. The invalidity is still flagged with the "unexpected NUL"

I worry that it will hide a legitimate bug, and users won't report anything if it doesn't crash.

**Comment by frosch123** [comment]
You could add both the assertion and the `if`. Then it asserts in nightly and testing, and insert the error message in release build.

File: src/strings.cpp [hunk 1]
```diff
@@ -1112,7 +1112,12 @@ static void FormatString(StringBuilder &builder, std::string_view str_arg, Strin
 			const size_t ref_param_offset = str_stack.top().first_param_offset;
 			const uint case_index = str_stack.top().case_index;
 			char32_t b = consumer.ReadUtf8();
-			assert(b != 0);
+			if (b == 0) {
+				/* A NUL character should never be encountered, but for non-debug builds handle it gracefully. */
+				NOT_REACHED();
```
Comment (frosch123) [inline src/strings.cpp]: `NOT_REACHED` also applies to release builds.

Comment (PeterN) [reply src/strings.cpp]: D'oh

**Review by frosch123 — APPROVED** [review]

**Comment by PeterN** [comment]
Is there a better way of ordering the assert/if condition to avoid upsetting CodeQL?

**Comment by frosch123** [comment]
No, CodeQL will even complain about variables being unused, if they are tagged `[[maybe_unused]]`. I always dismiss those as "false positive".

Maybe you can mess around with `#if defined(NDEBUG) && defined(WITH_ASSERT)`, but that is so messy, that I rather ignore CodeQL.
