### PR TITLE
Fix #12134: Use correct error messages if clearing drive-through road stops fails

### LINKED ISSUE #12134: [Bug]: Incorrect error message trying to demolish through bus station in town with very low company rating
### Version of OpenTTD

Windows 10 14.0-RC1

### Expected result

Demolishing/clearing a through bus station on a town-owned road tile removes the bus station and road. In a town with a very low company rating, this is disallowed due to the town disallowing the removal of the road. The error message should accurately reflect this.

### Actual result

image

The error message actually shown doesn't make sense - it says that the bus station must be demolished before it can be demolished. 

### Steps to reproduce

1. Build a through bus stop on a town-owned road.
2. Annoy the local authority by demolishing lots of trees.
3. Try to demolish the through bus stop tile.

### PR DESCRIPTION
**Pull request by merni-ns**
## Motivation / Problem
Fixes #12134.

While bombing a drive-through road stop, if clearing the underlying road was not allowed (due to bad local authority rating or being owned by a different company), a message "Must demolish truck/bus station first" was displayed which does not describe the actual reason.

## Description
Use the actual error messages returned from the various commands. Tested with "X local authority does not allow this" and "owned by X company", both of which returned the "must demolish station first" message before this change.

## Limitations
None?

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/station_cmd.cpp [hunk 1]
```diff
@@ -4486,16 +4498,8 @@ CommandCost ClearTile_Station(TileIndex tile, DoCommandFlag flags)
...
-			if (IsDriveThroughStopTile(tile) && !CanRemoveRoadWithStop(tile, flags)) {
-				return_cmd_error(STR_ERROR_MUST_DEMOLISH_TRUCK_STATION_FIRST);
-			}
-			return RemoveRoadStop(tile, flags);
-		case STATION_BUS:
-			if (IsDriveThroughStopTile(tile) && !CanRemoveRoadWithStop(tile, flags)) {
-				return_cmd_error(STR_ERROR_MUST_DEMOLISH_BUS_STATION_FIRST);
-			}
-			return RemoveRoadStop(tile, flags);
+		case STATION_TRUCK:    FALLTHROUGH;
```
Comment (glx22) [inline src/station_cmd.cpp]:
```suggestion
		case STATION_TRUCK:    [[fallthrough]];
```
or maybe just nothing in this case (we removed `FALLTHROUGH` some time ago).

Comment (merni-ns) [reply src/station_cmd.cpp]: CODINGSTYLE.md does not reflect that...

File: src/station_cmd.cpp [hunk 2]
```diff
@@ -2094,6 +2094,42 @@ static Vehicle *ClearRoadStopStatusEnum(Vehicle *v, void *)
...
+	if (_current_company == OWNER_WATER) return CommandCost();
+
+	CommandCost ret;
+
+	if (GetRoadTypeTram(tile) != INVALID_ROADTYPE) {
+		Owner tram_owner = GetRoadOwner(tile, RTT_TRAM);
+		if (tram_owner != OWNER_NONE) {
+		ret = CheckOwnership(tram_owner);
+		if (ret.Failed()) return ret;
+		}
```
Comment (2TallTyler) [inline src/station_cmd.cpp]: Missing indentation inside `if` statement.

File: src/station_cmd.cpp [hunk 3]
```diff
@@ -2094,6 +2094,42 @@ static Vehicle *ClearRoadStopStatusEnum(Vehicle *v, void *)
 	return nullptr;
 }
 
+/**
+ * Check if a drive-through road stop tile can be cleared.
+ * Road stops built on town-owned roads check the conditions
+ * that would allow clearing of the original road.
+ * @param tile road stop tile to check
```
Comment (2TallTyler) [inline src/station_cmd.cpp]: `@param` and `@return` tags don't have to be full sentences, but capitalization and punctuation are nice to have. 🙂 

```suggestion
 * @param tile The road stop tile to check.
```

File: src/station_cmd.cpp [hunk 4]
```diff
@@ -2094,6 +2094,42 @@ static Vehicle *ClearRoadStopStatusEnum(Vehicle *v, void *)
...
+ * @param flags command flags
```
Comment (2TallTyler) [inline src/station_cmd.cpp]:
```suggestion
 * @param flags Command flags.
```

File: src/station_cmd.cpp [hunk 5]
```diff
@@ -2094,6 +2094,42 @@ static Vehicle *ClearRoadStopStatusEnum(Vehicle *v, void *)
...
+ * @return A succeeded command if the road can be removed, a failed command otherwise.
```
Comment (2TallTyler) [inline src/station_cmd.cpp]: It might be nice to note that the failed command contains the proper error message, and it's not just a boolean succeeded/failed.

File: src/station_cmd.cpp [hunk 6]
```diff
@@ -2094,6 +2094,42 @@ static Vehicle *ClearRoadStopStatusEnum(Vehicle *v, void *)
...
+ */
+static CommandCost CanRemoveRoadWithStop(TileIndex tile, DoCommandFlag flags)
+{
+	if (_current_company == OWNER_WATER) return CommandCost();
```
Comment (2TallTyler) [inline src/station_cmd.cpp]:
```suggestion
	/* Ocean flooding is always allowed to remove road stops. */
	if (_current_company == OWNER_WATER) return CommandCost();
```

File: src/station_cmd.cpp [hunk 7]
```diff
@@ -2094,6 +2094,42 @@ static Vehicle *ClearRoadStopStatusEnum(Vehicle *v, void *)
...
+	CommandCost ret;
+
+	if (GetRoadTypeTram(tile) != INVALID_ROADTYPE) {
+		Owner tram_owner = GetRoadOwner(tile, RTT_TRAM);
+		if (tram_owner != OWNER_NONE) {
+		ret = CheckOwnership(tram_owner);
+		if (ret.Failed()) return ret;
+		}
+	}
+	if (GetRoadTypeRoad(tile) != INVALID_ROADTYPE) {
```
Comment (2TallTyler) [inline src/station_cmd.cpp]: Missing empty line between tram and road checks.

File: src/station_cmd.cpp [hunk 8]
```diff
@@ -2094,6 +2094,42 @@ static Vehicle *ClearRoadStopStatusEnum(Vehicle *v, void *)
...
+		Owner road_owner = GetRoadOwner(tile, RTT_ROAD);
+		if (road_owner != OWNER_TOWN) {
+			if (road_owner != OWNER_NONE) {
+				ret = CheckOwnership(road_owner);
+				if (ret.Failed()) return ret;
+			}
+		} else {
+			ret = CheckAllowRemoveRoad(tile, GetAnyRoadBits(tile, RTT_ROAD), OWNER_TOWN, RTT_ROAD, flags);
+			if (ret.Failed()) return ret;
+		}
```
Comment (2TallTyler) [inline src/station_cmd.cpp]: I wouldn't mind seeing this inverted, explicitly handling `road_owner == OWNER_TOWN` and other owners going in `else`. Just for clarity. 🙂

File: src/station_cmd.cpp [hunk 9]
```diff
@@ -2111,6 +2147,11 @@ static CommandCost RemoveRoadStop(TileIndex tile, DoCommandFlag flags, int repla
 		if (ret.Failed()) return ret;
 	}
 
+	if (IsDriveThroughStopTile(tile)) {
```
Comment (2TallTyler) [inline src/station_cmd.cpp]: This incorrectly blocks a company with a poor local authority rating from removing a stop, without bulldozing the road.

Comment (merni-ns) [reply src/station_cmd.cpp]: This should work now.

File: src/station_cmd.cpp [hunk 10]
```diff
@@ -4433,29 +4433,38 @@ static void ChangeTileOwner_Station(TileIndex tile, Owner old_owner, Owner new_o
...
 		Owner road_owner = GetRoadOwner(tile, RTT_ROAD);
-		if (road_owner != OWNER_TOWN) {
-			if (road_owner != OWNER_NONE && CheckOwnership(road_owner).Failed()) return false;
-		} else {
-			if (CheckAllowRemoveRoad(tile, GetAnyRoadBits(tile, RTT_ROAD), OWNER_TOWN, RTT_ROAD, flags).Failed()) return false;
+		if (road_owner == OWNER_TOWN) {
+			ret = CheckAllowRemoveRoad(tile, GetAnyRoadBits(tile, RTT_ROAD), OWNER_TOWN, RTT_ROAD, flags);
+			if (ret.Failed()) return ret;
+		}
+		else if (road_owner != OWNER_NONE) {
```
Comment (2TallTyler) [inline src/station_cmd.cpp]: OpenTTD code style says `else if` goes on the same line. 🙂 

```suggestion
		} else if (road_owner != OWNER_NONE) {
```

**Review by 2TallTyler — APPROVED** [review]
