### PR TITLE
Fix #12302: Allow empty train engines to use an invalid cargo type.

### LINKED ISSUE #12302: [Bug]: #11719 changes the availablity of some vehicles for some GRFs
### Version of OpenTTD

Since #11719 / 2fd9096

### Expected result

Availability of NewGRF vehicles is the same as before

### Actual result

In DACH 0.3.2 (on Bananas), some locomotives which do not carry cargo are now marked as unavailable via the `ei->climates = 0` path in `CalculateRefitMasks`.
It appears that this is due to the vehicle definition not explicitly overriding the cargo type for locomotives which do not carry cargo. (I cannot comment on whether this makes the GRF correct or incorrect).
An example of this is "DB BR 143", engine ID 40.

### Steps to reproduce

See available vehicles for DACH 0.3.2 from bananas before and after #11719.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

As per #12302.

Train engines are able to carry no cargo, and it did not used to matter what their default cargo type is.

Since #11719 it does now matter. If a NewGRF overrides an engine with a cargo type that is not valid for the current climate, and sets the capacity to zero without setting the cargo type to something valid (even though it does not carry cargo), the engine will be disabled.

## Description

Instead, if the cargo type is invalid, check if the cargo capacity is zero and that the cargo type has not been changed from its default value.

The cargo type will be forced to the first available type (usually passengers) instead of the engine being disabled.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/newgrf.cpp [hunk 1]
```diff
@@ -9161,6 +9161,13 @@ static void CalculateRefitMasks()
 				ei->cargo_type = (CargoID)FindFirstBit(ei->refit_mask);
 			}
 		}
+		if (!IsValidCargoID(ei->cargo_type) && e->type == VEH_TRAIN && e->u.rail.railveh_type != RAILVEH_WAGON && e->u.rail.capacity == 0) {
+			/* For train engines which do not carry cargo it does not matter if their cargo type is invalid, fallback to
+			 * the first available instead, if the cargo type has not been changed. */
+			if (GetActiveCargoLabel(ei->cargo_label) != CT_INVALID) {
```
Comment (TrueBrain) [inline src/newgrf.cpp:9168]: Is this check still needed? You already concluded the cargoID is not valid. Would this ever return anything other than `CT_INVALID`?

File: src/newgrf.cpp [hunk 2]
```diff
@@ -9161,6 +9161,13 @@ static void CalculateRefitMasks()
 				ei->cargo_type = (CargoID)FindFirstBit(ei->refit_mask);
 			}
 		}
+		if (!IsValidCargoID(ei->cargo_type) && e->type == VEH_TRAIN && e->u.rail.railveh_type != RAILVEH_WAGON && e->u.rail.capacity == 0) {
+			/* For train engines which do not carry cargo it does not matter if their cargo type is invalid, fallback to
+			 * the first available instead, if the cargo type has not been changed. */
```
Comment (TrueBrain) [inline src/newgrf.cpp]: Ghehe, this is a very long sentence :)

```suggestion
			/* For train engines which do not carry cargo it does not matter if their cargo type is invalid.
			 * Fallback to the first available instead, if the cargo type has not been changed. */
```

File: src/newgrf.cpp (hunk 1 above)
Comment (PeterN) [reply src/newgrf.cpp:9168]: This check is to ensure this change only applies if the default cargo type (stored as a label) has not been changed. 

This value is set to CT_INVALID only when cargo_type has been changed by NewGRF.

Comment (PeterN) [reply src/newgrf.cpp:9168]: I've updated the comment to document this slightly better.

**Review by TrueBrain — APPROVED** [review]
