### PR TITLE
Fix #6399: Create parent directories if they don't already exist

### LINKED ISSUE #6399: Fails to download online content when ~/.local/share does not exist
**_matthijs_ opened the ticket and wrote:**

> It seems that when downloading things through the online content user interface, and ~/.local/share does not exist, the download fails with a "file not writable" error.
> 
> strace shows that it tries to open up the final filename right away, which obviously fails:
> 
> open("/root/.local/share/openttd/content_download/baseset/OpenSFX-0.2.3.tar.gz", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 ENOENT (No such file or directory)
> 
> No mkdir calls happen at all (not even inside ~/.local/share, interestingly). When ~/.local/share *does* exist, mkdir calls do happen, but only inside ~/local.share. In this case, there is also a failed mkdir for ~/.config/openttd, so there is presumably also a problem for a non-existing ~/.config directory.
> 
> This problem was observed on version 1.5.3 and 1.4.4, on a Debian Sid and Jessie system respectively.
> 
> In addition, the automatic OpenGFX download (when no gfx are available) fails when ~/.local/share does not exist, though an additional problem is that no error (just a download dialog that gets shown for a fraction of a second, then disappears leaving an empty window).

**Reported version**: _1.5.3_
**Operating system**: _Linux_

---

### PR DESCRIPTION
**Pull request by LordAro**
I think ~/.local/share is special, in that it's the only 2-part personal directory where the parents haven't definitely been created already. So in this highly unlikely scenario where ~/.local/share doesn't exist, recursively try to create parents

Pretty sure I got all the pointers correct...

### CODE REVIEW

**Comment by James103** [comment]
It looks like you are getting "can't open file openttd.exe" during the testing step on the checks. Why? Is it something to do with the changes made?

File: src/fileio.cpp [hunk 1]
```diff
@@ -527,10 +527,23 @@ FILE *FioFOpenFile(const char *filename, const char *mode, Subdirectory subdir,
 
 /**
  * Create a directory with the given name
+ * If the parent directory does not exist, it will try to create that as well.
  * @param name the new name of the directory
  */
 void FioCreateDirectory(const char *name)
 {
+	char dirname[MAX_PATH];
+	strecpy(dirname, name, lastof(dirname));
```
Comment (James103) [inline src/fileio.cpp:536]: Why choose `strecpy` over `strcpy`? What is the difference between the two?

**Comment by glx22** [comment]
Re-ran the failed checks. Seems they are failing again, I guess it's an infinite loop or something similar.

**Comment by LordAro** [comment]
Damn. Curious that it's working on Linux...

File: src/fileio.cpp (hunk 1 above)
Comment (LordAro) [reply src/fileio.cpp:536]: strecpy is an OTTD-special that has a end-point parameter. Helps prevent buffer overruns (e.g. if name is longer than MAX_PATH)

**Review by glx22 — APPROVED** [review]
LGTM
