### PR TITLE
Fix #8137: New clients can't join (desync) after funding an industry

### LINKED ISSUE #8137: New clients can't join (desync) after funding an industry
## Version of OpenTTD
39092ee13b44573d1b8111a5d2ee1d46990f239f and 1.10.1

## Expected result
No desync

## Actual result
Connected clients stay, new clients desync almost instantly.

## Steps to reproduce
Fund a coal mine as shown on the screenshot and start taking coal from the station.
Screenshot from 2020-05-11 15-18-05

### PR DESCRIPTION
**Pull request by ldpl**
Ended up copying half of FindStationsAroundTiles (which is a mess anyway) in favor of reducing duplication with Station::RecomputeCatchment.

Closes #8141

### CODE REVIEW

**Comment by LordAro** [comment]
I have to wonder whether just returning a list/vector/whatever of stations then operating on the return value would be nicer than the lambda & capture variables...

File: src/industry_cmd.cpp [hunk 1]
```diff
@@ -1697,20 +1697,13 @@ static void PopulateStationsNearby(Industry *ind)
...
-	}
-	if (cargo_index >= lengthof(ind->accepts_cargo)) return;
-
-	/* Cargo is accepted, add industry to nearby stations nearby industry list. */
-	for (Station *st : ind->stations_near) {
-		st->industries_near.insert(ind);
-	}
+	ForAllStationsAroundTiles(ind->location, [ind](Station *st, TileIndex tile) {
+		if (!IsTileType(tile, MP_INDUSTRY) || GetIndustryIndex(tile) != ind->index)
+			return false;
```
Comment (LordAro) [inline src/industry_cmd.cpp]: Don't put this on its own line, or use braces

File: src/station_base.h [hunk 2]
```diff
@@ -557,4 +558,41 @@ class AirportTileIterator : public OrthogonalTileIterator {
...
+		if (st == nullptr) continue; /* Waypoint */
+
+		/* Check if station is attached to an industry */
+		if (!_settings_game.station.serve_neutral_industries && st->industry != nullptr) continue;
+
+		/* Test if the tile is within the station's catchment */
+		TILE_AREA_LOOP(tile, ta) {
+			if (st->TileIsInCatchment(tile)) {
+				if (func(st, tile))
+					break;
```
Comment (LordAro) [inline src/station_base.h]: same here

**Comment by ldpl** [comment]
@LordAro it may be nicer but I highly doubt it will be as performant.
Though StationFinder already returns a vector and is still a mess imo.

**Comment by LordAro** [comment]
You'd be surprised what optimisers can do with vectors. Especially when compared with variable-capturing lambdas...

File: src/station_base.h [hunk 3]
```diff
@@ -557,4 +558,41 @@ class AirportTileIterator : public OrthogonalTileIterator {
 
 void RebuildStationKdtree();
 
+/**
+ * Call a function on all stations that have any part of the requested area within their catchment.
+ * @param area The TileArea to check
+ * @param func The function to call, must take two parameters: Station* and TileIndex and return true
```
Comment (LordAro) [inline src/station_base.h:565]: `@tparam` for template variables

File: src/station_base.h [hunk 4]
```diff
@@ -557,4 +558,41 @@ class AirportTileIterator : public OrthogonalTileIterator {
...
+ *             if coverage of that tile is acceptable for a given station or false if search should continue
+ */
+template<typename Func>
```
Comment (LordAro) [inline src/station_base.h:568]: Though I accept it might be a bit much in this case, codestyle does dictate that all template parameters start with 'T'

File: src/station_base.h [hunk 5]
```diff
@@ -557,4 +558,41 @@ class AirportTileIterator : public OrthogonalTileIterator {
...
+void ForAllStationsAroundTiles(const TileArea &ta, Func func)
```
Comment (LordAro) [inline src/station_base.h:569]: Does it actually need to be templated at all? `std::function<void(Station *, TileIndex)>` (or whatever the correct syntax is) might be enough?

**Review by LordAro — CHANGES_REQUESTED** [review]
In the meantime...

File: src/station_cmd.cpp [hunk 6]
```diff
@@ -3965,70 +3966,29 @@ static void AddNearbyStationsByCatchment(TileIndex tile, StationList *stations,
...
+		if (IsTileType(this->tile, MP_HOUSE)) {
+			/* Town nearby stations need to be filtered per tile. */
+			assert(this->w == 1 && this->h == 1);
+			AddNearbyStationsByCatchment(this->tile, &this->stations, Town::GetByTile(this->tile)->stations_near);
+		} else {
+			ForAllStationsAroundTiles(*this, [this](Station *st, TileIndex tile) {
+				this->stations.insert(st);
+				return true;
+			});
+		}
```
Comment (glx22) [inline src/station_cmd.cpp:3985]: missing `MP_INDUSTRY` case ?

File: src/station_base.h (hunk 4 above)
Comment (ldpl) [reply src/station_base.h:568]: I copied Func name from other ForAllStations functions

File: src/station_cmd.cpp (hunk 6 above)
Comment (ldpl) [reply src/station_cmd.cpp:3985]: @glx22 not missing, it just makes no sense whatsoever if you see how it is called

File: src/station_base.h (hunk 5 above)
Comment (ldpl) [reply src/station_base.h:569]: @LordAro yes, that's the whole point, std::function call is not optimized afaik.

File: src/station_cmd.cpp (hunk 6 above)
Comment (glx22) [reply src/station_cmd.cpp:3985]: Oh I see, it's never called for industries. But I think the industry case was future proof.

Comment (ldpl) [reply src/station_cmd.cpp:3985]: @glx22 it's a weird way to future proof as it was not handled correctly and likely broke newgrf houses.

Comment (LordAro) [reply src/station_cmd.cpp:3985]: Perhaps an assert/NOT_REACHED to make it clear?

**Review by LordAro — APPROVED** [review]
Pretty sure this is fine now

File: src/station_cmd.cpp (hunk 6 above)
Comment (ldpl) [reply src/station_cmd.cpp:3985]: @LordAro Not reached what? industries can be reached, just shouldn't work as it was before.
