### PR TITLE
Fix travel times stored in the linkgraph 

### LINKED ISSUE #9665: [Bug]: Travel times stored in linkgraph are incorrect for all non-direct journey types
### Version of OpenTTD

Since #9457

### Expected result

Stored link graph travel times are correct

### Actual result

Link graph stored travel times are incorrect in the case where one or more of the following order types is present between the source and destination station orders:

* Go via waypoint
* Go via station (i.e. not stopping)
* Go to station with both no loading and no unloading
* Depot/hangar order (servicing and taken, or unconditional go to depot/hangar)

`current_order_time` is the time taken by the current order, not the time taken since cargo was last loaded/unloaded and does not correspond with `last_loading_station`.

### Steps to reproduce

Create an order list using one of the above intermediary order types.

See attached for an example: [savegame](https://github.com/OpenTTD/OpenTTD/files/7448559/Linkgraph.travel.time.test.1.1990-08-16.sav.zip)

### PR DESCRIPTION
**Pull request by nchappe**
## Motivation / Problem

This PR fixes a few problems with travel times in the linkgraph (#9457).
- The first commit is a tiny code cleanup.
- The second commit fixes a small loss of precision that can happen (rarely) on linkgraph compression for low-capacity links.
- The third commit fixes #9665.

## Description

To fix #9665, I added a member variable `BaseConsist::time_since_last_loading` that is incremented whenever `current_order_time` is, and that is reset when the vehicle loads cargo at a station, just like `last_loading_station`.

This fully fixes the travel times in the example savegame of #9665. I also tested with a go to depot order and with a basic conditional order.

## Limitations

This PR needs a savegame upgrade.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/linkgraph/refresh.cpp [hunk 1]
```diff
@@ -203,6 +203,7 @@ void LinkRefresher::RefreshStats(const Order *cur, const Order *next)
 	StationID next_station = next->GetDestination();
 	Station *st = Station::GetIfValid(cur->GetDestination());
 	if (st != nullptr && next_station != INVALID_STATION && next_station != st->index) {
+		Station *st_to = Station::Get(next_station);
```
Comment (frosch123) [inline src/linkgraph/refresh.cpp:206]: Can `st_to` ever be a nullptr?
Line 215 accesses it directly, whie line 225 checks the pointer first.
Possibly also remove the check in line 225?

**Comment by frosch123** [comment]
The counter `time_since_last_loading` added here seems to be similar to `last_station_departure_date` from #9093.
* In #9093 an absolute time was considered better than a relative time.
* #9093 seems to care only about the date, while this PR cares about ticks.
* #9093 is pretty unclear about when to set the counter "loading", "unloading", "stopping"...

Is it the same? or is there an important difference that makes it necessary to add two similar but distinct time stamps?

**Comment by nchappe** [comment]
I thought about using a date, the code would be a bit simpler but it would be a bit less precise. More importantly, it would break when using the cheat that changes the current year. While working on this PR I found out that setting the current year does break `date_of_last_service` a bit in master, I will probably open a bug or a PR about that later.

The time I store does not exactly correspond to the date of last station departure because to fix #9665 the variable introduced by my PR has to be exactly the time since `last_loading_station` was last updated, which is very specific  (see `Vehicle::LeaveStation()` for the exact conditions). So it makes sense to have three similar but separate variables `current_order_time`, `time_since_last_loading` and `last_station_departure_date`.

**Comment by glx22** [comment]
Isn't it possible to just store current vehicle tick and do some math when the exact value is needed ? And remove most counters.

**Comment by nchappe** [comment]
Without the time since last loading, you would probably need to store the date of last loading, which has its advantages (no need to increment the counters) and drawbacks (lower resolution, problems when using cheats and when reaching last valid year).

I grep'd for `current_order_time` to determine where I should increment `time_since_last_loading`, so assuming the former works fine, hopefully the latter will too.

**Comment by nchappe** [comment]
I looked a bit more into your suggestion and I think `_date * DAY_TICKS + _date_frac` as an int64 would probably work as a tick counter. Should I replace the counter introduced in this PR with a timestamp in ticks and deduce the travel time from it?

**Comment by nchappe** [comment]
As suggested, I replaced the tick counter with a date in the fix to #9665. I also added a trivial fix to #9708.

**Comment by nchappe** [comment]
Could someone please have another look at this PR?

**Comment by nchappe** [comment]
Ping. Cargodist is severely broken for some networks since OpenTTD 12.0 (#9665, #9708), and this PR aims to fix it.
I can always split it into several PRs if you are not convinced by some of the commits.

**Review by LordAro — DISMISSED** [review]
Seems reasonable to me, but I'd like another pair of eyes on it

(Please disregard that I screwed up the rebase, we can fix that on merge... or you can fix it :) )

**Comment by nchappe** [comment]
I rebased onto master. #10035 makes the third commit simpler, I now use _tick_counter instead of _date_frac to compute durations in ticks.

**Review by michicc — APPROVED** [review]
