### PR TITLE
Fix #10343: Towns attempt and fail to extend disallowed roadtypes

### LINKED ISSUE #10343: [Bug]: Towns attempt and fail to extend disallowed roadtypes
### Version of OpenTTD

nightly 20230112

### Expected result

The NewRoadType spec includes a property that disallows towns from building particular types of roads - so that a town does not inappropriately consist entirely of motorways or other non-urban roadtype. The town growth function does not appear to account for this, and will attempt to build off non-town roadtypes when expanding. This results in the town creating a lot of ugly T junctions on non-town roadtypes.

Instead, the town should not attempt to extend road from a non-town roadtype. It shouldn't *ignore* these roadtypes altogether, as if they were not roads, because that would mean it wouldn't find areas of town on the other side of the road...

### Actual result

New Godfield Transport, 1950-01-28
Setup, with non-town roadtype around the edge of the town.

New Godfield Transport, 1960-01-31
After 10 years, with spiky non-town road.

New Godfield Transport, 1950-02-15
Without roadtypes.

New Godfield Transport, 1960-01-27
After 10 years.

### Steps to reproduce

See above screenshots.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

As per #10343, and also way back in #8506/#8535, towns are able to build road pieces for road types even if the the roadtype disallows it.

image

## Description

This is resolved by checking if the tile currently has a non-buildable roadtype, and disallow building a road. This is slightly different from the fix in #8535 as that also inadvertently prevented building houses along non-buildable roadtypes, though that may be permitted.

image

This also resolves and additional concern if a NewGRF disallows towns from building all roadtypes, by forcing the default ROADTYPE_ROAD slot to be town-buildable if no other roadtypes are town-buildable.

Closes #10343

## Limitations

Some NewGRFs maybe rely on the previously broken behaviour. Those NewGRFs can be fixed by the author.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by PeterN** [comment]
And yes, this does affect town growth...

File: src/town_cmd.cpp [hunk 1]
```diff
@@ -1445,6 +1445,9 @@ static void GrowTownInTile(TileIndex *tile_ptr, RoadBits cur_rb, DiagDirection t
 
 		if (!_settings_game.economy.allow_town_roads && !_generating_world) return;
 
+		/* Don't allow junctions on roadtypes which can't be built by towns. */
```
Comment (rubidium42) [inline src/town_cmd.cpp]: Should both of these maybe be before the `_grow_town_result = GROWTH_SEARCH_STOPPED;`? After all, based on the comment it looks like it's definitely going to create some road, so it does not need to search further and then you still prevent it from building the road.
I've got no idea what the effect would be nor whether that would be a welcome effect.

Comment (PeterN) [reply src/town_cmd.cpp]: Not sure, there is a distinction between GROWTH_SUCCEED and GROWTH_SEARCH_STOPPED, but I don't know what.

**Comment by PeterN** [comment]
Rewrite of the change to cope with the issue of the town being unable to extend even the roadtype it is going to use.

File: src/town_cmd.cpp [hunk 2]
```diff
@@ -1362,6 +1362,20 @@ static inline bool RoadTypesAllowHouseHere(TileIndex t)
 	return !allow;
 }
 
+/** Test if town can grow road onto a specific tile.
+ * @param town Town that is building.
+ * @param tile Tile to build upon.
+ * @return true iif the tile's road type don't prevent extending the road.
```
Comment (rubidium42) [inline src/town_cmd.cpp]: Tiny typo: s/iif/iff/

**Review by rubidium42 — APPROVED** [review]
