### PR TITLE
Fix #9535: Maintain a reverse dependency map of network content

### LINKED ISSUE #9535: [Bug]: Poor performance opening "Check Online Content" window due to O(N^3) behaviour
### Version of OpenTTD

master (9c74dc24), however this is not a new bug

### Expected result

Blazing fast, silky smooth, positive adjectives performance when opening the check online content window

### Actual result

Frame rate decreases dramatically when the list is being populated.
Screenshot_2021-09-03_17-13-37-trim

The performance problem seems to be created in `ClientNetworkContentSocketHandler::ReverseLookupDependency` via `ClientNetworkContentSocketHandler::CheckDependencyState`.
This seems to be because each received content item calls `CheckDependencyState` on each previously received item, which calls `ReverseLookupDependency` which again iterates all previously received items, leading overall to O(N^3) behaviour in the number of content items. See below for approximate measurements.
Screenshot_2021-09-03_17-25-28

### Steps to reproduce

1. Open the "Check Online Content" window from the main menu (not when in a game).

### PR DESCRIPTION
**Pull request by JGRennison**
## Motivation / Problem

This fixes the performance issues in #9535 with dependency lookup when retrieving the content list from the content server.

## Description

Instead of iterating all content to find reverse dependencies, maintain an iteratively built reverse dependency map.
When a new content item arrives, instead of calling `CheckDependencyState` on all content items, only call it on the reverse tree dependencies of the newly received item.

## Limitations

N/A

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by TrueBrain — DISMISSED** [review]

File: src/network/network_content.h [hunk 1]
```diff
@@ -82,6 +84,7 @@ class ClientNetworkContentSocketHandler : public NetworkContentSocketHandler, Co
 	bool Receive_SERVER_CONTENT(Packet *p) override;
 
 	ContentInfo *GetContent(ContentID cid);
+	const ContentInfo *GetContent(ContentID cid) const { return const_cast<ClientNetworkContentSocketHandler *>(this)->GetContent(cid); }
```
Comment (LordAro) [inline src/network/network_content.h]: Unless I'm missing something obvious, the existing GetContent method doesn't make any changes to the object and can be declared const without making this hacky extra function

Comment (JGRennison) [reply src/network/network_content.h]: That's fixed now.

**Review by LordAro — APPROVED** [review]
