### PR TITLE
Fix #8230: Resolve ".." when opening files in .tar

### LINKED ISSUE #8230: Cannot open the file when starting AI downloaded via online service
## Version of OpenTTD
1.10.2
## Expected result
Script starts normaly
## Actual result
Script error with: cannot open the file
## Steps to reproduce
Download NotPerfectAI from the online service, set it up and start a new game.

Unnamed, 1950-01-09

### PR DESCRIPTION
**Pull request by glx22**
Possible solution. Not sure if my algorithm is optimal (but at least it's easy to understand).

### CODE REVIEW

File: src/fileio.cpp [hunk 1]
```diff
@@ -481,6 +482,25 @@ FILE *FioFOpenFile(const char *filename, const char *mode, Subdirectory subdir,
 		strecpy(resolved_name, filename, lastof(resolved_name));
 		strtolower(resolved_name);
 
+		/* Resolve ".." */
+		std::stringstream ss(resolved_name);
```
Comment (LordAro) [inline src/fileio.cpp]: streams are a bit ick. Is there no existing "string split" function that could be used? If nothing else `std::istringstream` might be a bit better.

File: src/fileio.cpp [hunk 2]
```diff
@@ -481,6 +482,25 @@ FILE *FioFOpenFile(const char *filename, const char *mode, Subdirectory subdir,
...
+				tokens.pop_back();
+				tokens.pop_back();
+			} else {
+				tokens.push_back(token);
+				tokens.push_back(PATHSEP);
+			}
+		}
+		tokens.pop_back();
+		resolved_name[0] = '\0';
+		for (std::string token : tokens) {
```
Comment (LordAro) [inline src/fileio.cpp]:
```suggestion
		for (const std::string &token : tokens) {
```

File: src/fileio.cpp [hunk 3]
```diff
@@ -481,6 +482,25 @@ FILE *FioFOpenFile(const char *filename, const char *mode, Subdirectory subdir,
...
+		std::stringstream ss(resolved_name);
+		std::vector<std::string> tokens;
+		for (std::string token; std::getline(ss, token, PATHSEPCHAR);) {
+			if (token == "..") {
+				if (tokens.size() < 4) return nullptr;
+				tokens.pop_back();
+				tokens.pop_back();
+			} else {
+				tokens.push_back(token);
+				tokens.push_back(PATHSEP);
```
Comment (LordAro) [inline src/fileio.cpp]: Maybe instead of storing the PATHSEP in the vector, it could be appended to resolved_name directly?

**Review by LordAro — CHANGES_REQUESTED** [review]
I know this isn't exactly a performance hotspot, but...

File: src/fileio.cpp [hunk 4]
```diff
@@ -481,6 +482,25 @@ FILE *FioFOpenFile(const char *filename, const char *mode, Subdirectory subdir,
 		strecpy(resolved_name, filename, lastof(resolved_name));
 		strtolower(resolved_name);
 
+		/* Resolve ".." */
+		std::stringstream ss(resolved_name);
+		std::vector<std::string> tokens;
+		for (std::string token; std::getline(ss, token, PATHSEPCHAR);) {
```
Comment (LordAro) [inline src/fileio.cpp]: Not really a fan of the for loop here, it seems a bit hacky. while loop might be nicer?

**Review by LordAro — APPROVED** [review]
