### PR TITLE
Fix #14620: Use full file path when deleting files.

### LINKED ISSUE #14620: [Bug]: Deleting a heightmap always fails
### Version of OpenTTD

Master

### Expected result

In the scenario editor the user has the ability to save heightmaps. In that window there's a delete button which should delete the selected heightmap file.

### Actual result

Deleting a heightmap in the scenario editor always fails. In OpenTTD-RC3 (don't know why I still have that one installed) it fails with a message "Unable to delete file". ~In current master it fails silently, this seems to be related to 4eaeccd.~ fixed by #14619.

Deleting savegames or scenarios using the same window works fine.

### Steps to reproduce

1. Start openttd, open the scenario editor
2. Press the floppy disk button, select save heightmap
3. Select a heightmap you want to delete
4. Click the delete button. Depending on the openttd version you get an error message or nothing happens.

### PR DESCRIPTION
**Pull request by Kuhnovic**
## Motivation / Problem

#14620 

## Description

The current implementation assumes the file to be deleted is either a .sav or .scn file. This works for savegames and scenarios but fails for heightmaps (typically .png), and other file types we might add in the future.

The currently selected item holds a full path to the file, so I've used that path to delete the file. This takes away need to make assumptions about the file path. It does mean the Delete button should only be clicked when something is selected, so the button is automatically enabled/disabled.

## Limitations

Changing the text in the lower textbox clears the current selection if there is one. If you then change the text back to a file that exist then it won't automatically select it. IMO it's not really something that is necessary.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/fios.cpp [hunk 1]
```diff
@@ -230,16 +230,6 @@ std::string FiosMakeHeightmapName(std::string_view name)
...
 }
 
-/**
- * Delete a file.
- * @param name Filename to delete.
- * @return Whether the file deletion was successful.
- */
-bool FiosDelete(std::string_view name)
-{
-	return FioRemove(FiosMakeSavegameName(name));
```
Comment (LordAro) [inline src/fios.cpp:240]: looks like there's only a single other usage of FiosMakeSavegameName - is that still necessary?

**Review by LordAro — COMMENTED** [review]
commit message missing a '#' :)

File: src/fios.cpp (hunk 1 above)
Comment (Kuhnovic) [reply src/fios.cpp:240]: FiosMakeSavegameName calls FiosMakeFilename which is currently local to fios.cpp, and does abstract away some technicalities. The same applies to FiosMakeHeightmapName. I think it's ok to keep them.

**Review by rubidium42 — APPROVED** [review]
