### PR TITLE
Fix #13839: Incorrect colour of first company legend in smallmap window.

### LINKED ISSUE #13839: [Bug]: Wrong company colour on the map
### Version of OpenTTD

15.0-beta1, Win10

### Expected result

The colours of the companies on the map are correct

### Actual result

Not always, but often the colours of companies on the map are not correct.
After loading a saved game, they are usually correct.
This isn't an entirely new bug. I encountered it a while ago.

Image

### Steps to reproduce

Start a new game and compare the colour of the company on the map with its actual colour.

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

As per #13839, the company legend can show the wrong colour for the initial company.

When overriding the initial company colour with the user's default colour setting, the smallmap's company legend was not updated.

## Description

Update the smallmap's company legend when setting the initial colour.

## Limitations

This flow is completely illogical and shouldn't hook into so many places. The smallmap window should just fill this information in when it is opened.

But that's a side-quest for another day...

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Review by 2TallTyler — DISMISSED** [review]

File: src/openttd.cpp [hunk 1]
```diff
@@ -875,6 +876,7 @@ static void MakeNewGameDone()
 		c->colour = _settings_client.gui.starting_colour;
 		ResetCompanyLivery(c);
 		_company_colours[c->index] = c->colour;
+		BuildOwnerLegend();
```
Comment (frosch123) [inline src/openttd.cpp]: I think this should use `CMD_SET_COMPANY_COLOUR`, just like for the second CC below.

Comment (PeterN) [reply src/openttd.cpp]: Good point, that would make it a lot neater.

**Review by frosch123 — APPROVED** [review]
