### PR TITLE
Fix #12019, #12020: Depot unbunching dropdown issues

### LINKED ISSUE #12019: [Bug]: Depot order dropdown in vehicle orders windows doesn't highlight the correct order type
### Version of OpenTTD

14.0-beta3 Windows10

### Expected result

The dropdown to select order type for a go to depot order should highlight the current order type, ie. if it's a "Stop" order then "Stop" should be highlighted, if it's a "Wait to unbunch" order then "Unbunch" should be highlighted.

This is the expected behaviour based on the behaviour of the Stop/Non-stop dropdown.
image

### Actual result

The "Always go" option is always highlighted.
image

### Steps to reproduce

1. Set up a vehicle with a go to depot order.
2. Change the depot order to Service if needed, Stop or Unbunch.
3. Open the dropdown to change the type of the depot order.

### LINKED ISSUE #12020: [Bug]: Unbunch and service if needed should be mutually exclusive depot order types
### Version of OpenTTD

14.0-beta3 Windows10

### Expected result

An "Unbunch" depot order type should be mutually exclusive with all other depot order types ("Always go", "Service if needed" and "Stop").

### Actual result

An "Unbunch" and "Service if needed" order type can be combined, giving a combined "Service at X Depot (wait to unbunch)" order.
image

I haven't tested if this order type makes the unbunch depot visit dependent on needing a service... But it presumably shouldn't be selectable as an order type!

### Steps to reproduce

1. Set up a vehicle with a go to depot order
2. Select the depot order and change to the "Unbunch" type
3. Change the depot order to the "Service if needed" type
The order is now listed as a service and unbunch order.

Doing the reverse (setting the order type to "Service if needed" first, then setting it to "Unbunch") works as expected.

### PR DESCRIPTION
**Pull request by 2TallTyler**
## Motivation / Problem

1. #12019: The dropdown to select order type for a go to depot order should highlight the current order type, ie. if it's a "Stop" order then "Stop" should be highlighted, if it's a "Wait to unbunch" order then "Unbunch" should be highlighted.
2. #12020: An "Unbunch" depot order type should be mutually exclusive with all other depot order types ("Always go", "Service if needed" and "Stop").

## Description

1. Properly highlight the Unbunch option in dropdown menus, if selected for the current depot. 
2. When changing the depot action from Unbunch to Service if required, unset the Unbunch action flag. 

Closes #12019.
Closes #12020.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/order_cmd.cpp [hunk 1]
```diff
@@ -1389,6 +1389,7 @@ CommandCost CmdModifyOrder(DoCommandFlag flags, VehicleID veh, VehicleOrderID se
 					case DA_SERVICE:
 						order->SetDepotOrderType((OrderDepotTypeFlags)(order->GetDepotOrderType() | ODTFB_SERVICE));
 						order->SetDepotActionType((OrderDepotActionFlags)(order->GetDepotActionType() & ~ODATFB_HALT));
+						order->SetDepotActionType((OrderDepotActionFlags)(order->GetDepotActionType() & ~ODATFB_UNBUNCH));
```
Comment (glx22) [inline src/order_cmd.cpp:1392]: I'd also exchange lines 1398 and 1399, so all cases use the same order.

**Review by rubidium42 — APPROVED** [review]
