### PR TITLE
Fix #9595: Always use plural forms of cargo for subsidy strings

### LINKED ISSUE #9595: [Bug]: Localized plural strings required in certain instances
### Version of OpenTTD

12.0-rc1, Linux Mint 20.2 Cinnamon (based on Ubuntu 20.04), using openttd-12.0-RC1-linux-ubuntu-focal-amd64.deb

### Expected result

In the Romanian locale, the STR_NEWS_SERVICE_SUBSIDY_OFFERED and STR_NEWS_SERVICE_SUBSIDY_AWARDED_* need to use plural form for: passengers and mail.

Specifically: STR_CARGO_PLURAL_PASSENGERS and STR_CARGO_PLURAL_MAIL

### Actual result

Currently, STR_CARGO_SINGULAR_PASSENGER and STR_CARGO_SINGULAR_MAIL are used - and they're incorrect in Romanian.

The screenshot below shows both wrong cases on 01-04-1967 and 01-03-1967:
wrong locale

### Steps to reproduce

Use the Romanian locale and wait for subsidy news, then do the required action to get the subsidy award. Both will be displayed in singular form.

### PR DESCRIPTION
**Pull request by LordAro**
## Motivation / Problem
Subsidy strings use a hardcoded singular/plural form of cargo names, depending on the string. For some languages this is the wrong one and cannot be changed.

## Description
Make subsidy strings always use the plural form of cargo names. Reword english strings to match (remove 'service')

## Limitations
Invalidates all existing translations. Might cause the reverse problem for some languages

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/subsidy.cpp [hunk 1]
```diff
@@ -74,13 +74,9 @@ std::pair<NewsReferenceType, NewsReferenceType> SetupSubsidyDecodeParam(const Su
...
 
-	/* Choose whether to use the singular or plural form of the cargo name based on how we're printing the subsidy */
+	/* Always use the plural form of the cargo name - trying to decide between plural or singular causes issues for translations */
 	const CargoSpec *cs = CargoSpec::Get(s->cargo_type);
-	if (mode == SubsidyDecodeParamType::Gui || mode == SubsidyDecodeParamType::NewsWithdrawn) {
-		SetDParam(parameter_offset, cs->name);
-	} else {
-		SetDParam(parameter_offset, cs->name_single);
-	}
+	SetDParam(parameter_offset, cs->name);
```
Comment (TrueBrain) [inline src/subsidy.cpp:79]: does this mean `name_single` can be removed completely?

Comment (LordAro) [reply src/subsidy.cpp:79]: Probably? It's not used anywhere else. Might make reintroducing it at some point in the future difficult though

Comment (TrueBrain) [reply src/subsidy.cpp:79]: But by the logic of this PR, it will always be a problem for translations?

Comment (LordAro) [reply src/subsidy.cpp:79]: I would guess that depends on the string, but likely, yes

**Review by TrueBrain — APPROVED** [review]
I have no clue if this is a good idea or not; but I do like you fix a bug. So YOLO?

(we can keep the `name_single` for now .. who knows)
