### PR TITLE
Fix #7400: WaterClass for tree tiles was not converted for old saves preventing industry creation.

### LINKED ISSUE #7400: Funding a new primary industry fails on top of trees
1.9.0-RC1

Fund a new industry.

Always shows "Can't construct this industry type here... site unsuitable"

Using a savegame from 1.8, (re-saved in 1.9.0-RC1) try to fund a new industry. This not happen when using a new fresh game.

### PR DESCRIPTION
**Pull request by PeterN**
#7309 added WaterClass to tree tiles without performing any savegame conversion, causing problems for old saves. The information is easily rebuildable from the tree ground type, which this PR does on load unconditionally.

An alternative solution is to revert #7309 and explicitly test for trees with tree ground type shore. A  branch with that version is https://github.com/PeterN/OpenTTD/commits/fix-7400

### CODE REVIEW

File: src/saveload/afterload.cpp [hunk 1]
```diff
@@ -3111,6 +3111,10 @@ bool AfterLoadGame()
 		FOR_ALL_INDUSTRIES(ind) if (ind->neutral_station != NULL) ind->neutral_station->industry = ind;
 	}
 
+	for (TileIndex t = 0; t < map_size; t++) {
```
Comment (Eddi-z) [inline src/saveload/afterload.cpp]: Should we guard this by a "up to and including the current savegame version" check?

Also i think a comment might be appropriate why this is here, for a person in the far future.

Comment (PeterN) [reply src/saveload/afterload.cpp]: This needs to be backported in which case the savegame version check is pointless, as we don't want to bump 1.9's version and it's not necessary anyway.

So we can add a savegame guard for master now, and remove it in the backport, or keep it as is here and add a savegame guard later in master?

Comment (nielsmh) [reply src/saveload/afterload.cpp]: The guard would just prevent the conversion from running when not necessary. On the other hand, the conversion doesn't hurt anything, at least not currently.

Comment (PeterN) [reply src/saveload/afterload.cpp]: Should we bump master's savegame version then? And ignore that part for the backport?

**Review by michicc — DISMISSED** [review]

File: src/saveload/afterload.cpp [hunk 2]
```diff
@@ -3111,6 +3111,13 @@ bool AfterLoadGame()
 		FOR_ALL_INDUSTRIES(ind) if (ind->neutral_station != NULL) ind->neutral_station->industry = ind;
 	}
 
+	if (IsSavegameVersionBefore(SLV_TREES_WATER_CLASS)) {
+		/* Update water class for trees for all current savegame versions. */
```
Comment (TrueBrain) [inline src/saveload/afterload.cpp]: Guess you forgot to update this comment now :D (nitpick :P)

**Review by nielsmh — DISMISSED** [review]

**Review by TrueBrain — APPROVED** [review]
