### PR TITLE
Fix #14256, dfd9fbf873: Company finance windows not updated when paused.

### LINKED ISSUE #14256: [Bug]: Burrow and Repay Loan buttons do not refresh
### Version of OpenTTD

OpenTTD 20250512-master-gd9247fa1a0

### Expected result

Own Funds, Loan and Bank Balance are refreshed when clicking Burrow/Repay Loan while the game is paused.

### Actual result

Own Funds, Loan and Bank Balance aren't refreshed when clicking Burrow/Repay Loan while the game is paused.
https://github.com/user-attachments/assets/4a723243-9bb3-49b8-808c-74ec33c21b67

### Steps to reproduce

In Game Options, Advanced and in Limitations branch, change When paused allow: All actions
Start a new game
Pause game
Open finances
Borrow or repay money

### PR DESCRIPTION
**Pull request by PeterN**
## Motivation / Problem

As per #14256, company finance windows are not updated when the game is paused.

## Description

Refresh company finance windows via a WindowTimer instead of in game loop.

As the invalidation affects multiple windows this is a global timer instead of window-specific.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/company_cmd.cpp [hunk 1]
```diff
@@ -233,8 +233,8 @@ void InvalidateCompanyWindows()
 		}
 		SetWindowWidgetDirty(WC_COMPANY, cid, WID_C_DESC_COMPANY_VALUE);
 	}
-	_dirty_company_finances = {};
-}
+	_dirty_company_finances.Reset();
```
Comment (2TallTyler) [inline src/company_cmd.cpp:236]: If it's being invalidated every millisecond, does it really need to be manually dirtied here? Or is this just for consistency?

**Review by 2TallTyler — APPROVED** [review]

File: src/company_cmd.cpp (hunk 1 above)
Comment (PeterN) [reply src/company_cmd.cpp:236]: This particular line doesn't change any behaviour, I just think `Reset()` is clearer than assigning a new default `CompanyMask`, which also has nothing set.

It's reset so that everything *isn't* invalidated every tick.
