### PR TITLE
Fix #14044: Negative string parameters from GS were rendered as zero.

### LINKED ISSUE #14044: [Bug]: GS can't display money below £0
### Version of OpenTTD

OpenTTD 20250420-master-gee81313254

### Expected result

Negative money is shown -£xxx and in red.

### Actual result

Negative money is shown as £0.

### Steps to reproduce

Image

[negative money not shown.zip](https://github.com/user-attachments/files/19825600/negative.money.not.shown.zip)
1. Load savegame, it uses the GS League Tables.
2. It displays negative money correctly in 15.0-beta2 but not on current master.

### PR DESCRIPTION
**Pull request by frosch123**
## Motivation / Problem

* String parameters are always stored as `uint64_t`.
* Negative values are sign-extended to `int64_t` and then casted to `uint64_t`.
* The same applies to encoded strings.
* But `ScriptText` did it different, and encoded them as `int64_t`.

Funnilly the old `strtoull` did not care, parsed signed integers and returned them as unsigned.

## Description

* Fix the encoding in `ScriptText`.
* Add savegame conversion for existing texts.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, game_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

File: src/saveload/saveload.h [hunk 1]
```diff
@@ -400,6 +400,7 @@ enum SaveLoadVersion : uint16_t {
 	SLV_ENCODED_STRING_FORMAT,              ///< 350  PR#13499 Encoded String format changed.
 	SLV_PROTECT_PLACED_HOUSES,              ///< 351  PR#13270 Houses individually placed by players can be protected from town/AI removal.
 	SLV_SCRIPT_SAVE_INSTANCES,              ///< 352  PR#13556 Scripts are allowed to save instances.
+	SLV_FIX_SCC_ENCODED_NEGATIVE,           ///< 352  PR# Fix encoding of negative parameters.
```
Comment (rubidium42) [inline src/saveload/saveload.h]:
```suggestion
	SLV_FIX_SCC_ENCODED_NEGATIVE,           ///< 353  PR#14049 Fix encoding of negative parameters.
```

**Review by rubidium42 — APPROVED** [review]
