### PR TITLE
Fix #9876: MacBook Touch Bar crash / render issues w/ 32bpp graphics

### LINKED ISSUE #9876: [Crash]: OpenTTD crashed on MacOS with 32bpp baseset due to touchbar
### Version of OpenTTD

OpenTTD 12.2 on MacOS Monterey 12.3.1

### Steps to reproduce

N/A

### Upload crash files

[crash20220503214114.log](https://github.com/OpenTTD/OpenTTD/files/8616920/crash20220503214114.log)
crash20220503214114

### PR DESCRIPTION
**Pull request by Bouke**
## Motivation / Problem

Rendering of the MacBook Touch Bar is incorrect on SSE-based blitters when using 32bpp base graphics and software rendering. The following problems related to Touch Bar rendering have been found:

Blitter|Result
-|-
32bpp-sse2|wrong (washed out colors)
32bpp-sse2-anim|correct (doesn't use `Blitter_32bppSSE_Base::Encode`)
32bpp-sse4|wrong (black buttons)
32bpp-sse4-anim|crash: #9876
32bpp-ssse3|wrong (black buttons)

## Description

The crash using `32bpp-sse4` is caused by trying to use the animation buffer while not rendering to the screen. Similar to `Blitter_40bppAnim::Draw` we need to forward to a non-animating `Draw()`. `Blitter_32bppSSE4_Anim` encodes sprites using `Blitter_32bppSSE_Base::Encode` but didn't inherit from a non-animating blitter, so it now inherits from `Blitter_32bppSSE4` to allow calling `Blitter_32bppSSE4::Draw` when a non-animated sprite is requested.

To fix the incorrect rendering @JGRennison had a look at the alpha channel rendering in the SSE blitters. My original patch (incorrectly) covered over the problems by disabling translucency altogether. The SSE blitters didn't set the alpha values to anything in particular. AlphaBlendTwoPixels are now adjusted so that the alpha output is as expected (i.e. it matches ComposeColourRGBA).

32bpp-simple (reference):
32bpp-simple

32bpp-sse2 (washed out):
32bpp-sse2

32bpp-ssse3 (black):
32bpp-ssse3

32bpp-ssse3 (with fix):
32bpp-ssse3-fixed-jgr

@glx22, @JGRennison and @frosch123 contributed to this PR by debugging and/or blitter / C++ support.

## Limitations

?

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
<s>* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)</s>

### CODE REVIEW

File: src/blitter/32bpp_sse_func.hpp [hunk 1]
```diff
@@ -438,6 +438,12 @@ void Blitter_32bppSSSE3::Draw(Blitter::BlitterParams *bp, BlitterMode mode, Zoom
 void Blitter_32bppSSE4::Draw(Blitter::BlitterParams *bp, BlitterMode mode, ZoomLevel zoom)
 #endif
 {
+	if (_screen_disable_anim) {
+		/* This means our output is not to the screen, so we must ignore any translucency stuff */
+		Draw<BM_NORMAL, RM_WITH_MARGIN, BT_NONE, false>(bp, zoom);
+		return;
+	}
+
```
Comment (JGRennison) [inline src/blitter/32bpp_sse_func.hpp]: This looks potentially problematic. _screen_disable_anim is not only used for drawing the touchbar sprites.
Drawing of sprites still needs to be correct when it is true.

This does not handle `mode`, `bp->skip_left`, `bp->width`, etc. and it's perfectly reasonable to render translucent sprites in a screenshot for example.

Comment (Bouke) [reply src/blitter/32bpp_sse_func.hpp]: The fix is inspired by the 40bpp-anim blitter, although that doesn't seem to have the alpha channel problem. What do you suggest?
https://github.com/OpenTTD/OpenTTD/blob/e5203f34092903693276b76f5c09bf00530e025f/src/blitter/40bpp_anim.cpp#L316-L320.

Comment (glx22) [reply src/blitter/32bpp_sse_func.hpp]: That's a different switch, 40bpp changes the blitter, while you change the blitting mode.

**Comment by JGRennison** [comment]
I had another look at the AlphaBlendTwoPixels commit and was able to make the instruction sequences slightly shorter: https://github.com/JGRennison/OpenTTD-patches/commit/8d8765e38ff035c7782b217327cf404a51cfa100

**Comment by Bouke** [comment]
> I had another look at the AlphaBlendTwoPixels commit and was able to make the instruction sequences slightly shorter: [JGRennison/OpenTTD-patches@8d8765e](https://github.com/JGRennison/OpenTTD-patches/commit/8d8765e38ff035c7782b217327cf404a51cfa100)

This is great! I've tested these changes and there appears to be no changes to the rendered Touch Bar 👍. I've included that commit in this PR.

**Comment by michicc** [comment]
Commit messages need to be fixed.

For the `Preprocessor hash is put into the first column, before the tab indentation` message, fixing it would require reformatting the complete file as the pre-existing contents is "wrongly" formatted as well. Maybe someone with commit super-powers can just ignore that and force this PR.

**Comment by Bouke** [comment]
I have fixed the commit messages. I haven't changed the indentation as that would require formatting the whole file as you've pointed out.

**Review by michicc — APPROVED** [review]
